### ISSUE TITLE
3.3.6: What are absolute file paths in package.json used for?

### ISSUE THREAD

**Issue by jamesshore** [npm/npm#10393]
After upgrading to Node 5.0.0/npm 3.3.6, I noticed that npm now adds an `_args` and `_where` property to the package.json file. I check my `node_modules` directory into git, so I'm concerned that these absolute paths will cause problems when I check out the `node_modules` directory on other machines.

What are those entries used for, and will they cause problems when `node_modules` is moved to another location?

Here's an example `package.json`, resulting from `npm install karma-commonjs`. Note the `_args` and `_where` properties:

```javascript
{
  "_args": [
    [
      "karma-commonjs@0.0.13",
      "/Users/jshore/Documents/Projects/weewikipaint"
    ]
  ],
  "_from": "karma-commonjs@0.0.13",
  "_id": "karma-commonjs@0.0.13",
  "_inCache": true,
  "_location": "/karma-commonjs",
  "_npmUser": {
    "email": "vojta.jina@gmail.com",
    "name": "vojtajina"
  },
  "_npmVersion": "1.4.4",
  "_phantomChildren": {},
  "_requested": {
    "name": "karma-commonjs",
    "raw": "karma-commonjs@0.0.13",
    "rawSpec": "0.0.13",
    "scope": null,
    "spec": "0.0.13",
    "type": "version"
  },
  "_requiredBy": [
    "#DEV:/"
  ],
  "_resolved": "https://registry.npmjs.org/karma-commonjs/-/karma-commonjs-0.0.13.tgz",
  "_shasum": "9b6c3feb7eed892d275c879e89ceb0c8accb0bb5",
  "_shrinkwrap": null,
  "_spec": "karma-commonjs@0.0.13",
  "_where": "/Users/jshore/Documents/Projects/weewikipaint",
  "author": {
    "email": "vojta.jina@gmail.com",
    "name": "Vojta Jina"
  },
  "bugs": {
    "url": "https://github.com/karma-runner/karma-commonjs/issues"
  },
  "contributors": [
    {
      "name": "Vojta Jina",
      "email": "vojta.jina@gmail.com"
    },
    {
      "name": "James Shore",
      "email": "jshore@jamesshore.com"
    },
    {
      "name": "Ben Drucker",
      "email": "bvdrucker@gmail.com"
    },
    {
      "name": "Marian Zagoruiko",
      "email": "marian@zagoruiko.gmail.com"
    }
  ],
  "dependencies": {},
  "description": "A Karma plugin. Test CommonJS modules.",
  "devDependencies": {
    "grunt": "~0.4.1",
    "grunt-auto-release": "~0.0.3",
    "grunt-bump": "~0.0.11",
    "grunt-contrib-jshint": "~0.6.0",
    "grunt-karma": "~0.6.2",
    "grunt-npm": "~0.0.2"
  },
  "directories": {},
  "dist": {
    "shasum": "9b6c3feb7eed892d275c879e89ceb0c8accb0bb5",
    "tarball": "http://registry.npmjs.org/karma-commonjs/-/karma-commonjs-0.0.13.tgz"
  },
  "homepage": "https://github.com/karma-runner/karma-commonjs",
  "installable": true,
  "keywords": [
    "commonjs",
    "karma-plugin"
  ],
  "license": "MIT",
  "main": "lib/plugin.js",
  "maintainers": [
    {
      "name": "vojtajina",
      "email": "vojta.jina@gmail.com"
    }
  ],
  "name": "karma-commonjs",
  "optionalDependencies": {},
  "peerDependencies": {
    "karma": ">=0.9"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/karma-runner/karma-commonjs.git"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "version": "0.0.13"
}
```

**Comment by iarna** [comment]
They are just there to provide greater transparency as to what the installer was thinking at install time.  At this time, the only `_` properties used in future installs are `_requiredBy` if it contains `#USER` and `_requested` in some limited cases.

**Comment by iarna** [comment]
And to directly address your concern, no, these will not impact moving the `node_modules` folder elsewhere– as explained above, these are sometimes used as hints to npm on future runs of the the npm installer, but are never required.

Does this answer your question?

**Comment by jamesshore** [comment]
Yep, thank you!

**Comment by juanjoDiaz** [comment]
Is there any way of avoiding those?? If I'm packaging my app to be distributed (let say an electron/NW app) I definitely don't want my local paths included.

**Comment by mrmayfield** [comment]
@juanjoDiaz Did you find a solution for this?

**Comment by juanjoDiaz** [comment]
Nope. Just manually (or using a script) removing those paths.

I still think that this is an issue that should be addressed by the npm team at some point.

**Comment by mrmayfield** [comment]
Yeah I just brought it up in an issue here on NPM.

What does your process for removing them / using a script to remove them look like? Can you post the code? I am building out an NW.js that I want to distribute

**Comment by juanjoDiaz** [comment]
Hey Anthony! I'm really sorry. Totally miss this message.

I've published a little module with the code I use for this so you can use it if you want.

https://www.npmjs.com/package/removeNPMAbsolutePaths

**Comment by mrmayfield** [comment]
Nice @juanjoDiaz, great work here! :)

**Comment by sanmai-NL** [comment]
I think was a bad decision to put these absolute paths in `package.json`. To log installation time info, write a log.

**Comment by mrmayfield** [comment]
^ Personally agreed

**Comment by atypicalprogrammer** [comment]
Any updates?

**Comment by juanjoDiaz** [comment]
@atypicalprogrammer, this issue is closed so I wouldn't expect any fix for this.

**Comment by armoucar** [comment]
There could be at least an option to run npm without adding this.

**Comment by davidkethel** [comment]
I think this may be causing my issue. 

[http://stackoverflow.com/questions/40712441/how-do-i-run-my-mocha-js-tests-in-visual-studio-online-build-process](http://stackoverflow.com/questions/40712441/how-do-i-run-my-mocha-js-tests-in-visual-studio-online-build-process)

Has this been resolved?

**Comment by juanjoDiaz** [comment]
This is not fixed. And, since it's closed, I don't think it will be fixed.
In theory, those absolute paths are not used for anything so they shouldn't be creating trouble.
I recommend you give it a go to https://www.npmjs.com/package/removeNPMAbsolutePaths which basically removes the stuff that npm add automatically to the package.json of modules and see if that fixes your problem.

**Comment by stanleyxu2005** [comment]
Hope there is a switch to turn them off. Sometimes we need to commit node modules into private repo for some reason. Developer 1 checkouts project at `c:/proj`, and Developer 2 checkouts project at `d:/proj` There will be many diff about the absolute paths change. This is really annoying!

**Comment by monshi** [comment]
This issue is fixed in npm@5 but I'm still wondering how this issue was around for such a long time!

**Comment by stanleyxu2005** [comment]
@monshi I dont know whether my install command is correct or not, but there are still many redundant information in package.json. I'm using npm 5.0.3 by the way.

![image](https://user-images.githubusercontent.com/5162687/29237624-ae69531e-7f54-11e7-920d-bf5560b92c82.png)

**Comment by monshi** [comment]
I agree and I'm not sure why something like `"_where": "d:\\ij"` is useful for install, but as far as I was concerned about the issue is fixed in v5, which was related to `"_inCache": true` causing npm install to fail with an `untar read error`.

**Comment by juanjoDiaz** [comment]
It is not fixed if  it still contains `_where": "d:\\ij`

I think that  it would be very useful if npm provides a list of fields that are not strictly necessary

**Comment by stanleyxu2005** [comment]
@juanjoDiaz @monshi Yeah, it becomes a very awkward fact that the only reason I use npm is to install and to upgrade yarn, which makes the node_modules dir more compact and easy to manage.

**Comment by Floo0S** [comment]
I had the same thought and do not understand why the npm team would like to keep that. I use yarn instead of npm now. Everything wonderful, no more private information in the files!

**Comment by sgronblo** [comment]
I agree this is awkward. This is something that shouldn't be there by default. It should ideally have been something you enable explicitly or at least have a way to disable this from being generated.

**Comment by alexeagle** [comment]
Another problem with this: it makes the installation non-deterministic. If using a build tool like Make or Bazel, the change in the package.json from one execution to another (eg. the CI machine has a different tmp folder) means that any build actions which depend on reading `package.json` (most of them) cannot be cache hits.
