### ISSUE TITLE
npm silently fails to update subdependencies when using shrinkwrap

### ISSUE THREAD

**Issue by AgentME** [npm/npm#10463]
I've run into an issue where running "npm install" doesn't always make node_modules match npm-shrinkwrap.json if there's already a node_modules folder.

**EDIT: Newer minimal reproduction steps a few posts down** Here's a reproduction case. Place the following files in a directory and run `npm install`:

old [package.json](https://gist.githubusercontent.com/AgentME/6607503775a2fc9ed94d/raw/b85aeedf96af9d313d32daedde8cd755b4412477/package-old.json)
old [npm-shrinkwrap.json](https://gist.githubusercontent.com/AgentME/981da81b943fd60358ee/raw/b392367ff98baefcb1ae1c81f4509c8e5a1a4699/npm-shrinkwrap-old.json)

Then replace them with the following updated files and run `npm install` again.

new [package.json](https://gist.githubusercontent.com/AgentME/05e55f54026fce7a24b8/raw/c75555cb71a3a47278055a46b73a9870713b462b/package-new.json)
new [npm-shrinkwrap.json](https://gist.githubusercontent.com/AgentME/faf9b102cfba869604dd/raw/e6c6b1914c85a7abf49504f4eca4a49739a494f8/npm-shrinkwrap-new.json)

The node_modules directory is now missing "readable-stream" despite being listed in the the shrinkwrap. The node_modules directory will have 649 directories under it while the shrinkwrap lists 650 things on the lowest level. It works fine if you start from a fresh slate with no node_modules directory.

I'm using OS X 10.11 with npm 3.4.0.

Interestingly, if you do the above steps without the package.json files, everything works fine.

Related to #7268.

**Comment by iarna** [comment]
I've verified that this happens in `npm@3.4.0` and is fixed in the latest npm, `npm@3.5.2`. Please try upgrading and I think you'll find this issue resolved!

**Comment by AgentME** [comment]
I've just tested with npm 3.5.2. The example in my original post appears to be fixed, but I've found a new failure:

old [package.json](https://gist.githubusercontent.com/AgentME/3f183b738c72fb1cfdee/raw/b1f116481f15e7a011a011bd00c45404dcb6a2ac/package-old.json)
old [npm-shrinkwrap.json](https://gist.githubusercontent.com/AgentME/2896bc8b9097be94692d/raw/67f9734088427b0bda3fdabd3d88901854d96434/npm-shrinkwrap-old.json)

new [package.json](https://gist.githubusercontent.com/AgentME/79870064e408482e9d4c/raw/a0d3ed3bb71493e83a171896d2d44b8a01b2da0a/package-new.json)
new [npm-shrinkwrap.json](https://gist.githubusercontent.com/AgentME/71386a4855bb4a3472fd/raw/e13b3a7fcc9b986341d285e3f690a2d90e78cbca/npm-shrinkwrap-new.json)

Inside "node_modules/regexpu/node_modules/esprima/package.json", you can see that it's version 2.7.0, but the new shrinkwrap says it should be version 2.7.1. If you do a fresh install from the shrinkwrap, then it will be the correct version.

**Comment by AgentME** [comment]
Was this ever looked into again? It went from "big bug" to "support" before I posted the new case of what seems to be the same type of issue (that still fails in npm 3.8.1). I regularly run into this type of issue still.

It leads to errors often if one module updates to a newer incompatible version of Lodash or Babel for example (both had major breaking updates in the last year), and NPM fails to update its dependency. It's so common that I made the build script of an application verify that a shrinkwrap was correctly installed, then if it wasn't then it deletes the entire node_modules directory and re-runs `npm i` from scratch.

**Comment by area** [comment]
I've been running into this recently as well, which is very frustrating.

**Comment by AgentME** [comment]
Still seeing this with npm v3.10.6. Here's a minimal reproduction case. The first shrinkwrap contains lodash@3.7.0, and the second shrinkwrap contains lodash@3.10.1. Trying to install the second shrinkwrap does nothing instead of updating the lodash subdependency.

```
$ wget -q https://gist.githubusercontent.com/AgentME/efae12c6a4b6be419eadfb82089ed177/raw/80c8d4af4234b87d1b91c489d95de6e5218f70cd/package.json
$ wget -qO npm-shrinkwrap.json https://gist.githubusercontent.com/AgentME/efae12c6a4b6be419eadfb82089ed177/raw/80c8d4af4234b87d1b91c489d95de6e5218f70cd/npm-shrinkwrap-OLD.json
$ npm i
test@1.0.0 /tmp/b
├─┬ auto-html@1.0.4 
│ └── lodash@3.7.0 
└── lodash@4.15.0 

$ wget -qO npm-shrinkwrap.json https://gist.githubusercontent.com/AgentME/efae12c6a4b6be419eadfb82089ed177/raw/80c8d4af4234b87d1b91c489d95de6e5218f70cd/npm-shrinkwrap-NEW.json
$ npm i
$ npm ls
test@1.0.0 /tmp/b
├─┬ auto-html@1.0.4
│ └── lodash@3.7.0
└── lodash@4.15.0

$ rm -r node_modules/
$ npm i
test@1.0.0 /tmp/b
├─┬ auto-html@1.0.4 
│ └── lodash@3.10.1 
└── lodash@4.15.0 

```

The issue is really annoying because you can't have continuous integration or deployment systems just run "npm install" to make sure the dependencies are in order. If the shrinkwrap is different from the last build, then you have to remove the node_modules directory before each build in order to be sure the dependencies listed in the shrinkwrap are actually used!

**Comment by AgentME** [comment]
It looks like this was fixed in v3.10.7, possibly by https://github.com/npm/npm/issues/12718 https://github.com/npm/npm/pull/12770. Closing.
