### ISSUE TITLE
npm install <package> downloads files with a set of NULL characters in the middle

### ISSUE THREAD

**Issue by root-talis** [npm/npm#10759]
[npm-debug.log.txt](https://github.com/npm/npm/files/56683/npm-debug.log.txt)
When I run gulp after installing it through NPM, I get the following error:

```
$ gulp
/vagrant/vhosts/default/web-root/svc/node_modules/gulp/node_modules/readable-stream/lib/_stream_readable.js:123
  if (!(this insta
             ^^^^^

SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/vagrant/vhosts/default/web-root/svc/node_modules/gulp/node_modules/readable-stream/lib/_stream_duplex.js:43:16)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
```

The file has a set of `0x00` symbols after `if (!(this insta` at the designated line. The text that goes after the NULLs is obviously not a continuation of the `if` statement. It seems like a part of the file was _replaced_ with NULLs. This is a fragment of `$ hexdump -C`:

```
00000fd0  0a 66 75 6e 63 74 69 6f  6e 20 52 65 61 64 61 62  |.function Readab|
00000fe0  6c 65 28 6f 70 74 69 6f  6e 73 29 20 7b 0a 20 20  |le(options) {.  |
00000ff0  69 66 20 28 21 28 74 68  69 73 20 69 6e 73 74 61  |if (!(this insta|
00001000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00004000  6f 75 6c 64 20 63 61 75  73 65 20 69 74 20 74 6f  |ould cause it to|
00004010  20 6e 65 76 65 72 20 73  74 61 72 74 0a 20 20 20  | never start.   |
00004020  20 2f 2f 20 66 6c 6f 77  69 6e 67 20 61 67 61 69  | // flowing agai|
```

Please note the length of the replaced fragment: it is 0x3000 bytes long (about 1.5 kilobytes)! Here is the damaged file: [_stream_readable.js.txt](https://github.com/npm/npm/files/56672/_stream_readable.js.txt).

I also encountered a set of issues https://github.com/npm/npm/issues/10758 during `$ npm install gulp`. Maybe they are connected.

This problem doesn't happen just with gulp, and sometimes it repeats with different files when fresh-installing other packages. Reinstalling the packages helps in some cases, in other cases the error remains.

```
$ npm --version
3.3.12

$ node --version
v5.1.1
```

Debug log of `$ npm install gulp` (same as in the issue referenced above):
[npm-debug.log.txt](https://github.com/npm/npm/files/56684/npm-debug.log.txt)

**Comment by corinna000** [comment]
I am seeing the same issue while performing an `npm install` on a vagrant box on both a Windows 7 and Mac host OS. 

* Linux local 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
* npm 2.14.12
* node 4.2.4

If I delete the offending package and reinstall it then it seems to work okay.

The attached examples are from the Mac host. The corrupted files on the Windows host were different.

[async.js.txt](https://github.com/npm/npm/files/92176/async.js.txt)
[AMDDefineDependencyParserPlugin.js.txt](https://github.com/npm/npm/files/92192/AMDDefineDependencyParserPlugin.js.txt)

**Comment by dholth** [comment]
Having same problem on OSX and Windows-hosted Linux virtualboxen. Are the other reporters using a proxy or security gateway?

**Comment by nabilfreeman** [comment]
+1 for this problem. it's so strange...

**Comment by nabilfreeman** [comment]
looking at other comments here, it seems we all have VirtualBox Shared Folders in common

**Comment by dholth** [comment]
Yes, shared folders is what we share. I have worked around the issue by
disabling the shared folder and running editors inside the VM.
 
 
On Thu, Apr 21, 2016, at 12:29 PM, Freeman wrote:
> looking at other comments here, it seems we all have VirtualBox Shared
> Folders in common
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub[1]
>
 

Links:

  1. https://github.com/npm/npm/issues/10759#issuecomment-212996833

**Comment by teohhanhui** [comment]
Yes, I only have this problem when using VirtualBox shared folder.

**Comment by nabilfreeman** [comment]
I have acquired a copy of Parallels 11 to see if this problem goes away when not using VirtualBox...

**Comment by matohavo** [comment]
I also had this issue on Laravel homestead vagrant box - it seems to be related to insufficient memory on virtual machine. When I increased the vbox RAM to 1GB and added some swap, everything went ponies and rainbows again.

**Comment by VoidVolker** [comment]
Same problem: incrasing RAM is fixed issue.

**Comment by Mezzair** [comment]
+1 Increasing RAM solved the problem for me too.

**Comment by olysyuk** [comment]
Issue is still reproducible on node 6.9.1 npm 3.10.8. Adding memory still fixes the issue.

**Comment by bobjohnbob** [comment]
I ran into this problem this week after everything working fine in this repo for months.  Increasing the memory to 1024 in my Vagrant file works around the issue.  Not sure if it's a problem with VirtualBox (highly likely) or npm.  Version I tried:
VirtualBox 5.0.36, 5.1.18
npm 4.2.0, 3.10.10 
node 7.8.0, 6.10.2
