### ISSUE TITLE
npm ERR! TypeError: Cannot read property '0.0.3' of undefined

### ISSUE THREAD

**Issue by trkailash** [npm/npm#10771]
I encountered the following error: 

```
SOLINK_MODULE(target) Release/node_expat.node: Finished
npm ERR! TypeError: Cannot read property '0.0.3' of undefined
npm ERR!     at /Users/kailashr/.nvm/v0.10.33/lib/node_modules/npm/lib/cache/add-named.js:123:27
npm ERR!     at RegClient.get_ (/Users/kailashr/.nvm/v0.10.33/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:130:14)
npm ERR!     at RegClient.<anonymous> (/Users/kailashr/.nvm/v0.10.33/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:49:12)
npm ERR!     at evalmachine.<anonymous>:271:14
npm ERR!     at /Users/kailashr/.nvm/v0.10.33/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
npm ERR!     at Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! System Darwin 14.5.0
npm ERR! command "/Users/kailashr/.nvm/v0.10.33/bin/node" "/Users/kailashr/.nvm/v0.10.33/bin/npm" "install"
npm ERR! cwd /Users/kailashr/Documents/workspace/simpragma/airfi-rss-feeder/article-processor
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! type non_object_property_load
```

while npm installing from the following package.json: 

``` json
{
  "name": "article-processor",
  "version": "1.1.0",
  "description": "consumes RSS feeds ",
  "main": "main.js",
  "directories": {
    "test": "test"
  },
  "engines": {
    "node": "0.10.33",
    "npm": "1.4.28"
  },
  "dependencies": {
    "MD5": "^1.2.1",
    "jsdom": "~3.1.0",
    "lodash": "^2.4.1",
    "mime": "~1.2.11",
    "mkdirp": "~0.5.0",
    "nano": "~5.12.2",
    "node-stringprep": "~0.7.0",
    "q": "^1.1.2",
    "request": "~2.51.0",
    "rimraf": "~2.2.8",
    "superfeedr": "~0.2.0"
  },
  "devDependencies": {
    "jshint": "^2.8.0"
  }
}
```

I think I use old versions of some modules but I would like to know if this is the _reason_ why this error comes up ? Please help. .. Thanks in advance.

**Comment by mattdesl** [comment]
I am seeing this as well in some installs, with npm@2.11.3 and node@0.12.7

**Comment by mattdesl** [comment]
Nevermind, `nvm` had put me onto an older version of npm. My issue is resolved with npm@2.14.9.

**Comment by trkailash** [comment]
I upgraded npm to version 2.14.9. I still get the error. Attached is the npm-debug.log. 
[npm-debug.txt](https://github.com/npm/npm/files/57677/npm-debug.txt)
Please advise. Thanks in advance.
