### ISSUE TITLE
"npm remove" deletes modules required for child modules.

### ISSUE THREAD

**Issue by martinheidegger** [npm/npm#11438]
This is a common use-case for me:
1. I have a new project: `mkdir test; cd test`
2. I want to use a package in this project: `npm i chai`
3. I want to use another package in this project: `npm i deep-eql`
   _(note: chai has a dependency to deep-eql already but I didn't notice that)_
4. I decide that I don't need deep-eql: `npm r deep-eql`
5. I try to run chai again: `node -e "require('chai')"`

_Current Result:_ `Error: Cannot find module 'deep-eql'`
_Expected Result:_ It could throw an error while trying to remove deep-eql or it could move deep-eql from the node_modules folder to the node_modules folder of chai.

(Note: usually I use `npm i chai --save-dev` to note the dependency in my package.json)

**Comment by ashleygwilliams** [comment]
confirmed this on my machine with node 4.2.4 and npm 3.6.0

**Comment by ashleygwilliams** [comment]
also confirmed that this happens when using a `package.json` (i.e. `--save`)

**Comment by ashleygwilliams** [comment]
my thought here is that this a bug. we, as a pkg mgr, shouldn't require that our users know all the deps of the deps they use and be able to navigate around this issue. 

this should not throw an error either. if `deep-eql` is installed as dep-dep, and then as a primary dep, then removed as a primary dep, it should return to its original state as a dep-dep.

this could either mean that it is nested as @martinheidegger suggested, but it could also stay in place.

**Comment by iarna** [comment]
Yeah, we consciously affirmed the current behavior last summer, but in retrospect it was a mistake.

**Comment by martinheidegger** [comment]
@ashleygwilliams Thank you for taking the time to confirm it. If the dependency would be allowed to stay in place without error message it would be weird:  "I removed it, why is it still there?"

**Comment by iarna** [comment]
This is almost certainly fixed by the internals rewrite in 3.10.0, but we need to stop back by here and verify that it is in fact fixed.

**Comment by zkat** [comment]
This is still happening with the latest release. On top of that, npm crashes in a pretty unhelpful way while reporting the results of `npm i deep-eql`:

```
npm sill executeActions Finishing
npm sill rollbackFailedOptional Starting
npm sill rollbackFailedOptional Finishing
npm sill runTopLevelLifecycles Starting
npm sill install runTopLevelLifecycles
npm sill runTopLevelLifecycles Finishing
npm sill install printInstalled
@zkat/test@3.0.0 /Users/zkat/Documents/code/test
└── (empty)

npm WARN @zkat/test@3.0.0 No repository field.
npm verb exit [ 0, true ]
npm ERR! code 1
```

**Comment by iarna** [comment]
What we should be doing here:

1. Warn and refuse to remove modules that doing so would result in breaking the tree.
2. Allow it if run with `--force`
