### ISSUE TITLE
registry unconditionally returning gzipped JSON responses breaks old npm

### ISSUE THREAD

**Issue by mayank-jain** [npm/npm#12196]
```
sudo npm install -g localtunnel
[sudo] password for rails: 
npm http GET https://registry.npmjs.org/localtunnel
npm http 304 https://registry.npmjs.org/localtunnel
npm http GET https://registry.npmjs.org/request/2.65.0
npm http GET https://registry.npmjs.org/yargs/3.29.0
npm http GET https://registry.npmjs.org/debug/2.2.0
npm http GET https://registry.npmjs.org/openurl/1.1.0
npm http 304 https://registry.npmjs.org/debug/2.2.0
npm http 304 https://registry.npmjs.org/yargs/3.29.0
npm http 200 https://registry.npmjs.org/request/2.65.0
npm ERR! registry error parsing json
npm http 304 https://registry.npmjs.org/openurl/1.1.0
npm ERR! SyntaxError: Unexpected token 
npm ERR! �V[o�6�+��a�hY�e����C6`غ�M@I�D["U�r��o�wH�I�u���D<��w��}>�=e\�Q��*tJJ�q�Ro��V���Z���%�T��*D�g�F�r'�E��l��cHj���hb����*��HDۜ���m�z�DB���3�d>�4I�{�V�,}�"k�w�R���tzj���� ��l���'V����x�%MMh�����*��݁�9b򐺳^&
                                                                                                                          B�'���[�!�S��2pP�95e>���k���
!���2ɑ�$�Ə�
             �1̌o��9��j"3����E�^E�7��J~A*������,���D��
�H�k                                                    O�6`$H�#D�u\�SU
;�C�rHr5�Ճ)y��$Ji|1P8*2ڈ5�Fp"n����m���4m�iZ���\s��<��u�J�\T5��� F,h�����V��\ŷ~s̋���*�ڎۉ���</�MV^�z��WM������y�5׫mQע�d�1���n�-���g�f6�-����E��I���=�!\1L����[huX��A_ ��?t�v�.�,��gF�~�.:��
                                                                                                                              �Le�	/�]d#���$::u�C�̤���yï¿½ï¿½Dc4ï¿½(ï¿½ï¿½X'%ï¿½rNï¿½-ÌCï¿½ï¿½ï¿½iÓ/ï¿½"9ï¿½bï¿½?Ìµï¿½ï¿½Fï¿½FTØ´ï¿½><ï¿½ï¿½ï¿½Ý
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:238:23)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-àgooglegroups.com>

npm ERR! System Linux 3.19.0-56-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "localtunnel"
npm ERR! cwd /home/rails/workspace/office/batooni-dev
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type unexpected_token
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/rails/workspace/office/batooni-dev/npm-debug.log
npm ERR! not ok code 0
```

**Comment by mayank-jain** [comment]
some one can help me?

**Comment by gunsch** [comment]
Seeing similar issues right now for other packages as well.


> npm install -g is-posix-bracket
npm http GET https://registry.npmjs.org/is-posix-bracket
npm http 200 https://registry.npmjs.org/is-posix-bracket
npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected token
npm ERR! �Y�n����R\lW�DR�W����s��r1�\�V�9Kr)��W�Kɺ4@��@_���'�o��%YR,	�?�!�;;;�3������e4��Hy&���+�-T�ٸ,�3�؞���~���~;
                ��Px֠+D���6����%�/�\EY
npm ERR! ��B�E*�*J�����`�h*R&U�cI��٫7�f�$L�䅐
                                              �A5�O8�T�`~̥<4!AIe(>����F̕�
npm ERR! ��M˴���(�����6�}y�k�jI��c�%"�c:͉R��Z�HMJ����u�I�עP�-F㥚dŊr?����.�e���ά�*+��O�s
npm ERR! ��2���,�I��++[�'φ�����)�|�J���F1&��F��Ƽ���f#�9��P�!�q�!!
                                                                 h��'p�6|L+�ճ�/%���1�N��S?�Ts�������)����Z�gYhyȣAݫ ��[_^}7�_�7����xb,nϼz)c^��p,�4+��AP B��Hcg��?�F�?��/��+��[I�1O�*�$?@'X������@�;��v��N���m��N�ӵw��	��q��*1-'\�	x��^��}���0��0��A�ߵC��M<C��%�i����r��dHKö�q
                                                                     �f�&�Y��PY
                                                                               .�
                                                                                 �
npm ERR! �E�}+E�(�dY�(�?��c�E�q���<�����W�>~���i\I3+ƛ�cl
                                                        �
npm ERR! ����;*����|�
                     NӖ�/����I�?b���.��qn�Y�1��_��z��KA���׀�%2U,͆���0���{��YIEF B^Ɣ���
                                                                                      �#*"�w�H3z��ʘ܂�;�=��������|��;��1�H��kH��n=�'_'�?@�O[n�g�����������9��kȽ�2�q:����z��;l[]�
npm ERR! ���)%��E�����i��O�I����>�MiX�1C�l�Q4M�?(����n���'�ߥ�q}�cz}˺l���s���v;.��n�,�]u�
                                                                                        ��P���A��7���^��/�f��M9�DH3�Zв5�������I��p�|6�-�k�G���p�}���8��\r�"@�lp�-�29t�ge�����*�4���
                                                                             v�R-7�H�
npm ERR! k�ˆB���y��}�K1􈝦R���_�+��c#���6<��w���<�-%��M�2
/.�l���)�Yc                                             ɧBS�;�,5�+y�Ny�egt~V��	+��J�E��z��������Ga�
           �M��܋t4�BLH����hy�O��²��wr57�ѰV����~�C�����e���Fmc���P��uuby�]�����ӿd%K��D1���yhF�E�W�KHq�B{��y�.B��:���ҍ
             Am
               ��.�F�
                     7�f���I��
                              x��B	&�<�
npm ERR! ň�f�q9aө������l�d��S�w6Z���%��fKc�V�<��wn����!���9��D_!w6u$;��W�!�Tް�+JH�|�w�Ъ,���i���w��/�U��2�²��PW�XHG*�!��������vZ�eג�ѵ@[m�@�j)���ͽ�
�H3�4RR!�����~(���\V$}�Ѭ����y��)����Oyկi�qe�cYn���Ɗ�wID�hO1��Ǻ�Q�>2�
npm ERR! z��Y�|F�B��y��֍g|.�LĀa�8��U
                                    T Z�m�P��|\T�6��N[�a'4��k�b	ԇk�bvhւ뺅�d�����$�Qu/�B���|Iv�j���βU�Ȥh�٬�,F�����2?��]:壣���ёe��p�����\+�P��Z�8���4%�	����"]C��
�{+��U�׵���~�v�����)?�|��&6������^����Dw_��*GKWmj��X�'q:��b��%�4�ɉ�Ç��n��V
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/usr/local/Cellar/node/0.10.25/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:241:23)
npm ERR!     at Request.self.callback (/usr/local/Cellar/node/0.10.25/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/Cellar/node/0.10.25/lib/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/Cellar/node/0.10.25/lib/node_modules/npm/node_modules/request/request.js:844:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Darwin 15.3.0
npm ERR! command "/usr/local/Cellar/node/0.10.25/bin/node" "/usr/local/bin/npm" "install" "-g" "is-posix-bracket"
npm ERR! cwd /Users/jesse/Dropbox/projects/notes
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! type unexpected_token
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/jesse/Dropbox/projects/notes/npm-debug.log
npm ERR! not ok code 0

**Comment by gunsch** [comment]
It seems I was using a rather old version of npm. Upgrading to much more recent npm (v3.8.5) makes things run more smoothly.

**Comment by larowlan** [comment]
Seeing lots of the same errors today, updating npm/node resolves - did something change on the endpoints to render the old versions non-functional?

**Comment by p0wl** [comment]
we're seeing the same problems with nvm 1.3.14. is updating npm the only solution?

**Comment by m0nkmaster** [comment]
We're running node 0.10.21 and npm 1.3.11 on CentOS and are experiencing the same issues. We're not that able to update node at the moment, has anyone found a solution which doesn't require updating node?

**Comment by p0wl** [comment]
you can update npm without updating node via `npm install -g npm`

**Comment by schorsch3000** [comment]
@p0wl you cant if your npm as old as the ubuntu-14.01 default package :(

**Comment by Asvarox** [comment]
We have same problem, npm 1.3.10 and node 0.10.25.

Our current workaround is to install newer npm via the old one locally, ie.
```
npm install npm@2.10.0
```
And then use it to install other dependencies
```
nodejs node_modules/npm/bin/npm-cli install
````

**Comment by othiym23** [comment]
@npm/registry-team team is testing a switch over to `Content-Encoding: gzip` for package metadata, because the savings in bandwidth would make installs faster and more reliable for everyone. Unfortunately, `npm@1.3` and older can't handle gzipped responses. Doubly unfortunately, the npm CLI team doesn't support `npm@1.3` anymore, as it's quite old (and buggy).

The registry team is in the process of rolling back this change until we can try again with a safer combination of headers that won't break old npm. I would also strongly urge anyone and everyone running `npm@1.3` to upgrade, even if – especially if – you've gotten it through using the official Ubuntu packages, because that means you're running an old, insecure version of Node as well. I encourage everyone using old Ubuntu- or Fedora-distributed packages for Node and npm to switch to using the [Node|Source distribution](https://github.com/nodesource/distributions) instead, which uses official builds from the Node.js build working group.

Thanks for your time and the detailed reports, everyone. I'll close this once we've rolled back the changes to the registry and given the CDN cache time to invalidate.

**Comment by kelsmj** [comment]
I was on NPM 3.3.6 and Node 5.0 and getting these issues

**Comment by othiym23** [comment]
@kelsmj Can you upload the console output to <https://gist.github.com/>? I suspect that your node process may be running a subprocess that's a Node of an older version, because by default `npm@2+` handles gzipped responses without difficulty. Thanks!

**Comment by kelsmj** [comment]
It was actually JSPM that was failing, saying it could not parse the package.json when it was trying to npm:install some of dependencies (angular, moment etc).  We don't get any verbose logging with that.  To further complicate things, we are doing all this in Docker off a base Ubuntu 14.04.2 image.  We are using an older version of JSPM, so maybe we need to upgrade that as well.

**Comment by cah-oster** [comment]
I'm using a version newer than 1.3 and getting this error:

**Comment by othiym23** [comment]
@cah-oster Until we have this change rolled back, you'll need to update to a newer version of `npm@2`, which is easily enough done with `sudo npm install -g npm@latest-2`. The changes to how npm and `npm-registry-client` handle gzipped response bodies didn't land until mid-`npm@2` release lifecycle.

**Comment by cah-oster** [comment]
othiym23 that fixed it. thanks.  I read in another issue that was closed as a duplicate of this, that npm version > 1.3 was good enough.

**Comment by othiym23** [comment]
@cah-oster Your comment caused me to dig more deeply into the source, so I was able to figure out roughly when the change had been made. Thanks!

**Comment by othiym23** [comment]
Retitled issue to reflect the underlying issue.

**Comment by mikedoug** [comment]
Is there an ETA to solving this issue?

**Comment by othiym23** [comment]
@mikedoug I believe that it should be resolved now, in that the responses returned to the npm CLI are now only gzipped if the client sends an `accepts-encoding: gzip` header, which is only done by versions of npm that can handle decoding the response, and the unconditionally compressed responses should have aged out of the cache on our CDN. Are you seeing evidence to the contrary?

**Comment by mikedoug** [comment]
It is not working here: npm http GET https://registry.npmjs.org/gulp
npm http 200 https://registry.npmjs.org/gulp
npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected token
npm ERR! �Yێ�6�C��Z�E��Zh�"@ۗ�})�/#[�n��M�`��CI��ٍ]��~0lQ�̐s�19�]�6���C�Eѕ�k|���%�Ia5#V��&#UB�2i����`
                  �qe�˶��w�ށ��f��CY�E��=�8Ж�_z���ˏQ�

**Comment by mikedoug** [comment]
We worked around it by upgrading our Node to 4.x from nodesource.com's debian packages.  This includes 2.15.0 which upgrades nicely to 2.15.2 and does not suffer from these problems.

**Comment by othiym23** [comment]
Having consulted with @npm/registry-team about the current CDN configuration for the primary npm registry, I'm going to call this issue resolved, barring some hiccups as cached metadata ages out. Please let us know if you notice new instances of this behavior, or if you're unable to get npm working. Keep in mind that you may need to run `npm cache clear` to remove inappropriately gzipped responses from your local npm cache. Thanks to everyone for information and your patience!

**Comment by hc000** [comment]
Still seeing this even after running npm cache clear.

https://gist.github.com/hc000/e2789d271743e4ddf8ebd7e6bfcc6cf4

**Comment by faust64** [comment]
+1
upgrading npm sure fixes, though older version (2.x, 1.40) are still broken, no matter what IP I've forced my DNS to resolve, ...

**Comment by larowlan** [comment]
Still seeing this on brand-new environments (ec2 instances) with no cache, but older version of npm

**Comment by krotscheck** [comment]
For those of us who are required to use the versions available on the current LTS release of ubuntu, the next LTS release (Xenial) arrives on the 21st of this month. It should have both Node 4.6.2 LTS and NPM 3.5.2.

**Comment by larowlan** [comment]
and until then...?

**Comment by jameshalsall** [comment]
@krotscheck - you can't just upgrade npm with `npm install -g npm`?

**Comment by krotscheck** [comment]
@jamiehalsall - Not if you're required to stick to LTS packages, no. Because lawyers.

@larowlan - Well, this particular issue seems to have been resolved, with old versions of content still aging out of CDN's. So until then, I'd say: Wait for the caches to reset, and hope something else doesn't break the world for us. Speaking for myself, we will likely not adopt Xenial nodes until the first flood of CVE's are addressed, so I feel your pain.

**Comment by abrarkhan1234** [comment]
hi @othiym23 I am still getting this issue. My npm version is 1.3.11. I'm not in a position to upgrade to the latest. I have run the clear cache command but still no luck.

**Comment by mattandrews** [comment]
I'm still seeing this right now, too. My npm version is 1.3.11 (node 0.10.21) and I'm somewhat restricted from being able to upgrade it. Have ran both `npm cache clear` and `npm cache clean`; still fails.

**Comment by krotscheck** [comment]
We're still seeing this issue as well, same versions.

**Comment by barbarak** [comment]
Seeing it here too: node 0.10.25 and npm 1.3.24
Would really be against upgrading due to other dependencies and company policy :(

**Comment by neilwood** [comment]
Node v0.10.21 and npm 1.3.11.  Still failing as of this morning on our build servers.  Locally it works fine with node 5.7 and npm 3.6.   We have to go through and test all of our other builds utilizing these servers before upgrading so this getting rolled back would sure help. 

 npm http GET https://registry.npmjs.org/resolve/-/resolve-0.3.1.tgz

         npm ERR! SyntaxError: Unexpected token 

         npm ERR! )"%\%)"%\%Y[o)"%\%6)"%\%+)"%\%)"%\%X)"%\%)"%\%T)"%\%%¡)"%\%!)"%\%)"%\%)"%\%a)"%\%)"%\%r)"%\%)"%\%s$C)"%\%S)"%\%A)"%\%)"%\%)"%\%8i)"%\%4N<{)"%\%)"%\%)"%\%)"%\%D)"%\%)"%\%)"%\%)"%\%)"%\%G)"%\%|)"%\%)"%\%)"%\%f%ÉfU=)"%â"]%ü+|*)"%\%)"%\%Z")"%\%b)"%\%)"%\%^%\%)"%\%T )"%\%9)"%\%8)"%\%)"%\%+{	M)"%\%)"%\%))"%\%]YWX)"%\%K3)"%\%%ª-)"%\%)"%\%()"%\%)"%\%)"%\%)"%\%p0j)"%\%y)"%\%t)"%\%)"%\%)"%\%)"%\%C)"%\%%)"%\%|a)"%\%)"%\%)"%\%)"%\%)"%\%|)"%\%)"%\%)"%\%0rk%új~)"%\%c7)"%\%l)"%\%qg)"%\%mvx)"%\%)"%\%lm)"%\%)"%\%)"%\%)"%\%*)"%\%=Z%«)"%\%)"%\%)"%\%)"%\%-)"%\%B)"%\%)"%\%})"%\%)"%\%]l5T@)"%\%)"%\%r)"%\%.:)"%\%g.)"%\%)"%\%)"%\%d%»)"%\%)"%\%)"%\%_)"%\%)"%\%A)"%\%C)"%\%K[)"%\%h%¥)"%\%U)"%\%)"%\%)"%\%1)"%\%%óI]7?)"%\%L%¼)"%\%)"%\%%½I#VOA)"%\%)"%\%n)"%\%&*)"%\%)"%\%b)"%\%!)"%\%)"%\%)"%\%)"%\%bRa)"%\%G)"%\%)"%\%I)"%\%)"%\%T)"%\%70)"%\%%%)"%\%)"%\%)"%\%)"%\%X

         npm ERR! ;)"%\%)"%\%i,%çn)"%\%{)"%\%)"%\%)"%\%)"%\%)"%\%}}9))"%\%)"%\%)"%\%)"%\%Y)"%\%)"%\%F`%í

**Comment by mdopieralski** [comment]
Same configuration as @barbarak, still getting this issue and clearing cache doesn't solve the problem.

**Comment by tambnguyen** [comment]
+1 I'm still experiencing this issue. We can't deploy to production due to the major failure with npm install.

**Comment by xanat0s9** [comment]
Please roll this back.  I am still seeing the same issue after clearing cache and this has major impact to a production rollout.

**Comment by robinboening** [comment]
We noticed this issue about 36h ago when our builds were failing and we were not able to deploy anymore. It took us hours of investigation and updating nodejs/npm in the builds. Was there any public information about that change? Where can we look to get these kind of information in the future? Thanks

**Comment by pmenocal** [comment]
Throwing in some more reports on this issue. Noticed this around the same time as @robinboening 

npm debug info:

`980 error SyntaxError: Unexpected token 
980 error ��S�j1��E�Bq������bh/
���R��J��rw�E�ڸ&��7��:�Pz03�޼�y{N�$V���D�(D�S9�7��:�!��\V���>c�
980 error ���R1F
980 error �b1�)2���j����{L�"&��=���#@�&�C��$'��=
�a�mJC\�ecS;VR���n�q�����ljL-8V�����{4V<��v ʨuLmd�4K.r��_��X{���F(b�/|V#T|���t��k��r���zβ�z�ߣ�8���
��M���c�W�7{����Ē롾�<^����1�!X�k�Ów�MB���T.唳�psCN�\�#�ϯ����U�g��nQݛ"d��Vg���%�����r�D1!�*6�7cG���ee���
6֠��/6��<�ت8��.fzN׷��n�e����ыY=W��ō��S��m�!v��T��a8U�t� ��o����r˫�w�{����Z������/_е\��9��
��=}m�+"��ȓ1�
�ِ���/���{������#Nl���~�
%�
980 error     at Object.parse (native)
980 error     at RegClient.<anonymous> (/home/codio/.nvm/v0.10.25/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:241:23)
980 error     at Request.self.callback (/home/codio/.nvm/v0.10.25/lib/node_modules/npm/node_modules/request/request.js:123:22)
980 error     at Request.EventEmitter.emit (events.js:98:17)
980 error     at Request.<anonymous> (/home/codio/.nvm/v0.10.25/lib/node_modules/npm/node_modules/request/request.js:893:14)
980 error     at Request.EventEmitter.emit (events.js:117:20)
980 error     at IncomingMessage.<anonymous> (/home/codio/.nvm/v0.10.25/lib/node_modules/npm/node_modules/request/request.js:844:12)
980 error     at IncomingMessage.EventEmitter.emit (events.js:117:20)
980 error     at _stream_readable.js:920:16
980 error     at process._tickCallback (node.js:415:13)`

**Comment by abrarkhan1234** [comment]
Can someone from npm please provide an update? Why has the issue been closed when it is clearly an ongoing concern for many. Can you confirm that the rollback has happened and if so then why are we still unable to do npm install. Cache has been cleared out too.

**Comment by xanat0s9** [comment]
I've run the same packages several times and sometimes a package will work, but sometimes it won't.  Suggesting the issue hasn't been consistently resolved/aged out at the CDN level.   Each time I run it can happen on a different package.  Might I suggest in the future that things like this are tested somewhere other than production, and that backwards compatibility is crucial?

**Comment by soldair** [comment]
hey folks.
It may be that stale objects are being served form our cdn so this morning we started purging all package metadata from the cdn. This process takes time but ill update again when it's done.

**Comment by othiym23** [comment]
I'm reopening this issue until we believe that the cache is fully purged. My apologies for closing it prematurely – the documentation for our CDN indicates that the cached metadata should have aged out in around 5-10 minutes, but that hasn't been the case. Thanks for your patience while we get this sorted out!

**Comment by tambnguyen** [comment]
FYI our app on AWS ElasticBeanstalk is finally able to run npm install without a problem, as of around 1:30pm EDT.

**Comment by othiym23** [comment]
After some painstaking sleuthing, the npm registry team and I have determined that the fix that we deployed yesterday wasn't consistently deployed across the registry. The purpose of the change was to  make sure that npm's CDN delivered correctly-encoded versions of JSON metadata got sent to the correct versions of the CLI. `npm@1` can't handle gzip-compressed responses, so your builds are failing when the CDN incorrectly delivers a gzip-encoded body. Now that we've identified the problem, we're waiting for two things to complete before we call this completely fixed and close this issue again:

1. The correct code and configuration is verified to be deployed across our infrastructure.
2. A process that @soldair is running to incrementally invalidate cached metadata runs to completion (busting the entire cache at once imposes an enormous amount of load on the registry, and is only used for critical emergencies).

When both of those things have finished, I'll re-close this issue as a signal that we believe you should no longer see build failures, so you can let us know if the problem isn't completely addressed. Thanks for your patience as we work through this.

**Comment by mattandrews** [comment]
Thank you for finding the source of this and fixing it! I'm going to make the effort to get my internal npm version upgraded in light of this, so thanks for the (inadvertant) push! Appreciate you spending the time to get this right :)

**Comment by othiym23** [comment]
Since the cache invalidation process is now complete, and we believe that the infrastructure is now running the correct code to send appropriate responses to all versions of the CLI, I'm going to re-close this issue. If you run into issues where you're getting corrupt responses, please first try clearing your local cache (`npm cache clean`) and then rerunning the process, but if the issue persists, please let us know here or via support@npmjs.com. Thanks once again to all for their assistance and patience!

**Comment by jogendrajangid1** [comment]
Hi @othiym23 we are still facing npm ERR! registry error parsing json on node v0.10.26 and npm 1.4.3

npm http 200 https://registry.npmjs.org/extsprintf/1.0.2
npm ERR! registry error parsing json
npm http GET https://registry.npmjs.org/graceful-readlink
npm http 200 https://registry.npmjs.org/cryptiles
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/root/node-v0.10.26-linux-x64/bin/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/test/json-schema-draft4'
npm ERR! error rolling back  request@2.70.0 { [Error: ENOTEMPTY, rmdir '/root/node-v0.10.26-linux-x64/bin/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/test/json-schema-draft4']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/root/node-v0.10.26-linux-x64/bin/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/test/json-schema-draft4' }
npm ERR! SyntaxError: Unexpected token 
npm ERR! �Q�N� ����hg�k�٫O���1
                                    ����tZ���g\} ��9�p��1�	|���6qG��>hk�)�"
npm ERR! ����3��`������k����B�N\�zݰ�0�T��l�����G'���:������f
                                                                �nl��S�N��e�*�f��xZ0�6H�FR����ӊr��$[�P�B��}I��,�N�qH=9�����V�7�*�W�5���C^��X�;U��F��'�]��zhQ�OԸa�����,���|ۯd|��/��sZ�����>��]��Mc���@?
                                               5&�{ărĿ����$�D���7	G8�
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/root/node-v0.10.26-linux-x64/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:203:23)
npm ERR!     at Request.self.callback (/root/node-v0.10.26-linux-x64/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/root/node-v0.10.26-linux-x64/lib/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/root/node-v0.10.26-linux-x64/lib/node_modules/npm/node_modules/request/request.js:844:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/root/node-v0.10.26-linux-x64/bin/node" "/root/node-v0.10.26-linux-x64/bin/npm" "install" "request"
npm ERR! cwd /root/node-v0.10.26-linux-x64/bin
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! type unexpected_token
npm http 200 https://registry.npmjs.org/json-schema/0.2.

**Comment by mdopieralski** [comment]
Hi @othiym23, I'd like to admire that we really appreciate the effort that npm team's putting to fix that problem, but it's still occuring :disappointed:

**Comment by Ronfladonf** [comment]
Hi 
Tried this morning  and I have this error too 

npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected token 
�{w-9�ۃ@h9��̈X�PY׉�b��K������O��P�P�!h/AaP�J�#�I�i
FG�Nh��Y�|8�W����hQ�4yPPu-���;��Yc;��b�z_$I����L����U$1��:V�i���c6��)r�S��2�����x��2�bUЃQ`�
                                                                                                          t@����`j�Fΐ���L�}��|�����-�%�=��$1
                                                                                                                                               �d�,��8����_Sy��D�!fҚ�t9K[��(�q����
}o]�7 ;��q��[�S��|L��g��w��NA%�6�G+ԅJihG�~��L��y*�\���m�ݬ��6����j�U�VU.U	p��A�R��t�Y��pP#��M
                                                                                                   �{n]�\�j��=���C����VH�P�ځ���%��?\5
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/home/sribiere/.nvm/v0.10.26/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:203:23)
npm ERR!     at Request.self.callback (/home/sribiere/.nvm/v0.10.26/lib/node_modules/npm/node_modules/request/request.js:123:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/home/sribiere/.nvm/v0.10.26/lib/node_modules/npm/node_modules/request/request.js:893:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/home/sribiere/.nvm/v0.10.26/lib/node_modules/npm/node_modules/request/request.js:844:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.2.0-101-generic
npm ERR! command "/home/sribiere/.nvm/v0.10.26/bin/node" "/home/sribiere/.nvm/v0.10.26/bin/npm" "i"
npm ERR! cwd /home/sribiere/src/AFCHELSINK/GTO/gto_api_card_access/trunk
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! type unexpected_token

**Comment by mdopieralski** [comment]
So, finally we managed to fix it by upgrade'ing node_js on travis to 4.2.0, and npm to 3.3.6. Both set in package.json "engines" property.

**Comment by jogendrajangid1** [comment]
#12251

**Comment by beloha** [comment]
Same issue here.
We are stucked with npm 1.4.3 and node 0.10.26 and this pb is blocking our deliveries.

**Comment by beloha** [comment]
We managed to update to npm version 1.4.5 and we don't have the issue anymore.
Hope we don't face such regression later...

**Comment by soldair** [comment]
The invalidation process is still running. there are LOTS of packages now =). This was a miscommunication cross teams but we'll update again soon when its actually done purging everything.

**Comment by soldair** [comment]
the invalidation process is complete. Invalid responses should no longer be possible from our servers.
Please let us know if you run into this issue.

**Comment by mrjefftang** [comment]
@soldair Still getting invalid responses.

```
npm ERR! node -v v0.8.24
npm ERR! npm -v 1.2.24
npm http 200 https://registry.npmjs.org/pause/0.0.1
npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected token
...
npm http 200 https://registry.npmjs.org/range-parser/0.0.4
npm http GET https://registry.npmjs.org/range-parser/-/range-parser-0.0.4.tgz
npm ERR! SyntaxError: Unexpected token
...
npm http 200 https://registry.npmjs.org/optimist/0.3.7
npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected token
...
npm http GET https://registry.npmjs.org/connect/2.9.0
npm http 200 https://registry.npmjs.org/connect/2.9.0
npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected token
```

**Comment by terenya-aleksandr** [comment]
Still getting the same errors

**Comment by soldair** [comment]
this is my oversight i need smarter invalidation. The older npm clients pull specific verisons by url directly whereas the suported clients pull the top level document. I apologize again for the delay in resolving this and now that we've found another case ill update again soon.

**Comment by soldair** [comment]
@mrjefftang how do things look for you now? The per version invalidation is still in progress but i verified the urls in your issue comment have been purged.

**Comment by terenya-aleksandr** [comment]
npm http 200 https://registry.npmjs.org/concat-map/0.0.1
npm ERR! registry error parsing json
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/grunt-cli/node_modules/findup-sync/node_modules/glob/node_modules/inflight/node_modules/wrappy'
npm ERR! error rolling back  glob@5.0.15 { [Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/grunt-cli/node_modules/findup-sync/node_modules/glob/node_modules/inflight/node_modules/wrappy']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/grunt-cli/node_modules/findup-sync/node_modules/glob/node_modules/inflight/node_modules/wrappy' }
npm http 200 https://registry.npmjs.org/balanced-match
npm http GET https://registry.npmjs.org/balanced-match/-/balanced-match-0.3.0.tgz
npm ERR! SyntaxError: Unexpected token
xldQ=T7o>|bFmYaM!Tp+
y0%j               IAM!;:u0oO,;"twx1yaxjz)VhRToE_mwAXE
npm ERR!
npm ERR! 4'D5zXP>~1dZD&t?0Hu:08/xB>.=~eu$2o|M.+ZGkQ!t_6"m6Rl]Cne:#V|hP(|dgP@;=P
{1Uzn4}!        ;QQ
E      U.,l,MHs"YE
 q;r[We:Ee=$h8)E#y};=oT
                       @6
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:238:23)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.1.13-boot2docker
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "grunt-cli"
npm ERR! cwd /devops/docker/ansible
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type unexpected_token
npm http 200 https://registry.npmjs.org/balanced-match/-/balanced-match-0.3.0.tgz
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /devops/docker/ansible/npm-debug.log
npm ERR! not ok code 0

**Comment by soldair** [comment]
thanks @terenya-aleksandr ill look at these! note that if you don't run `npm cache clear` we respond with the same etag so it may use a garbled version from cache.

**Comment by mrjefftang** [comment]
Thanks @soldair that fixed it for all of my package dependencies.

**Comment by soldair** [comment]
@terenya-aleksandr concat-map/0.0.1 was not in my invalidation list yet. i ran just that one and /balanced-match for good measure. its really hard to tell whats going on because logging was so racy in those versions. helps?

**Comment by soldair** [comment]
just so anyone still effected knows my strategy. 
I'm pulling every url y'all have requested with the patterns used by the effected older npm versions from massive logs generated the past couple days. 

Hopefully this will ensure we don't miss anything folks are actually using. These old urls had support for dynamic version ranges and things that makes it impossible to generate the url strings any other way. 

Please post module version urls you are still having issues with and ill look into each to make sure we have everything sorted out. Don't forget to `npm cache clear` if it's applicable to your build setup though! =)

**Comment by chiefy** [comment]
```
09:16:35 npm http GET https://registry.npmjs.org/serve-index/-/serve-index-1.7.3.tgz
09:16:35 npm ERR! SyntaxError: Unexpected token 
09:16:35 npm ERR! ��R=O�0�+���qh(U$Pl�"'��.�m�N�P��sN��	�X֝�����(��H�,S)Ȍ��:�M(ÊWZi�X}�{p�Ʊh����hK��	��J�%W��Fx��������˾@�����[C3b�h'��}���	4k`:@���1�����6Q��#�bh��bjn]��j��
���n#FST���2?��.��QR�>MV�'{
(���,`w�E=��ߝ|�����\�m���s�	��,�r�P�T�1���uh�x�x󬹘`�,r����X%��P�U�؊A7X-ҊIQ����s[�&ĵ��`^j��=Es��j[�3����|����딠�Q
09:16:35 npm ERR! �����?a|���B�������>�;
09:16:35 npm ERR!     at Object.parse (native)
09:16:35 npm ERR!     at RegClient.<anonymous> (/usr/lib/node_modules/npm-registry-client/lib/request.js:238:23)
09:16:35 npm ERR!     at Request.self.callback (/usr/lib/node_modules/request/index.js:148:22)
09:16:35 npm ERR!     at Request.emit (events.js:98:17)
09:16:35 npm ERR!     at Request.<anonymous> (/usr/lib/node_modules/request/index.js:891:14)
09:16:35 npm ERR!     at Request.emit (events.js:117:20)
09:16:35 npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/node_modules/request/index.js:842:12)
09:16:35 npm ERR!     at IncomingMessage.emit (events.js:117:20)
09:16:35 npm ERR!     at _stream_readable.js:943:16
09:16:35 npm ERR!     at process._tickCallback (node.js:419:13)
09:16:35 npm ERR! If you need help, you may report this log at:
09:16:35 npm ERR!     <http://github.com/isaacs/npm/issues>
09:16:35 npm ERR! or email it to:
09:16:35 npm ERR!     <npm-@googlegroups.com>
09:16:35 
09:16:35 npm ERR! System Linux 3.10.0-123.el7.x86_64
09:16:35 npm ERR! command "node" "/usr/bin/npm" "install" "--development"
09:16:35 npm ERR! cwd /home/xxx
09:16:35 npm ERR! node -v v0.10.33
09:16:35 npm ERR! npm -v 1.3.6
09:16:35 npm ERR! type unexpected_token
```

**Comment by soldair** [comment]
@chiefy i need a bit more log data to see the url that had the encoding issue. the logging is very racey
If you could [make a gist](https://gist.github.com/) with your npm-debug.log contents i can figure out exactly the requests with the issue.

Anyone still experiencing the issue can feel free to contact us through support@npmjs.com so we can track these as regular tickets. I dont want to miss anyone.

**Comment by terenya-aleksandr** [comment]
@soldair 
npm http 304 https://registry.npmjs.org/is-property
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/sites/evessio/apps/evessio/evessio-admin/npm-debug.log
npm ERR! not ok code 0

**Comment by soldair** [comment]
@terenya-aleksandr could we move this to ticket via an email to support@npmjs.com so i can helkp you more directly? and or I need a gist to your npm-debug.log

**Comment by terenya-aleksandr** [comment]
npm http 200 https://registry.npmjs.org/tiny-lr-fork/0.0.5
npm ERR! registry error parsing json
npm http 200 https://registry.npmjs.org/sugar/-/sugar-1.4.1.tgz
npm http 200 https://registry.npmjs.org/open/0.0.5
npm http 200 https://registry.npmjs.org/gaze
npm http GET https://registry.npmjs.org/qs/-/qs-1.2.2.tgz
npm http GET https://registry.npmjs.org/istanbul/-/istanbul-0.3.22.tgz
npm http 200 https://registry.npmjs.org/connect-livereload
npm http 304 https://registry.npmjs.org/connect
npm ERR! SyntaxError: Unexpected token
npm ERR!TN0(q^IP
                hZKU!'$%qCR
                           x|w}cl
                                 {Q     m+
BEz@_0Z#U=                                )jmT
npm ERR! Ynkk^EvGn%"QiLGyp6q\k(M/Z[yBC]dM(bI]3
                                              Vf@?t'`)
                                                      kl8RT5hgoa
npm ERR! Dhf7JNrK~998
N^+
npm ERR! H;E⌂3+(E#K7#J+8X8O8fy4}O7

**Comment by soldair** [comment]
@terenya-aleksandr i cleared open/0.0.5 and tiny-lr-fork/0.0.5. lets continue in a support ticket if you are still having issues so we can use this more for status announcements. support@npmjs.com

**Comment by terenya-aleksandr** [comment]
@soldair thanks. Ok, let's continue in a support ticket.

**Comment by soldair** [comment]
ok folks. We setup a process that will catch anything that you might have an issue with that we haven't been able to purge manually. this change resolves this issue. 

If you get an encoding error please npm cache clear. wait 20 or so seconds and try again. 
If you continue to get the error please send a support request to support@npmjs.com along with your npm-debug.log so i can help you directly.

**Comment by soldair** [comment]
we had a some valid package names that were incorrectly filtered by a regular expression. this should be resolved now for you folks using socket.io-client etc =)

**Comment by sarsenault** [comment]
Still seeing errors while using Kappa to proxy the npm registry. There is an update that can handle the gzipped packages that works fine, but with an old install it still doesn't seem to be working any better yet. Unfortunately, there isn't any npm-debug.log since it is a proxy client, but I am noticing that every package with the version in the url (eg. /angular-messages/-/angular-messages-1.4.8.tgz) is fine, while those directly querying (eg. /angular-annotorious) are having failures. 

Is this because you are checking the client string? The proxy server will pass along the client npm version in the request, which could be high enough to handle gzipped content (eg v3.8.3) but the proxy itself doesn't necessarily know to expect gzipped content. I assume given this that older Kappa versions will be permanently broken, for anyone else with similar problems.

**Comment by barbarak** [comment]
What was not working for me now is, I think you make have cracked it :)

**Comment by sirLisko** [comment]
Same here. Thanks a lot guys :)

**Comment by soldair** [comment]
@sarsenault we are not checking agent strings. if the proxy passes `accept-encoding: gzip` through from the npm client but does not support gzip responses for json it then it probably won't work. The proxy would have to strip the accept-encoding header on the way to the registry.

tarballs are always gzip and the npm client itself unpacks them. There was no change there so it makes sense that this would work.

**Comment by chiefy** [comment]
fwiw, npm did a [post-mortem](https://www.youtube.com/watch?v=vLcOkHhEt1g) on this subject. thank you @othiym23 @soldair !
