### ISSUE TITLE
npm installer not able to install ionic 1.3.19

### ISSUE THREAD

**Issue by pushparajsamant** [npm/npm#12673]
```
npm ERR! fetch failed https://registry.npmjs.org/i/-/i-0.3.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 504
npm ERR! fetch failed https://registry.npmjs.org/i/-/i-0.3.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 504
npm ERR! fetch failed https://registry.npmjs.org/i/-/i-0.3.2.tgz
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ionic@1.3.19"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12

npm ERR! fetch failed with status code 504
```

**Comment by chatterburger97** [comment]
@pushparajsamant , I get the same error while trying to install ionic version 1.3.1 using npm. 
I tried to fix the problem in the following ways. Please do let me know if you find a solution. 

1) `npm install ionic@1.3.1`

2) `npm install https://registry.npmjs.org/ionic/-/ionic-1.3.1.tgz` - this is the repository hosted on npmjs

3) I opened the url above using a browser, and downloaded the corresponding tar.gz file. Then proceeded to run the command `npm install <tarball>` to the tarball sitting on my file system.

4)  I have tried uninstalling and reinstalling nodejs and npm using  brew. Even after doing so I get the same error that I get in the above three cases^

Error output:
```
npm ERR! fetch failed https://registry.npmjs.org/i/-/i-0.3.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 504
npm ERR! fetch failed https://registry.npmjs.org/i/-/i-0.3.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 504
npm ERR! fetch failed https://registry.npmjs.org/i/-/i-0.3.2.tgz
npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/home/user/.linuxbrew/Cellar/node/6.4.0/bin/node" "/home/user/.linuxbrew/bin/npm" "install" "-g" "https://registry.npmjs.org/ionic/-/ionic-1.3.1.tgz"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3

npm ERR! fetch failed with status code 504
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/Downloads/npm-debug.log
```
Note: ` npm install ionic` works fine, but installs the latest version (ionic 2.0.0 CLI and libraries) - and I would like my old version back. 
[npm-debug.log.zip](https://github.com/npm/npm/files/427626/npm-debug.log.zip)

**Comment by tyronedougherty** [comment]
+1, I'm getting the exact same issue here trying to `sudo npm install ionic@1.3.1 -g`. Anyone have a fix?

**Comment by redwildfire13** [comment]
+1, I'm also getting the same issue. It looks like npm is looking in the wrong place as it checks https://registry.npmjs.org/i/-/i-0.3.2.tgz instead of https://registry.npmjs.org/ionic/-/ionic-1.3.1.tgz

**Comment by KenanY** [comment]
Is this still an issue with newer versions of `ionic` (like, say `1.7`)?

**Comment by redwildfire13** [comment]
`npm install -g ionic@1.7` successfully installed ionic 1.7.16.

**Comment by PatrickKelly** [comment]
+1 Seeing as well for 1.3.1

**Comment by KenanY** [comment]
Sounds like this has been resolved with newer versions of `ionic`.

**Comment by samrocksc** [comment]
This issue still persists for trying to use 1.3 versions of ionic.

**Comment by KenanY** [comment]
@samrocksc Yup, fortunately it's fixed in newer versions.

**Comment by DuaneNielsen** [comment]
Fixed in newer version so issue closed?  I always thought that one of the features of a package management system was you were able to retrieve older versions.

**Comment by KenanY** [comment]
@DuaneNielsen The old versions depend `i@0.3.2` which was unpublished from the registry. `¯\_(ツ)_/¯`

**Comment by ahmedsafwat** [comment]
Just in case if any one still interested in installing ionic 1.3.19 or 1.3.2 you can easily follow these steps:

1- Download the ionic package from npm registry : https://registry.npmjs.org/ionic/-/ionic-1.3.19.tgz
2- If you're using windows open the archive using 7zip and edit npm-shrinkwrap.json 
3- Modify the "i" dependency to be as following:
"i": {
              "version": "0.3.3",
              "from": "i@>=0.3.0 <0.4.0",
              "resolved": "https://registry.npmjs.org/i/-/i-0.3.3.tgz"
            }

4- Install the package manually 
ex: npm install -g C:\ionic\ionic-1.3.2.tgz
