### ISSUE TITLE
"Error: This socket is closed" when running any npm command

### ISSUE THREAD

**Issue by petschekr** [npm/npm#12887]
I upgraded to Windows 10 Build 14352 (Insider Preview Fast Ring) overnight and it appears to have broken npm in some way.
For any command (such as `npm help`):

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
    at WriteStream.Socket._writeGeneric (net.js:672:19)
    at WriteStream.Socket._write (net.js:724:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at WriteStream.Writable.write (_stream_writable.js:220:11)
    at WriteStream.Socket.write (net.js:650:40)
    at WriteStream.stream.write (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\newlines.js:36:21)
    at Cursor.write (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\ansi.js:157:23)
    at Cursor.(anonymous function) [as show] (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\ansi.js:226:26)
    at Object.ProgressBar.hide (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\gauge\progress-bar.js:101:15)

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link,
    list, ln, logout, ls, outdated, owner, pack, ping, prefix,
    prune, publish, rb, rebuild, repo, restart, root, run,
    run-script, s, se, search, set, shrinkwrap, star, stars,
    start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\Ryan\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.8.9 C:\Program Files\nodejs\node_modules\npm
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
    at WriteStream.Socket._writeGeneric (net.js:672:19)
    at WriteStream.Socket._write (net.js:724:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at WriteStream.Writable.write (_stream_writable.js:220:11)
    at WriteStream.Socket.write (net.js:650:40)
    at WriteStream.stream.write (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\newlines.js:36:21)
    at Cursor.write (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\ansi.js:157:23)
    at Cursor.(anonymous function) [as show] (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\ansi.js:226:26)
    at Object.ProgressBar.hide (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\gauge\progress-bar.js:101:15)
```

Other commands like `npm -v` also have a similar output with the output of the command surrounded by `Error: This socket is closed` stacktraces. However, `npm install` does not seem to work at all:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
    at WriteStream.Socket._writeGeneric (net.js:672:19)
    at WriteStream.Socket._write (net.js:724:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at WriteStream.Writable.write (_stream_writable.js:220:11)
    at WriteStream.Socket.write (net.js:650:40)
    at WriteStream.stream.write (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\newlines.js:36:21)
    at Cursor.write (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\ansi.js:157:23)
    at Cursor.(anonymous function) [as show] (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\ansi.js:226:26)
    at Object.ProgressBar.hide (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\gauge\progress-bar.js:101:15)
 events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
    at WriteStream.Socket._writeGeneric (net.js:672:19)
    at WriteStream.Socket._write (net.js:724:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at WriteStream.Writable.write (_stream_writable.js:220:11)
    at WriteStream.Socket.write (net.js:650:40)
    at WriteStream.stream.write (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\newlines.js:36:21)
    at Cursor.write (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\ansi.js:157:23)
    at Cursor.(anonymous function) [as show] (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\ansi.js:226:26)
    at Object.ProgressBar.hide (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\node_modules\gauge\progress-bar.js:101:15)
```

I've tried reinstalling the latest version of node (v6.2.0) and deleting temp files but neither fix the problem.
I'm assuming that this has something to do with the new build of Windows because everything was working just fine yesterday. I might try to run the current failing build in a clean VM to see if it really is the issue.

`node -v: v6.2.0`
`npm -v: 3.8.9`

**Comment by petschekr** [comment]
Reverting to Build 14342 confirms that this issue is specific to the latest Windows 10 build (Build 14352 ).

**Comment by michaellashinsky** [comment]
I have the same issue but only when I execute npm in something other than a regular cmd.exe window.  If I use git bash, or cmd.exe from within Intellij the issue occurs.

**Comment by EvNaverniouk** [comment]
I thought I was going crazy. I have this same problem as well and also after upgrading Windows 10, however, in my case mine is Build 14352,

This is happening for me in the regular `cmd.exe` window as well as in the `Git bash` window and occurs for any npm command that makes network requests (ie. `npm install`, `npm outdated`, `npm info`, etc...)

**Comment by michaellashinsky** [comment]
My cmd.exe works I think mostly in part to how I updated npm.  I opened an admin cmd.exe, changed directory to nodejs and ran npm i -g npm@latest just to see if it would fix the issue. Here's my output from running npm -v:

```
Microsoft Windows [Version 10.0.14352]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\micha>npm -v
3.9.3

C:\Users\micha>
```

**Comment by randallmeeker** [comment]
running from `npm i -g npm@latest` from the nodejs directory does nothing. Still presents the same error. 

> Error: This socket is closed.

**Comment by randallmeeker** [comment]
re-installed node 4.4.5 (downgraded from v5) and it all works now.

**Comment by randallmeeker** [comment]
Downgraded node to 4.4 (from v5). Now `npm -v` works, but other commands `npm start` `npm help` all result in the same "socket is closed error"

**Comment by karn09** [comment]
Just came across this issue after upgrading Windows 10. NPM seems to work as expected if using PowerShell or CMD - however from within Cmder I receive the same error.

**Comment by randallmeeker** [comment]
I was about to argue the point, because it was not working in mine. But I restarted power shell to confirm. Then it was working, then I tried a few more commands and it stopped working again? 

So I started a new powershell window. Ran `npm help` works as expected. I open a second powershell and run the exact same command in the exact same directory and get an error. See attached. Super erratic window. I would ask that any who says its "Working" check for "consistently working"

 
![image](https://cloud.githubusercontent.com/assets/2538537/15636686/0a3672ea-25cd-11e6-87ea-c08f1092e5a1.png)

**Comment by paulcbetts** [comment]
Disabling progress in npm will let you at least install packages, but everything else is indeed still borked :(

**Comment by casfnq** [comment]
I have two command windows open (both from cmd.exe) one works and the other doesn't.  running build 14352.

**Comment by jefbarn** [comment]
I find that I only see this issue if I change the width of the console away from the default .

**Comment by randallmeeker** [comment]
confirmed. it has to do with window re-sizing.

**Comment by randallmeeker** [comment]
@casfnq that link is not a link?

**Comment by casfnq** [comment]
@randallmeeker  that is a Windows 10 feedback hub link.  Feedback Hub is for direct MS feedback within Windows 10 Insider builds.

**Comment by casfnq** [comment]
@jefbarn @randallmeeker yes I agree, and confirm.  Open window standard and even increase the height, no issue.  change the width and it occurs.

**Comment by BaronVonPerko** [comment]
Yep, not touching the width of the git bash prompt has fixed my issues.

**Comment by john-osullivan** [comment]
Ran into the same issue, fixed it by changing the window width within preferences and saving.  Super funky bug, but at least there's a work-around?

**Comment by michaellashinsky** [comment]
Using the legacy mode for terminal also appears to work.

**Comment by LawlietBlack** [comment]
I had the same problem, can confirm that opening a plain cmd window and leaving the size unchanged was an effective workaround. Using console modifiers like console2 or cmder that have their own preferences seem to break it upon opening, possibly because they change the dimensions as well.

**Comment by casfnq** [comment]
The issue with the standard windows cmd, is only on width.  Altering the height does not cause the issue to occur.

**Comment by leocavalcante** [comment]
That is the strangest bug I have saw.
I'm using Cmder. Just need to avoid resize the window to make npm work.

**Comment by jefbarn** [comment]
Another possible workaround:
> cd C:\Users\Jeff\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog
> npm install gauge@latest --save

**Comment by michaellashinsky** [comment]
Good news, it does appear that this issue is not in the latest Build of 14361.

**Comment by randallmeeker** [comment]
Build of 14361 still gets the same error for me. All the work arounds seem to work though, so . . . . I so far don't find I'm resizing my window too often for it to be a problem, or when it happens I restart my console. Otherwise I just use `--no-progress`

**Comment by michaellashinsky** [comment]
Odd I just installed it on a clean machine clean node and I can resize without issue.  Upgrading gauge per @jefbarn worked previously.

**Comment by randallmeeker** [comment]
@michaellashinsky  hmmm, what version of node / npm?

**Comment by michaellashinsky** [comment]
@randallmeeker nodejs: 6.2.1 and npm: 3.9.3

**Comment by jRoadie** [comment]
@all issues is fixed in nodejs 6.2.1

**Comment by UziTech** [comment]
nope still an issue

node: 6.2.1
npm: 3.9.5

**Comment by randallmeeker** [comment]
Its fixed, its not fixed, its now fixed for everyone, its not fixed for everyone. . . . . hehehe, I love this bug.

**Comment by michaellashinsky** [comment]
@UziTech do you still see the issue in Windows 10 build 14361

**Comment by michaellashinsky** [comment]
@randallmeeker this bug is starting to feel like my day job ;)

**Comment by UziTech** [comment]
didn't work after updating to 14361 initially but after I updated gauge with @jefbarn fix I don't get the error any more :+1: 

node: 6.2.1
npm: 3.9.5
windows 10: 14361
gauge: 2.5.0

**Comment by randallmeeker** [comment]
does gauge need to be installed globally for it to work as a fix?

**Comment by UziTech** [comment]
I didn't install it globally

**Comment by randallmeeker** [comment]
hmmm, well `gauge@latest` does nothing for me, locally or globally. Granted I'm still on node 4.x. To ensure compatibility with production environments I'm not eager to upgrade to 6.x

**Comment by leocavalcante** [comment]
Sorry about the off-topic, but @randallmeeker, Node 6 is ready for production, it includes improvements on performance, reliability, usability and security. If you have a good code coverage in your tests, there is no fear on upgrade ;)

**Comment by petschekr** [comment]
Still seeing this issue after resizing the width of the cmd.exe console on Build 14361. PowerShell and Git Bash seem to work fine after resizing, however.

**Comment by UziTech** [comment]
@petschekr did you update gauge?

**Comment by petschekr** [comment]
@UziTech I didn't because there isn't a `npm` or `npmlog` directory under `C:\Users\Ryan\AppData\Roaming\npm\node_modules`

**Comment by UziTech** [comment]
@petschekr what version of npm do you have?

**Comment by petschekr** [comment]
@UziTech 3.9.3 on Node.js v6.2.1

**Comment by UziTech** [comment]
try searching for gauge in `.../npm/node_modules/`

![image](https://cloud.githubusercontent.com/assets/97994/15971914/244d13fe-2f01-11e6-977e-80416d8f2d1f.png)

**Comment by UziTech** [comment]
here is what my `.../npm/node_modules/` folder looks like

![image](https://cloud.githubusercontent.com/assets/97994/15971973/6e3cb406-2f01-11e6-9c7d-bd4f50174ea4.png)

**Comment by petschekr** [comment]
Hmm weird. This is all that I've got in that directory:

![2016-06-10 1](https://cloud.githubusercontent.com/assets/1111373/15972173/df8e3036-2f0a-11e6-8897-751aa4ae62db.png)

I did, however, find gauge at `C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog` and running `npm install gauge@latest --save` there as administrator fixed the issue.

**Comment by jefbarn** [comment]
There are several nested levels of 'node_modules', you need to go deeper.....
....\npm\node_modules\npm\node_modules\npmlog

**Comment by DaveMiscampbell** [comment]
Can confirm that updating gauge to latest fixed this for me.

The directory I had to install it to was `C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog`.

node: 4.4.3
npm: 3.8.9
Windows 10: 14361

**Comment by joshgav** [comment]
This seems to come down to [these lines](https://github.com/TooTallNate/ansi.js/blob/master/lib/ansi.js#L219-L229) in [TooTallNate/ansi.js](https://github.com/TooTallNate/ansi.js).

The code for `show` is defined [here](https://github.com/TooTallNate/ansi.js/blob/master/lib/ansi.js#L38) as `?25h`, that may not be working on latest console.

**Comment by zadjii-msft** [comment]
Hey everybody,

I'm an engineer on the windows console team, and I've been investigating this a little bit on our end. It seems as though yes, resizing the console window (any conhost window, cmd, powershell, bash.exe, etc) could cause that particular exception to get thrown by npm. Turns out it was an exception in the lower levels of conhost itself.

 I'm happy to say that fortunately, this has **already been fixed**, and should be on it's way out to insiders soon<sup>tm</sup>, however the best I can say is that it should be fixed when the Anniversary Update officially ships.

Sorry for any troubles this regression may have accidentally caused!

**Comment by razy69** [comment]
Hi,

I got the same issue on Windows 10 Pro build 14388.
I'm running on the latest nodejs version 6.3.3.

To fix this i used to remove 'npm-cache' and 'npm' folders from 'appdata'.
Then i repair nodejs (Control Panel / Programs and Features / NodeJS).

I try 'npm install -g npm@latest' and it works (i got 'This socket is closed' before this 'fix')

**Comment by henningms** [comment]
I still get this issue on Windows 10 Insider Build 14936.

**Comment by jonh88** [comment]
i'm getting this issue running the following command "appium --session-override" from python script. The fact is that it started to happend suddenly.... i'm in ubuntu 16.04. It's also funny that when I run the command directly from cmd it does not happend... :D. I don't know why this is happening but definitely is not because of window resizing. I hope this helps...

**Comment by NicolasParada** [comment]
I'm getting this issue again 😪

Windows 10 build 14393.447
Node v7.1.0
npm 4.0.2

**Comment by PascaleBeier** [comment]
Same setup here as @NicolasParada - does not work in CMD or PowerShell, does work however on git bash. :dancing_women:

**Comment by legodude17** [comment]
@zadjii-msft, any news?

**Comment by DavidChristiansen** [comment]
Likewise, An update would be very much appreciated.  Fresh windows install, node 7.1.0, npm 4.0.2

**Comment by zadjii-msft** [comment]
It appears this is https://github.com/nodejs/node/issues/9542

**Comment by legodude17** [comment]
Ok. If you still have this issue, go to nodejs/node#9542.

**Comment by jquintozamora** [comment]
I was using Windows 10 + Node 7.1 and I had the same error.

npm ERR!events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed
    at WriteStream.Socket._writeGeneric (net.js:683:19)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at WriteStream.stream.write (C:\Users\Jose\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\newlines.js:36:21)
    at Cursor.write (C:\Users\Jose\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\ansi.js:157:23)
    at Colorer.setColorCode [as _setColorCode] (C:\Users\Jose\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\ansi.js:209:38)
    at Colorer.(anonymous function) [as white] (C:\Users\Jose\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog\node_modules\ansi\lib\ansi.js:263:10)



**Fixed for me using Node version 6.9.1**

**Comment by AbrantesMar** [comment]
Hello, on my windows 10, I uninstalled node v 7.1.0 and reinstalled 6.9.1, and it worked normally ...

The error was:

Error: This socket is closed at WriteStream.Socket._writeGeneric (net.js:683:19) at WriteStream.Socket._write (net.js:734:8) at doWrite (_stream_writable.js:334:12) at writeOrBuffer (_stream_writable.js:320:5) at WriteStream.Writable.write (_stream_writable.js:247:11) at WriteStream.Socket.write (net.js:661:40) at WriteStream.stream.write (C:\Users\m.nunes.abrantes\Documents\Projeto\react_ative\testereact\node_modules\ansi\lib\newlines.js:36:21) at Console.warn (console.js:51:16) at process.on (internal/process/warning.js:21:17) at emitOne (events.js:96:13)

**Comment by JEEVANJGA** [comment]
@jquintozamora ,
Thanks for the insight.

going back from node version 7.10 to 6.91, helped me to resolve similar issues while initializing web projects while using both polymer-cli and yoeman.

**Comment by NicolasParada** [comment]
This was solved in v7.2.0.

**Comment by jux-t** [comment]
Can confirm with @NicolasParada.

This issue is fixed with:
Node@v7.2.0|v7.2.1
NPM@v4.0.3
