### ISSUE TITLE
I met an installation problem NPM run-script build 

### ISSUE THREAD

**Issue by toufuccc** [npm/npm#13558]
#### I'm opening this issue because:

  - [x] npm is producing an incorrect install.

#### What's going wrong?
npm run-script build

### supporting information:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run-script',
1 verbose cli   'build' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 verbose stack Error: missing script: build
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:311:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:455:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
5 verbose cwd C:\PokemonGo-Map
6 error Windows_NT 6.3.9600
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "build"
8 error node v6.3.1
9 error npm  v3.10.3
10 error missing script: build
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by KenanY** [comment]
@toufuccc 

```
4 verbose stack Error: missing script: build
```

Do you have a `"build"` script defined in your `package.json`?

**Comment by toufuccc** [comment]
@KenanY   yes  I have a script in package.json ！

**Comment by KenanY** [comment]
@toufuccc Can I see your `package.json` then?

**Comment by toufuccc** [comment]
@KenanY  I get! thank you very much!

**Comment by KenanY** [comment]
@toufuccc Do you mean that your issue has been resolved?

**Comment by toufuccc** [comment]
@KenanY  Not resolved, after the re structure is still so, but it does not seem to affect my work, so I ignored it

**Comment by toufuccc** [comment]
@KenanY  Does this have any bad effect on it ？

**Comment by KenanY** [comment]
@toufuccc If it's not an issue for you anymore then feel free to close this issue.

**Comment by toufuccc** [comment]
@KenanY  Thank you help

**Comment by KenanY** [comment]
Closing as resolved.
