### ISSUE TITLE
Latest NPM version on windows doesn't finish installing.

### ISSUE THREAD

**Issue by martinheidegger** [npm/npm#13722]
#### I'm opening this issue because:

Its not possible to install `learnyounode` or `javascripting` on windows.

#### What's going wrong?

It is stuck during installation.

#### How can the CLI team reproduce the problem?

Try to install `learnyounode` or `javascripting` with `-g`

### supporting information:

 - `npm -v` prints: 3.10.6
 - `node -v` prints: 4.5.0 (also tried with other versions)
 - `npm config get registry` prints: https://registry.npmjs.org
 - Windows 10

**Comment by martinheidegger** [comment]
Here is the verbose output
```
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\semver-b34da655
npm verb tar unpack C:\Users\hiroko\AppData\Roaming\npm-cache\rc\1.1.6\package.tgz
npm verb tar unpacking to C:\Program Files (x86)\Nodist\bin\node_modules\.staging\rc-409557f7
npm verb gentlyRm don't care about contents; nu verbose outputking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\rc-409557f7
npm verb tar unpack C:\Users\hiroko\AppData\Roaming\npm-cache\strip-json-comments\1.0.4\package.tgz
npm verb tar unpacking to C:\Program Files (x86)\Nodist\bin\node_modules\.staging\strip-json-comments-fbf5de91
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\strip-json-comments-fbf5de91
npm verb tar unpack C:\Users\hiroko\AppData\Roaming\npm-cache\rimraf\2.5.4\package.tgz
npm verb tar unpacking to C:\Program Files (x86)\Nodist\bin\node_modules\.staging\rimraf-7d30ba56
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\rimraf-7d30ba56
npm verb tar unpack C:\Users\hiroko\AppData\Roaming\npm-cache\msee\0.3.2\package.tgz
npm verb tar unpacking to C:\Program Files (x86)\Nodist\bin\node_modules\.staging\msee-9c3a7704
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\msee-9c3a7704
npm verb tar unpack C:\Users\hiroko\AppData\Roaming\npm-cache\boganipsum\0.1.0\package.tgz
npm verb tar unpacking to C:\Program Files (x86)\Nodist\bin\node_modules\.staging\boganipsum-06f4e54c
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\boganipsum-06f4e54c
npm verb tar unpack C:\Users\hiroko\AppData\Roaming\npm-cache\learnyounode\3.5.5\package.tgz
npm verb tar unpacking to C:\Program Files (x86)\Nodist\bin\node_modules\.staging\learnyounode-1e9bf190
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\learnyounode-1e9bf190
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\capture-stack-trace-9408142a\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\lowercase-keys-e2413b6b\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\brace-expansion-5d22a986\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\timed-out-aaaa4f98\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\buffer-shims-77a2db2f\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\abbrev-9e8c64f1\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\is-redirect-f158959d\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\has-ansi-63ca5cae\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\escape-string-regexp-dbb1f801\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\prepend-http-e048c4ab\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\strip-ansi-89a0c38d\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\pinkie-promise-2f3756d3\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\is-plain-obj-31090913\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\registry-url-e551a575\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\once-bf061193\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\url-parse-lax-b57ecc4d\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\latest-version-9e3d6b8b\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\ansi-regex-c5a654b0\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\ini-2fd8e5ce\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\ansi-styles-5f016e9d\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\is-stream-9a7c55ff\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\error-ex-979998b1\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\is-retry-allowed-f57a0a1e\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\path-is-absolute-8c3c901c\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\node-status-codes-0ce24c46\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\pinkie-79f205b2\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\object-assign-271b05df\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\chalk-a5f35065\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\supports-color-34a972f3\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\create-error-class-331853c3\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\package-json-f4bd05f3\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\unzip-response-03bddd8c\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\read-all-stream-c06f7ce8\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\duplexer2-07b83743\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\table-header-c0eb17ef\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\inflight-03c40aa4\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\combined-stream-e586dbba\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\repeat-string-b221ce68\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\got-80265358\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\wrappy-cd0ed00a\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\concat-stream-4df90ed6\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\minimatch-dfa666bc\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\string_decoder-3b55d0d3\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\isarray-6f935f72\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\isarray-8cbefbae\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\balanced-match-ca6e747a\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\isarray-35e31d73\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\through2-99ddec09\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\through2-7a347fc8\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\through2-8f6707dc\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\fs.realpath-628f5fef\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\sprintf-0f8d66aa\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\ansicolors-eb6dad11\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\strip-json-comments-fbf5de91\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\rimraf-7d30ba56\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\inherits-c0cab49f\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\util-deprecate-1f06a8f8\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\process-nextick-args-22a57f0a\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\delayed-stream-99dea2d4\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\deep-extend-08a6621c\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\varsize-string-87cbc927\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\core-util-is-79df1960\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\string-to-stream-14c1f2fc\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\simple-terminal-menu-a1a74751\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\through2-map-f7855ecf\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\parse-json-e9716334\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\ansicolors-19cf2187\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\semver-b34da655\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\concat-map-2c2e71d1\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\wcsize-584b0e31\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\duplexer-b0c1c1a0\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\after-35744db4\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\isarray-cc5269b2\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\is-arrayish-3bc9d067\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\glob-f5847c66\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\colors-tmpl-e522a2e8\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\resumer-4a7b8d45\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\bl-d8bff427\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\tuple-stream-924c71e8\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\duplexer2-b73a5db6\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\typedarray-faef6da4\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\xtend-bcccb174\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\xtend-52737c5f\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\commandico-6d68b53d\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\wcstring-0ae70e27\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\boganipsum-06f4e54c\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\extended-terminal-menu-4603c114\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\nopt-b93884b5\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\topo-b3f3fc48\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\esprima-4dfbc673\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\through-aa652607\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\split-05757a15\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\isemail-bf80ad37\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\object-keys-b90e2106\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\charm_inheritance-fix-498faad9\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\workshopper-wrappedexec-2702745b\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\rc-409557f7\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\minimist-48ff5e3b\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\readable-stream-cbee460b\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\readable-stream-8d036d97\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\readable-stream-04739c9c\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\text-table-cf24d277\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\hoek-a627bdce\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\marked-16f32f5a\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\msee-9c3a7704\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\readable-stream-3af960e4\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\hyperquest-294d09b5\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\minimist-47100fc8\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\readable-stream-bf547cb4\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\mustache-59d3fdfd\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\i18n-core-f5f9a1db\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\colors-c796d7c7\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\mkdirp-3930b478\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\workshopper-exercise-df283077\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\redeyed-f57be3fc\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\explicit-153d5f8d\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\cardinal-5ffde213\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\joi-e8c5c449\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\moment-9b27f722\node_modules
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\learnyounode-1e9bf190\node_modules
[               ...] \ extract:learnyounode: verb gentlyRm don't care about cont[               ...] \ extract:learnyounode: verb gentlyRm don't care[               ...] \ extract:learnyounode: verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging[               ...] \ extract:learnyounode: verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.[        [               ...] \ extract:learnyounode: verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging
```

**Comment by legodude17** [comment]
This doesn't happen on v3.10.5. For now try downgrading.

**Comment by jtrollkarl** [comment]
After downgrading, i can confirm it still occurs with v3.10.5. Are you using windows? This seems to only be affecting windows users

**Comment by legodude17** [comment]
That might be it, I am running Ubuntu. It appears that npm is unpacking the tarball and then removing the directory indefinitely.

**Comment by martinheidegger** [comment]
I published a new version of learnyounode last week. It might be that some part of npm's publish system is broken?!

**Comment by martinheidegger** [comment]
(there is a report of very old versions of npm with the same error)

**Comment by legodude17** [comment]
It appears that the problem is with the install, not with the publish. I successfully installed `learnyounode`.

**Comment by legodude17** [comment]
@martinheidegger or @jtrollkarl can you try running `npm install learnyounode --disable-progress --loglevel=silly`? And post the result.

**Comment by martinheidegger** [comment]
```
npm sill gunzTarPerm extractEntry exercises/my_first_io/problem.pl.md
npm sill gunzTarPerm modified mode [ 'exercises/my_first_io/problem.pl.md', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/ss.js
npm sill gunzTarPerm modified mode [ 'locale/ss.js', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/de-at.js
npm sill gunzTarPerm modified mode [ 'locale/de-at.js', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/my_first_io/problem.pt-br.md
npm sill gunzTarPerm modified mode [ 'exercises/my_first_io/problem.pt-br.md', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/my_first_io/problem.ru.md
npm sill gunzTarPerm modified mode [ 'exercises/my_first_io/problem.ru.md', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/sv.js
npm sill gunzTarPerm modified mode [ 'locale/sv.js', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/da.js
npm sill gunzTarPerm modified mode [ 'locale/da.js', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/my_first_io/problem.uk.md
npm sill gunzTarPerm modified mode [ 'exercises/my_first_io/problem.uk.md', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/my_first_io/problem.vi.md
npm sill gunzTarPerm modified mode [ 'exercises/my_first_io/problem.vi.md', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/sw.js
npm sill gunzTarPerm modified mode [ 'locale/sw.js', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/cy.js
npm sill gunzTarPerm modified mode [ 'locale/cy.js', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/ta.js
npm sill gunzTarPerm modified mode [ 'locale/ta.js', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/cv.js
npm sill gunzTarPerm modified mode [ 'locale/cv.js', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/my_first_io/problem.es.md
npm sill gunzTarPerm modified mode [ 'exercises/my_first_io/problem.es.md', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/my_first_io/problem.it.md
npm sill gunzTarPerm modified mode [ 'exercises/my_first_io/problem.it.md', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/te.js
npm sill gunzTarPerm modified mode [ 'locale/te.js', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/cs.js
npm sill gunzTarPerm modified mode [ 'locale/cs.js', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/my_first_io/solution/solution.js
npm sill gunzTarPerm modified mode [ 'exercises/my_first_io/solution/solution.js', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/my_first_io/solution_fr/solution.js
npm sill gunzTarPerm modified mode [ 'exercises/my_first_io/solution_fr/solution.js', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/th.js
npm sill gunzTarPerm modified mode [ 'locale/th.js', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/ca.js
npm sill gunzTarPerm modified mode [ 'locale/ca.js', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/my_first_io/solution_it/solution.js
npm sill gunzTarPerm modified mode [ 'exercises/my_first_io/solution_it/solution.js', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/my_first_io/solution_ja/solution.js
npm sill gunzTarPerm modified mode [ 'exercises/my_first_io/solution_ja/solution.js', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/tl-ph.js
npm sill gunzTarPerm modified mode [ 'locale/tl-ph.js', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/bs.js
npm sill gunzTarPerm modified mode [ 'locale/bs.js', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/my_first_io/solution_nb-no/solution.js
npm sill gunzTarPerm modified mode [ 'exercises/my_first_io/solution_nb-no/solution.js', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/my_first_io/solution_ru/solution.js
npm sill gunzTarPerm modified mode [ 'exercises/my_first_io/solution_ru/solution.js', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/tlh.js
npm sill gunzTarPerm modified mode [ 'locale/tlh.js', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/br.js
npm sill gunzTarPerm modified mode [ 'locale/br.js', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/my_first_io/solution_uk/solution.js
npm sill gunzTarPerm modified mode [ 'exercises/my_first_io/solution_uk/solution.js', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/my_first_io/solution_vi/solution.js
npm sill gunzTarPerm modified mode [ 'exercises/my_first_io/solution_vi/solution.js', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/tr.js
npm sill gunzTarPerm modified mode [ 'locale/tr.js', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/bo.js
npm sill gunzTarPerm modified mode [ 'locale/bo.js', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/my_first_io/solution_zh-cn/solution.js
npm sill gunzTarPerm modified mode [ 'exercises/my_first_io/solution_zh-cn/solution.js', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/my_first_io/solution_zh-tw/solution.js
npm sill gunzTarPerm modified mode [ 'exercises/my_first_io/solution_zh-tw/solution.js', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/tzl.js
npm sill gunzTarPerm modified mode [ 'locale/tzl.js', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/bn.js
npm sill gunzTarPerm modified mode [ 'locale/bn.js', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/my_first_io/problem.zh-cn.md
npm sill gunzTarPerm modified mode [ 'exercises/my_first_io/problem.zh-cn.md', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/time_server/exercise.js
npm sill gunzTarPerm modified mode [ 'exercises/time_server/exercise.js', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/tzm-latn.js
npm sill gunzTarPerm modified mode [ 'locale/tzm-latn.js', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/bg.js
npm sill gunzTarPerm modified mode [ 'locale/bg.js', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/time_server/solution/solution.js
npm sill gunzTarPerm modified mode [ 'exercises/time_server/solution/solution.js', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/time_server/problem.fr.md
npm sill gunzTarPerm modified mode [ 'exercises/time_server/problem.fr.md', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/tzm.js
npm sill gunzTarPerm modified mode [ 'locale/tzm.js', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/be.js
npm sill gunzTarPerm modified mode [ 'locale/be.js', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/time_server/problem.it.md
npm sill gunzTarPerm modified mode [ 'exercises/time_server/problem.it.md', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/time_server/problem.ja.md
npm sill gunzTarPerm modified mode [ 'exercises/time_server/problem.ja.md', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/uk.js
npm sill gunzTarPerm modified mode [ 'locale/uk.js', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/az.js
npm sill gunzTarPerm modified mode [ 'locale/az.js', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/time_server/problem.ko.md
npm sill gunzTarPerm modified mode [ 'exercises/time_server/problem.ko.md', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/time_server/problem.md
npm sill gunzTarPerm modified mode [ 'exercises/time_server/problem.md', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/uz.js
npm sill gunzTarPerm modified mode [ 'locale/uz.js', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/ar.js
npm sill gunzTarPerm modified mode [ 'locale/ar.js', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/time_server/problem.nb-no.md
npm sill gunzTarPerm modified mode [ 'exercises/time_server/problem.nb-no.md', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/time_server/problem.es.md
npm sill gunzTarPerm modified mode [ 'exercises/time_server/problem.es.md', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/vi.js
npm sill gunzTarPerm modified mode [ 'locale/vi.js', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/ar-tn.js
npm sill gunzTarPerm modified mode [ 'locale/ar-tn.js', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/time_server/problem.pt-br.md
npm sill gunzTarPerm modified mode [ 'exercises/time_server/problem.pt-br.md', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/time_server/problem.ru.md
npm sill gunzTarPerm modified mode [ 'exercises/time_server/problem.ru.md', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/x-pseudo.js
npm sill gunzTarPerm modified mode [ 'locale/x-pseudo.js', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/ar-sa.js
npm sill gunzTarPerm modified mode [ 'locale/ar-sa.js', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/time_server/problem.uk.md
npm sill gunzTarPerm modified mode [ 'exercises/time_server/problem.uk.md', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/time_server/problem.vi.md
npm sill gunzTarPerm modified mode [ 'exercises/time_server/problem.vi.md', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/zh-cn.js
npm sill gunzTarPerm modified mode [ 'locale/zh-cn.js', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/ar-ma.js
npm sill gunzTarPerm modified mode [ 'locale/ar-ma.js', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/time_server/problem.zh-cn.md
npm sill gunzTarPerm modified mode [ 'exercises/time_server/problem.zh-cn.md', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/time_server/problem.zh-tw.md
npm sill gunzTarPerm modified mode [ 'exercises/time_server/problem.zh-tw.md', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/zh-tw.js
npm sill gunzTarPerm modified mode [ 'locale/zh-tw.js', 420, 438 ]
npm sill gunzTarPerm extractEntry locale/ka.js
npm sill gunzTarPerm modified mode [ 'locale/ka.js', 420, 438 ]
npm sill gunzTarPerm extractEntry exercises/time_server/problem.pl.md
npm sill gunzTarPerm modified mode [ 'exercises/time_server/problem.pl.md', 420, 438 ]
npm sill gunzTarPerm extractEntry LICENSE.md
npm sill gunzTarPerm modified mode [ 'LICENSE.md', 420, 438 ]
npm sill gunzTarPerm extractEntry CHANGELOG.md
npm sill gunzTarPerm modified mode [ 'CHANGELOG.md', 420, 438 ]
npm sill gunzTarPerm extractEntry min/locales.js
npm sill gunzTarPerm modified mode [ 'min/locales.js', 420, 438 ]
npm sill gunzTarPerm extractEntry .jshintrc
npm sill gunzTarPerm modified mode [ '.jshintrc', 420, 438 ]
npm sill gunzTarPerm extractEntry README.vi.md
npm sill gunzTarPerm modified mode [ 'README.vi.md', 420, 438 ]
npm sill gunzTarPerm extractEntry min/locales.min.js
npm sill gunzTarPerm modified mode [ 'min/locales.min.js', 420, 438 ]
npm sill gunzTarPerm extractEntry bin/learnyounode
npm sill gunzTarPerm modified mode [ 'bin/learnyounode', 493, 511 ]
npm sill gunzTarPerm extractEntry docs/bl.html
npm sill gunzTarPerm modified mode [ 'docs/bl.html', 420, 438 ]
npm sill gunzTarPerm extractEntry min/moment-with-locales.js
npm sill gunzTarPerm modified mode [ 'min/moment-with-locales.js', 420, 438 ]
npm sill gunzTarPerm extractEntry docs/concat-stream.html
npm sill gunzTarPerm modified mode [ 'docs/concat-stream.html', 420, 438 ]
npm sill gunzTarPerm extractEntry docs/through2-map.html
npm sill gunzTarPerm modified mode [ 'docs/through2-map.html', 420, 438 ]
npm sill gunzTarPerm extractEntry min/moment-with-locales.min.js
npm sill gunzTarPerm modified mode [ 'min/moment-with-locales.min.js', 420, 438 ]
npm sill gunzTarPerm extractEntry i18n/nb-no.json
npm sill gunzTarPerm modified mode [ 'i18n/nb-no.json', 420, 438 ]
npm sill gunzTarPerm extractEntry i18n/credits/it.txt
npm sill gunzTarPerm modified mode [ 'i18n/credits/it.txt', 420, 438 ]
npm sill gunzTarPerm extractEntry i18n/es.json
npm sill gunzTarPerm modified mode [ 'i18n/es.json', 420, 438 ]
npm sill gunzTarPerm extractEntry i18n/fr.json
npm sill gunzTarPerm modified mode [ 'i18n/fr.json', 420, 438 ]
npm sill gunzTarPerm extractEntry min/moment.min.js
npm sill gunzTarPerm modified mode [ 'min/moment.min.js', 420, 438 ]
npm sill gunzTarPerm extractEntry i18n/it.json
npm sill gunzTarPerm modified mode [ 'i18n/it.json', 420, 438 ]
npm sill gunzTarPerm extractEntry i18n/ja.json
npm sill gunzTarPerm modified mode [ 'i18n/ja.json', 420, 438 ]
npm sill gunzTarPerm extractEntry i18n/ko.json
npm sill gunzTarPerm modified mode [ 'i18n/ko.json', 420, 438 ]
npm sill gunzTarPerm extractEntry i18n/en.json
npm sill gunzTarPerm modified mode [ 'i18n/en.json', 420, 438 ]
npm sill gunzTarPerm extractEntry i18n/pl.json
npm sill gunzTarPerm modified mode [ 'i18n/pl.json', 420, 438 ]
npm sill gunzTarPerm extractEntry i18n/pt-br.json
npm sill gunzTarPerm modified mode [ 'i18n/pt-br.json', 420, 438 ]
npm sill gunzTarPerm extractEntry i18n/ru.json
npm sill gunzTarPerm modified mode [ 'i18n/ru.json', 420, 438 ]
npm sill gunzTarPerm extractEntry i18n/uk.json
npm sill gunzTarPerm modified mode [ 'i18n/uk.json', 420, 438 ]
npm sill gunzTarPerm extractEntry i18n/vi.json
npm sill gunzTarPerm modified mode [ 'i18n/vi.json', 420, 438 ]
npm sill gunzTarPerm extractEntry i18n/zh-cn.json
npm sill gunzTarPerm modified mode [ 'i18n/zh-cn.json', 420, 438 ]
npm sill gunzTarPerm extractEntry i18n/zh-tw.json
npm sill gunzTarPerm modified mode [ 'i18n/zh-tw.json', 420, 438 ]
npm sill gunzTarPerm extractEntry lib/rndport.js
npm sill gunzTarPerm modified mode [ 'lib/rndport.js', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/index.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/index.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/_toc.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/_toc.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/all.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/all.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/assert.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/assert.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/assets/joyent-footer.svg
npm sill gunzTarPerm modified mode [ 'node_apidoc/assets/joyent-footer.svg', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/assets/logo.svg
npm sill gunzTarPerm modified mode [ 'node_apidoc/assets/logo.svg', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/assets/sh.css
npm sill gunzTarPerm modified mode [ 'node_apidoc/assets/sh.css', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/assets/style.css
npm sill gunzTarPerm modified mode [ 'node_apidoc/assets/style.css', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/buffer.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/buffer.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/child_process.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/child_process.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/cluster.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/cluster.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/console.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/console.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/crypto.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/crypto.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/debugger.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/debugger.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/dgram.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/dgram.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/dns.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/dns.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/documentation.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/documentation.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/domain.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/domain.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/events.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/events.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/fs.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/fs.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/globals.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/globals.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/http.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/http.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/https.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/https.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/addons.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/addons.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/modules.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/modules.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/net.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/net.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/os.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/os.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/path.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/path.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/process.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/process.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/punycode.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/punycode.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/querystring.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/querystring.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/readline.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/readline.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/repl.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/repl.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/stream.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/stream.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/string_decoder.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/string_decoder.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/synopsis.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/synopsis.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/timers.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/timers.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/tls.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/tls.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/tty.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/tty.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/url.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/url.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/util.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/util.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/vm.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/vm.html', 420, 438 ]
npm sill gunzTarPerm extractEntry node_apidoc/zlib.html
npm sill gunzTarPerm modified mode [ 'node_apidoc/zlib.html', 420, 438 ]
npm sill gunzTarPerm extractEntry .travis.yml
npm sill gunzTarPerm modified mode [ '.travis.yml', 420, 438 ]
npm sill gunzTarPerm extractEntry ~/.workshopper-test/storage/.config/learnyounode/lang.json
npm sill gunzTarPerm modified mode [ '~/.workshopper-test/storage/.config/learnyounode/lang.json',
npm sill gunzTarPerm   420,
npm sill gunzTarPerm   438 ]
npm sill gunzTarPerm extractEntry ~/.workshopper-test/storage/.config/workshopper/lang.json
npm sill gunzTarPerm modified mode [ '~/.workshopper-test/storage/.config/workshopper/lang.json',
npm sill gunzTarPerm   420,
npm sill gunzTarPerm   438 ]
npm sill gentlyRm C:\Program Files (x86)\Nodist\bin\node_modules\.staging\moment-9b27f722\node_modules is being purged
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\moment-9b27f722\node_modules
npm sill gentlyRm C:\Program Files (x86)\Nodist\bin\node_modules\.staging\learnyounode-1e9bf190\node_modules is being purged
npm verb gentlyRm don't care about contents; nuking C:\Program Files (x86)\Nodist\bin\node_modules\.staging\learnyounode-1e9bf190\node_modules
```

**Comment by Lars-m** [comment]
Any ideas about when this problem is solved, i have the same problem (Windows7, node 4.5.0, npm 2.15.9)

**Comment by zkat** [comment]
@martinheidegger could you upload the `npm-debug.log` for this?

**Comment by martinheidegger** [comment]
@zkat It hangs, there is no debug.log ...

**Comment by zkat** [comment]
@martinheidegger can you dump the *entire* output from `npm i -g learnyounode -ddd`?

**Comment by iarna** [comment]
I'm going to do a little binary search for the version this was introduced in, more in a lil bit.

**Comment by iarna** [comment]
I have thus far seen the same behavior in:

* `3.9.6`
* `2.15.10` !!!!

**Comment by martinheidegger** [comment]
https://github.com/npm/npm/issues/13722

**Comment by martinheidegger** [comment]
@iarna When trying to triage the bug it seems to have happened around even older versions of Node.js : https://github.com/nodeschool/discussions/issues/1849#issuecomment-241491507
My guess is that something in the learnyounode package is breaking on windows?! File system depth? We published a new version of learnyounode recently.

**Comment by iarna** [comment]
It looks like the culprit is `workershoper-adventure`...

**Comment by iarna** [comment]
Yup, 4.6.3 installs and 4.7.0 hangs.

**Comment by iarna** [comment]
I looked at the diffs I can't see how those'd cause anything like this, so I'm gonna compare the actual package files.

**Comment by martinheidegger** [comment]
@iarna ! I have a thought !

**Comment by iarna** [comment]
@martinheidegger I found it, there's a bogus file in the 4.7.0 tarball:

```
-rw-r--r--  0 501    20         10 Aug 19 09:48 package/true\n/Users/martin/Private/projects/workshopper/true\n/Users/martin/.npm/workshopper-adventure/4.7.0/package.tgz.31392148
```

**Comment by iarna** [comment]
How that would get in there, I have _no_ idea, but the newlines in the filename are giving Windows fits.

**Comment by martinheidegger** [comment]
@iarna I just edited my comment: https://github.com/npm/npm/issues/13722#issuecomment-241924381

**Comment by iarna** [comment]
oh wow!

**Comment by iarna** [comment]
As we've diagnosed the root cause of this issue as outside of an installer bug I'm going to close it, but I'll be opening a new issue around weird files in tarballs so that doesn't get lost entirely.

**Comment by martinheidegger** [comment]
@legodude17 @jtrollkarl @jtrollkarl Just to be clear: It was a problem created with the weird tarball I published of `workshopper-adventure` I have since published a new version (installing now should work)

**Comment by pocesar** [comment]
this still happening with npm 4.6.1 / node 8.1.2 on Windows 10 (it's totally random). sometimes it happen with seamlessly small files like installing Typescript @types (can't use npm 5.x, it's even worse). almost all the time happens when trying to install or update `react-devtools-core`

**Comment by ghost** [comment]
Yo puedo suponer que es el antivirus. Seguro muchos se burlarán de mi, pero desactive el antivirus y me fue mejor.!
