### ISSUE TITLE
Unable to install strongloop

### ISSUE THREAD

**Issue by akuntal** [npm/npm#14188]
#### I'm unable to install strongloop
I have installed npm@3.10.8, node@4.6 on my windows7(64x) system.

here is the error log, I am getting while installing

<details>
```
158691 warn install:sqlite3@3.1.5 sqlite3@3.1.5 preinstall: `npm install node-pre-gyp`
158691 warn install:sqlite3@3.1.5 Exit status 4294963214
158692 verbose install:sqlite3@3.1.5 Error: sqlite3@3.1.5 preinstall: `npm install node-pre-gyp`
158692 verbose install:sqlite3@3.1.5 Exit status 4294963214
158692 verbose install:sqlite3@3.1.5     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
158692 verbose install:sqlite3@3.1.5     at emitTwo (events.js:106:13)
158692 verbose install:sqlite3@3.1.5     at EventEmitter.emit (events.js:191:7)
158692 verbose install:sqlite3@3.1.5     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
158692 verbose install:sqlite3@3.1.5     at emitTwo (events.js:106:13)
158692 verbose install:sqlite3@3.1.5     at ChildProcess.emit (events.js:191:7)
158692 verbose install:sqlite3@3.1.5     at maybeClose (internal/child_process.js:877:16)
158692 verbose install:sqlite3@3.1.5     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
158693 verbose lifecycle strong-arc@1.8.8~preinstall: unsafe-perm in lifecycle true
158694 verbose lifecycle strong-arc@1.8.8~preinstall: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\Users\AppData\Roaming\npm\node_modules\.staging\strong-arc-213dd542\node_modules\.bin;D:\Users\AppData\Roaming\npm\node_modules\.bin;C:\Program Files\nodejs;C:\Program Files\CA\webagent\win64\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Windows\CCM;C:\Windows\CCM;C:\Program Files\Java\jdk1.8.0_60\bin;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Brackets\command;C:\Program Files\TortoiseGit\bin;C:\Program Files\nodejs\;C:\Program Files\MongoDB\Server\3.2\bin;C:\Program Files\TortoiseSVN\bin;D:\Users\AppData\Local\Android\sdk\platform-tools;D:\Users\AppData\Local\Android\sdk\tools;D:\Users\AppData\Roaming\npm
158695 verbose lifecycle strong-arc@1.8.8~preinstall: CWD: D:\Users\AppData\Roaming\npm\node_modules\.staging\strong-arc-213dd542
158696 silly lifecycle strong-arc@1.8.8~preinstall: Args: [ '/d /s /c', 'node .sl-blip.js' ]
158697 info lifecycle strong-arc@1.8.8~preinstall: Failed to exec preinstall script
158698 silly lifecycle strong-arc@1.8.8~preinstall: Returned: code: -4058  signal: null
158699 info lifecycle strong-arc@1.8.8~preinstall: Failed to exec preinstall script
158700 verbose unlock done using D:\Users\AppData\Roaming\npm-cache\_locks\staging-ded6943d77cb2c21.lock for D:\Users\AppData\Roaming\npm\node_modules\.staging
158701 silly rollbackFailedOptional Starting
158702 silly rollbackFailedOptional Finishing
158703 silly runTopLevelLifecycles Starting
158704 silly runTopLevelLifecycles Finishing
158705 silly install printInstalled
158706 warn optional Skipping failed optional dependency /strongloop/modern-syslog:
158707 warn notsup Not compatible with your operating system or architecture: modern-syslog@1.1.4
158708 warn optional Skipping failed optional dependency /strongloop/strong-supervisor/modern-syslog:
158709 warn notsup Not compatible with your operating system or architecture: modern-syslog@1.1.4
158710 verbose stack Error: strong-arc@1.8.8 preinstall: `node .sl-blip.js`
158710 verbose stack spawn C:\WINDOWS\system32\cmd.exe ENOENT
158710 verbose stack     at exports._errnoException (util.js:1036:11)
158710 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
158710 verbose stack     at onErrorNT (internal/child_process.js:359:16)
158710 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
158710 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
158711 verbose pkgid strong-arc@1.8.8
158712 verbose cwd D:\Users\AppData\Roaming\npm\node_modules
158713 error Windows_NT 6.1.7601
158714 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "strongloop"
158715 error node v6.7.0
158716 error npm  v3.10.3
158717 error file C:\WINDOWS\system32\cmd.exe
158718 error path C:\WINDOWS\system32\cmd.exe
158719 error code ELIFECYCLE
158720 error errno ENOENT
158721 error syscall spawn C:\WINDOWS\system32\cmd.exe
158722 error strong-arc@1.8.8 preinstall: `node .sl-blip.js`
158722 error spawn C:\WINDOWS\system32\cmd.exe ENOENT
158723 error Failed at the strong-arc@1.8.8 preinstall script 'node .sl-blip.js'.
158723 error Make sure you have the latest version of node.js and npm installed.
158723 error If you do, this is most likely a problem with the strong-arc package,
158723 error not with npm itself.
158723 error Tell the author that this fails on your system:
158723 error     node .sl-blip.js
158723 error You can get information on how to open an issue for this project with:
158723 error     npm bugs strong-arc
158723 error Or if that isn't available, you can get their info via:
158723 error     npm owner ls strong-arc
158723 error There is likely additional logging output above.
158724 verbose exit [ 1, true ]
```
</details>

**Comment by KenanY** [comment]
@akuntal Hmm, looks like `strong-arc`'s `preinstall` script is failing on your system. Probably not an `npm` issue but it'd be nice if someone else could reproduce.

**Comment by rikantro** [comment]
Same issue
npm 3.10.3 - node 6.7.0 - Windows 10 

npm WARN optional Skipping failed optional dependency /strongloop/modern-syslog:
npm WARN notsup Not compatible with your operating system or architecture: modern-syslog@1.1.4
npm WARN optional Skipping failed optional dependency /strongloop/strong-supervisor/modern-syslog:
npm WARN notsup Not compatible with your operating system or architecture: modern-syslog@1.1.4
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "strongloop"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! path C:\Users\TCP4\AppData\Roaming\npm\node_modules\.staging\argparse-f5709cd5
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\TCP4\AppData\Roaming\npm\node_modules\.staging\argparse-f5709cd5' -> 'C:\Users\TCP4\AppData\Roaming\npm\node_modules\strongloop\node_modules\argparse'
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\TCP4\AppData\Roaming\npm\node_modules\.staging\argparse-f5709cd5' -> 'C:\Users\TCP4\AppData\Roaming\npm\node_modules\strongloop\node_modules\argparse'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\TCP4\npm-debug.log
npm ERR! code 1

**Comment by KenanY** [comment]
@rikantro Error message looks different to me.

**Comment by glen-anderson** [comment]
Same here on Windows 10, npm 3.10.8, node 4.6.0 (LTS). Here's the relevant output from --loglevel=info

```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\ganders\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-pre-gyp"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8
npm ERR! path C:\Users\ganders\AppData\Roaming\npm\node_modules\.staging\sqlite3-0ca53160
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rmdir

npm ERR! EBUSY: resource busy or locked, rmdir 'C:\Users\ganders\AppData\Roaming\npm\node_modules\.staging\sqlite3-0ca53160'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ganders\AppData\Roaming\npm\node_modules\.staging\sqlite3-0ca53160\npm-debug.log
npm info lifecycle sqlite3@3.1.5~preinstall: Failed to exec preinstall script

> strong-arc@1.8.8 preinstall C:\Users\ganders\AppData\Roaming\npm\node_modules\.staging\strong-arc-07f3db93
> node .sl-blip.js

npm info lifecycle strong-arc@1.8.8~preinstall: Failed to exec preinstall script
npm info lifecycle strong-arc@1.8.8~preinstall: Failed to exec preinstall script
C:\Users\ganders\AppData\Roaming\npm
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@^1.1.2 (node_modules\strongloop\node_modules\modern-syslog):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for modern-syslog@1.1.4: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@^1.x (node_modules\strongloop\node_modules\strong-supervisor\node_modules\modern-syslog):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for modern-syslog@1.1.4: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sqlite3@3.1.5 (node_modules\strongloop\node_modules\sqlite3):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sqlite3@3.1.5 preinstall: `npm install node-pre-gyp`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 4294963214
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\ganders\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "strongloop" "-g" "--loglevel=info"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8
npm ERR! file C:\Windows\system32\cmd.exe
npm ERR! path C:\Windows\system32\cmd.exe
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\Windows\system32\cmd.exe

npm ERR! strong-arc@1.8.8 preinstall: `node .sl-blip.js`
npm ERR! spawn C:\Windows\system32\cmd.exe ENOENT
npm ERR!
npm ERR! Failed at the strong-arc@1.8.8 preinstall script 'node .sl-blip.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the strong-arc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node .sl-blip.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs strong-arc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls strong-arc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Work\git\users\ganders\web-registration-viewer\server\npm-debug.log
npm ERR! code 1
```

**Comment by rikantro** [comment]
I uninstall strong loop , then reinstall and this is the log


npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@^1.1.2 (node_modules\strongloop\node_modules\modern-syslog):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for modern-syslog@1.1.4: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@^1.x (node_modules\strongloop\node_modules\strong-supervisor\node_modules\modern-syslog):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for modern-syslog@1.1.4: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sqlite3@3.1.5 (node_modules\strongloop\node_modules\sqlite3):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sqlite3@3.1.5 preinstall: `npm install node-pre-gyp`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 4294963214
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\TCP4\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "strongloop"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! file C:\WINDOWS\system32\cmd.exe
npm ERR! path C:\WINDOWS\system32\cmd.exe
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\WINDOWS\system32\cmd.exe

npm ERR! strong-arc@1.8.8 preinstall: `node .sl-blip.js`
npm ERR! spawn C:\WINDOWS\system32\cmd.exe ENOENT
npm ERR!
npm ERR! Failed at the strong-arc@1.8.8 preinstall script 'node .sl-blip.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the strong-arc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node .sl-blip.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs strong-arc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls strong-arc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\testing\loopback\demo01\npm-debug.log
npm ERR! code 1

**Comment by rikantro** [comment]
currently I'm make another test, but this time the module has installed without problems. In this time opened the node.js command prompt, an in the previuos tests opened a other command windows ( without node.js path i think)

**Comment by rurivera6** [comment]
I too am now getting this error.  I don't see a resolution yet, hmm...

**Comment by KenanY** [comment]
ref. https://github.com/strongloop/strong-arc/issues/1732, https://github.com/strongloop/strong-arc/issues/1733

**Comment by djabif** [comment]
Same here trying to deploy in Heroku:

```
remote: 158950 verbose stack Error: strong-arc@1.8.8 preinstall: `node .sl-blip.js`
remote: 158950 verbose stack spawn sh ENOENT
remote: 158950 verbose stack     at exports._errnoException (util.js:893:11)
remote: 158950 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
remote: 158950 verbose stack     at onErrorNT (internal/child_process.js:348:16)
remote: 158950 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
remote: 158950 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
remote: 158951 verbose pkgid strong-arc@1.8.8
remote: 158952 verbose cwd /tmp/build_4dc4f82995fac0c9fae5dfd4533b0145
remote: 158953 error Linux 3.13.0-95-generic
remote: 158954 error argv "/tmp/build_4dc4f82995fac0c9fae5dfd4533b0145/vendor/node/bin/node" "/tmp/build_4dc4f82995fac0c9fae5dfd4533b0145/vendor/node/bin/npm" "install" "-g" "strongloop"
remote: 158955 error node v5.11.1
remote: 158956 error npm  v3.8.6
remote: 158957 error file sh
remote: 158958 error path sh
remote: 158959 error code ELIFECYCLE
remote: 158960 error errno ENOENT
remote: 158961 error syscall spawn sh
remote: 158962 error strong-arc@1.8.8 preinstall: `node .sl-blip.js`
remote: 158962 error spawn sh ENOENT
remote: 158963 error Failed at the strong-arc@1.8.8 preinstall script 'node .sl-blip.js'.
remote: 158963 error Make sure you have the latest version of node.js and npm installed.
remote: 158963 error If you do, this is most likely a problem with the strong-arc package,
remote: 158963 error not with npm itself.
remote: 158963 error Tell the author that this fails on your system:
remote: 158963 error     node .sl-blip.js
remote: 158963 error You can get information on how to open an issue for this project with:
remote: 158963 error     npm bugs strong-arc
remote: 158963 error Or if that isn't available, you can get their info via:
remote: 158963 error     npm owner ls strong-arc
```

**Comment by tamitutor** [comment]
Same here.

I am as well.

npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/twright/.nvm/versions/node/v6.7.0/bin/node" "/Users/twright/.nvm/versions/node/v6.7.0/bin/npm" "install" "strongloop" "-g"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! file sh
npm ERR! path sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn sh

npm ERR! strong-arc@1.8.8 preinstall: `node .sl-blip.js`
npm ERR! spawn sh ENOENT
npm ERR! 
npm ERR! Failed at the strong-arc@1.8.8 preinstall script 'node .sl-blip.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the strong-arc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node .sl-blip.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs strong-arc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls strong-arc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/twright/npm-debug.log
npm ERR! code 1

**Comment by tamitutor** [comment]
FWIW: If I downgrade to node@6.6.0 and keep npm@3.10.0 I do not see this problem any more.

**Comment by rikantro** [comment]
@tamitutor  thanks for the help

**Comment by JonEustace** [comment]
Also having this issue. No matter if I'm on v6.7.0 or v6.6.0 using npm 3.10.3

**Comment by akuntal** [comment]
Is it working for anyone?

**Comment by othiym23** [comment]
As far as I can tell, this isn't caused by anything in the npm CLI. As @KenanY pointed out, it looks like most of you are failing on `strong-arc`'s `"preinstall"` script, which is trying to run a script that, for whatever reason, is missing. Please move this discussion over to strongloop/strong-arc#1733, where, with luck, the Strongloop team will be able to get you all sorted out. Thanks for your time!

**Comment by rmg** [comment]
Some of the comments here show the bug reported in strongloop/strong-arc#1733, which should now be resolved.

@rikantro your error message looks like the race condition in npm that has been popping up more frequently recently. I've been funnelling those errors into #11265.

Some of these errors are also showing the same error message as mapbox/node-sqlite3#720, which appears to have _just_ been resolved.

**Comment by archenroot** [comment]
I am able to install strongloop on node 3.1 on windows 10:
https://nodejs.org/download/release/v6.3.1/

Some warnings still appear, but installation finished without error.
