### ISSUE TITLE
npm@4 warning a lot about node binary path

### ISSUE THREAD

**Issue by dpogue** [npm/npm#14372]
#### I'm opening this issue because:
* npm is doing something I don't understand.

#### What's going wrong?

After updating to npm@4, running any script from package.json is printing a warning:

```
npm WARN lifecycle The node binary used for scripts is /usr/local/bin/node but npm is using /usr/local/Cellar/node/6.9.1/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
```

I understand this is related to a change in npm@4 to warn if the node binary used by npm and the scripts are different, but it probably shouldn't warn in the case of a symlink.

#### How can the CLI team reproduce the problem?

This seems to happen consistently every time a script is run, when node is installed via homebrew.

In my case, `/usr/local/bin/node` is a symlink to `/usr/local/Cellar/node/6.9.1/bin/node`

### supporting information:

 - `npm -v` prints: 4.0.0
 - `node -v` prints: v6.9.1 (installed via homebrew)
 - Windows, OS X/macOS, or Linux?: OSX 10.11.6

**Comment by zkat** [comment]
Fixed by #14374.

**Comment by diegodesouza** [comment]
I'm still experiencing this issue, what should I do in order to fix it? 
`npm -v => 4.1.1` 
`node -v => v7.4.0`
Mac OS `10.12.2`

**Comment by addaleax** [comment]
@diegodesouza Hey, what do `which npm` and `which node` print for you when run from the command line? Also, what is the exact warning message that `npm` prints?

**Comment by diegodesouza** [comment]
```
npm WARN lifecycle The node binary used for scripts is /usr/local/opt/node but npm is using /usr/local/Cellar/node/7.4.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
```

```
➜  ~ which npm
/usr/local/bin/npm
➜  ~ which node
/usr/local/bin/node
```

Here's the output @addaleax.

**Comment by addaleax** [comment]
Oh, yea, maybe I should have been asking for `realpath $(which node)` and `realpath $(which npm)`.

In any case, the situation is about this: You have (at least) two node binaries installed on your machine, and running `npm` from the command line doesn’t seem to use the one that would come first in the `PATH` environment variable (that you can view using `echo $PATH`).

If you want `npm` to run package scripts using the same node binary the `npm` uses, you can set that by doing `npm config set scripts-prepend-node-path true`; if you don’t want that to happen, and you want npm to run scripts using the same `node` that you get when you directly enter `node` in the command line, you can achieve that via `npm config set scripts-prepend-node-path false`.
