### ISSUE TITLE
Getting error when running 'npm install' 

### ISSUE THREAD

**Issue by satishmfka** [npm/npm#14408]
#### I'm opening this issue because:

 npm is doing something I don't understand and getting below error message:-

Error :
npm ERR! Windows_NT 6.1.7601  
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\satish.kumar.tiwari\AppData\Roaming\npm\node_
modules\npm\bin\npm-cli.js" "install"  
npm ERR! node v6.8.0  
npm ERR! npm  v3.10.9  
npm ERR! code 128                                                                                                

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\satish.kumar.tiwari\AppData\Roaming
\npm-cache_git-remotes_templates --mirror 
npm ERR! Cloning into bare repository 'C:\Users\satish.kumar.tiwari\AppData\Roaming\npm-cache_git-remotes\git-ht

npm ERR! fatal: bad object f05b96730bdbda3da6e6c6ea1463a5e47d13f622  
npm ERR! fatal: remote did not send all necessary objects      
### supporting information:

```
 Node Version - 6.8.0
  sls Version - 0.5.6
 NPM Version - 3.10.9
```
- Windows 7,
  Tried with and without VPN both ways

**Comment by watilde** [comment]
Hi! Thanks for reporting this issue. Could you please give us more detail which is like the `npm-debug.log`?

**Comment by satishmfka** [comment]
[npm-debug.txt](https://github.com/npm/npm/files/552286/npm-debug.txt)

Please let me know if anything else required and give me solution ASAP.

**Comment by mmurukutla** [comment]
I am also getting same error. But it was working fine a week or 10 days ago. Please share if there is any resolution.

30 error node v6.9.1
31 error npm  v3.10.8
32 error code 128
33 error Command failed: git -c core.longpaths=true clone --template=C:\Users\I97463\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://<personel-access-token>:x-oauth-basic@github.com/<user>/<repository-name>.git C:\Users\I97463\AppData\Roaming\npm-cache\_git-remotes\git-https-<personel-access-token>-x-oauth-basic-github-com-<user>-<repository-name>-git-29dc8b2b
33 error Cloning into bare repository 'C:\Users\I97463\AppData\Roaming\npm-cache\_git-remotes\git-https-<personel-access-token>-x-oauth-basic-github-com-<user>-<repository-name>-git-29dc8b2b'...
33 error fatal: bad object a1b154eb08d4189026602c18d25a37671e68520c
33 error fatal: remote did not send all necessary objects
34 error If you need help, you may report this error at:
34 error     <https://github.com/npm/npm/issues>
35 verbose exit [ 1, true ]

**Comment by legodude17** [comment]
Hi! Have you check you internet connection? Do you use a proxy, VPN, or firewall?

**Comment by mmurukutla** [comment]
- Thank you for the response.
- We have internet connection for sure.
- I work on VDI machine using VMWare and not using VPN.
- And GIT is able to download the repository but not NPM.
- Also it was working fine few days ago and now it is saying bad object and the bad object id in the error is commit id.
- And in we registered below proxies (these are in .npmrc file)
      proxy=http://proxy.<our domain>.com:8080/
      strict-ssl=false
      https-proxy=http://proxy.<our domain>.com:8080/

**Comment by legodude17** [comment]
Is your proxy messing up the response?

**Comment by mmurukutla** [comment]
I deleted those Proxy settings but still getting same error.

**Comment by legodude17** [comment]
What is `npm config get registry`?

**Comment by mmurukutla** [comment]
Can you elaborate your question, I am sorry, i didn't get you.

**Comment by legodude17** [comment]
What is the result of running the command `npm config get registry`?

**Comment by mmurukutla** [comment]
Please refer below:
![image](https://cloud.githubusercontent.com/assets/20815123/20295731/b9323d94-ab2c-11e6-879d-b769dff80760.png)

**Comment by mmurukutla** [comment]
Hi, could you share if you have any thoughts on this? we are blocked here and no further thoughts to apply.

**Comment by legodude17** [comment]
What version of `git` do you have?

**Comment by mmurukutla** [comment]
We are using 2.10.2

![image](https://cloud.githubusercontent.com/assets/20815123/20476620/f192c378-aff7-11e6-99a5-9d9946f622b0.png)

**Comment by mmurukutla** [comment]
It has been fixed. We were trying with Personal Access Token on the machine where Git is already configured. We removed the token from URL and it started working.
Thank you for your response.

**Comment by legodude17** [comment]
Thank you for your patience @mmurukutla. Anyone still having this issue?

**Comment by Jmales** [comment]
Yes, me on Windows 10. https://github.com/npm/npm/issues/15699

**Comment by legodude17** [comment]
This can be closed @KenanY

**Comment by waseem18** [comment]
@legodude17 Is this problem resolved? I'm still facing it.

> wasim@waseem18:~/Desktop/project

$ npm install xlsx
npm ERR! Linux 4.4.0-64-generic
npm ERR! argv "/home/wasim/.nvm/versions/node/v6.9.1/bin/node" "/home/wasim/.nvm/versions/node/v6.9.1/bin/npm" "install" "xlsx"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code EREADFILE

> npm ERR! Error extracting /home/wasim/.npm/cfb/0.10.2/package.tgz archive: ENOENT: no such file or directory, open '/home/wasim/.npm/cfb/0.10.2/package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

> npm ERR! Please include the following file with any support request:
npm ERR!     /home/wasim/Desktop/tablor/npm-debug.log
wasim@waseem18:~/Desktop/tablor$
