### ISSUE TITLE
npm WARN enoent ENOENT: no such file or directory

### ISSUE THREAD

**Issue by sahtlil** [npm/npm#15192]
while installing things on npm always I got the errors of : npm WARN enoent ENOENT: no such file or directory
any explanations ?
C:\Users\sahtlil07\Desktop\My Project\recovery\bizlight 2>npm install --save-dev gulp-livereload
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\sahtlil07\Desktop\My Project\recovery\bizlight 2\package.json'
C:\Users\sahtlil07\Desktop\My Project\recovery\bizlight 2
`-- gulp-livereload@3.8.1
  +-- chalk@0.5.1
  | +-- ansi-styles@1.1.0
  | +-- has-ansi@0.1.0
  | | `-- ansi-regex@0.2.1
  | +-- strip-ansi@0.3.0
  | `-- supports-color@0.2.0
  +-- debug@2.3.3
  | `-- ms@0.7.2
  +-- event-stream@3.3.4
  | +-- duplexer@0.1.1
  | +-- from@0.1.3
  | +-- map-stream@0.1.0
  | +-- pause-stream@0.0.11
  | +-- split@0.3.3
  | +-- stream-combiner@0.0.4
  | `-- through@2.3.8
  +-- lodash.assign@3.2.0
  | +-- lodash._baseassign@3.2.0
  | `-- lodash._createassigner@3.1.1
  |   `-- lodash._bindcallback@3.0.1
  `-- mini-lr@0.1.9
    +-- body-parser@1.14.2
    | +-- bytes@2.2.0
    | +-- content-type@1.0.2
    | +-- debug@2.2.0
    | | `-- ms@0.7.1
    | +-- depd@1.1.0
    | +-- http-errors@1.3.1
    | | `-- statuses@1.3.1
    | +-- iconv-lite@0.4.13
    | +-- on-finished@2.3.0
    | | `-- ee-first@1.1.1
    | +-- qs@5.2.0
    | +-- raw-body@2.1.7
    | | +-- bytes@2.4.0
    | | `-- unpipe@1.0.0
    | `-- type-is@1.6.14
    |   +-- media-typer@0.3.0
    |   `-- mime-types@2.1.13
    |     `-- mime-db@1.25.0
    +-- faye-websocket@0.7.3
    | `-- websocket-driver@0.6.5
    |   `-- websocket-extensions@0.1.1
    +-- livereload-js@2.2.2
    +-- parseurl@1.3.1
    `-- qs@2.2.5

npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\sahtlil07\Desktop\My Project\recovery\bizlight 2\package.json'
npm WARN bizlight 2 No description
npm WARN bizlight 2 No repository field.
npm WARN bizlight 2 No README data
npm WARN bizlight 2 No license field.

**Comment by legodude17** [comment]
This is the expected behavior when you don't have a package.json. What is the problem?

**Comment by Charlotteis** [comment]
@sahtlil, you can't `--save-dev` to a folder with no `package.json`

Try

`npm init` to get setup your package.json
then you can do `npm install --save-dev gulp-livereload`

**Comment by KenanY** [comment]
Closing since this behavior is 100% intentional.

**Comment by hidaytrahman** [comment]
@Charlotteis: thanks!  this is fixed previous error and made a json file.
but now am getting another message, that is 
> npm WARN first-app@1.0.0 No repository field.
Now what's solution?

**Comment by worldwayii** [comment]
I am still getting this error guys. I tried running an angular 2 app and it surface. Also came up when i tried installing vue

**Comment by rkn411** [comment]
DevRabbit-MAC:~ DevRabbit$ npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (Logic) npm install --save-dev gulp-livereload
Sorry, name can only contain URL-friendly characters.
name: (Logic)

**Comment by abdallahokasha** [comment]
what happened with me that i had an old version of node and yeoman requires node v6 or higher
so i simply run:
```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```
and it works with me 
you can check this if you have Linux OS distribution:
[https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions)
[http://yeoman.io/codelab/setup.html](http://yeoman.io/codelab/setup.html)

**Comment by Mansi-Mittal** [comment]
run npm install -g express
This will solve the issue
