### ISSUE TITLE
Can't deprecate package

### ISSUE THREAD

**Issue by mk-pmb** [npm/npm#15450]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I accidentially published a package with bad bugs in it, so I try to unpublish it, but npm fails (after a long wait) with
```text
"generic-diff-context status = 403" : generic-diff-context
```

So I tried to at least deprecate the package, and get an even more strange error:
```text
npm ERR! 'object' == 'string'
```
No idea what that could mean.

#### How can the CLI team reproduce the problem?

1. Use Node.js v6.9.4, npm v3.10.10, Ubuntu 14.04.5 LTS trusty
2. Clone [my broken code](https://github.com/mk-pmb/generic-diff-context-js/commit/47840b06fb883737539143ce987bcc627648850a)
3. Change package name or use a registry where you own it
4. `npm deprecate . "gdc.splitFinalLfPart duplicates the entire part even if it's huge"`
5. npm takes a long time and then says `npm ERR! 'object' == 'string'`

Debug log: https://gist.github.com/mk-pmb/dda12fe43eeb5e6ed82ed71cfa97ae26

### supporting information:

 - `npm -v` prints: 3.10.10
 - `node -v` prints: v6.9.4
 - `npm config get registry` prints: http://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [x] I use a proxy to connect to the web.
   - [x] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by legodude17** [comment]
Try updating npm to the latest version

**Comment by mk-pmb** [comment]
Actually, I did install npm@latest. `npm --version` reported `4.0.5` and `which npm` reported a file inside my home directory, but the debug log didn't change.
I tried again, and this time removed `/usr/lib/node_modules/npm/`. The version line in the debug log now shows `npm ERR! npm  v4.0.5` but the error messages are the same for both unpublish and deprecate.

**Comment by dzonatan** [comment]
@mk-pmb Were you able to solve this issue?

**Comment by mk-pmb** [comment]
@dzonatan nope, I still have no idea what

> npm ERR! 'object' == 'string'

could mean.

**Comment by legodude17** [comment]
Maybe try using the latest version? (`4.3.0`?)

**Comment by kentcdodds** [comment]
I'm also seeing this:

- package: `p-s`
- npm: `4.3.0`
- node: `6.9.5`
- OS: Mac OSX 10.11.6 (El Capitan)

```
~/Desktop/tmp
😄  $ npm deprecate p-s@"^4" "this has been renamed to nps. Uninstall p-s and install nps instead"
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/kdodds/.nvm/versions/node/v6.9.5/bin/node" "/Users/kdodds/.nvm/versions/node/v6.9.5/bin/npm" "deprecate" "p-s@^4" "this has been renamed to nps. Uninstall p-s and install nps instead"
npm ERR! node v6.9.5
npm ERR! npm  v4.3.0
npm ERR! code E500

npm ERR! "p-s status = 403" : p-s
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kdodds/.npm/_logs/2017-02-18T06_07_13_799Z-debug.log
```

**Comment by bsc1780** [comment]
<xsd:simpleType name="TypeName"> 
 <xsd:restriction base="xsd:boolean"/> 
</xsd:simpleType>

**Comment by i-like-robots** [comment]
I am also suffering from this problem, I believe it may be because the package has multiple owners or perhaps has previously changed ownership in the past.


```
$ npm deprecate next-ft-api-client@"^3" "This module is no longer maintained. Please use Next API or speak to a member of the Next team about using Elasticsearch."
npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/matt.hinchliffe/.nvm/versions/node/v6.6.0/bin/node" "/Users/matt.hinchliffe/.nvm/versions/node/v6.6.0/bin/npm" "deprecate" "next-ft-api-client@^3" "This module is no longer maintained. Please use Next API or speak to a member of the Next team about using Elasticsearch."
npm ERR! node v6.6.0
npm ERR! npm  v4.3.0
npm ERR! code E500

npm ERR! "next-ft-api-client status = 403" : next-ft-api-client
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/matt.hinchliffe/.npm/_logs/2017-02-20T16_04_07_403Z-debug.log
```

And the log... http://pastebin.com/ne7GCVxg

**Comment by dzonatan** [comment]
@i-like-robots in my case no multiple owners nor it have changed.. still getting same error ;(

**Comment by kentcdodds** [comment]
I should have mentioned mine also has only had one owner (me).

**Comment by dzonatan** [comment]
@zkat @iarna ping.

**Comment by zkat** [comment]
If you're logged in to the correct user (check `npm whoami`), then you'll need to file an issue over at https://github.com/npm/registry, since this is likely a registry issue.

**Comment by mk-pmb** [comment]
> since this is likely a registry issue.

If it really is a registry issue, I'd expect npm-cli to either explain it better, or communicate more clearly that it doesn't know either and can't do better than just report what the registry said.

**Comment by zkat** [comment]
@mk-pmb I would expect that too, and that's something we're working on improving, but it happens to be lower priority than, well... all the other things (right now?)

**Comment by mk-pmb** [comment]
No problem. :-) Same reason here, keeping me from investigating that `'object' == 'string'` myself.

**Comment by dzonatan** [comment]
@mk-pmb @kentcdodds should work now. https://github.com/npm/registry/issues/131

**Comment by i-like-robots** [comment]
All working here 👍

**Comment by mk-pmb** [comment]
Has it arrived in the "latest" branch yet? I cloned a08189f3b0d0409db6d5774d3943d45be252c9b7, changed my command mappings to use its `cli.js`, and still get the cryptic error, although in condensed form.
Log file: https://gist.github.com/mk-pmb/e890e33fdb7f7397a9d075d682029336
Versions: Node.js v6.10.0, npm v4.4.0, Ubuntu 14.04.5 LTS trusty.
