### ISSUE TITLE
npm update -g npm fails (ENOENT node_modules/.staging/@npmcorp/copy-5f73018a)

### ISSUE THREAD

**Issue by EtienneMiret** [npm/npm#16055]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

When trying to update npm, I get the below error:
```
npm ERR! Linux 4.4.0-66-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update" "-g" "npm"
npm ERR! node v7.7.3
npm ERR! npm  v4.1.2
npm ERR! path /usr/local/lib/node_modules/.staging/@npmcorp/copy-5f73018a
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/@npmcorp/copy-5f73018a' -> '/usr/local/lib/node_modules/npm/node_modules/@npmcorp/copy'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/@npmcorp/copy-5f73018a' -> '/usr/local/lib/node_modules/npm/node_modules/@npmcorp/copy'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/etienne/Téléchargements/node-v7.7.3-linux-x64/npm-debug.log
```

After the update, npm won't run at all (/usr/local/bin/npm was removed during the update).

#### How can the CLI team reproduce the problem?

Run `sudo npm update -g npm` (WARNING: this will break your npm installation)

### supporting information:

 - `npm -v` prints: 4.1.2
 - `node -v` prints: v7.7.3
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by xafarr** [comment]
Happened to me as well.

**Comment by xafarr** [comment]
@EtienneMiret Did you try to update it through Homebrew or some other method ?

**Comment by EtienneMiret** [comment]
No. I installed the latest node from https://nodejs.org/en/ and then ran `sudo npm update -g npm`.

**Comment by blakcap** [comment]
Getting the same thing, on vanilla Arch Linux. I've tried the official versions through pacman, the AUR NVM, and just installing NVM by myself. Every one is getting this error.

**Comment by xafarr** [comment]
I updated node through Homebrew and then did npm update -g.

**Comment by blakcap** [comment]
@xafarr did it work?

I ended up just installing the last version (`npm i -g npm@v4.1.1`) and it works fine.

**Comment by xafarr** [comment]
@blakcap No. I meant to say that I did "npm update -g" and it broke. After that I could not find "npm" in my PATH. Somehow the update deleted the "npm" executable from /usr/local/bin. Attached is the debug file that got generated when I ran the command.
[npm-debug.txt](https://github.com/npm/npm/files/847428/npm-debug.txt)

**Comment by zirill** [comment]
I also can not update for a few days on centos 6/7
"npm update npm -g"

**Comment by stevefaulkner** [comment]
we are experiencing same issue

**Comment by AykutCevik** [comment]
fixed it with ```npm i -g npm@latest```

**Comment by stephenmoore56** [comment]
Experiencing the same issue / symptoms on Ubuntu 16.04.  Purging / reinstalling nodejs and npm didn't help.

9198 verbose stack Error: ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/@npmcorp/copy-0e0b3de3' -> '/usr/lib/node_modules/npm/node_modules/@npmcorp/copy'
9199 verbose cwd /home/stephen
9200 error Linux 4.4.0-67-generic
9201 error argv "/usr/bin/nodejs" "/usr/bin/npm" "update" "-g"
9202 error node v7.7.3
9203 error npm  v4.1.2
9204 error path /usr/lib/node_modules/.staging/@npmcorp/copy-0e0b3de3
9205 error code ENOENT
9206 error errno -2
9207 error syscall rename
9208 error enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/@npmcorp/copy-0e0b3de3' -> '/usr/lib/node_modules/npm/node_modules/@npmcorp/copy'
9209 error enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/@npmcorp/copy-0e0b3de3' -> '/usr/lib/node_modules/npm/node_modules/@npmcorp/copy'
9209 error enoent This is most likely not a problem with npm itself
9209 error enoent and is related to npm not being able to find a file.
9210 verbose exit [ -2, true ]

**Comment by wiggels** [comment]
I was also experiencing this on Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-64-generic x86_64)...
I uninstalled nodejs, reinstalled, and updated to latest npm thanks to @AykutCevik response.
Thanks @AykutCevik! Didn't even think of that...

**Comment by zkat** [comment]
Fixed by https://github.com/npm/npm/pull/16053

General note that `npm@next` is essentially a beta channel. Please stick to `npm@latest` if you need something that we have more confidence around. :)

**Comment by iarna** [comment]
This should be fixed now with [v4.4.4](https://github.com/npm/npm/releases/tag/v4.4.4). It turns out there had been long standing bugs involving bundled dependencies and scoped modules that we only managed to just step on.

If you just failed to upgrade `npm` then you can try again. If you have a broken v4.4.2 install:

…and you're on Mac or Linux you can use the [fancy unix install](https://github.com/npm/npm/#fancy-install-unix) described in the readme.

…if you're on Windows then run from `cmd`:
```
del /Q /S %APPDATA%\npm\node_modules\npm
npm install -g npm@next
```

**Comment by EtienneMiret** [comment]
Reading [npm-update][1] it seems me that `npm update -g npm` should install `npm@latest`. Hence, @zkat's comment confuses me. Should I specify `npm update -g npm@latest` when I want to update npm to a stable release?

[1]: https://docs.npmjs.com/cli/update

**Comment by myst729** [comment]
Still encounter the issue with node 7.7.4:

1. Download the Mac installer from https://nodejs.org/en/
2. Install
3. Run `npm update -g`, it tells me npm has updated to 4.4.4
4. Run the npm command again, now it breaks:

```sh
npm -v
module.js:472
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

`npm i -g npm@latest` will install 4.4.1, but it also breaks.

**Comment by luchillo17** [comment]
Can this be re-open? i just get a similar issue with `npm@5.4.1`:
![image](https://user-images.githubusercontent.com/9698639/30144882-9122f306-9353-11e7-82bd-cbfe355ca990.png)

**Comment by lod61** [comment]
When i run `npm i -g npm@latest` it talk me `Please try running this command again as root/Administrator.`&& my npm was useless,so i reinstall my node and npm,and run `sudo i -g npm@latest`,it work.
