### ISSUE TITLE
npm@5.0.0-beta.44 not working well with 302 redirect from http to https

### ISSUE THREAD

**Issue by yyjdelete** [npm/npm#16569]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm@5.0.0-beta.44 not working well with 302 redirect from http to https, while npm@4 works well.
#### How can the CLI team reproduce the problem?

```
> npm5 config set registry http://r.cnpmjs.org

> npm5 install caniuse-db@^1.0.30000634
npm ERR! Protocol "https:" not supported. Expected "http:"

# set to an working proxy
> npm5 config set proxy http://127.0.0.1:8888

> npm5 install caniuse-db@^1.0.30000634
npm ERR! code E400
npm ERR! 400 Bad Request: caniuse-db@1.0.30000634

```
[logs](https://gist.github.com/yyjdelete/ec6ce472f21a4dcf72b5c655bd39f9c2)
And found npm5 is trying to access https://xxx/ with http://xxx:443 with proxy.

Or just install direct, with/without an proxy(different behavior).
```
npm5 install http://r.cnpmjs.org/caniuse-db/download/caniuse-db-1.0.30000634.tgz
```

### supporting information:

 - `npm5 -v` prints:`5.0.0-beta.44`
 - `node -v` prints:`v7.10.0`
 - `npm5 config get registry` prints:`http://r.cnpmjs.org/` or `http://registry.npm.taobao.org/`
 - Windows, OS X/macOS, or Linux?: `Windows`
 - Network issues:
   - Geographic location where npm was run:`China`
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

#16510

**Comment by drewfish** [comment]
I'm running into this as well with 5.0.0-beta.46. Our company's internal registry mirror uses https.

**Comment by zkat** [comment]
Was this working with earlier betas?...

**Comment by yyjdelete** [comment]
@zkat
Seems only works with `5.0.0-beta.1`

version(5.0.0-beta.*)|status 
---|---
1		|working
30		|NOT working
31		|NOT working
32|not tested
33|not tested
34|not tested
35|not tested
36		|NOT working
37|not tested
38|not tested
39|not tested
40|not tested
41|not tested
42		|NOT working
43		|NOT working
44		|NOT working
45|not tested
46		|NOT working

**Comment by zkat** [comment]
As mentioned in #16613, this is almost certainly due to `make-fetch-happen` currently being unable to switch agents during redirects. https://github.com/zkat/make-fetch-happen/issues/26 is the relevant tracking issue for the bug in that library. Once that's fixed (if any community folks care to volunteer before I get around to it!), this should also be fixed 🎉

**Comment by zkat** [comment]
@yyjdelete This should be fixed as of `beta.58`. Do you mind confirming that this is working for you now, and I can close this?

**Comment by yyjdelete** [comment]
@zkat Now it work without proxy, but still `ERR! 400 Bad Request` with proxy.

**Comment by yyjdelete** [comment]
Maybe it's an new issue with proxy. Install directly with proxy get the same result.

```
#Watch it with Fiddler, Charles or some other tools
npm5 config set proxy=http://127.0.0.1:8888
npm5 i https://cnpmjs.oss-ap-southeast-1.aliyuncs.com/caniuse-db/-/caniuse-db-1.0.30000634.tgz
```
Expected: Get an `CONNECT cnpmjs.oss-ap-southeast-1.aliyuncs.com:443 HTTP/1.1` request.
Actual: Get an `GET http://cnpmjs.oss-ap-southeast-1.aliyuncs.com:443/caniuse-db/-/caniuse-db-1.0.30000634.tgz HTTP/1.1` request.

**Comment by yyjdelete** [comment]
@zkat May found the reason.
https://github.com/zkat/make-fetch-happen/blob/f45c915/agent.js#L137
Unlike `socks-proxy-agent`, `http-proxy-agent` and `https-proxy-agent` should be chosen by destUrl(`isHttps`) instead of `proxyUrl`.

https://github.com/zkat/make-fetch-happen/blob/f45c915/agent.js#L151
`proxyUrl.startsWith is not a function`

**Comment by zkat** [comment]
@yyjdelete nice catch. Would you like to put a patch together for this? I can help however you want. Otherwise, I can pick it up in the next couple of days. I really appreciate the time you've taken with this. It's been really helpful!

I was really worried about this part of the code in particular, since it's a setup I'm less familiar with, and also has a lot of sharp edges. It was a big reason for us to keep using `request` and `npm-registry-client`.

Anyway lmk if you're interested in submitting a patch :)

**Comment by zkat** [comment]
@yyjdelete I went ahead and patched it myself, since you pretty much spelled out the patch for me. Thanks a ton for that. I've pushed `beta.59` which should do proper https tunneling now. Fingers crossed that this does it 😂

**Comment by zkat** [comment]
`beta.60` includes a better patch for the same issue. I jumped the gun a bit and didn't notice @yyjdelete's PR, which was better than my hacky thing.

As they pointed out, there's still a keepalive issue with the proxy, and socks proxies still don't quite work. This is going to require more effort than I think I can expect to have done in the next couple of days, since it might require rewriting/fixing proxy libraries. womp womp

I'll close this one @yyjdelete confirmed that this specific issue has been fixed for them. Cheers~

**Comment by yyjdelete** [comment]
Fixed in `beta.60`.

**Comment by yyjdelete** [comment]
For the socks-proxy: 
https://github.com/JoshGlazebrook/socks/commit/c65706d6b95c1d002fcf61db828b3e11f7622b6e
should also be apply
https://github.com/TooTallNate/node-agent-base/blob/master/agent.js
which both used by `socks-proxy-agent`.
Maybe you can create an PR.

**Comment by zkat** [comment]
@yyjdelete the socks proxy issue is still a concern, but `beta.63` fixes the dangling npm process issue. npm should exit when it's done installing, now, even if you use a proxy.
