### ISSUE TITLE
Docker: Error: Cannot find module 'semver'

### ISSUE THREAD

**Issue by olalonde** [npm/npm#16807]
```Dockerfile
FROM node:7.10.0
RUN npm install npm@5 -g
```

When I run `npm info` using the Dockerfile above, I'm getting this:

```
module.js:472
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by zkat** [comment]
This... is what I'd expect to see from a completely hosed npm install. Huh. Can you see if you can figure out what's missing from this after install?

**Comment by SimenB** [comment]
```Dockerfile
FROM node:7.10.0
RUN npm install npm@5 -g
RUN apt-get update && apt-get install tree -y

CMD ["tree", "/usr/local/lib/node_modules/"]
```

```sh-session
$ docker build -t npm5-bug .
#...
$ docker run npm5-bug | pbcopy
```

output: https://gist.github.com/SimenB/937400a0d022ceee3182d4ec87a77fc3

**Comment by zkat** [comment]
🤔 ?!

**Comment by SimenB** [comment]
@zkat was that a "I don't get the error 🤔" or an "I don't get the repro you provided 🤔"? 😀

**Comment by SimenB** [comment]
Just listing the directories

```Dockerfile
FROM node:7.10.0
RUN npm install npm@5 -g

CMD ["ls", "-l", "/usr/local/lib/node_modules/npm/node_modules"]
```

```
total 172
drwxr-xr-x 5 nobody root 4096 Jun  1 06:58 JSONStream
drwxr-xr-x 2 nobody root 4096 Jun  1 06:58 abbrev
drwxr-xr-x 2 nobody root 4096 Jun  1 06:58 aproba
drwxr-xr-x 3 nobody root 4096 Jun  1 06:58 bluebird
drwxr-xr-x 5 nobody root 4096 Jun  1 06:58 cacache
drwxr-xr-x 2 nobody root 4096 Jun  1 06:58 call-limit
drwxr-xr-x 3 root   root 4096 Jun  1 06:58 columnify
drwxr-xr-x 2 nobody root 4096 Jun  1 06:58 detect-indent
drwxr-xr-x 3 root   root 4096 Jun  1 06:58 dezalgo
drwxr-xr-x 3 nobody root 4096 Jun  1 06:58 fs-vacuum
drwxr-xr-x 3 nobody root 4096 Jun  1 06:58 fs-write-stream-atomic
drwxr-xr-x 4 nobody root 4096 Jun  1 06:58 fstream
drwxr-xr-x 5 nobody root 4096 Jun  1 06:58 fstream-npm
drwxr-xr-x 3 nobody root 4096 Jun  1 06:58 glob
drwxr-xr-x 2 nobody root 4096 Jun  1 06:58 hosted-git-info
drwxr-xr-x 3 nobody root 4096 Jun  1 06:58 init-package-json
drwxr-xr-x 2 nobody root 4096 Jun  1 06:58 lazy-property
drwxr-xr-x 4 nobody root 4096 Jun  1 06:58 lru-cache
drwxr-xr-x 3 root   root 4096 Jun  1 06:58 mississippi
drwxr-xr-x 3 nobody root 4096 Jun  1 06:58 move-concurrently
drwxr-xr-x 8 nobody root 4096 Jun  1 06:58 node-gyp
drwxr-xr-x 4 nobody root 4096 Jun  1 06:58 normalize-package-data
drwxr-xr-x 2 nobody root 4096 Jun  1 06:58 npm-package-arg
drwxr-xr-x 4 nobody root 4096 Jun  1 06:58 npm-registry-client
drwxr-xr-x 2 nobody root 4096 Jun  1 06:58 npm-user-validate
drwxr-xr-x 3 nobody root 4096 Jun  1 06:58 npmlog
drwxr-xr-x 2 nobody root 4096 Jun  1 06:58 opener
drwxr-xr-x 4 nobody root 4096 Jun  1 06:58 pacote
drwxr-xr-x 2 nobody root 4096 Jun  1 06:58 promise-inflight
drwxr-xr-x 3 root   root 4096 Jun  1 06:58 read
drwxr-xr-x 4 nobody root 4096 Jun  1 06:58 read-package-json
drwxr-xr-x 5 nobody root 4096 Jun  1 06:58 readable-stream
drwxr-xr-x 4 nobody root 4096 Jun  1 06:58 request
drwxr-xr-x 2 nobody root 4096 Jun  1 06:58 rimraf
drwxr-xr-x 2 nobody root 4096 Jun  1 06:58 safe-buffer
drwxr-xr-x 3 root   root 4096 Jun  1 06:58 sorted-union-stream
drwxr-xr-x 2 nobody root 4096 Jun  1 06:58 ssri
drwxr-xr-x 3 root   root 4096 Jun  1 06:58 tar
drwxr-xr-x 3 nobody root 4096 Jun  1 06:58 update-notifier
drwxr-xr-x 3 root   root 4096 Jun  1 06:58 validate-npm-package-license
drwxr-xr-x 4 nobody root 4096 Jun  1 06:58 validate-npm-package-name
drwxr-xr-x 4 nobody root 4096 Jun  1 06:58 which
drwxr-xr-x 2 nobody root 4096 Jun  1 06:58 write-file-atomic
```

**Comment by zkat** [comment]
@SimenB "don't get the error"

That seems like a kinda random selection of missing deps.

**Comment by zeg-io** [comment]
I have this same error within Ubuntu Docker from Mac

**Comment by Lange** [comment]
FWIW I'm having this same problem on both my main Windows 10 x64 dev environment and on Travis linux containers. `npm i` seems to leave out certain deps. It's not random, as it's always the same deps. In my case, `semver` is also one of these deps. I am not using Docker at any point in my workflow.

**Comment by kazazor** [comment]
I'm having the same issue. In addition to the topic above I'm also seeing what @Lange mentioned and some dependencies are being broken for some reason.
You can take as example `cross-env`.

It seems like npm is really broken on Docker :/

**Comment by iamdoron** [comment]
The problem is not fresh installing npm on docker/linux, but upgrading. 
I had similar issues in MacOS with some `npm i`. Usually I just remove the node_modules and start a clean install if that happens. I couldn't reproduce it now, though.

In this case, as a workaround, you can do the following: 
```
FROM node:6.10.3
RUN npm i -g npm3 && npm3 -g uninstall npm
RUN npm3 i -g npm@5.0.3
RUN npm -v
```

I can also see this issue when installing npm2. If you run in the `node:6.10.3` docker image:
```
npm i -g npm@2
npm -v
```

```
module.js:471
    throw err;
    ^

Error: Cannot find module 'are-we-there-yet'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npmlog/log.js:2:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by rpadovani** [comment]
I had the same problem on a Linux machine.

Updating npm to last version (5.0.3), removing `node_modules/` AND `package-lock.json`, and then reinstalling again fixed everything

**Comment by olalonde** [comment]
Still same bug in Docker with npm 5.0.3: https://gist.github.com/73c41c8b587b74648dac98640a83ebff

**Comment by hutson** [comment]
Reposting from #15611 

---

I've recently found myself running into this exact same problem while attempting to run builds within GitLab CI.

It only occurs while using the `node:6` and `node:latest` Docker images. `node:4` works fine.

Therefore, I've needed to set those GitLab CI jobs to allow failure.

My GitLab CI YAML file looks like the following:

```yaml
stages:
    - test

.node_4: &node_4
  image: node:4

.node_6: &node_6
  image: node:6

.npm: &npm
  script:
    - npm update && npm test

.npm_4: &npm_4
  <<: [*npm]
  before_script:
    - npm prune
    - npm install --global npm@4

node_4_npm_4:
  <<: [*node_4, *npm_4]
  stage: test

node_6_node_6_npm_4:
  <<: [*node_6, *npm_4]
  stage: test
```

My `package.json` file looks like:

```json
{
  "license": "Apache-2.0",
  "name": "test-failures",
  "scripts": {
    "test": "echo 'no tests'"
  },
  "version": "1.0.0"
}
```

The output from my CI job is:

```bash
`-- npm@4.5.0 
  +-- abbrev@1.1.0 
  +-- ansi-regex@2.1.1 
  +-- aproba@1.1.1 
  +-- bluebird@3.5.0 
  +-- call-limit@1.1.0 
  +-- fs-vacuum@1.2.10 
  +-- fs-write-stream-atomic@1.0.10 
  +-- fstream@1.0.11 
  +-- glob@7.1.1 
  +-- graceful-fs@4.1.11 
  +-- hosted-git-info@2.4.1 
  +-- inflight@1.0.6 
  +-- init-package-json@1.9.5 
  +-- JSONStream@1.3.1 
  | +-- jsonparse@1.3.0 
  | `-- through@2.3.8 
  +-- lazy-property@1.0.0 
  +-- lockfile@1.0.3 
  +-- mississippi@1.3.0 
  | +-- concat-stream@1.6.0 
  | | `-- typedarray@0.0.6 
  | +-- duplexify@3.5.0 
  | | +-- end-of-stream@1.0.0 
  | | | `-- once@1.3.3 
  | | `-- stream-shift@1.0.0 
  | +-- end-of-stream@1.1.0 
  | | `-- once@1.3.3 
  | +-- flush-write-stream@1.0.2 
  | +-- from2@2.3.0 
  | +-- parallel-transform@1.1.0 
  | | `-- cyclist@0.2.2 
  | +-- pump@1.0.2 
  | +-- pumpify@1.3.5 
  | +-- stream-each@1.2.0 
  | | `-- stream-shift@1.0.0 
  | `-- through2@2.0.3 
  |   `-- xtend@4.0.1 
  +-- move-concurrently@1.0.1 
  | +-- copy-concurrently@1.0.3 
  | `-- run-queue@1.0.3 
  +-- node-gyp@3.6.0 
  | `-- nopt@3.0.6 
  +-- nopt@4.0.1 
  | `-- osenv@0.1.4 
  |   +-- os-homedir@1.0.2 
  |   `-- os-tmpdir@1.0.2 
  +-- normalize-package-data@2.3.6 
  +-- npm-package-arg@4.2.1 
  +-- npm-registry-client@8.1.0 
  | `-- concat-stream@1.6.0 
  +-- npmlog@4.0.2 
  | `-- gauge@2.7.2 
  |   +-- signal-exit@3.0.2 
  |   +-- string-width@1.0.2
  |   | +-- code-point-at@1.1.0 
  |   | `-- is-fullwidth-code-point@1.0.0
  |   |   `-- number-is-nan@1.0.1 
  |   `-- supports-color@0.2.0 
  +-- opener@1.4.3 
  +-- osenv@0.1.4 
  | +-- os-homedir@1.0.2 
  | `-- os-tmpdir@1.0.2 
  +-- read-package-json@2.0.5 
  +-- readable-stream@2.2.6 
  +-- request@2.81.0 
  | +-- aws4@1.6.0 
  | +-- caseless@0.12.0 
  | +-- form-data@2.1.2 
  | +-- har-validator@4.2.1 
  | | +-- ajv@4.11.4 
  | | | +-- co@4.6.0 
  | | | `-- json-stable-stringify@1.0.1 
  | | |   `-- jsonify@0.0.0 
  | | `-- har-schema@1.0.5 
  | +-- http-signature@1.1.1
  | | `-- sshpk@1.11.0 
  | |   +-- bcrypt-pbkdf@1.0.1 
  | |   +-- dashdash@1.14.1 
  | |   +-- jsbn@0.1.1 
  | |   `-- tweetnacl@0.14.5 
  | +-- mime-types@2.1.14 
  | | `-- mime-db@1.26.0 
  | +-- performance-now@0.2.0 
  | +-- qs@6.4.0 
  | +-- safe-buffer@5.0.1 
  | +-- tough-cookie@2.3.2 
  | | `-- punycode@1.4.1 
  | `-- tunnel-agent@0.6.0 
  +-- retry@0.10.1 
  +-- rimraf@2.6.1 
  +-- sorted-union-stream@2.1.3 
  | +-- from2@1.3.0 
  | | `-- readable-stream@1.1.14 
  | |   +-- core-util-is@1.0.2 
  | |   +-- isarray@0.0.1 
  | |   `-- string_decoder@0.10.31 
  | `-- stream-iterate@1.1.1 
  +-- update-notifier@2.1.0 
  | +-- boxen@1.0.0 
  | | +-- ansi-align@1.1.0 
  | | | `-- string-width@1.0.2 
  | | |   +-- code-point-at@1.1.0 
  | | |   `-- is-fullwidth-code-point@1.0.0 
  | | |     `-- number-is-nan@1.0.1 
  | | +-- camelcase@4.0.0 
  | | +-- cli-boxes@1.0.0 
  | | +-- string-width@2.0.0 
  | | | `-- is-fullwidth-code-point@2.0.0 
  | | +-- term-size@0.1.1 
  | | | `-- execa@0.4.0 
  | | |   +-- cross-spawn-async@2.2.5 
  | | |   | `-- lru-cache@4.0.2 
  | | |   |   +-- pseudomap@1.0.2 
  | | |   |   `-- yallist@2.0.0 
  | | |   +-- is-stream@1.1.0 
  | | |   +-- npm-run-path@1.0.0 
  | | |   +-- object-assign@4.1.1 
  | | |   +-- path-key@1.0.0 
  | | |   `-- strip-eof@1.0.0 
  | | `-- widest-line@1.0.0 
  | |   `-- string-width@1.0.2 
  | |     +-- code-point-at@1.1.0 
  | |     `-- is-fullwidth-code-point@1.0.0 
  | |       `-- number-is-nan@1.0.1 
  | +-- chalk@1.1.3 
  | | +-- ansi-styles@2.2.1 
  | | +-- escape-string-regexp@1.0.5 
  | | +-- has-ansi@2.0.0 
  | | `-- supports-color@2.0.0 
  | +-- configstore@3.0.0 
  | | +-- dot-prop@4.1.1 
  | | | `-- is-obj@1.0.1 
  | | `-- unique-string@1.0.0 
  | |   `-- crypto-random-string@1.0.0 
  | +-- is-npm@1.0.0 
  | +-- latest-version@3.0.0 
  | | `-- package-json@3.1.0 
  | |   +-- got@6.7.1 
  | |   | +-- create-error-class@3.0.2 
  | |   | | `-- capture-stack-trace@1.0.0 
  | |   | +-- duplexer3@0.1.4 
  | |   | +-- get-stream@3.0.0 
  | |   | +-- is-redirect@1.0.0 
  | |   | +-- is-retry-allowed@1.1.0 
  | |   | +-- is-stream@1.1.0 
  | |   | +-- lowercase-keys@1.0.0 
  | |   | +-- safe-buffer@5.0.1 
  | |   | +-- timed-out@4.0.1 
  | |   | +-- unzip-response@2.0.1 
  | |   | `-- url-parse-lax@1.0.0 
  | |   |   `-- prepend-http@1.0.4 
  | |   +-- registry-auth-token@3.1.0 
  | |   | `-- rc@1.1.7 
  | |   |   +-- deep-extend@0.4.1 
  | |   |   +-- minimist@1.2.0 
  | |   |   `-- strip-json-comments@2.0.1 
  | |   `-- registry-url@3.1.0 
  | |     `-- rc@1.1.7 
  | |       +-- deep-extend@0.4.1 
  | |       +-- minimist@1.2.0 
  | |       `-- strip-json-comments@2.0.1 
  | +-- lazy-req@2.0.0 
  | +-- semver-diff@2.1.0 
  | `-- xdg-basedir@3.0.0 
  +-- uuid@3.0.1 
  +-- validate-npm-package-name@3.0.0 
  | `-- builtins@1.0.3 
  +-- which@1.2.14 
  | `-- isexe@2.0.0 
  `-- write-file-atomic@1.3.1 

npm info ok 
$ npm update && npm test
module.js:471
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

According to the npm documentation I can uninstall npm by running `npm uninstall npm -g`.

Then I can run `curl -L https://www.npmjs.com/install.sh | sh`.

However, how do I specify the npm version? I would like to test multiple versions of npm.

**Comment by olalonde** [comment]
@hbetts I'm using this as a workaround:

```
  cd /tmp
  npm install "npm@5"
  rm -rf /usr/local/lib/node_modules
  mv node_modules /usr/local/lib/
```

**Comment by devonwesley** [comment]
@hbetts Did you ever figure out how to specify a npm version?

**Comment by hutson** [comment]
@Jusdev89 I haven't had an opportunity to move forward on this issue with my own personal projects.

The npm install script is incapable of installing other versions of npm other than latest.

Once I have a little time I plan on testing the suggestion made by @olalonde.

**Comment by hutson** [comment]
@Jusdev89 I finally had a few minutes to test @olalonde's suggestion.

His suggestion works quite well.

Here's the relevant snippet from my GitLab CI file:

```
    - currentDirectory=$(pwd)
    - mkdir -p /tmp/npm-install-directory
    - cd /tmp/npm-install-directory
    - npm install npm@2
    - rm -rf /usr/local/lib/node_modules
    - mv node_modules /usr/local/lib/
    - cd $currentDirectory
```

**Comment by snewell92** [comment]
Thanks a ton @Jusdev89 and @hbetts - had the same issue within GitLab CI + docker executor. 👍 💯 🎉 🎊

**Comment by devonwesley** [comment]
Sweet @hbetts Thank you so much for posting this.

**Comment by zkat** [comment]
This is definitely working for me in the latest canary, so I'm gonna call it done. Cheers~

**Comment by nkbt** [comment]
@zkat though there is a hacky workaround for this issue, it is still a quite major bug, which better be solved in a right way... I reckon it is too early to close this ticket

**Comment by zkat** [comment]
@nkbt no, like, I'm pretty sure it's _actually_ fixed, in the _right_ way, in the latest canary, since I can't get myself into this corner.

If you can reproduce this issue on the canary itself, I'll reopen, though.

**Comment by thats4shaw** [comment]
Stuck this issue with Gitlab CI also.  Here's my slight variation of @hbetts snippet I used:

```
  - mkdir -p /tmp/npm-install-directory
  - pushd /tmp/npm-install-directory
  - npm install npm@latest
  - rm -rf /usr/local/lib/node_modules
  - mv node_modules /usr/local/lib/
  - popd
```

**Comment by nkbt** [comment]
@zkat not sure how exactly it is fixed. I cannot install `npm@next` globally anyway

```sh
10:29 $ docker run -it mhart/alpine-node:7.10.0 sh
/ # npm install -g npm@next
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
- asap@2.0.5 node_modules/npm/node_modules/asap
- once@1.3.3 node_modules/npm/node_modules/mississippi/node_modules/end-of-stream/node_modules/once
- os-homedir@1.0.2 node_modules/npm/node_modules/nopt/node_modules/osenv/node_modules/os-homedir
- os-tmpdir@1.0.2 node_modules/npm/node_modules/nopt/node_modules/osenv/node_modules/os-tmpdir
- osenv@0.1.4 node_modules/npm/node_modules/nopt/node_modules/osenv
- supports-color@0.2.0 node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/supports-color
- buffer-shims@1.0.0 node_modules/npm/node_modules/readable-stream/node_modules/buffer-shims
- pseudomap@1.0.2 node_modules/npm/node_modules/update-notifier/node_modules/boxen/node_modules/term-size/node_modules/execa/node_modules/cross-spawn-async/node_modules/lru-cache/node_modules/pseudomap
- yallist@2.0.0 node_modules/npm/node_modules/update-notifier/node_modules/boxen/node_modules/term-size/node_modules/execa/node_modules/cross-spawn-async/node_modules/lru-cache/node_modules/yallist
- lru-cache@4.0.2 node_modules/npm/node_modules/update-notifier/node_modules/boxen/node_modules/term-size/node_modules/execa/node_modules/cross-spawn-async/node_modules/lru-cache
- spdx-exceptions@1.0.4 node_modules/npm/node_modules/validate-npm-package-license/node_modules/spdx-expression-parse/node_modules/spdx-exceptions
- spdx-license-ids@1.2.0 node_modules/npm/node_modules/validate-npm-package-license/node_modules/spdx-expression-parse/node_modules/spdx-license-ids
- normalize-git-url@3.0.2 node_modules/npm/node_modules/normalize-git-url
- realize-package-specifier@3.0.3 node_modules/npm/node_modules/realize-package-specifier
/usr/lib
`-- npm@5.0.4
  +-- aproba@1.1.2
  +-- cacache@9.2.8
# ~~~ CUT ~~~
  `-- write-file-atomic@2.1.0


/ # npm -v
module.js:472
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
/ #
```

**Comment by zkat** [comment]
@nkbt we mark things as fixed once they're in `release-next` and _usually_ also the canary. Please try to install `npm@latest` a little later today. We're about to tag `npm@5.1.0`.

**Comment by nkbt** [comment]
How to install it? It is not in dist tags

```sh
/ # npm i -g npm@release-next
npm ERR! code ETARGET
npm ERR! notarget No compatible version found: npm@release-next
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.1.25, 1.2.32, 1.3.2, 1.3.4, 1.2.20, 1.2.21, 1.2.22, 1.2.23, 1.2.24, 1.2.25, 1.2.27, 1.2.28, 1.2.30, 1.2.31, 1.3.0, 1.3.1, 1.2.19, 1.1.70, 1.1.71, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.3.9, 1.3.10, 1.3.11, 1.3.12, 1.3.13, 1.3.14, 1.3.15, 1.3.16, 1.3.17, 1.3.18, 1.3.20, 1.3.21, 1.3.22, 1.3.23, 1.3.24, 1.3.25, 1.3.26, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.4.10, 1.4.11, 1.4.12, 1.4.13, 1.4.14, 1.4.15, 1.4.16, 1.2.8000, 1.4.17, 1.4.18, 1.4.19, 1.5.0-alpha-0, 1.5.0-alpha-1, 1.4.20, 1.5.0-alpha-2, 1.4.21, 1.5.0-alpha-3, 1.5.0-alpha-4, 2.0.0-alpha-5, 1.4.22, 1.4.23, 2.0.0-alpha.6.0, 1.4.24, 2.0.0-alpha.6, 2.0.0-alpha.7, 2.0.0-beta.0, 1.4.25, 2.0.0-beta.1, 1.4.26, 2.0.0-beta.2, 1.4.27, 2.0.0-beta.3, 1.4.28, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9, 2.1.10, 2.1.11, 2.1.12, 2.1.13, 2.1.14, 2.1.15, 2.1.16, 2.1.17, 2.1.18, 2.2.0, 2.3.0, 2.4.0, 2.4.1, 2.5.0, 2.5.1, 2.6.0, 2.6.1, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.7.5, 2.7.6, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0, 2.9.1, 2.10.0, 2.10.1, 2.11.0, 2.11.1, 2.11.2, 2.11.3, 2.12.0, 3.0.0, 2.12.1, 2.13.0, 3.1.0, 2.13.1, 3.1.1, 3.1.2, 2.13.2, 3.1.3, 2.13.3, 3.2.0, 2.13.4, 3.2.1, 2.13.5, 3.2.2, 2.14.0, 3.3.0, 2.14.1, 2.14.2, 3.3.1, 2.14.3, 3.3.2, 2.14.4, 3.3.3, 2.14.5, 3.3.4, 2.14.6, 3.3.5, 3.3.6, 2.14.7, 2.14.8, 3.3.7, 3.3.8, 3.3.9, 3.3.10, 2.14.9, 3.3.11, 1.4.29, 3.3.12, 2.14.10, 3.4.0, 3.4.1, 2.14.11, 2.14.12, 3.5.0, 3.5.1, 2.14.13, 2.14.14, 3.5.2, 2.14.15, 3.5.3, 3.5.4, 3.6.0, 2.14.16, 2.14.17, 3.7.0, 3.7.1, 3.7.2, 2.14.18, 3.7.3, 2.14.19, 2.14.20, 3.7.4, 3.7.5, 2.14.21, 3.8.0, 2.14.22, 3.8.1, 3.8.2, 2.15.0, 2.15.1, 3.8.3, 2.15.2, 3.8.4, 3.8.5, 3.8.6, 2.15.3, 3.8.7, 2.15.4, 3.8.8, 3.8.9, 2.15.5, 3.9.0, 3.9.1, 2.15.6, 3.9.2, 3.9.3, 3.9.4, 3.9.5, 3.9.6, 3.10.0, 2.15.7, 3.10.1, 2.15.8, 3.10.2, 3.10.3, 3.10.4, 2.15.9, 3.10.5, 3.10.6, 3.10.7, 2.15.10, 3.10.8, 2.15.11, 3.10.9, 4.0.0, 4.0.1, 4.0.2, 3.10.10, 4.0.3, 4.0.5, 4.1.0, 4.1.1, 4.1.2, 4.2.0, 4.3.0, 4.4.0, 4.4.1, 4.4.2, 4.4.3, 4.4.4, 4.5.0, 2.15.12, 4.6.0, 4.6.1, 5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.0.4
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-07-06T01_14_08_397Z-debug.log
```

```sh
/ # npm info npm dist-tags

{ latest: '5.0.4',
  next: '5.0.4',
  'latest-2': '2.15.12',
  'next-2': '2.15.12',
  'latest-1': '1.4.29',
  lts: '2.15.11',
  'latest-3': '3.10.10',
  'next-3': '3.10.10',
  'latest-4': '4.6.1',
  'next-4': '4.6.1',
  'latest-5': '5.0.4',
  'next-5': '5.0.4',
  'v5.0-next': '5.0.4' }
```

**Comment by zkat** [comment]
@nkbt the canary exists as a separate package so it can exist side-by-side with regular npm: `npm i -g npmc && npmc -v`.

**Comment by zkat** [comment]
and by `release-next`, I'm referring to the _git_ branch. There is no released version of npm called `release-next`.

**Comment by nkbt** [comment]
Oh, ok, so it is not really possible to test that new `npm` does not screw old `npm` until you publish to "production"...

**Comment by zkat** [comment]
@nkbt then just wait.

**Comment by nkbt** [comment]
Well, I was just trying to help testing... 

We are totally ok with workarounds, and not in a hurry or something. I was pointing out that in current way you have with `npmc` there is no way to test that this issue is fixed or not until you roll this out as main `npm` update, which defies the purpose of having `canary` of some sorts in the first place.

**Comment by zkat** [comment]
@nkbt it's out. Go ahead and update.

**Comment by nkbt** [comment]
Nah, same stuff...

```sh
11:34 $ docker run -it mhart/alpine-node:7.10.0 sh
/ # npm -v
4.5.0
/ # npm install -g npm
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
- asap@2.0.5 node_modules/npm/node_modules/asap
- once@1.3.3 node_modules/npm/node_modules/mississippi/node_modules/end-of-stream/node_modules/once
- os-homedir@1.0.2 node_modules/npm/node_modules/nopt/node_modules/osenv/node_modules/os-homedir
- os-tmpdir@1.0.2 node_modules/npm/node_modules/nopt/node_modules/osenv/node_modules/os-tmpdir
- osenv@0.1.4 node_modules/npm/node_modules/nopt/node_modules/osenv
- supports-color@0.2.0 node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/supports-color
- buffer-shims@1.0.0 node_modules/npm/node_modules/readable-stream/node_modules/buffer-shims
- jodid25519@1.0.2 node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/node_modules/jodid25519
- safe-buffer@5.0.1 node_modules/npm/node_modules/request/node_modules/safe-buffer
- code-point-at@1.1.0 node_modules/npm/node_modules/update-notifier/node_modules/boxen/node_modules/ansi-align/node_modules/string-width/node_modules/code-point-at
- number-is-nan@1.0.1 node_modules/npm/node_modules/update-notifier/node_modules/boxen/node_modules/ansi-align/node_modules/string-width/node_modules/is-fullwidth-code-point/node_modules/number-is-nan
- is-fullwidth-code-point@1.0.0 node_modules/npm/node_modules/update-notifier/node_modules/boxen/node_modules/ansi-align/node_modules/string-width/node_modules/is-fullwidth-code-point
- string-width@1.0.2 node_modules/npm/node_modules/update-notifier/node_modules/boxen/node_modules/ansi-align/node_modules/string-width
- pseudomap@1.0.2 node_modules/npm/node_modules/update-notifier/node_modules/boxen/node_modules/term-size/node_modules/execa/node_modules/cross-spawn-async/node_modules/lru-cache/node_modules/pseudomap
- yallist@2.0.0 node_modules/npm/node_modules/update-notifier/node_modules/boxen/node_modules/term-size/node_modules/execa/node_modules/cross-spawn-async/node_modules/lru-cache/node_modules/yallist
- lru-cache@4.0.2 node_modules/npm/node_modules/update-notifier/node_modules/boxen/node_modules/term-size/node_modules/execa/node_modules/cross-spawn-async/node_modules/lru-cache
- safe-buffer@5.0.1 node_modules/npm/node_modules/update-notifier/node_modules/latest-version/node_modules/package-json/node_modules/got/node_modules/safe-buffer
- lazy-req@2.0.0 node_modules/npm/node_modules/update-notifier/node_modules/lazy-req
- spdx-exceptions@1.0.4 node_modules/npm/node_modules/validate-npm-package-license/node_modules/spdx-expression-parse/node_modules/spdx-exceptions
- spdx-license-ids@1.2.0 node_modules/npm/node_modules/validate-npm-package-license/node_modules/spdx-expression-parse/node_modules/spdx-license-ids
- normalize-git-url@3.0.2 node_modules/npm/node_modules/normalize-git-url
- realize-package-specifier@3.0.3 node_modules/npm/node_modules/realize-package-specifier
/usr/lib
`-- npm@5.1.0
# ~~~~ CUT ~~~~
  `-- write-file-atomic@2.1.0

/ # npm -v
module.js:472
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
/ #
```

**Comment by SimenB** [comment]
It also fails when updating from 5.0.3 to 5.1.0.

```Dockerfile
FROM node:8

RUN npm -v

RUN npm install -g npm@latest

RUN npm -v

CMD ["ls", "-l", "/usr/local/lib/node_modules/npm/node_modules"]
```

```
 ---> 8ef72c1dee73
Step 2/5 : RUN npm -v
 ---> Running in 2cbfce0bfc55
5.0.3
 ---> 83c98b4c09a3
Removing intermediate container 2cbfce0bfc55
Step 3/5 : RUN npm install -g npm@latest
 ---> Running in 1dce83820238
npm info it worked if it ends with ok
npm info using npm@5.0.3
npm info using node@v8.1.3
npm http fetch GET 200 https://registry.npmjs.org/npm 178ms
npm http fetch GET 200 https://registry.npmjs.org/npm/-/npm-5.1.0.tgz 3610ms

...

+ npm@5.1.0
added 27 packages, removed 16 packages and updated 47 packages in 12.02s
npm info ok
 ---> 8c958e9a9da9
Removing intermediate container 1dce83820238
Step 4/5 : RUN npm -v
 ---> Running in 18a0154ffd4c
module.js:487
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
The command '/bin/sh -c npm -v' returned a non-zero code: 1
```

`ls` before upgrade

```
total 380
drwxrwxr-x 4 500 500 4096 Jun 29 04:55 JSONStream
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 abbrev
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 ansi-regex
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 ansicolors
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 ansistyles
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 aproba
drwxrwxr-x 3 500 500 4096 Jun 29 04:55 archy
drwxrwxr-x 3 500 500 4096 Jun 29 04:55 bluebird
drwxrwxr-x 5 500 500 4096 Jun 29 04:55 cacache
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 call-limit
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 chownr
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 cmd-shim
drwxrwxr-x 3 500 500 4096 Jun 29 04:55 columnify
drwxrwxr-x 3 500 500 4096 Jun 29 04:55 config-chain
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 debuglog
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 detect-indent
drwxrwxr-x 3 500 500 4096 Jun 29 04:55 dezalgo
drwxrwxr-x 3 500 500 4096 Jun 29 04:55 editor
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 fs-vacuum
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 fs-write-stream-atomic
drwxrwxr-x 4 500 500 4096 Jun 29 04:55 fstream
drwxrwxr-x 4 500 500 4096 Jun 29 04:55 fstream-npm
drwxrwxr-x 3 500 500 4096 Jun 29 04:55 glob
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 graceful-fs
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 has-unicode
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 hosted-git-info
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 iferr
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 imurmurhash
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 inflight
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 inherits
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 ini
drwxrwxr-x 3 500 500 4096 Jun 29 04:55 init-package-json
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 lazy-property
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 lockfile
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 lodash._baseindexof
drwxrwxr-x 3 500 500 4096 Jun 29 04:55 lodash._baseuniq
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 lodash._bindcallback
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 lodash._cacheindexof
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 lodash._createcache
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 lodash._getnative
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 lodash.clonedeep
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 lodash.restparam
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 lodash.union
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 lodash.uniq
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 lodash.without
drwxrwxr-x 4 500 500 4096 Jun 29 04:55 lru-cache
drwxrwxr-x 3 500 500 4096 Jun 29 04:55 mississippi
drwxrwxr-x 5 500 500 4096 Jun 29 04:55 mkdirp
drwxrwxr-x 3 500 500 4096 Jun 29 04:55 move-concurrently
drwxrwxr-x 7 500 500 4096 Jun 29 04:55 node-gyp
drwxrwxr-x 5 500 500 4096 Jun 29 04:55 nopt
drwxrwxr-x 4 500 500 4096 Jun 29 04:55 normalize-package-data
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 npm-cache-filename
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 npm-install-checks
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 npm-package-arg
drwxrwxr-x 4 500 500 4096 Jun 29 04:55 npm-registry-client
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 npm-user-validate
drwxrwxr-x 3 500 500 4096 Jun 29 04:55 npmlog
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 once
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 opener
drwxrwxr-x 3 500 500 4096 Jun 29 04:55 osenv
drwxrwxr-x 4 500 500 4096 Jun 29 04:55 pacote
drwxrwxr-x 3 500 500 4096 Jun 29 04:55 path-is-inside
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 promise-inflight
drwxrwxr-x 4 500 500 4096 Jun 29 04:55 read
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 read-cmd-shim
drwxrwxr-x 3 500 500 4096 Jun 29 04:55 read-installed
drwxrwxr-x 3 500 500 4096 Jun 29 04:55 read-package-json
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 read-package-tree
drwxrwxr-x 5 500 500 4096 Jun 29 04:55 readable-stream
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 readdir-scoped-modules
drwxrwxr-x 4 500 500 4096 Jun 29 04:55 request
drwxrwxr-x 4 500 500 4096 Jun 29 04:55 retry
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 rimraf
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 safe-buffer
drwxrwxr-x 3 500 500 4096 Jun 29 04:55 semver
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 sha
drwxrwxr-x 3 500 500 4096 Jun 29 04:55 slide
drwxrwxr-x 3 500 500 4096 Jun 29 04:55 sorted-object
drwxrwxr-x 3 500 500 4096 Jun 29 04:55 sorted-union-stream
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 ssri
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 strip-ansi
drwxrwxr-x 5 500 500 4096 Jun 29 04:55 tar
drwxrwxr-x 3 500 500 4096 Jun 29 04:55 text-table
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 uid-number
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 umask
drwxrwxr-x 4 500 500 4096 Jun 29 04:55 unique-filename
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 unpipe
drwxrwxr-x 3 500 500 4096 Jun 29 04:55 update-notifier
drwxrwxr-x 4 500 500 4096 Jun 29 04:55 uuid
drwxrwxr-x 3 500 500 4096 Jun 29 04:55 validate-npm-package-license
drwxrwxr-x 3 500 500 4096 Jun 29 04:55 validate-npm-package-name
drwxrwxr-x 4 500 500 4096 Jun 29 04:55 which
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 wrappy
drwxrwxr-x 2 500 500 4096 Jun 29 04:55 write-file-atomic
```

`ls` after

```
total 92
drwxr-xr-x 3 root root    4096 Jul  6 05:48 JSONStream
drwxr-xr-x 2  501 dialout 4096 Jul  6 05:48 ansi-regex
drwxr-xr-x 5  501 dialout 4096 Jul  6 05:48 cacache
drwxr-xr-x 3 root root    4096 Jul  6 05:48 columnify
drwxr-xr-x 3 root root    4096 Jul  6 05:48 fstream-npm
drwxr-xr-x 3 root root    4096 Jul  6 05:48 glob
drwxr-xr-x 2  501 dialout 4096 Jul  6 05:48 hosted-git-info
drwxr-xr-x 3  501 dialout 4096 Jul  6 05:48 lru-cache
drwxr-xr-x 3 root root    4096 Jul  6 05:48 node-gyp
drwxr-xr-x 4  501 dialout 4096 Jul  6 05:48 normalize-package-data
drwxr-xr-x 2  501 dialout 4096 Jul  6 05:48 npm-package-arg
drwxr-xr-x 4  501 dialout 4096 Jul  6 05:48 npm-registry-client
drwxr-xr-x 3  501 dialout 4096 Jul  6 05:48 npmlog
drwxr-xr-x 4  501 dialout 4096 Jul  6 05:48 pacote
drwxr-xr-x 3  501 dialout 4096 Jul  6 05:48 read-package-json
drwxr-xr-x 5  501 dialout 4096 Jul  6 05:48 readable-stream
drwxr-xr-x 3 root root    4096 Jul  6 05:48 request
drwxr-xr-x 2  501 dialout 4096 Jul  6 05:48 safe-buffer
drwxr-xr-x 2  501 dialout 4096 Jul  6 05:48 ssri
drwxr-xr-x 3  501 dialout 4096 Jul  6 05:48 strip-ansi
drwxr-xr-x 3  501 dialout 4096 Jul  6 05:48 update-notifier
drwxr-xr-x 4  501 dialout 4096 Jul  6 05:48 uuid
drwxr-xr-x 6  501 dialout 4096 Jul  6 05:48 worker-farm
```

**Comment by zkat** [comment]
aaaaaa ok so

This isn't an `npm@5` issue. I got hella confused by what we were doing _differently_, but this is just plain not working and doesn't work with `npm@4` either:

```
FROM node:7
RUN npm -v
RUN npm install -g npm@4.6.1
RUN npm -v
```

Will reproduce this behavior just as well. I'm not sure what it is that's messing with Docker here specifically. I've removed the `npm5` tag, since this is a general issue, but I'll reopen this so we can look into it more.

**Comment by devonwesley** [comment]
@zkat Yeah that makes sense. I had to use v3.10.10, then it worked fine.

**Comment by batjko** [comment]
> This isn't an npm@5 issue. I got hella confused by what we were doing differently, but this is just plain not working and doesn't work with npm@4 either

@zkat Just to add context: I'm having the same issue with npm5, but it works again after downgrading back to npm4.

**Comment by shawnmcknight** [comment]
>I'm not sure what it is that's messing with Docker here specifically.

@zkat I'd just like to qualify that this may or may not be helpful.  I haven't done any research on this topic and my statement is merely based on behavior I saw when researching an entirely different issue.

In docker containers, the user is running with root privileges by default.  I'm seen that npm has certain failsafes in place to prevent running scripts when operating as root.  I know this impacted the running of "prepare" scripts in my CI environment (see #17346).  Is it possible that the npm@5 install in Docker issue isn't really a "Docker" issue, per se, but is instead related to running as root and npm lowering some privilege level under the covers?

**Comment by mtibben** [comment]
Semi-related, https://github.com/npm/npm/issues/17578 also demonstrates some weird behaviour when npm is running as root on docker

**Comment by SimenB** [comment]
`USER node` doesn't help, as the node user does not have access to the files of npm

**Comment by shawnmcknight** [comment]
> USER node doesn't help, as the node user does not have access to the files of npm

@SimenB I didn't mean to imply that operating in the container as the `node` user would resolve the problem.  I was just pointing out that the behavior we're seeing with npm@5 installs in the container environment might have something to do with being run as the root user in that environment.  It just stands out as a fairly large difference between operating in a traditional environment versus a container environment.  It might have absolutely nothing to do with the actual problem, but it might be a path that is worthy of some initial exploration.

**Comment by jspiro** [comment]
Also been suffering with this problem and using canary as a workaround:
`RUN npm install -g npmc@5.0.4-canary.10 && cd /usr/local/bin && rm npm && ln -s /root/n/bin/npmc npm`

Incidentally, installing npm with the canary doesn't get rid of the semver error, the only way around it is to symlink npm to the canary, or to install npm to a local directory and move it to node_modules.

**Comment by mtibben** [comment]
A quick and dirty workaround:

```Dockerfile
FROM node:8

# update npm to v5.1.0
RUN rm -rf /usr/local/lib/node_modules/npm \
  && mkdir /usr/local/lib/node_modules/npm \
  && curl -sL https://github.com/npm/npm/archive/v5.1.0.tar.gz | tar xz -C /usr/local/lib/node_modules/npm --strip-components=1 \
  && npm --version

```

**Comment by SimenB** [comment]
Another workaround

```Dockerfile
FROM node:8

RUN yarn global add npm

RUN npm -v
```

Kinda ironic 😆

**Comment by olalonde** [comment]
@SimenB 
<details>
![burnn](https://user-images.githubusercontent.com/416585/27944800-14bf80c6-629e-11e7-8116-2230853210a8.gif)
</details>

*Edited by @zkat: It's an issue tracker, not an image board.* 😘

**Comment by swernerx** [comment]
Installing 5.1.0 in the VM also does not work for me. Same error with semver.

**Comment by swernerx** [comment]
My current workaround which unfortunately does not work is this:

```
- npm --global install npmc
- npmc --global install npm@latest
- node --version
- npm --version
```

crashes with running `npm --version` in the end.

**Comment by glenjamin** [comment]
I suspect this problem is going to linger for a while, as the problem is about older versions of npm having trouble when they try and upgrade to newer versions. 

Unless there's some trick to making the newest version installable because it's got the right bits inside its tarball?

**Comment by Stono** [comment]
Meh this hurt me today.
Fresh install of v8.1.4, came with npm 5.0.3, did npm install -g npm@latest, completed fine but broken npm.

My dockerfile looks like this now:
```
FROM centos:7

ENV NODE_VERSION=8.1.4
ENV NPM_VERSION=5.3.0

# Get nodejs repos
RUN curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -

RUN dnf -y install nodejs-$NODE_VERSION gcc-c++ make git && \
    dnf -y clean all

RUN rm -rf /usr/lib/node_modules/npm && \
    mkdir /usr/lib/node_modules/npm && \
    curl -sL https://github.com/npm/npm/archive/v$NPM_VERSION.tar.gz | tar xz -C /usr/lib/node_modules/npm --strip-components=1

RUN node --version && \
    npm --version
```

**Comment by mhart** [comment]
Just for others stumbling on this – if you try to upgrade to v5.4.0 (either using `npm update -g` or `npm install -g npm@5.4.0`), it's also hosed, but the error is slightly different:

```console
...
+ npm@5.4.0
added 22 packages, removed 22 packages and updated 19 packages in 12.271s
npm info ok 

/ # npm -v
module.js:491
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:22:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
```

**Comment by mcibique** [comment]
Same here, when trying to update from 5.3.0 to version 5.4.0 the missing package is now `npmlog`. I noticed that the node_modules folder before installing 5.4.0 contained 98 packages, but only these 12 after updating:

```
drwxr-xr-x  4 root root 4096 Aug 27 15:48 libnpx
drwxr-xr-x  2 root root 4096 Aug 27 15:48 meant
drwxr-xr-x  3 root root 4096 Aug 27 15:48 node-gyp
drwxr-xr-x  3 root root 4096 Aug 27 15:48 npm-lifecycle
drwxr-xr-x  3 root root 4096 Aug 27 15:48 npm-packlist
drwxr-xr-x  4 root root 4096 Aug 27 15:48 pacote
drwxr-xr-x  3 root root 4096 Aug 27 15:48 read-package-json
drwxr-xr-x  3 root root 4096 Aug 27 15:48 semver
drwxr-xr-x  4 root root 4096 Aug 27 15:48 tar
drwxr-xr-x  4 root root 4096 Aug 27 15:48 which
drwxr-xr-x  6 root root 4096 Aug 27 15:48 worker-farm
drwxr-xr-x  3 root root 4096 Aug 27 15:48 write-file-atomic
```

^^ this list is exactly the same as the list of packages that have been updated between 5.3.0 and 5.4.0 (https://github.com/npm/npm/commits/latest/package.json). Because `semver` was updated too, it survives the installation and now the `npmlog` is missing.

It seems like npm removes whole node_modules folder and then only copies packages that need to be updated. I added silly logging to the `npm install`, the logs can be found here: https://gist.github.com/mcibique/4f7219628768f8c8da01e02d6c74c092#file-docker-log
and the Dockerfile: https://gist.github.com/mcibique/4f7219628768f8c8da01e02d6c74c092#file-dockerfile

**Comment by richil-bhalerao** [comment]
With node@6.11.1 and npm@5.3.0, I am still getting "Error: Cannot find module 'semver' " in Docker

**Comment by Grey2k** [comment]
Another workaround

```
# npm v3 fixes https://github.com/npm/npm/issues/13306
RUN cd $(npm root -g)/npm && npm install fs-extra && sed -i -e s/graceful-fs/fs-extra/ -e s/fs.rename/fs.move/ ./lib/utils/rename.js

# installing global npm packages
RUN npm install -g npm@5.4.0;
```

**Comment by waldemarnt** [comment]
any news here? I'm having the same issue on npm@5.4.0

**Comment by whymarrh** [comment]
I can reproduce this issue using the latest `node:8-alpine` (at the time of writing):

```
$ docker run --rm -it node:8-alpine sh
/ # npm i -g npm@latest
npm info it worked if it ends with ok
... truncated for brevity ...
+ npm@5.4.1
added 22 packages, removed 22 packages and updated 20 packages in 10.512s
npm info ok 
/ # npm -v
module.js:491
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:22:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:92:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
/ # npx -v
module.js:491
    throw err;
    ^

Error: Cannot find module 'safe-buffer'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:3:16)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```

(Full log available as a Gist: https://gist.github.com/whymarrh/5908d050a391d86a72b47969318d68c5)

Both the `npm` and `npx` commands no longer work.

**Comment by virtyaluk** [comment]
Rolling back to older version (node - 8.0.0, npm - 5.0.0) did the trick. Nowadays npm became too shitty to work with. Seems like it's the time to give Yarn a shot.

**Comment by kourge** [comment]
It looks like [Node.js Docker images now come with Yarn pre-installed](https://hub.docker.com/r/yarnpkg/node-yarn/), so you're not locked in to npm if you want to try Yarn. I'm not sure if it has the same set of problems, though, so your mileage may vary.

**Comment by tomonari-t** [comment]
In my docker env, works fine
`
node@8.5.0
npm@5.3.0
`

**Comment by hutson** [comment]
@tomonari-t can you please provide a set of steps, similar to @whymarrh, in which you are able to successfully install a newer version of npm within a Docker container?

**Comment by e-ts** [comment]
I use `yarn global add npm@5.4.2` to update npm inside node:alpine @hbetts

**Comment by collinmesser** [comment]
I didn't test this solution with Docker, but since I was having the same issues globally on my machine I tried this and it worked. Use the Node/NPM installer from https://nodejs.org/en/download/ then run `npm install` in the project directory.

**Comment by joshdcomp** [comment]
Echoing what others have said about using Yarn, adding this layer in my Dockerfile works consistently for Linux-64:

```dockerfile
RUN apt-get update && apt-get install apt-transport-https && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && apt-get install yarn && \
    yarn global add npm@5.2
```
npm@5.2 is the latest, most stable version I'm aware of, but you can change the version number to whatever you want in that last line, should work.

**Comment by mscottx88** [comment]
I came across this one.  We have the following scenario:

1. Building a node app in Docker
2. Some of the dependencies are private repositories in Github.
3. We want to use #semver syntax on git+ssh.

Due to issue #18434, we need to downgrade to npm 5.4.

Here is the current, working Dockerfile for anyone interested.  

```Dockerfile
# intermediate container for SSH isolation
FROM node:8.9.0 AS intermediate
ARG SSH_KEY

# setup SSH
RUN mkdir /root/.ssh
RUN echo "${SSH_KEY}" > /root/.ssh/id_rsa
RUN chmod 600 /root/.ssh/id_rsa
RUN touch /root/.ssh/known_hosts
RUN ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts

# install into intermediate
WORKDIR /usr/src/app
COPY index.js .
COPY package.json .
COPY package-lock.json .
COPY src ./src

# downgrade npm for semver support on git+ssh (see issues list below as to why)
# https://github.com/npm/npm/issues/18434 (can't use #semver)
# https://github.com/npm/npm/issues/16807 (can't use npm to install npm)
RUN yarn global add npm@5.4.0
RUN npm install --production

# build final image
FROM node:8.9.0
WORKDIR /usr/src/app
COPY --from=intermediate /usr/src/app .
CMD npm start
```

**Comment by vespaiach** [comment]
I'm not sure that is Npm's issue or Semver's issue. Everything was fine on my local pc, but when building docker image with production mode (NODE_ENV=production), the error **Cannot find module 'semver'** showed up and i turned to development mode (NODE=development), everything worked again. :D

Here is my workaround 

```javascript
FROM mhart/alpine-node:9.3.0
EXPOSE 80
WORKDIR /app

ARG APP_ENV
ENV APP_ENV=${APP_ENV:-development} NODE_ENV=${APP_ENV}

COPY package.json yarn.lock /app/
RUN yarn
RUN NODE_ENV=development && yarn add semver@5.3.0 -D
RUN NODE_ENV=${APP_ENV}

COPY . /app
RUN npm run build
```

**Comment by jeremygaither** [comment]
Still seeing this behavior on Docker image `node:8.9.3-alpine`.

**Comment by glasser** [comment]
I think this (currently open on GitHub) bug may have been fixed between npm 5.5.1 and 5.6.0.  Nothing in the 5.6.0 release notes leaps out to me as an obvious explanation but maybe @zkat can recognize what fixed it?

Node 8.9.3 and 8.9.4 have almost no differences except for the bundled npm was upgraded from 5.5.1 to 5.6.0.  On a 8.9.3 Docker image, `npm -g install npm@5.5.1` and `npm -g install npm@5.6.0` both breaks the system so npm does not run (its dependencies are deleted).  On a 8.9.4 Docker image, both of those commands succeed.

It would be nice to understand what fixed this, but it sure does seem fixed?  (Specifically I'd like to understand it better because I'm trying to create a single Docker image that at runtime installs an arbitrary combination of Node and npm versions, and it would be nice for this to work without breaking in some random combinations!)

Full reproductions:

5.5.1 installing 5.5.1 (broken):
```
$ docker run --rm -it node:8.9.3-alpine sh
/ # npm --version
5.5.1
/ # npm -g install npm@5.5.1
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
+ npm@5.5.1
updated 1 package in 6.777s
/ # npm info
module.js:538
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

5.5.1 installing 5.6.0 (broken):
```
$ docker run --rm -it node:8.9.3-alpine sh
/ # npm --version
5.5.1
/ # npm -g install npm@5.6.0
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
+ npm@5.6.0
added 27 packages, removed 11 packages and updated 38 packages in 6.874s
/ # npm info
module.js:538
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/unsupported.js:2:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

5.6.0 installing 5.5.1 (works):
```
$ docker run --rm -it node:8.9.4-alpine sh
/ # npm --version
5.6.0
/ # npm -g install npm@5.5.1
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
+ npm@5.5.1
added 11 packages, removed 27 packages and updated 37 packages in 10.366s
/ # npm info
npm ERR! Invalid package.json

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-31T22_06_16_085Z-debug.log
```

5.6.0 installing 5.6.0 (works):
```
$ docker run --rm -it node:8.9.4-alpine sh
/ # npm --version
5.6.0
/ # npm -g install npm@5.6.0
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
+ npm@5.6.0
updated 2 packages in 10.86s
/ # npm info
npm ERR! Invalid package.json

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-31T22_07_02_060Z-debug.log
```

**Comment by glasser** [comment]
Also note that the failure only occurs if I install Node in a Docker image, start another Docker container based on that image, and try to upgrade npm in the new image.

If I run precisely the same commands to install Node and upgrade npm in the same container, it does not fail, even with Node 8.9.3 / npm 5.5.1.

That means for our use case, the best workaround is just to make sure we install the proper versions of Node and npm during the same Docker layer. This might work for others too, if you're OK installing Node yourself instead of relying on it existing in a base image.  This works for us (to install into `/node-v8.9.4-linux-x64` rather than `/usr/local`, so you need to add `/node-v8.9.4-linux-x64/bin` to PATH afterwards):

```
curl -sSLO "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz" \
  && tar -xzf "node-v$NODE_VERSION-linux-x64.tar.gz" -C / \
  && rm "node-v$NODE_VERSION-linux-x64.tar.gz"
```

**Comment by zkat** [comment]
Hey all: this is fixed as of `npm@5.6.0`, and I've confirmed it.

Unfortunately, since it's the currently-installed npm that's got the bug, you can't _just_ upgrade to 5.6 or later.

But, if the version loaded into your current Docker image is `npm@5.2.0` or later, you can do this to reliably upgrade: `# npx npm@5.6 i -g npm@latest`, and everything should be working fine.

The actual fix was obnoxiously small and a bug that was hidden in plain sight, but I'm so relieved to have finally found this. I'd looked everywhere and just kept skipping over this until I finally spotted it. Thank you all for your time and patience to post here about it, too -- I've been really frustrated about this being the experience Docker users have been having and I assure you it was the case only because it was difficult to spot. The Docker filesystem is a bit special and needs some special affordances, and a fallback was not working the way I expected.

Since this is solved, and there's a straightforward workaround until most Docker images start including `npm@5.6.0` by default (this is already the case with `node@8.9.4` and later), I'm gonna close this. Have a nice day, y'all!

**Comment by glasser** [comment]
Amazing! Thanks @zkat for fixing it and for the workaround as well.

Out of curiosity, what change was the bug fix?

**Comment by Lambdac0re** [comment]
Still having this problem on Win7 for 5.6.0 -> 5.6.1 and 5.7.1 -> 6.1.0
