### ISSUE TITLE
npm 5; "Cannot read property 'type' of undefined"

### ISSUE THREAD

**Issue by ljharb** [npm/npm#16812]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
`npm install browserify` or `npm install --save-dev browserify`

#### How can the CLI team reproduce the problem?
No idea, if the above doesn't work. Note that I'm constantly switching between npm 2, 3, 4, and 5 via nvm, so if sharing the cache would collide, that might be a problem.

debug log: https://gist.github.com/ljharb/3f80b50af196a1ef15d38e46a8884bca

### supporting information:

 - `npm -v` prints: 5.0.0
 - `node -v` prints: 8.0.0
 - `npm config get registry` prints: default
 - Windows, OS X/macOS, or Linux?: Mac OS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by zkat** [comment]
🤔 weeeeeeird. We'll take a gander and see if it's obvious why that child has neither a `_requested` or a `requiredBy` /cc @iarna

**Comment by pocesar** [comment]
having this when trying `npm i` without any extra arguments. 

```
34 verbose unlock done using F:\Users\Paulo\AppData\Roaming\npm-cache\_locks\staging-24d47ac3f0267b0f.lock for G:\www\cim-prefeitura\node_modules\.staging
35 silly install runPostinstallTopLevelLifecycles
36 silly build cim-prefeitura@1.0.0
37 info linkStuff cim-prefeitura@1.0.0
38 silly linkStuff cim-prefeitura@1.0.0 has G:\www as its parent node_modules
39 verbose linkBins cim-prefeitura@1.0.0
40 verbose linkMans cim-prefeitura@1.0.0
41 silly install cim-prefeitura@1.0.0
42 info lifecycle cim-prefeitura@1.0.0~install: cim-prefeitura@1.0.0
43 silly lifecycle cim-prefeitura@1.0.0~install: no script for install, continuing
44 silly postinstall cim-prefeitura@1.0.0
45 info lifecycle cim-prefeitura@1.0.0~postinstall: cim-prefeitura@1.0.0
46 silly lifecycle cim-prefeitura@1.0.0~postinstall: no script for postinstall, continuing
47 silly prepublish cim-prefeitura@1.0.0
48 info lifecycle cim-prefeitura@1.0.0~prepublish: cim-prefeitura@1.0.0
49 silly lifecycle cim-prefeitura@1.0.0~prepublish: no script for prepublish, continuing
50 info lifecycle cim-prefeitura@1.0.0~prepare: cim-prefeitura@1.0.0
51 silly lifecycle cim-prefeitura@1.0.0~prepare: no script for prepare, continuing
52 silly install saveToDependencies
53 verbose saving []
54 info lifecycle undefined~preshrinkwrap: undefined
55 silly lifecycle undefined~preshrinkwrap: no script for preshrinkwrap, continuing
56 verbose stack TypeError: Cannot read property 'type' of undefined
56 verbose stack     at C:\nodejs\node_modules\npm\lib\shrinkwrap.js:111:12
56 verbose stack     at Array.forEach (native)
56 verbose stack     at shrinkwrapDeps (C:\nodejs\node_modules\npm\lib\shrinkwrap.js:103:97)
56 verbose stack     at C:\nodejs\node_modules\npm\lib\shrinkwrap.js:138:7
56 verbose stack     at Array.forEach (native)
56 verbose stack     at shrinkwrapDeps (C:\nodejs\node_modules\npm\lib\shrinkwrap.js:103:97)
56 verbose stack     at treeToShrinkwrap (C:\nodejs\node_modules\npm\lib\shrinkwrap.js:93:5)
56 verbose stack     at C:\nodejs\node_modules\npm\lib\shrinkwrap.js:76:21
56 verbose stack     at done (C:\nodejs\node_modules\npm\lib\utils\lifecycle.js:136:5)
56 verbose stack     at LOOP (C:\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:7:26)
56 verbose stack     at C:\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
56 verbose stack     at C:\nodejs\node_modules\npm\lib\utils\lifecycle.js:333:20
56 verbose stack     at C:\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
56 verbose stack     at FSReqWrap.oncomplete (fs.js:114:15)
57 verbose cwd G:\www\cim-prefeitura
58 verbose Windows_NT 10.0.15063
59 verbose argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
60 verbose node v7.10.0
61 verbose npm  v5.0.0
62 error Cannot read property 'type' of undefined
63 verbose exit [ 1, true ]
```

**Comment by donaldpipowitch** [comment]
I get the same stack trace on a Mac.

```
2238 info lifecycle undefined~preshrinkwrap: undefined
2239 silly lifecycle undefined~preshrinkwrap: no script for preshrinkwrap, continuing
2240 verbose stack TypeError: Cannot read property 'type' of undefined
2240 verbose stack     at /Users/foo/.nvm/versions/node/v6.9.1/lib/node_modules/npm/lib/shrinkwrap.js:111:12
```

**Comment by squarrel** [comment]
Same error here. I'm on Debian Jessie 8.8, using node v6.10.3, npm v5.0.0.

First I try to install a package:
```
$npm install --save-dev jest
npm WARN checkPermissions Missing write access to ...
```

which is some thing I didn't have problems before. Then I try with sudo:
```
$sudo npm install --save-dev jest
npm ERR! Cannot read property 'type' of undefined
npm ERR! A complete log of this run can be found ...
```
and when I check the log:
```
149 verbose saving [ { name: 'jest', spec: '^20.0.4', save: 'devDependencies' } ]
150 info lifecycle undefined~preshrinkwrap: undefined
151 silly lifecycle undefined~preshrinkwrap: no script for preshrinkwrap, continuing
152 verbose stack TypeError: Cannot read property 'type' of undefined
152 verbose stack     at /usr/local/lib/node_modules/npm/lib/shrinkwrap.js:111:12
152 verbose stack     at Array.forEach (native)
152 verbose stack     at shrinkwrapDeps (/usr/local/lib/node_modules/npm/lib/shrinkwrap.js:103:97)
152 verbose stack     at /usr/local/lib/node_modules/npm/lib/shrinkwrap.js:138:7
152 verbose stack     at Array.forEach (native)
152 verbose stack     at shrinkwrapDeps (/usr/local/lib/node_modules/npm/lib/shrinkwrap.js:103:97)
152 verbose stack     at treeToShrinkwrap (/usr/local/lib/node_modules/npm/lib/shrinkwrap.js:93:5)
152 verbose stack     at /usr/local/lib/node_modules/npm/lib/shrinkwrap.js:76:21
152 verbose stack     at done (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:136:5)
152 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
152 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
152 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:333:20
152 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:284:29
152 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
153 verbose cwd /home/milos/projects/...
154 verbose Linux 3.16.0-4-686-pae
155 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "jest"
156 verbose node v6.10.3
157 verbose npm  v5.0.0
158 error Cannot read property 'type' of undefined
159 verbose exit [ 1, true ]
```
all this started after I updated node and npm to newest versions. Previously I'd been using node v4.4.7.

**Comment by nicojs** [comment]
Same here. Updated to node 5.

```
$ npm i
npm ERR! Cannot read property 'type' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     \npm-cache\_logs\2017-05-31T18_40_19_445Z-debug.log
```

Note: i'm using windows 10

**Comment by bbrzoska** [comment]
Same problem here.

```

59 silly lifecycle undefined~preshrinkwrap: no script for preshrinkwrap, continuing
60 verbose stack TypeError: Cannot read property 'type' of undefined
60 verbose stack     at /Users/bazyli.brzoska/.nvs/node/8.0.0/x64/lib/node_modules/npm/lib/shrinkwrap.js:111:12
60 verbose stack     at Array.forEach (native)
60 verbose stack     at shrinkwrapDeps (/Users/bazyli.brzoska/.nvs/node/8.0.0/x64/lib/node_modules/npm/lib/shrinkwrap.js:103:97)
60 verbose stack     at /Users/bazyli.brzoska/.nvs/node/8.0.0/x64/lib/node_modules/npm/lib/shrinkwrap.js:138:7
60 verbose stack     at Array.forEach (native)
60 verbose stack     at shrinkwrapDeps (/Users/bazyli.brzoska/.nvs/node/8.0.0/x64/lib/node_modules/npm/lib/shrinkwrap.js:103:97)
60 verbose stack     at treeToShrinkwrap (/Users/bazyli.brzoska/.nvs/node/8.0.0/x64/lib/node_modules/npm/lib/shrinkwrap.js:93:5)
60 verbose stack     at /Users/bazyli.brzoska/.nvs/node/8.0.0/x64/lib/node_modules/npm/lib/shrinkwrap.js:76:21
60 verbose stack     at done (/Users/bazyli.brzoska/.nvs/node/8.0.0/x64/lib/node_modules/npm/lib/utils/lifecycle.js:136:5)
60 verbose stack     at LOOP (/Users/bazyli.brzoska/.nvs/node/8.0.0/x64/lib/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
60 verbose stack     at /Users/bazyli.brzoska/.nvs/node/8.0.0/x64/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
60 verbose stack     at /Users/bazyli.brzoska/.nvs/node/8.0.0/x64/lib/node_modules/npm/lib/utils/lifecycle.js:333:20
60 verbose stack     at /Users/bazyli.brzoska/.nvs/node/8.0.0/x64/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:284:29
60 verbose stack     at FSReqWrap.oncomplete (fs.js:152:21)
```

**Comment by grantila** [comment]
If this helps anyone; I got this after having run `npm link` in a repo with old `node_modules` and an upgrade of node (to 8) and npm (to 5). After removing `node_modules` and reinstalling all dependencies again with npm 5, `npm link` worked.

**Comment by squarrel** [comment]
I fixed my issue by doing the following:
1) installed the new npm update 5.0.1
2) fixed previous permission problems (node modules owned by root)
3) tried with updating all  outdated packages ('npm outdated', 'npm 'update')
3) removed node_modules folder out of the project
4) ran 'npm install'
5) installed a missing 'axios' module
All is well now.

**Comment by zkat** [comment]
This seems like it's fixed in 5.0.1. Closing.

**Comment by tivac** [comment]
I'm still seeing this on 5.0.1 with node 8.0.0 in Win10.

I'm in a lerna repo so there's definitely linked modules from a pre-5 version of npm kicking around. Will try clearing them out I guess.

**Comment by ds82** [comment]
Still happening for me in 5.0.1 (node 6), too. Cannot really reproduce the error locally .. just happens in gitlab-ci builds.

**Comment by zkat** [comment]
@tivac @ds82 can either of you file a new issue with a fresh debug log on 5.0.1?

**Comment by ljharb** [comment]
@zkat the original issue is not solved for me in v5.0.1. here's the debug log: https://gist.github.com/ljharb/44f6da9a3b9eb94ecf96587a2cbec964

**Comment by zkat** [comment]
Thanks. Reopening 👍

**Comment by tivac** [comment]
@zkat Putting this here, happy to file a new issue if you'd prefer.

https://gist.github.com/tivac/df8f5ee8cab44196512f75b3a31bf8d6

**Comment by ngocvantran** [comment]
I have this issue as well, which I traced it to a local package. In npm 4.6.1, local package is kind of copied to node_modules, and its package.json file is populated with additional information, such as `_request`. In npm 5 and 5.0.1, local packages are sym-linked; therefore, their package.json file does not have any additional information. When shrinkwrap tries to check the `_request.type` value, it does not exists.

The error I'm talking about is https://github.com/npm/npm/blob/19397ad523434656af3d3765e80e22d7e6305f48/lib/shrinkwrap.js#L110

**Comment by nicojs** [comment]
> In npm 4.6.1, local package is kind of copied to node_modules, and its package.json file is populated with additional information, such as _request. In npm 5 and 5.0.1, local packages are sym-linked; therefore, their package.json file does not have any additional information.

Yeah, i figured it had to do with the new way of `file:` dependencies being linked. I actually have quite a few projects that rely on this feature, so that means more rework for me. I guess we can use `npm pack` and `npm i ....tar.gz` as a work around.

**Comment by ljharb** [comment]
(I'm not using links or `file:` in any way on the project my OP is about, fwiw)

**Comment by pospi** [comment]
I am also having this issue in a project that has had dependency symlinks setup with Lerna. Presumably the same issue would manifest when using `npm link`. Bit of a false start after getting excited about the blog post, really.

I'm on node 7.7.2; and further to the above I've found the error occurs when running `npm shrinkwrap` as well as `npm install`... so perhaps the shrinkwrap code is where the error lies.

In the meantime, it's `npm i -g npm@^4` for me!

**Comment by philipp-winterle** [comment]
Havnig the same issue with another module. 
 - On Win 7 64 and nodejs 7.10.0 it crashes
 - on Ubuntu 16.04 64 and nodejs 7.10.0 it worked

**Comment by nicojs** [comment]
@hummal what npm version are you using in both environments?

**Comment by philipp-winterle** [comment]
Fresh updated 5.0.1

**Comment by Dudemullet** [comment]
Has anybody found a workaround in the meantime for this ?

**Comment by philipp-winterle** [comment]
Use npm@4

**Comment by nicojs** [comment]
For anyone who is struggling with this issue because of the new way `npm install file:./dep` is working: i've created a small package that brings the old functionality back: https://www.npmjs.com/package/install-local

**Comment by WaleedAshraf** [comment]
Still facing this issue :/

**Comment by ljharb** [comment]
ftr, I'm still getting the same error with v5.0.2.

**Comment by asymmetric** [comment]
In my case, the issue was that the executable that `pm2` was told to run was not executable. A `chmod` fixed it.

This makes me think that the error could be more descriptive.

**Comment by orefalo** [comment]
same issue, reverting to @4

**Comment by montogeek** [comment]
Same issue in 5.0.3
https://gist.github.com/montogeek/4e6d37038db1c03c1ce46d880a7b8e27

**Comment by Dudemullet** [comment]
For anyone wondering how to downgrade easily, I'll save you a google search

`npm install npm@4.*.* -g`

**Comment by chardos** [comment]
I deleted all my modules and reinstalled, and that resolved this issue. Also, I'm on node v8.0.0 and npm v5.0.0.

**Comment by liuwensa** [comment]
remove node_modules and npm install

**Comment by mmc41** [comment]
Got same issue in 5.0.3 on MacOS X - even though I deleted all node_modules before running.

Got this detailed error in the log file:
```
4082 info lifecycle undefined~preshrinkwrap: undefined
24083 silly lifecycle undefined~preshrinkwrap: no script for preshrinkwrap, continuing
24084 verbose stack TypeError: Cannot read property 'type' of undefined
24084 verbose stack     at /usr/local/lib/node_modules/npm/lib/shrinkwrap.js:111:12
24084 verbose stack     at Array.forEach (native)
24084 verbose stack     at shrinkwrapDeps (/usr/local/lib/node_modules/npm/lib/shrinkwrap.js:103:97)
24084 verbose stack     at /usr/local/lib/node_modules/npm/lib/shrinkwrap.js:138:7
24084 verbose stack     at Array.forEach (native)
24084 verbose stack     at shrinkwrapDeps (/usr/local/lib/node_modules/npm/lib/shrinkwrap.js:103:97)
24084 verbose stack     at treeToShrinkwrap (/usr/local/lib/node_modules/npm/lib/shrinkwrap.js:93:5)
24084 verbose stack     at /usr/local/lib/node_modules/npm/lib/shrinkwrap.js:76:21
24084 verbose stack     at done (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:136:5)
24084 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
24084 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
24084 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:333:20
24084 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:284:29
24084 verbose stack     at FSReqWrap.oncomplete (fs.js:152:21)
```

**Comment by zkat** [comment]
hey y'all!

Anyone experiencing this: Would you mind installing the newest npm canary (`npm i -g npmc@5.0.3-canary.8`) and letting me know if it's resolved it for you? It has a patch by @forivall intended to at least paper over this (and tbh, probably resolve it) Note that you'll get an `npmc` binary instead of `npm` for it.

**Comment by Dudemullet** [comment]
@zkat Worked for me 🎉

using : 
```
node: v6.10.1
```

No removing of `node_modules` had to be done

**Comment by zkat** [comment]
@Dudemullet awesome. It'll be available with the next release then (probably tomorrow?), so 5.0.4. Thanks for all y'all's patience. We're fixing things as we're able, and there's a *lot* of really particular things people did, and a lot of edge cases we couldn't possibly have even tested against. It's really handy to have the community using it, and we figured there'd be a week or two of heavy bugfixing post-release :)

**Comment by ljharb** [comment]
@zkat it also worked for me! after which, npm v5.0.3 no longer errored either, fwiw.

**Comment by zkat** [comment]
woot 💃 

I'm gonna go ahead and close this then. Thanks y'all for your time and patience with all this!

**Comment by mmc41** [comment]
@zkat A question about npmc..... Since I got this (and other) problems with npm 5, I have reinstalled an older version of the node installer (v7.9.0) in order to get npm 4 back. I am not eager to reinstall "npm 5" yet so is it possible to stay with npm version 4.x and run "npmc" safely side by side (so I can wait upgrading until npm 5 is stable enough) ? - Without any problems with different repository formats or files/folders that need deletion etc. ?

**Comment by dwasyluk** [comment]
@zkat using your canary version and `npmc shrinkwrap` fixed the problem here, thanks! Fwiw `npm shrinkwrap` still produces the same error, version is `5.0.3`.

**Comment by zkat** [comment]
@mmc41 `npmc` installs a separate binary, `npmc`, which you can safely use without changing your main npm.

**Comment by ferrants** [comment]
Confirmed that for me, this was causing an issue with npm 5.0.3 and works in canary 10:

```
$ npm --version
5.0.3

$ npm shrinkwrap --dev
npm ERR! Cannot read property 'type' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mferrante/.npm/_logs/2017-06-08T22_11_50_861Z-debug.log

$ tail -n 200  /Users/mferrante/.npm/_logs/2017-06-08T22_11_50_861Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/Users/mferrante/.nvm/versions/node/v4.4.6/bin/node',
1 verbose cli   '/Users/mferrante/.nvm/versions/node/v4.4.6/bin/npm',
1 verbose cli   'shrinkwrap',
1 verbose cli   '--dev' ]
2 info using npm@5.0.3
3 info using node@v4.4.6
4 info lifecycle traverse-api@1.12.2~preshrinkwrap: traverse-api@1.12.2
5 silly lifecycle traverse-api@1.12.2~preshrinkwrap: no script for preshrinkwrap, continuing
6 verbose stack TypeError: Cannot read property 'type' of undefined
6 verbose stack     at /Users/mferrante/.nvm/versions/node/v4.4.6/lib/node_modules/npm/lib/shrinkwrap.js:111:12
6 verbose stack     at Array.forEach (native)
6 verbose stack     at shrinkwrapDeps (/Users/mferrante/.nvm/versions/node/v4.4.6/lib/node_modules/npm/lib/shrinkwrap.js:103:97)
6 verbose stack     at /Users/mferrante/.nvm/versions/node/v4.4.6/lib/node_modules/npm/lib/shrinkwrap.js:138:7
6 verbose stack     at Array.forEach (native)
6 verbose stack     at shrinkwrapDeps (/Users/mferrante/.nvm/versions/node/v4.4.6/lib/node_modules/npm/lib/shrinkwrap.js:103:97)
6 verbose stack     at treeToShrinkwrap (/Users/mferrante/.nvm/versions/node/v4.4.6/lib/node_modules/npm/lib/shrinkwrap.js:93:5)
6 verbose stack     at /Users/mferrante/.nvm/versions/node/v4.4.6/lib/node_modules/npm/lib/shrinkwrap.js:76:21
6 verbose stack     at done (/Users/mferrante/.nvm/versions/node/v4.4.6/lib/node_modules/npm/lib/utils/lifecycle.js:136:5)
6 verbose stack     at LOOP (/Users/mferrante/.nvm/versions/node/v4.4.6/lib/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
6 verbose stack     at /Users/mferrante/.nvm/versions/node/v4.4.6/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
6 verbose stack     at /Users/mferrante/.nvm/versions/node/v4.4.6/lib/node_modules/npm/lib/utils/lifecycle.js:333:20
6 verbose stack     at /Users/mferrante/.nvm/versions/node/v4.4.6/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:284:29
6 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
7 verbose cwd /Users/mferrante/code/traverse/sails
8 verbose Darwin 16.1.0
9 verbose argv "/Users/mferrante/.nvm/versions/node/v4.4.6/bin/node" "/Users/mferrante/.nvm/versions/node/v4.4.6/bin/npm" "shrinkwrap" "--dev"
10 verbose node v4.4.6
11 verbose npm  v5.0.3
12 error Cannot read property 'type' of undefined
13 verbose exit [ 1, true ]

$ npm i -g npmc@5.0.3-canary.10
/Users/mferrante/.nvm/versions/node/v4.4.6/bin/npmc -> /Users/mferrante/.nvm/versions/node/v4.4.6/lib/node_modules/npmc/bin/npm-cli.js
+ npmc@5.0.3-canary.10
added 350 packages in 24.631s

$ npmc shrinkwrap --dev
npm notice CANARY npmc is experimental software. If you find an issue, please file it in the main npm repository, and call out that you were using npmc.
npm notice created a lockfile as npm-shrinkwrap.json. You should commit this file.
```

Though, looking at the diff of my shrinkwrap file, it seems that some that used to have a version and integrity, now have just a `{}`

```
                             "once": {
-                              "version": "https://registry.npmjs.org/once/-/once-1.4.0.tgz",
-                              "integrity": "sha1-WDsap3WWHUsROsF9nFC6753Xa9E=",
                               "dependencies": {
-                                "wrappy": {
-                                  "version": "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz",
-                                  "integrity": "sha1-tSQ9jz7BqjXxNkYFvA0QNuMKtp8="
-                                }
+                                "wrappy": {}
                               }
                             },
```

**Comment by zkat** [comment]
@ferrants ahah 👀

**Comment by nikita240** [comment]
+1 had this issue with v5.0.3, but installing 5.0.3-canary.8 resolved the issue.

**Comment by ndelangen** [comment]
Can this be released as `5.0.4` please? Using `npmc` is not practical for us at all. 💛

**Comment by ndelangen** [comment]
Please? this is still breaking our builds, I can confirm `5.0.3-canary.8` solves this issue.

**Comment by ferrants** [comment]
I don't think that an invalid npm-shrinkwrap.json file is really what you want. It might not fail your builds, but it won't bring integrity to your builds. I think some work is still needed here to get it right.

**Comment by a7madgamal** [comment]
same here with 5.0.3 on mac

**Comment by hcharley** [comment]
Running into this as well

**Comment by davearel** [comment]
I was getting this error as well.
`npm ERR! Cannot read property 'type' of undefined`

Removing `node_modules` and re-installing all packages worked for me.

`rm -rf node_modules && npm install`

**Comment by muratozgul** [comment]
npm 5.0.4 worked for me (node 8.0.0). I used `npm install -g npm`

**Comment by Nagarjuna32** [comment]
I am also getting "Cannot read property 'type' of undefined" when I run npm install. I tried mentioned all options. Any suggestions?
13955 info lifecycle undefinedpreshrinkwrap: undefined
13956 silly lifecycle undefinedpreshrinkwrap: no script for preshrinkwrap, continuing
13957 verbose stack TypeError: Cannot read property 'type' of undefined
13957 verbose stack at C:\Program Files\nodejs\node_modules\npm\lib\shrinkwrap.js:111:12
13957 verbose stack at Array.forEach (native)

**Comment by amir-arad** [comment]
same bug here. `rm -rf node_modules && npm install` 
version `5.0.3`

**Comment by physikerwelt** [comment]
same problem 
```
$ npm i node-mocks-http --save
npm ERR! Cannot read property '0' of undefined
$ npm -v
5.3.0

**Comment by rachelwilson** [comment]
@zkat I can confirm `npm i -g npmc@5.0.3-canary.8` worked for me.  Problem started when I introduced a local dependency into package.json with `file:../my_module`
