### ISSUE TITLE
npm 5 fails to install binary add-on that depends on another binary add-on

### ISSUE THREAD

**Issue by bjouhier** [npm/npm#16824]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I upgraded to node 8 (npm 5.0.0) and got the problem when trying to install `libxml-xsd`. This package is a binary add-on with a dependency on another binary add-on: `libxmljs-mt`. 

The installation of `libxml-xsd` fails with the following error:

```
  SOLINK_MODULE(target) Release/node-libxml-xsd.node
clang: error: no such file or directory: '/Users/bruno/dev/bug1/node_modules/libxmljs-mt/build/Release/xmljs.node'
make: *** [Release/node-libxml-xsd.node] Error 1
```

The problem is that `npm install` did not build the binary in the `libxmljs-mt` dependency before building the binary in `libxml-xsd`.

Backtracking to npm 3.10.10 fixed the problem.

To reproduce:
```sh
nvm use 8
npm install libxml-xsd
```

### supporting information:

 - `npm -v` prints: 5.0.0
 - `node -v` prints: v8.0.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: OS X
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by ankon** [comment]
I'm seeing exactly the same with `libxslt`, also depending on `libxmljs-mt` in https://github.com/Collaborne/gulp-xliff-to-carbon-i18n.

I've tried to add the libxmljs-mt dependency explicitly to `package.json`, which didn't change anything really: according to npm-debug.log it tried building libxslt first, and then failed because of the missing xmljs.node dependency. Even when doing something like adding a `preinstall` script like `npm install --no-save libxmljs-mt` npm seems to just ignore the build.

What somehow works is to remove any package-lock.json, then `npm install --no-save libxmljs-mt`, and then a regular `npm install` of the project itself.

**Comment by liushuyu** [comment]
>Backtracking to npm 3.10.10 fixed the problem.

You don't have to backtrack to 3.10.10, npm 4.6.1 does not have the problem either.

**Comment by bjouhier** [comment]
@liushuyu Thanks for the info. I tried 3.10.10 as this was known territory for me.

**Comment by richardpringle** [comment]
Fails on node 7 and 6 as well so it's just an npm 5 issue.

Failing on a couple different versions of OSx and Linux, don't know if that info helps but let me know if you want more specific versions.

**Comment by rainabba** [comment]
Possible to follow without commenting?

**Comment by ankon** [comment]
> Possible to follow without commenting?

Yes, use the "Subscribe" button on the right side-bar. See https://help.github.com/articles/subscribing-to-conversations/

**Comment by corvinrok** [comment]
this is still an issue with **npm 5.0.4** ... [at least for my environment: Windows 7 building]

below is a transcript of my build results (`npm install`, which runs the rebuild in the process). I have also tried this on latest `Node8` with the included npm. Results are the same.

Does `npm` expect to resolve this? It seems like a pretty important issue, that stops me from accessing the benefits of `npm5`.


```
> libxml-xsd@0.5.2 install C:\git\std_default_project\node_modules\libxml-xsd
> node-gyp rebuild


C:\git\std_default_project\node_modules\libxml-xsd>if not defined npm_config_node_gyp (node "C:\Users\std_default_user\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.
js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  schema.cc
..\src\schema.cc(31): warning C4996: 'v8::Function::NewInstance': was declared deprecated [C:\git\std_default_project\node_modules\libxml-xsd\build\node-libxml-xsd.vcxproj]
          c:\users\std_default_user\.node-gyp\7.10.0\include\node\v8.h(3662) : see declaration of 'v8::Function::NewInstance'
  node_libxml_xsd.cc
..\src\node_libxml_xsd.cc(1): warning C4005: 'BUILDING_NODE_EXTENSION' : macro redefinition [C:\git\std_default_project\node_modules\libxml-xsd\build\node-libxml-xsd.vcxproj]
          command-line arguments :  see previous definition of 'BUILDING_NODE_EXTENSION'
  win_delay_load_hook.cc
LINK : fatal error LNK1181: cannot open input file 'C:\git\std_default_project\node_modules\libxmljs-mt\build\Release\xmljs.lib' [C:\git\std_default_project\node_modules\libxml-xsd\build\node-libxml-xsd.vcx
proj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\std_default_user\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\std_default_user\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\git\std_default_project\node_modules\libxml-xsd
gyp ERR! node -v v7.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

**Comment by rainabba** [comment]
Kick... Anyone on the project working on this or have any updates? I don't want to put a few hours into trying to solve only to find out someone else was nearly done :)

**Comment by zkat** [comment]
Dropping in to give an update: Gonna see if we can queue this one up for this week. We're making our way through the major bugs now that the team is all in one place again and not sick/on vacation. Stand by for more updates 👍

**Comment by corvinrok** [comment]
Greatly appreciate this kind of update. It helps those of us who are
scheduling our own projects that include this as a dependency in our build
ecosystem.

Our only block in moving to node 8 recently is the use of the included npm5
(which included the issue in this thread).

Regardless of the exact time, just knowing this is planned to be addressed
is just good communication. Thank you.

Kim Gentes

**Comment by corvinrok** [comment]
well.. still waiting here... any progress?

**Comment by corvinrok** [comment]
bump on looking for this in a release soon... stuck on node 7 until this is fixed.. :(

**Comment by patrickjane** [comment]
Same here. Unfortunately I already switched to 8 since rebuilding did not cause the error. Now I've wiped the node_modules folder, and can't reinstall the modules because of the above error.

[edit] I just found out that `npm install libxml-xsd` **works** after I updated `npm` from 5.0.3 to 5.3.0 :)

**Comment by corvinrok** [comment]
bump for update... devs? is this fixed in latest?

Does anyone know if I should try Node 8.3.0 now? I can't find where in the release info for a given version of node what version of npm it includes. (I know you can run `npm -v` _after_ node is installed to find out, but that is hardly proactive)

**Comment by liushuyu** [comment]
The problem still exist in latest `npm` release (as of 2017-10-19) `5.5.1`
And the problem got even worse.

From the npm log, it seems like `npm` thought these two packages are parallel dependencies, so which install first does not matter.

Below is the part of the log
```
2399 silly unbuild one-time@0.0.4
2400 info lifecycle one-time@0.0.4~preuninstall: one-time@0.0.4
2401 info lifecycle one-time@0.0.4~uninstall: one-time@0.0.4
2402 verbose unbuild rmStuff one-time@0.0.4 from /home/liushuyu/test/node_modules/.staging
2403 info lifecycle one-time@0.0.4~postuninstall: one-time@0.0.4
2404 silly unbuild debug
2405 info lifecycle undefined~preuninstall: undefined
2406 info lifecycle undefined~uninstall: undefined
2407 verbose unlock done using /home/liushuyu/.npm/_locks/staging-5c5014a13f8ffd10.lock for /home/liushuyu/test/node_modules/.staging
2408 verbose stack TypeError: Cannot read property '0' of undefined
2408 verbose stack     at rmStuff (/home/liushuyu/.nvm/versions/node/v8.4.0/lib/node_modules/npm/lib/unbuild.js:61:24)
2408 verbose stack     at tryCatcher (/home/liushuyu/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
2408 verbose stack     at ret (eval at makeNodePromisifiedEval (/home/liushuyu/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
2408 verbose stack     at lifecycle.then.then (/home/liushuyu/.nvm/versions/node/v8.4.0/lib/node_modules/npm/lib/install/action/unbuild.js:12:12)
2408 verbose stack     at tryCatcher (/home/liushuyu/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
2408 verbose stack     at Promise._settlePromiseFromHandler (/home/liushuyu/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
2408 verbose stack     at Promise._settlePromise (/home/liushuyu/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
2408 verbose stack     at Promise._settlePromise0 (/home/liushuyu/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
2408 verbose stack     at Promise._settlePromises (/home/liushuyu/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
2408 verbose stack     at Promise._fulfill (/home/liushuyu/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
2408 verbose stack     at /home/liushuyu/.nvm/versions/node/v8.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/nodeback.js:42:21
2408 verbose stack     at <anonymous>
2411 verbose argv "/home/liushuyu/.nvm/versions/node/v8.4.0/bin/node" "/home/liushuyu/.nvm/versions/node/v8.4.0/bin/npm" "install" "libxmljs-mt"
```
