### ISSUE TITLE
`npm version` fails with .gitignore package-lock.json

### ISSUE THREAD

**Issue by geek** [npm/npm#17208]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?

The `npm version` command fails and the --force suggestion from the error output doesn't work when `package-lock.json` is in the `.gitignore` file

#### How can the CLI team reproduce the problem?

1. add `package-lock.json` to `.gitignore`
2. run `npm version v1.0.0 -m "version 1.0.0"` or similar version command
3. npm errors and cannot complete command

### supporting information:

 - `npm -v` prints: 5.0.3
 - `node -v` prints: 8.0.0
 - Windows, OS X/macOS, or Linux?: macOS

**Comment by milichev** [comment]
@geek , what's your workaround?

**Comment by geek** [comment]
@milichev I removed `package-lock.json` from the `.gitignore` and just delete it before running `npm version`

**Comment by geek** [comment]
@zkat will you accept a fix for this issue if I create a PR?

**Comment by zkat** [comment]
@geek totally! Thanks :)

**Comment by wildlyinaccurate** [comment]
@geek let me know if you want a hand with the fix. This has been bugging me as well and I'd be more than happy to help out!

**Comment by zkat** [comment]
wait I think this is fixed? I'll check tomorrow. But 90bd11cbed140ac35f2a44c5e3ae805cbc8de98d is in the canary.

**Comment by zkat** [comment]
Actually yeah, this is fixed by that.

**Comment by lili21** [comment]
<img width="566" alt="2017-10-11 1 46 24" src="https://user-images.githubusercontent.com/4456380/31424027-a465f2d0-ae1d-11e7-8851-70a056f1e506.png">


still have the issue.

**Comment by klammm** [comment]
@lili21 I have this issue also and I resolved it by `rm package-lock.json` and discarding the changes to the `package.json` created by the version bump. Afterwards, `npm version <version_type>` worked normally for me.
