### ISSUE TITLE
Infinite loop @angular/cli/.../node-sass/.node-gyp/8.1.2

### ISSUE THREAD

**Issue by mksmtn** [npm/npm#17431]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
npm runs an infinite loop attempting to install @angular/cli/node_modules/node-sass/.node-gyp/8.1.2
#### How can the CLI team reproduce the problem?
`sudo npm install -g @angular/cli`
[gist with trace](https://gist.github.com/krabovm/b1be902f657cc7d896ef0ac82d479644)
I solved this issue with `npm cache clean --force`, but I suppose it's a bug since npm -v > 5, and you don't recommend to clean cache anymore

### supporting information:

 - `npm -v` prints:5.0.3
 - `node -v` prints:v8.1.2
 - `npm config get registry` prints:https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?:Linux (Elementary)
 - Network issues:
   - Geographic location where npm was run:Samara, Russia
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by treeder** [comment]
I'm getting the same thing. This forever:

```
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '8.1.2' ]
gyp verb install input version string "8.1.2"
gyp verb install installing version: 8.1.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.1.2
gyp verb ensuring nodedir is created /usr/local/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp/8.1.2
gyp WARN EACCES user "nobody" does not have permission to access the dev dir "/usr/local/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp/8.1.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '8.1.2' ]
gyp verb install input version string "8.1.2"
gyp verb install installing version: 8.1.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.1.2
gyp verb ensuring nodedir is created /usr/local/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp/8.1.2
gyp WARN EACCES user "nobody" does not have permission to access the dev dir "/usr/local/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp/8.1.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '8.1.2' ]
gyp verb install input version string "8.1.2"
```

**Comment by stephansamuel** [comment]
+1, adding my env, maybe it'll help someone.

Narrowed it down, `npm install -g node-sass` produces the same result as `npm install -g @angular/cli`. `npm cache clean --force` does not solve this issue for me. `npm install -g --unsafe-perm @angular/cli` is work-around. I'm running Debian Jessie in a Docker container.

This happens on infinite loop:

gyp verb command install [ '8.1.2' ]
gyp verb install input version string "8.1.2"
gyp verb install installing version: 8.1.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp WARN EACCES user "undefined" does not have permission to access the dev dir "/root/.node-gyp/8.1.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space

Here's what logs before that, from the line after the `npm install`:

/usr/local/bin/node-sass -> /usr/local/lib/node_modules/node-sass/bin/node-sass

> node-sass@4.5.3 install /usr/local/lib/node_modules/node-sass
> node scripts/install.js

Unable to save binary /usr/local/lib/node_modules/node-sass/vendor/linux-x64-57 : { Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:890:18)
    at sync (/usr/local/lib/node_modules/node-sass/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/usr/local/lib/node_modules/node-sass/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/usr/local/lib/node_modules/node-sass/scripts/install.js:111:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-sass/scripts/install.js:154:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/lib/node_modules/node-sass/vendor' }

> node-sass@4.5.3 postinstall /usr/local/lib/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /usr/local/lib/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/node-sass/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.1.2 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.9\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.1.2

**Comment by stephansamuel** [comment]
Possible duplicate-of/related-to https://github.com/sass/node-sass/issues/2006

(Sorry if I'm following the wrong bug reporting procedure, will read docs if someone points me.)

**Comment by totomz** [comment]
Same problem with docker image `ubuntu:latest`; fixed with towrkaround  `npm install -g --unsafe-perm @angular/cli`  (thanks @stephansamuel )

**Comment by bitgandtter** [comment]
Im using the official docker node image and that does not fix it for me @totomz any other advice?

**Comment by manish-appface** [comment]
npm install -g --unsafe-perm @angular/cli (thanks @totomz )

**Comment by Tharindu-Diluksha** [comment]
@krabovm  Same happened to me. Fixed by manually installing node-gyp before installing angular cli as mentioned in [#6727](https://github.com/angular/angular-cli/issues/6727)

`$ sudo npm install -g node-gyp`
`$ sudo npm install -g @angular/cli`

**Comment by ogomesrafael** [comment]
`$ sudo chmod 755 -R /path/to/node_modules`
after install.
or
`$ sudo npm install -g @angular/cli`

**Comment by djackreuter** [comment]
Same issue happening for me.  Running `sudo npm install -g node-gyp` before `sudo npm install -g @angular/cli` did not fix the issue.  `npm cache clear --force` did not work either.

**Comment by MarDenDev** [comment]
Same issue here, manually installing `node-gyp` module before angular cli and clearing cache didn't work.

I tried to give to npm installer the `--unsafe-perm` option so that the command looked like this: `sudo npm install --unsafe-perm -g @angular/cli` and it worked.

I think it's not a permanent solution, but it helped out.

**Comment by charlesreitz** [comment]
+1

**Comment by Nicolas-Bouteille** [comment]
I faced the same problem. But in my situation, I quit the Terminal then restarted and repeated install and this time no problem.

**Comment by kumaxim** [comment]
I have Ubuntu 16.04 as my primary(host) system. The same issue happened for me.
The solution in my case:
- Login as root: `sudo -s`
- Install node-gyp: `npm install -g node-gyp`
- Install angular/cli with `--unsafe-perm` option: `npm install --unsafe-perm -g @angular/cli`

In my case the folder `.node-gyp` was missing and install process going to the loop. The problem will resolved when I add option `--unsafe-perm`. The issue happens only for root user. When I works as normal user the problem does not happen

**Comment by fuadhaider** [comment]
I think it's only a permission issue for which you can take an idea from the official npm site. I had similar issue and resolved upon changing user permission. Link given below:
[https://docs.npmjs.com/getting-started/fixing-npm-permissions](url)

**Comment by ain** [comment]
Also reproduced with `8.9.3`:

```
gyp verb command install [ '8.9.3' ]
gyp verb install input version string "8.9.3"
gyp verb install installing version: 8.9.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.9.3
gyp verb ensuring nodedir is created /usr/local/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp/8.9.3
gyp WARN EACCES user "nobody" does not have permission to access the dev dir "/usr/local/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp/8.9.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '8.9.3' ]
gyp verb install input version string "8.9.3"
gyp verb install installing version: 8.9.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.9.3
gyp verb ensuring nodedir is created /usr/local/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp/8.9.3
gyp WARN EACCES user "nobody" does not have permission to access the dev dir "/usr/local/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp/8.9.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp"
```

__UPDATE__: resolved with `npm install --unsafe-perm -g @angular/cli ` as well.

**Comment by r0b3r70** [comment]
Had the same issue. Tried installing the CLI with root permissions on OSX. Thanks to @ain for the solution.

**Comment by hdehal** [comment]
Same issue on OSX.

First made the mistake of installing Angular globally without sudo, which yielded an obvious permissions error. Next tried with sudo which ran into the infinite loop. Simply canceling and redoing (again, with sudo) worked.

**Comment by techouseconsulting** [comment]
Good day, I recently had a similar issue and the fix for me was to install(as root) saas using ruby gem; hopefully that works... Bless.

**Comment by techouseconsulting** [comment]
Good day, I recently had a similar issue and the fix for me was to install(as root) saas using ruby's gem; hopefully that works... Bless.

**Comment by stiofand** [comment]
@fuadhaider those docs dont fix this specific problem

Even installing node-gyp beforehand fails to address this issue

**Comment by stevematdavies** [comment]
Sorry but even installing node-gyp beforehand fails to address this issue

**Comment by jsuria** [comment]
Thank you, @totomz . It's a bit hacky, but got the job done.

**Comment by saadBoudfor** [comment]
fixed by using npm@4.3.0: 

FROM node

ENV HOME=/home/app
WORKDIR $HOME

RUN mkdir /home/node/.npm-global
ENV PATH=/home/node/.npm-global/bin:$PATH
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
RUN npm install -g node-gyp
RUN npm install -g npm@4.3.0
RUN npm install -g --unsafe-perm @angular/cli

EXPOSE 4200

**Comment by Karimai** [comment]
for me install node-gyp solved the issue. Surprisingly, I faced many times with this loop and in every time I used the following command. 
root@debian:/...# npm install -g node-gyp

When I wanted to install fabric composer playground in every other command I had to install node-gyp.
