### ISSUE TITLE
npm install Semver issue when pointing to git repo

### ISSUE THREAD

**Issue by dcatoday** [npm/npm#17621]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

I am attempting to allow semver ranges from an npm install with:
git+ssh://git@bitbucket:blahblahblah.git#semver:^1.0.0

in the package.json and receive this error:

Command failed: C:\Program Files (x86)\Git\bin\git.EXE checkout  ^1.0.0
npm ERR! error: pathspec ' ^1.0.0' did not match any file(s) known to git.

When I install with --save from the command line it drops the caret and pulls the 1.0.0 version of the git repo.  Pointing to specific versions also works such as 1.2.0 or 1.3.0 but the range produces the error when in the package.json and fails to install latest when in the command line. 

#### How can the CLI team reproduce the problem?

Add a version tag to a git repo and try to install the repo with the semver syntax from the documentation.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\sxudma\\.npm-home\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@5.0.4
3 info using node@v6.9.5
4 verbose npm-session eca960e14ac59384
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall version-test@0.0.0
7 info lifecycle version-test@0.0.0~preinstall: version-test@0.0.0
8 silly lifecycle version-test@0.0.0~preinstall: no script for preinstall, continuing
9 silly install loadCurrentTree
10 silly install readLocalPackageData
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 silly install loadShrinkwrap
14 silly install loadAllDepsIntoIdealTree
15 silly fetchPackageMetaData error for fm-cdx-version-testing@git+ssh://git@bitbucket:7999/~sxudma/fm-cdx-version-testing.git#semver: ^1.0.0 Command failed: C:\Program Files (x86)\Git\bin\git.EXE checkout  ^1.0.0
15 silly fetchPackageMetaData error: pathspec ' ^1.0.0' did not match any file(s) known to git.
16 verbose stack Error: Command failed: C:\Program Files (x86)\Git\bin\git.EXE checkout  ^1.0.0
16 verbose stack error: pathspec ' ^1.0.0' did not match any file(s) known to git.
16 verbose stack
16 verbose stack     at ChildProcess.exithandler (child_process.js:206:12)
16 verbose stack     at emitTwo (events.js:106:13)
16 verbose stack     at ChildProcess.emit (events.js:191:7)
16 verbose stack     at maybeClose (internal/child_process.js:877:16)
16 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
17 verbose cwd C:\Users\sxudma\projects\version-test
18 verbose Windows_NT 10.0.10586
19 verbose argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\sxudma\\.npm-home\\node_modules\\npm\\bin\\npm-cli.js" "install"
20 verbose node v6.9.5
21 verbose npm  v5.0.4
22 error code 1
23 error Command failed: C:\Program Files (x86)\Git\bin\git.EXE checkout  ^1.0.0
23 error error: pathspec ' ^1.0.0' did not match any file(s) known to git.
24 verbose exit [ 1, true ]

### supporting information:

 - `npm -v` prints: 5.0.4
 - `node -v` prints: 6.9.5
 - `npm config get registry` prints: http://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues:
   - Geographic location where npm was run: Corporate Office North America
   - [ x] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by smithdalec** [comment]
I'm having the same issue while referencing a GitHub Enterprise URL (SSH), but github.com URLs (also SSH) work fine. I noticed your example is pointing to Bitbucket, so I'm guessing that only github.com URLs are supported by the changes for #3328

**Comment by dcatoday** [comment]
Hmm, I'm not sure what would be different.  My job uses Bitbucket and I'm creating components that will need to be versioned.  Semver works if you point to specific version but not a range.  I'm hoping this can be fixed or added!

**Comment by aheckmann** [comment]
Same here using internal github enterprise (non github.com urls)

npm version 5.3.0

**Comment by mauricios** [comment]
Same here using private repo in Assembla 
npm version 5.3.0
git version 2.13.3

package.json
```  
{
    "dependencies": {
        "my-private-package": "git+ssh://git@git.assembla.com:my-private-repo.git#semver:^1.1.0"
    }
}
```
Error:
```
npm ERR! code 1
npm ERR! Command failed: /usr/local/bin/git checkout semver:^1.1.0
npm ERR! error: pathspec 'semver:^1.1.0' did not match any file(s) known to git.
```

**Comment by krlwlfrt** [comment]
We have the same issue on a private GitLab instance.

**Comment by rluba** [comment]
Seems like this broke as early as 5.1.x. It works when using `npm i -g npm@~5.0.0` (but then you get to enjoy a scoop of other bugs).

**Comment by ben-coble-sp** [comment]
@dcatoday Have you tried changing your git dep to `semver:^1.x.x`? I was having problems and a similar change (`semver:^0.0.22` -> `semver:^0.0.x`) allowed me to get the latest version correctly. I'm on npm 5.3.0.

**Comment by chris-dura** [comment]
I'm having the same problem with an "Internal" project on a GitLab Enterprise instance.

Also, the [documentation](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies) states that "npm will look for any tags or refs matching that range..."
However, the default tag created when you run `npm version minor` is prefixed with a `v`, so the tags are actually `v1.0.0` not `1.0.0`... is that the same thing in the eye of npm?

UPDATE: I was able, to (sort of) get it to work by changing the syntax around... this "works" in the sense that it installs `v1.2.1` of the project... but that's also the "latest", so I don't know if the semver is actually working or just pulling the most recent tag it finds.
```json
"my-repo": "git+ssh://git@gitlab.company.com/group-name/my-repo.git#semver:1.x.x";
"my-repo": "git+ssh://git@gitlab.company.com/group-name/my-repo.git#semver:^1.0.0";
```

Also, the examples in the documentation makes use of the `:` as a delimiter instead of `/` in some cases... I was only able to get the above to work by using `/`, trying to use a `:` syntax seemed to break it, but I could have been misusing it.
The `.git` suffix after `my-repo` also seems to be optional, at least in the examples above.

**Comment by mdschmidt** [comment]
This issue is showing up inconsistently based on npm cache. Using an internal gitlab instance and npm 5.3.0, #semver: syntax ONLY works if the package version in question has already been installed once before WITHOUT using #semver:. Adding #semver: after having installed the package once before results in correct behavior and no errors, however cleaning the cache with npm cache clean --force results in #semver: syntax once again being unable to find any versions and throwing an error. 

With an empty cache, #semver: does not work.

**Comment by alfaproject** [comment]
I had to ask my team to revert to not using `semver:` because of this. ):

**Comment by nervgh** [comment]
I have the same issue with the GitLab repos.

**Comment by timg456** [comment]
This broke sometime after npm 5.3. I can confirm it doesn't work on npm 5.4.1 and 5.4.2. After uninstalling node.js then reinstalling node.js version 8.5.0 with npm 5.3.0, the problem has gone away.

**Comment by Halt001** [comment]
I can confirm that it doesn't work on Windows 10 with npm 5.4.2. and reverting back to 5.3 does solve the problem. This is the second time I need to revert back to 5.3. Not having much luck with these updates lately.

**Comment by MeenaAlfons** [comment]
The same issues still exists in npm 5.5.1. Reverting to 5.3 do get `#semver:^1.x.x` to work.

**Comment by andreeib** [comment]
I think this should be fixed by: https://github.com/zkat/pacote/pull/125

**Comment by Naktibalda** [comment]
@andreeib I am still getting with error with npm 5.6.0 and pacote 7.0.2

**Comment by awwebapp** [comment]
also having this issue with npm 5.6.0 (on a private GitLab instance); any hope that this will be solved in the upcoming releases ?

**Comment by andreeib** [comment]
@Naktibalda and @awwebapp what errors are you getting? Can you give an example package.json that fails?

**Comment by awwebapp** [comment]
npm version : 5.6.0

package.json dependencies :

```json
"dependencies": {
    "my-private-package": "git+ssh://git@pcgitlab:WebApp/my-private-package.git#semver:^1.10.0"
  }
```

The project "my-private-package" is in a private GitLab instance. It has a tag "v1.10.0".
npm install outputs the following error :

```
npm ERR! code 1
npm ERR! Command failed: C:\Program Files\Git\mingw64\bin\git.EXE checkout semver:^1.10.0
npm ERR! error: pathspec 'semver:^1.10.0' did not match any file(s) known to git.
```

**Comment by andreeib** [comment]
It does work with `git+http` protocol but not with `git+ssh`. I'll investigate further.

**Comment by QuentinLemCode** [comment]
Hello

Same problem on npm install with npm5.5.1

I'm using a private gogs server. The repo has some tags (v1.0.0, v1.0.1, v1.1.0 ...)

Log here
```

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 verbose npm-session 2a441ff36ad7d582
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall test@1.0.2
7 info lifecycle test@1.0.2~preinstall: test@1.0.2
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly install loadAllDepsIntoIdealTree
14 silly fetchPackageMetaData error for framemanager@git+ssh://gogs:Npm_Module/FrameManager.git#semver:^1.0.0 Command failed: C:\CAT_USERDATA\Prog\Cmder\vendor\git-for-windows\cmd\git.EXE checkout semver:^1.0.0
14 silly fetchPackageMetaData error: pathspec 'semver:^1.0.0' did not match any file(s) known to git.
15 verbose stack Error: Command failed: C:\CAT_USERDATA\Prog\Cmder\vendor\git-for-windows\cmd\git.EXE checkout semver:^1.0.0
15 verbose stack error: pathspec 'semver:^1.0.0' did not match any file(s) known to git.
15 verbose stack
15 verbose stack     at ChildProcess.exithandler (child_process.js:275:12)
15 verbose stack     at emitTwo (events.js:126:13)
15 verbose stack     at ChildProcess.emit (events.js:214:7)
15 verbose stack     at maybeClose (internal/child_process.js:925:16)
15 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
16 verbose cwd X:\test
17 verbose Windows_NT 6.1.7601
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
19 verbose node v8.9.3
20 verbose npm  v5.5.1
21 error code 1
22 error Command failed: C:\CAT_USERDATA\Prog\Cmder\vendor\git-for-windows\cmd\git.EXE checkout semver:^1.0.0
22 error error: pathspec 'semver:^1.0.0' did not match any file(s) known to git.
23 verbose exit [ 1, true ]

```

**Comment by andreeib** [comment]
Hey @Worlor you should switch to `git+http` protocol until this is fixed.

**Comment by QuentinLemCode** [comment]
Hello @andreeib 
Thanks, but it's not better :cry: 

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 verbose npm-session c2857ebb493d3208
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall test@1.0.2
7 info lifecycle test@1.0.2~preinstall: test@1.0.2
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly install loadAllDepsIntoIdealTree
14 silly fetchPackageMetaData error for framemanager@git+http://10.70.129.13:3000/Npm_Module/FrameManager.git#semver:^1.0.0 No valid versions available for framemanager
15 verbose type range
16 verbose stack framemanager: No valid versions available for framemanager
16 verbose stack     at pickManifest (C:\CAT_USERDATA\Prog\Cmder\bin\nvm\v8.9.3\node_modules\npm\node_modules\pacote\node_modules\npm-pick-manifest\index.js:19:11)
16 verbose stack     at git.revs.then.remoteRefs (C:\CAT_USERDATA\Prog\Cmder\bin\nvm\v8.9.3\node_modules\npm\node_modules\pacote\lib\fetchers\git.js:136:7)
16 verbose stack     at tryCatcher (C:\CAT_USERDATA\Prog\Cmder\bin\nvm\v8.9.3\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
16 verbose stack     at Promise._settlePromiseFromHandler (C:\CAT_USERDATA\Prog\Cmder\bin\nvm\v8.9.3\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
16 verbose stack     at Promise._settlePromise (C:\CAT_USERDATA\Prog\Cmder\bin\nvm\v8.9.3\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
16 verbose stack     at Promise._fulfillPromises (C:\CAT_USERDATA\Prog\Cmder\bin\nvm\v8.9.3\node_modules\npm\node_modules\bluebird\js\release\promise.js:668:14)
16 verbose stack     at Promise._settlePromises (C:\CAT_USERDATA\Prog\Cmder\bin\nvm\v8.9.3\node_modules\npm\node_modules\bluebird\js\release\promise.js:694:18)
16 verbose stack     at Promise._fulfill (C:\CAT_USERDATA\Prog\Cmder\bin\nvm\v8.9.3\node_modules\npm\node_modules\bluebird\js\release\promise.js:638:18)
16 verbose stack     at Promise._resolveCallback (C:\CAT_USERDATA\Prog\Cmder\bin\nvm\v8.9.3\node_modules\npm\node_modules\bluebird\js\release\promise.js:432:57)
16 verbose stack     at Promise._settlePromiseFromHandler (C:\CAT_USERDATA\Prog\Cmder\bin\nvm\v8.9.3\node_modules\npm\node_modules\bluebird\js\release\promise.js:524:17)
16 verbose stack     at Promise._settlePromise (C:\CAT_USERDATA\Prog\Cmder\bin\nvm\v8.9.3\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
16 verbose stack     at Promise._settlePromise0 (C:\CAT_USERDATA\Prog\Cmder\bin\nvm\v8.9.3\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
16 verbose stack     at Promise._settlePromises (C:\CAT_USERDATA\Prog\Cmder\bin\nvm\v8.9.3\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
16 verbose stack     at Promise._fulfill (C:\CAT_USERDATA\Prog\Cmder\bin\nvm\v8.9.3\node_modules\npm\node_modules\bluebird\js\release\promise.js:638:18)
16 verbose stack     at Promise._resolveCallback (C:\CAT_USERDATA\Prog\Cmder\bin\nvm\v8.9.3\node_modules\npm\node_modules\bluebird\js\release\promise.js:432:57)
16 verbose stack     at Promise._settlePromiseFromHandler (C:\CAT_USERDATA\Prog\Cmder\bin\nvm\v8.9.3\node_modules\npm\node_modules\bluebird\js\release\promise.js:524:17)
17 verbose cwd X:\test
18 verbose Windows_NT 6.1.7601
19 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
20 verbose node v8.9.3
21 verbose npm  v5.5.1
22 error code ENOVERSIONS
23 error No valid versions available for framemanager
24 verbose exit [ 1, true ]

```

Something wrong with my tags ?
![image](https://user-images.githubusercontent.com/3814031/35925445-04bc64a0-0c26-11e8-9263-e1db5efab1d6.png)

**Comment by andreeib** [comment]
Can you try with npm >5.6.0?

**Comment by QuentinLemCode** [comment]
Thanks @andreeib , it works with npm 5.6

**Comment by andreineculau** [comment]
~FWIW I'm using npm 5.7.1 and I'm still seeing spurious errors.~
My errors were of a different kind. Reported in https://github.com/zkat/pacote/issues/143

**Comment by LannyCodes** [comment]
@Worlor @andreeib I am using npm 5.6.0,I still seeing similar issue,Can you help me ,thanks!

**Comment by andreeib** [comment]
Hey @LannyCodes Can you show the URL you are using?
If you are using the colon separator switch to a `/`;

Example:
from `git+ssh://git@notgithub.com:npm/npm-package-arg.git#semver:^5.1.0` 
to     `git+ssh://git@notgithub.com/npm/npm-package-arg.git#semver:^5.1.0`

Take a look at this pull request: https://github.com/npm/npm-package-arg/pull/33

**Comment by DJDaveMark** [comment]
Having just been bitten by this bug, it would be good to change the [examples in the official docs](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies) to use the slash instead of a colon, to save people in the future tearing their hair out.

Can anyone here make that happen? Or where should I ask?

Just to resume, all of the following works for me (npm -v 5.6.0):
```
# with slash between host & path
git+ssh://git@gitlab.example.com/path/repo.git
git+ssh://git@gitlab.example.com/path/repo.git#branch_1_2
git+ssh://git@gitlab.example.com/path/repo.git#1.2.3
git+ssh://git@gitlab.example.com/path/repo.git#semver:^1.2.3
git+ssh://git@gitlab.example.com/path/repo.git#semver:~1.2.3

# with colon between host & path
git+ssh://git@gitlab.example.com:path/repo.git
git+ssh://git@gitlab.example.com:path/repo.git#branch_1_2
git+ssh://git@gitlab.example.com:path/repo.git#1.2.3
```
but this doesn't work:
```
# with colon between host & path
git+ssh://git@gitlab.example.com:path/repo.git#semver:^1.2.3
git+ssh://git@gitlab.example.com:path/repo.git#semver:~1.2.3
```

In the mean time I posted a question & answer for this over at [ye olde stackoverflow](https://stackoverflow.com/questions/50160639/git-ssh-url-with-semver-range-as-npm-dependency) since I didn't find this issue when I first searched for it. I only found it once I accidentally found the workaround by trying multiple different combinations of slashes, colons all over the place.

**Comment by crazy4groovy** [comment]
I'm having an issue with `npm v6.0.0` that is resolved when I downgrade to `npm@5.8.0`.

I had v1.6.2 of lib
`"company-client": "bitbucket:company/client.git#v1.6.2"`

Then I upgraded to npm v6.

Then I needed v1.7.1
`"company-client": "bitbucket:company/client.git#v1.7.1"`

But kept getting `v1.6.2`! I deleted node_modules, and even cleared the npm cache folder on my machine (~\AppData\Roaming\npm-cache). Still kept getting `v1.6.2` until I downgraded to `npm v5.8.0`, and I got `v1.7.1` as expected.

**Comment by DJDaveMark** [comment]
It looks like GitLab is probably going to change the format they use because of this:
https://gitlab.com/gitlab-org/gitlab-ce/issues/46053
