### ISSUE TITLE
NPM throwing 404 error for ansi-styles package

### ISSUE THREAD

**Issue by techieanant** [npm/npm#17723]
#### I'm opening this issue because:

  - npm is throwing 404 not found error for the package ansi-styles v2.2.0.

#### What's going wrong?
  - npm is not able to fetch this package.

#### How can the CLI team reproduce the problem?

`npm install` 
`npm ERR! fetch failed https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.0.tgz`
`npm ERR! fetch failed https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.0.tgz`
`npm WARN retry will retry, error on last attempt(0,0): Error : fetch failed with status code 404`
`npm ERR! fetch failed https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.0.tgz`
`npm ERR! fetch failed https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.0.tgz`
`npm WARN retry will retry, error on last attempt(0,0): Error : fetch failed with status code 404`

### supporting information:

 - `npm -v` prints: 3.7.3
 - `node -v` prints: 5.8.0
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: Windows
 - Network issues: None

### Temporary fix

Replacing all the instances of 2.2.0 to 2.2.1 for ansi-styles in your npm-shrinkwrap.json should fix it for now.

**Comment by oliveiradouglas** [comment]
I am getting the same problem.

**Comment by JPranjali** [comment]
same here

**Comment by gicanoi** [comment]
same

**Comment by aromine** [comment]
Same - my guess is a lot of people are effected... this is a pretty basic package as it's used by Chalk

**Comment by TarynChambers** [comment]
I'm getting the same error. Does anyone know what library is trying to download this? I'm not sure how to get around it.

**Comment by abuteler** [comment]
+1

**Comment by ashleyryan** [comment]
https://registry.npmjs.org/ansi-styles/

doesn't have a 2.2.0 in the versions object, but there *is* is a 2.2.0 in the "time" object. At some point there must have been a 2.2.0

**Comment by tsolyanNew** [comment]
same

**Comment by ftaiolivista** [comment]
idem. But if I do npm ls and search ansi-style I got reference to ansi-styles@2.2.1 not 2.2.0. But npm try to search 2.2.0.

**Comment by IgorTIV** [comment]
the same issue

**Comment by sudharsanseenivasan** [comment]
same issue with node -v: 7.6.0 and npm -v :4.6.1

**Comment by sudharsanseenivasan** [comment]
same issue with node -v: 7.6.0 and npm -v :4.6.1

**Comment by ssudhars** [comment]
same issue with node -v : 7.6.0 and npm -v :4.6.1

**Comment by ghost** [comment]
I upgraded node to v8.1.3 and npm5.0.3 and have the same issue

**Comment by ahendrick-tillster** [comment]
I'm seeing this due to the nexus-deployer package which has shrinkwrapped to 2.2.0. Obviously 2.2.0 was on the registry and no longer is now, but if you're having this issue and are using the nexus deployer, you can update your own shrinkwrap to require 2.2.1 to get around this temporarily, though it's not quite ideal.

For reference https://github.com/cthorne66/nexus-deployer/blob/master/npm-shrinkwrap.json

**Comment by techieanant** [comment]
I got mine to work the same way by manually changing all 31 instances of ansi-styles from version 2.2.0 to version 2.2.1 in my npm-shrinkwrap file. Hopefully this problem gets fixed soon.

**Comment by akythaky** [comment]
any luck for anyone ?

**Comment by mderriey** [comment]
Also got bit by this.

Funny thing is `2.2.0` has been [unlisted in July 2016](https://github.com/chalk/ansi-styles/issues/15#issuecomment-202562321), so not sure why this bits all of us only now.

Seems like replacing all the instances of `2.2.0` to `2.2.1` for `ansi-styles` in our `npm-shrinkwrap.json` did the trick.

**Comment by Mexassi** [comment]
In my case I used https://www.npmjs.com/package/npm-install-que and found out that an old version of `gulp-angular-protractor` was trying to fetch ansi-styles 2.2.0. Updating the gulp-angular-protractor package fixed the issue.

**Comment by ssudhars** [comment]
@Mexassi Thank you . I followed your step.Its fixed my issue.

**Comment by unimonkiez** [comment]
nexus-deployer accidently published their shrinkwrap with their package.
opened a [PR](https://github.com/cthorne66/nexus-deployer/pull/8) which fixes that issue.

In the meanwhile I just moved to yarn and the issue was solved (Because it ignores the shrinkwrap).

**Comment by abuteler** [comment]
Still failing for me. Is there anything I'm missing?

**Comment by abuteler** [comment]
installing Yarn (https://yarnpkg.com/) and doing 'yarn install' instead of 'npm install' will bypass the issue for anyone still experiencing it.

**Comment by vjarysta** [comment]
Thanks @Mexassi ! 😊

**Comment by Qix-** [comment]
FWIW This can be closed.
