### ISSUE TITLE
package-lock.json and optional packages

### ISSUE THREAD

**Issue by Strate** [npm/npm#17722]
#### I'm opening this issue because:

  - [x] npm is doing something I don't understand.

#### What's going wrong?

Npm accidently make changes to package-lock.json

#### How can the CLI team reproduce the problem?

Assume you have a 2 developers, one on mac, and one on linux. You use npm@5.1 and your project depends on `chokidar` package. That package has optional dependency of `fsevents`, which is useful only for mac. So, you are on linux, and do `npm i chokidar`. npm generates package-lock.json withous fsevents, because it is useless on linux. You commit that generated file.

Your teammate pulls your changes, and do `npm i`, to get `node_modules` in sync with `package-lock.json`. Npm installs `fsevents`, and write it to `package-lock.json`. What should mac user to do? commit that file?

Assume that mac user commits file. Linux user pulls it, and make `npm install`. Npm does not install `fsevents`, and remove it from `package-lock.json`. And this become annoying very quickly.

How lock files could be used in this case?

### supporting information:

 - `npm -v` prints: 5.1.0
 - `node -v` prints: v6.10.0
 - `npm config get registry` prints: undefined
 - Windows, OS X/macOS, or Linux?: max + linux
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by mborisv** [comment]
👍

**Comment by topheman** [comment]
We have the exact same problem. Developers use MacOS and Linux across our team and a simple `npm install` might update the `package-lock.json` (adding or removing `fsevents`) (according on the plaform this file was created first) - even though there wasn't any package added.

Is there a flag to do the opposite of `npm install --no-optional` ? (though, this might not work, since the platform will override anyway)

**Comment by Strate** [comment]
We also can not force to use `fsevents` package, because it has strict requirement of os.

**Comment by topheman** [comment]
@Strate I agree, it can also be the other way around - it might even make more sense: treat `optionalDependencies` as **side effects** (since `package.json` ➡️ `package-lock.json` should be **pure**), but some people will raise the fact that this isn't a 100% reproducible build.

At the end this is what we want, using `package-lock.json`: **reproducible builds**.

How is that issue managed using `yarn` ? (I don't remember having this kind of problem - I'll have to check).

*Edit: On the other hand, if you use the `--no-optional` flag, on a MacOS computer, you wont be able to benefit from `fsevents` ...*

**Comment by vitormil** [comment]
:+1:

**Comment by rgajrawala** [comment]
Hey team, any updates on this? We're getting really close to having `npm-shrinkwrap.json` working 100% between our Linux CI server and our local OS X machines, just have this last issue. Thanks!

**Comment by wojtekk** [comment]
We have this issue on Travis CI with package `fsevents` - we are working on Macs, Travis CI uses Ubuntu images.

To prevent the issue we install packages with flag: `--no-save` in a `.travis.yml`:

    npm install --no-save

**Comment by VincentBailly** [comment]
We have the same issue in my team, I don't understand why "npm install" on windows/linux removes fsevents from package-lock.json. The documentation states that it should be there always: https://docs.npmjs.com/files/package-lock.json

**Comment by mtibben** [comment]
Using `npm install --no-save` works, but isn't ideal in a CI environment. In a CI environment you want to ensure you have a reproducible build from the lockfile, but using `--no-save` can result in a `node_modules` different to your lockfile if your package.json specifies something different. You want to get feedback (ideally a hard fail) if node_modules and package-lock.json is out of sync after an `npm install`. And this is just not always possible if the lock file is flapping between architectures.

So I would really like to see a flag to assert that the lockfile and node_modules is in sync, and incorporated into the `install` command. Perhaps something like `npm install --from-lockfile-only` which then hard fails if package.json and the lockfile are out of sync

**Comment by 00dani** [comment]
An added flag like `npm install --from-lockfile-only` would be perfect for CI and the like, but it doesn't help so much when your development machines have different architectures, as ours do. 

Perhaps the lockfile format should be extended so that optional dependencies are annotated as such - `"fsevents": {"version": "1.1.1", "optional": true, ...}` - with npm interpreting the `optional` flag as specifying something like "if this package is installed at all, it must be the version specified, but if it's not installed at all don't worry about it"? I believe currently the lockfile is directly derived from the contents of `node_modules`, which would be why optional packages vanish from it if not installed, so that would need to change.

… and then I noticed that the lockfile *does* have `"optional": true` already. Alright. So, maybe npm should simply copy across optional packages into the new lockfile?

**Comment by gfzabarino** [comment]
👍

**Comment by desfero** [comment]
Our team also have the same problem which is really annoying, because each reviewer should check what was changed in package-lock. Maybe like @00dani propose add all optionals with a flag?

**Comment by cristovaoth** [comment]
Is there a workaround for this issue, other than using --no-save?

**Comment by DmitryKorlas** [comment]
As workaround I see the only solution - not to commit **package-lock.json** if you don't change **package.json**

**Comment by impaler** [comment]
If something is non optional and platform specific it doesn't seem enough to describe that with "optionalDependencies". Until then we will see scripts & solutions like this https://github.com/bertofer/npm-platform-dependencies. If the lock-file is supposed to be an immutable representation of an install to reproduce its not entirely possible if the os isn't recorded as well. Maybe we need platform specfic lock files or an addition in there that is platform specific? 

Ideally I'd like to see cross platform development as frictionless as possible. Platform specific dependencies should be described as what they are. imo:

```
"fs-events is a mac & development only requirement" !== "optionalDependencies"
```

Also `--no-save` is useful in itself :+1:

**Comment by 00dani** [comment]
Making the _whole_ lockfile platform-specific - `package-lock.darwin.json` or whatever - makes it harder to guarantee that the packages you *do* install are at exactly the same versions. The majority of packages installed in a typical project should be identical across platforms.

Pushing platform-specific packages into a special subtree of the lockfile would be fine, though. How 'bout this?
```json
"dependencies": {"some-package": {...}, "some-other-package": {...}, ...},
"osDependencies": {
  "darwin":  {"some-mac-package": {...}, ...},
  "linux": {"some-linux-package": {...}, ...}
}
```
If added, `osDependencies` probably should also be supported in package.json.

**Comment by impaler** [comment]
Yes thats what I had in mind @00dani and it would probably need to support `dev` dependencies as well.

**Comment by 00dani** [comment]
The lockfile would handle `dev` dependencies just fine with just the keys above, since currently it handles `dev` dependencies simply by marking them with a `"dev": true` flag rather than storing them in a separate section.

It's trickier for package.json, however, since that file has actual separate sections for `devDependencies` and `optionalDependencies`. So as an alternative proposal, perhaps we could repurpose package.json's existing `os` key? Currently that key can only contain an array of supported platforms - keeping that behaviour unchanged, we could alternatively allow an object:
```json
{
  "name": "chokidar",
  "dependencies": {"anymatch": "^1.3.0", ...},
  "os": {
    "darwin": {"dependencies": {"fsevents": "^1.0.0", ...}}
  }
}
```

**Comment by acutmore** [comment]
Split optional dependencies into separate folders with separate package.json files.

Not the cleanest solution but very simple.

Can have a different folder for mac/Linux/windows/developers/CI.

**Comment by Strate** [comment]
So, yarn do not have this problem, gonna to migrate.

**Comment by deivid-rodriguez** [comment]
It doesn't seem fixed in `npm 5.4.2`.

**Comment by felixfbecker** [comment]
This is preventing big cross-platform open source projects like VS Code from updating https://github.com/Microsoft/vscode/issues/30134

**Comment by cristovaoth** [comment]
Is there any follow up happening on npm's side?

This is a serious issue that forced us to develop tooling to make the install platform independent.

Looking forward to seeing this fixed in an upcoming release.

**Comment by felixfbecker** [comment]
https://twitter.com/ReBeccaOrg/status/915729327882248193

**Comment by drewlustro** [comment]
**+1 on this**... Making our team consider `yarn`

Whenever I commit from my Ubuntu machine, it nukes `fsevents` out of the `package-lock.json` file, creating tons of noise in our repo.

**Comment by Grawl** [comment]
I just migrated from Yarn to NPM 5 believing in that lockfile and there is no progress on such a critical bug. Migrating back. Long Life Classic NPM.

**Comment by uhlryk** [comment]
Is there any update about it.
We have the same issue in my team.

**Comment by maiis** [comment]
Switch to Yarn seams to be to solution for now... 😏

**Comment by jekh** [comment]
We migrated to yarn due to this issue. We've also noticed that `yarn install` is significantly faster than `npm install`, on the order of 2-4x faster.

**Comment by jdalton** [comment]
If I put myself in the maintainer's shoes I don't think these comments would make me feel great or positively motivate me. It's on their radar. Instead of piling on why not pitch in?

>
<a href="https://twitter.com/ReBeccaOrg/status/915729327882248193"><img src="https://user-images.githubusercontent.com/4303/32639372-82bbcfc0-c578-11e7-966f-5b8ccea4ee53.png" width=50%></a>

**Comment by Grawl** [comment]
anyway there is a major issue for teams and we need a workaround

**Comment by mightyiam** [comment]
As an attempt for a workaround, I tried to specifically install --save-dev a sub-dependency, in the hope that it would monomorphize the `package-lock.json`. But in the case of the fsevents package, it refused to be installed on Linux.

I wish I had a working workaround as input for the subscribers of this issue, but this is all I got for now. Any ideas?

**Comment by thibaudcolas** [comment]
@mightyiam there are a few workarounds mentioned above:

- using the `--no-save` flag, https://github.com/npm/npm/issues/17722#issuecomment-317108180, https://github.com/npm/npm/issues/17722#issuecomment-319828295
- not committing the changes to `package-lock.json` if `package.json` hasn't been changed, https://github.com/npm/npm/issues/17722#issuecomment-324329821

Personally I don't think it's a good idea to have people use and remember yet another CLI flag that they might forget anyway, so I've told people to go with option 2.

**Comment by jacksonrayhamilton** [comment]
I've started a bounty for this issue: https://www.bountysource.com/issues/47124204-package-lock-json-and-optional-packages.

**EDIT:** I've put up a modest amount of my own money because I know a lot of other people will benefit from this, and I'd like those people to pitch in too, to raise the bounty and thereby get this fixed.

**Comment by naugtur** [comment]
@npm Could you share some pointers to places where one would look to fix this if it were their first contribution? Do you have a conceptual idea for the fix?

> edited to replace `@maintainers` with `@npm`

**Comment by karfau** [comment]
(I think `@maintainers` might not have an idea, since it is an actual organization ;))

**Comment by naugtur** [comment]
I meant that figuratively, I'm surprised it notified anyone.

**Comment by shospodarets** [comment]
Looks like fixed in npm 5.6.0:
http://blog.npmjs.org/post/167963735925/v560-2017-11-27

**Comment by dijonkitchen** [comment]
Guessing this should be closed since it's merged in #19054

**Comment by vitalyster** [comment]
> Npm does not install fsevents, and remove it from package-lock.json

Still reproduced with npm 5.6.0

**Comment by luislobo** [comment]
As far as I tested, this PR is included in `npmc`, so you could `npm install npmc -g` and then run `npmc` instead of `npm`

**Comment by dijonkitchen** [comment]
That's just the canary version of `npm` no?

**Comment by luislobo** [comment]
@dijonkitchen yup!

**Comment by ljharb** [comment]
This might be affecting Airbnb; npm 5.6 just started shipping with node 8.9.4, and our builds on an internal project started failing (because we run `npm ls` to verify) with:
```sh
$ npm ls >/dev/null
npm ERR! extraneous: fsevents $PWD/node_modules/fsevents
npm ERR! error in $PWD/node_modules/fsevents: ENOENT: no such file or directory, open '$PWD/node_modules/fsevents/package.json'
npm ERR! extraneous: nan@2.8.0 $PWD/node_modules/nan
```

This passes fine on our Mac; it's failing in travis (Linux). `package-lock` is set to `false` in our `.npmrc`, so there's no lockfile at all. It passes on Linux in npm <= v5.5.

cc @zkat / @iarna ; iow this bug is now breaking an LTS version of node :-/

**Comment by vitalyster** [comment]
```
$ npmc --version
5.6.0-canary.6
```
still have issue with fsevents

**Comment by travi** [comment]
@vitalyster the full release of 5.6 had been available for a while now and is even the default with node `v8.9.4`, so it's worth trying after updating. 

After committing the addition to the lockfile of `fsevents` with the `optional` flag set, i no longer see any churn of `fsevents`

**Comment by travi** [comment]
I have still been seeing some churn with an indirect dependency on `jsbn` though. The `optional` flag gets added to it on macOS. If we commit that change, it gets removed again on CI (linux on Travis) when greenkeeper updates our lockfile there. 

This is the only place we're still seeing churn after updating to v5.6

**Comment by ljharb** [comment]
At @Airbnb this fsevents bug is still very much a problem on npm v5.6.0; specifically, it's the `npm shrinkwrap` change that seems to add the empty/broken fsevents hash; `npm install` doesn't add it.

We're looking into a terrible workaround of adding a postshrinkwrap step that excises "fsevents", but it's still very much a bug.

**Comment by Grawl** [comment]
seems still not fixed

**Comment by ShadowRZ** [comment]
But **why** it wants to remove dep from `package-lock.json`?
Does this make sense in some way?

EDIT:
> One key detail about **package-lock.json** is that it cannot be published, and it will be ignored if found in any place other than the toplevel package. It shares a format with [npm-shrinkwrap.json](https://docs.npmjs.com/files/shrinkwrap.json), which is essentially the same file, but allows publication. This is not recommended unless deploying a CLI tool or otherwise using the publication process for producing production packages.
(In https://docs.npmjs.com/files/package-lock.json)

......

**Comment by iarna** [comment]
@ShadowRZ It should not being that under 5.6, whatever other bugs 5.6 may have.

It was doing that because the installer was removing it from the "ideal tree" which represented what we were going to write to your node modules, and your package-lock is a serialization of the ideal tree.

5.6 patched this to simply mark the module as uninstallable without removing it from the tree, which will stop it from mutating your package-lock.

If folks would like to see this bug move forward, a repro under 5.6 would go a long way. Alternatively, anyone who would like to spend some engineering hours on this should drop by #npm on the https://package.community discord and we'll spend however much time is needed to get you up to speed and answer questions. If this bug is critical to your company then that would be the most expedient course of action.

**Comment by travi** [comment]
>This might be affecting Airbnb; npm 5.6 just started shipping with node 8.9.4, and our builds on an internal project started failing (because we run npm ls to verify) with:
>
> ```
> $ npm ls >/dev/null
> npm ERR! extraneous: fsevents $PWD/node_modules/fsevents
> npm ERR! error in $PWD/node_modules/fsevents: ENOENT: no such file or directory, open '$PWD/node_modules/fsevents/package.json'
> npm ERR! extraneous: nan@2.8.0 $PWD/node_modules/nan
> ```
>
> This passes fine on our Mac; it's failing in travis (Linux). package-lock is set to false in our .npmrc, so there's no lockfile at all. It passes on Linux in npm <= v5.5.

 i've been using the `npm ls >/dev/null` check in my projects after seeing you [suggest it previously](https://github.com/greenkeeperio/greenkeeper/issues/278#issuecomment-308818609). i've noticed that it has been failing more with npm v5.6, mostly related to `fsevents`. i've been able to avoid the problem in some projects using `npm ls --production >/dev/null` because `fsevents` is only being pulled in be `devDependencies`. in projects that pull `fsevents` from `dependencies`, i've had to completely disable the check. in both cases, i'm obviously losing the benefit of the `npm ls` exit code alerting me to incompatibilities.

what i think i've identified is that `npm ls` is failing for `optional` dependencies with npm 5.6 for whatever reason. @ljharb, does this sound like it could be related to the issue you describe above? if so, it seems completely unrelated to lockfile churn, but very much a problem. `npm ls` should exit with `0` if optional dependencies are not installed.

**Comment by ljharb** [comment]
@travi Yes, this seems like it might be very related.

**Comment by rbruelisauer** [comment]
I've came across the same issue on our windows build server.

Long search, short answer: Some npm version seem to have issues with race-conditions in OS detection. Sometimes it works, sometimes not.

In the end, I upgraded npm from 5.5.1 to 5.6.0. This version seems to run stable on windows.
I also added the "--no-optional" option to any npm call.

**Comment by xfh** [comment]
We are running into this issue in combination with npm dedupe (npm 5.6.0):
When we execute npm dedupe, all the fsevent dependencies are removed from package-lock.json. The next time anyone in the team runs npm install, fsevents is added again.

In my opinion, npm install is doing the right thing: the optional dependency is not installed in node_modules/ on platforms, where it isn't required. However, npm dedupe should honour optional dependencies and not remove them from package-lock.json.

**Comment by edi9999** [comment]
This can be closed , since it is fixed in the 5.6.0 version : 

> bc263c3fd  #19054  Fully cross-platform package-lock.json. Installing a failing optional  dependency on one platform no longer removes it from the dependency tree,  meaning that package-lock.json should now be generated consistently across  platforms! 🎉  (@iarna)

(Source : http://blog.npmjs.org/post/167963735925/v560-2017-11-27)

**Comment by alfaproject** [comment]
No, it's not fixed. `fsevents` keeps appearing/disappearing depending on who installs/updates node modules.

**Comment by edi9999** [comment]
Are you sure you're all using npm version 5.6.0 ?

**Comment by elektronik2k5** [comment]
I've been using `npm@5.7.1` for a while, and can confirm the issue definitely exists. Didn't try the new `5.8.0`.

**Comment by huntie** [comment]
I can confirm the issue still exists as of `5.8.0` today.

**Comment by casey-speer** [comment]
`npm@5.7.1`: Install works fine locally on mac os, can confirm that `fsevents` is marked as `optional` in the `package-lock.json`s. However, fails on linux build server with 
```
03-Apr-2018 14:16:33    npm ERR! code EBADPLATFORM
03-Apr-2018 14:16:33    npm ERR! notsup Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
03-Apr-2018 14:16:33    npm ERR! notsup Valid OS:    darwin
03-Apr-2018 14:16:33    npm ERR! notsup Valid Arch:  any
03-Apr-2018 14:16:33    npm ERR! notsup Actual OS:   linux
03-Apr-2018 14:16:33    npm ERR! notsup Actual Arch: x64
```

There are no problems when `package-lock=false` is set in `.npmrc`. I have tried adding `fsevents` as an `optionalDependency` in all the `package.json`s I have control of, but no luck with that.

Any thoughts on what to do here? This makes it impossible for my organization to use package locks and gain any benefits from `npm ci` etc.

**Comment by drc-gcoakley** [comment]
One of the advantages of development in the npm / nodejs ecosystem is the ability to leverage cross-platform code libraries. I understand there is quite likely to be some code that is platform specific and the users of that don't care about other platforms. So, there is a general case here for specifying packages which are optional.  I can see npm having a defined pattern of how that should be approached. npm does have an 'optionalDependencies' section. but, that does not seem sufficient to describe the desire here which is that fsevents be required when on OSX but optional on, say, Windows. 
It also does not handle a situation such as this (https://softwareengineering.stackexchange.com/questions/238257/optional-dependencies-in-npm) where there is a required dependency in some circumstances but not other. And, the functionality needs to interact appropriately with all of the NPM functions (install, update, shrinkwrap) for all types of dependencies.  This does not sound like something that is likely to have a quick and easy design or fix. 

Most of the people commenting in this thread refer to fsevents, which only provides an implementation for OSX. To me this violates on of the tenants of creating a node package.  Further, it does so despite the fact that the same functionality is supported and can be provided on Windows (https://msdn.microsoft.com/en-us/library/windows/desktop/aa365261(v=vs.85).aspx) and on Unix (https://stackpointer.io/unix/linux-monitor-file-system-changes/397/).  It seems that the ire here should be directed more at the development of fsevents and/or the packages that are requiring it.  If there was a implementation for the other platforms then this would not be an issue for many and the NPM developers could focus on determining the best solution.

This does not currently effect my company but, it will. My two cents on a possible solution? Each dependency could have an optional 'is-install-required' property for its installation specified in the package.json. This precondition could be a javascript expression that if it evaluated to true, would require the dependency be installed.  The default implementation would be 'return true'. The precondition for what is now and optional dependency would be 'return false'. The precondition for fsevents could be '$os == OSX', etc.  

The same type of property expression could be applied to a 'is-packaged' or 'is-distributable' property that could specify if the dependency it applied to should be packaged and deployed with the application / library code.  I am not very familiar with all of the distinctions but, it seems that it could also replace the various *Dependencies blocks which, to me, all seem like accretions crying out for a better design aided by experience / hindsight that could clarify much.  Dependencies may need to be installed for the build, packaging, testing or execution of code. This boils down to two places a development workspace or a execution environment. Then there is a co-mingled use of dependencies as artifacts referenced (for transformation or just deployment) during a build. 

    DevDependencies -- are needed to build but not run the code.  (install-at-build-time=true, distribute=false, install-at-runtime=false)
    PeerDependencies -- are required to run the code but are not provided.  (install-at-build-time=true, distribute=false, install-at-runtime=true)
    BundledDependencies -- are required to run the code and are provided.  (install-at-build-time=false (they are part of the source), distribute=true, install-at-runtime=false)
    OptionalDependencies -- are not required to run built or run the code but would be used in some case if available. (install-at-build-time=conditionally, distribute=false, install-at-runtime=conditionally?)
     dependencies -- are required both to build and to run the code.  (install-at-build-time=true, distribute=false, install-at-runtime=true)

The install-at-build-time value is the same as the install-at-runtime except for the devDependencies which are often installed globally on a development system anyway. I know there are exceptions to this for version differences so, it cannot be totally glossed over. Generally, a development workspace needs a superset of the dependencies of an execution / runtime environment. For this, I can see continuing to have 'devDependencies'. 

The distribute value is always false except for bundledDependencies which honestly seem like a build step that was shoehorned into the existing pattern of the *Dependency properties. Should npm (the Package Manager) care if a dependency is bundled or not? I think that should be left to webpack, etc.

These are just some initial impressions and thoughts. Do what you like with them.

**Comment by luislobo** [comment]
@iarna @zkat: @drc-gcoakley last comment actually brings some new ideas into how to solve this problem. Is there anything in the Roadmap to handle this kind of problem?

**Comment by ankon** [comment]
This reminds me of how Maven handles a "scope" per dependency: https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope

**Comment by drc-gcoakley** [comment]
Maven's scope model would be a good example to follow given the wealth of experience that has gone into it and that people have with it. The System and Import values probably would not be necessary. Though, honestly I am not sure I understand the Import one at this hour of the morning. (I need more go-go juice.)

**Comment by nknapp** [comment]
> Most of the people commenting in this thread refer to fsevents, which only provides an implementation for OSX. To me this violates on of the tenants of creating a node package. Further, it does so despite the fact that the same functionality is supported and can be provided on Windows (https://msdn.microsoft.com/en-us/library/windows/desktop/aa365261(v=vs.85).aspx) and on Unix (https://stackpointer.io/unix/linux-monitor-file-system-changes/397/). 

In our case, the [7zip-bin](https://github.com/develar/7zip-bin/tree/master/win) package made problems.
It has three optional dependencies (`7zip-bin-win`, `7zip-bin-linux`and `7zip-bin-mac`) which are available depending on the OS. This separation makes sense (less disk-space), but it causes the following behaviour:

* Run `npm install` on a Windows system: `package-lock.json` will contain `7zip-bin-win`.
* Commit the `package-log.json` and clone the repo on a Linux system: `npm` will NOT install any `7zip-bin-*` package, because `7zip-bin-linux` is not in the `package-lock.json` and `7zip-bin-win` is for a different platform.

After wondering-why a couple of times, we decided to disable the `package-lock.json` completely, but I now have the feeling that this causes other problems, although I have not verified that yet.

I think the following behaviour would solve the problem.

* If an optional dependency in the `package-lock.json` but does not match the platform, ignore it.
* If an optional dependency is NOT in the `package-lock.json` but should be installed for the current platform, install it and add an entry to `package-lock.json` (without removing the other entry).

**Comment by MikelArnaiz** [comment]
Still having issues with `6.1.0`.

We develop in Mac OS.
In Circleci `npm install` modifies `package-lock.json`, e.g:

```
         "brace-expansion": {
           "version": "1.1.11",
           "bundled": true,
+          "optional": true,
           "requires": {
             "balanced-match": "^1.0.0",
             "concat-map": "0.0.1"
@@ -5625,15 +5627,18 @@
         },
         "code-point-at": {
           "version": "1.1.0",
-          "bundled": true
+          "bundled": true,
+          "optional": true
         },
         "concat-map": {
           "version": "0.0.1",
-          "bundled": true
+          "bundled": true,
+          "optional": true
         },
```

It is a problem because for caching `node_modules` we use as key the checksum of `package-lock.json `. Therefore `restore_cache` key and `save_cache` key is not the same.

I would like to avoid `--no-save` trick.

**Comment by heymackey** [comment]
Our `package-lock.json` does not differ (the `"optional": true` +/- diff) between installs on mac / linux* on `npm@6.0.1`, but does on `npm@6.1.0`. 

So if it was fixed in 6.0.x, it has regressed in 6.1.x

**Comment by reggi** [comment]
I can confirm in 6.1.0 it is still happening. 

Here's the diff from my `jenkins` pipeline running `docker` `node`.

Just want the file to be generated and be stable cross os.

```
diff --git a/package-lock.json b/package-lock.json
index 6c784f4..6e7bd4c 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -4719,7 +4719,8 @@
         "ansi-regex": {
           "version": "2.1.1",
           "bundled": true,
-          "dev": true
+          "dev": true,
+          "optional": true
         },
         "aproba": {
           "version": "1.2.0",
@@ -5134,7 +5135,8 @@
         "safe-buffer": {
           "version": "5.1.1",
           "bundled": true,
-          "dev": true
+          "dev": true,
+          "optional": true
         },
         "safer-buffer": {
           "version": "2.1.2",
@@ -5190,6 +5192,7 @@
           "version": "3.0.1",
           "bundled": true,
           "dev": true,
+          "optional": true,
           "requires": {
             "ansi-regex": "^2.0.0"
           }
@@ -5233,12 +5236,14 @@
         "wrappy": {
           "version": "1.0.2",
           "bundled": true,
-          "dev": true
+          "dev": true,
+          "optional": true
         },
         "yallist": {
           "version": "3.0.2",
           "bundled": true,
-          "dev": true
+          "dev": true,
+          "optional": true
         }
       }
     },
```

**Comment by DimitarChristoff** [comment]
@reggi can confirm here. so frustrating.
