### ISSUE TITLE
NPM update fails with a non-registry tarball URL dependency

### ISSUE THREAD

**Issue by michaelstone** [npm/npm#17835]
#### I'm opening this issue because:

  - [X] npm is doing something I don't understand.

#### What's going wrong?

NPM update fails when a non-registry tarball URL dependency exists for a module. It errors out of the process with this:

```
npm ERR! code E404
npm ERR! 404 Not found : <module_name>
npm ERR! 404
npm ERR! 404  '<module_name>' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/michael.stone/.npm/_logs/2017-07-18T15_28_47_274Z-debug.log
```

It looks like this issue was raised previously as https://github.com/npm/npm/issues/9531

A summary of that thread:
- This previously worked, but started throwing the error as the result of this commit:
https://github.com/npm/npm/commit/765fd4bfca8ea3e2a4a399765b17eec40a3d893d
- No problems reported with npm install
- Issue also affects npm outdated because that's used by npm update under the hood
- Setting "private: true" in the tarball dependency package.json should be a workaround as private packages are ignored by npm outdated as the result of a previous patch. This has been reported as unsuccessful by a user more recently, and may not always be an option.

The actual behaviour of the npm update relating to tarball URL dependencies is probably debatable given the possible scenarios, but at a minimum it seems like this should warn rather than fail the update for all dependencies.

It looks like the block of code [here](https://github.com/npm/npm/blob/latest/lib/outdated.js#L327) needs to prevent a dependency with a type of 'remote' from being passed to the mapToRegistry function, similar to the exclusions for linked and git dependencies.

I'm happy to take a swing at a PR for this if there's an agreement about the approach.

#### How can the CLI team reproduce the problem?

1. Add a dependency with a non-registry hosted tarball URL
```
{
  "dependencies": {
    "module-name": "http://myserver.com/module-name-v1.tgz"
  }
}
```

2. npm install (which successfully downloads the dependency from the url)
3. npm update

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: 7.10.0
 - `npm config get registry` prints: <private nexus repository>
 - Windows, OS X/macOS, or Linux?: macOS

**Comment by KlavierCat** [comment]
I run into the same problem, digging into the log file, I saw that npm is trying to find the dependency under my organisation's private npm registry, instead of going to the designated url to download the tarball.

**Comment by maxthoursie** [comment]
I followed @michaelstone's instructions to create a simple PR for this annoying bug, in hope that it'll increase the chance of it being fixed.

> It looks like the block of code here needs to prevent a dependency with a type of 'remote' from being passed to the mapToRegistry function, similar to the exclusions for linked and git dependencies.

**Comment by iarna** [comment]
This was resolved in 5.4.2 (released 2017-09-14), sorry about not getting back to this issue sooner to close it!

**Comment by AndreKR** [comment]
I can still reproduce it in 5.8.0.

In an empty directory, create a package.json:
```json
{
	"name": "@example/consumer",
	"version": "0.0.1",
	"description": "Some description",
	"license": "UNLICENSED",
	"private": true,
	"repository": {
		"type": "git",
		"url": "git@example.com:example/consumer.git"
	},
	"dependencies": {
		"@example/foo": "https://filebin.net/o4swjkc5ednetn8e/package.tar.gz"
	}
}
```

Output of `npm update`:
```plaintext
npm ERR! code E404
npm ERR! 404 Not found : @example/foo
npm ERR! 404
npm ERR! 404  '@example/foo' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\andre\AppData\Roaming\npm-cache\_logs\2018-04-12T14_53_25_709Z-debug.log
```

There is no `node_modules` folder.

Output of `npm install`:
```plaintext
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated natives@1.1.3: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm notice created a lockfile as package-lock.json. You should commit this file.
added 83 packages from 65 contributors in 4.723s
```

Everything was installed.
