### ISSUE TITLE
npm ERR! code EINVALIDTYPE npm ERR! typeerror Error: Argument #5: Expected object but got string

### ISSUE THREAD

**Issue by dinanrm** [npm/npm#18128]
npm ERR! code EINVALIDTYPE
npm ERR! typeerror Error: Argument #5: Expected object but got string
npm ERR! typeerror     at inflatableChild (C:\Users\Dinan Rangga Maulana\AppData\Roaming\npm\node_modules\npm\lib\install\inflate-shrinkwrap.js:69:3)
npm ERR! typeerror     at BB.each (C:\Users\Dinan Rangga Maulana\AppData\Roaming\npm\node_modules\npm\lib\install\inflate-shrinkwrap.js:51:12)
npm ERR! typeerror     at tryCatcher (C:\Users\Dinan Rangga Maulana\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm ERR! typeerror     at Object.gotValue (C:\Users\Dinan Rangga Maulana\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\reduce.js:155:18)
npm ERR! typeerror     at Object.gotAccum (C:\Users\Dinan Rangga Maulana\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\reduce.js:144:25)
npm ERR! typeerror     at Object.tryCatcher (C:\Users\Dinan Rangga Maulana\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm ERR! typeerror     at Promise._settlePromiseFromHandler (C:\Users\Dinan Rangga Maulana\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
npm ERR! typeerror     at Promise._settlePromise (C:\Users\Dinan Rangga Maulana\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
npm ERR! typeerror     at Promise._settlePromise0 (C:\Users\Dinan Rangga Maulana\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
npm ERR! typeerror     at Promise._settlePromises (C:\Users\Dinan Rangga Maulana\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
npm ERR! typeerror     at Async._drainQueue (C:\Users\Dinan Rangga Maulana\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
npm ERR! typeerror     at Async._drainQueues (C:\Users\Dinan Rangga Maulana\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
npm ERR! typeerror     at Immediate.Async.drainQueues (C:\Users\Dinan Rangga Maulana\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
npm ERR! typeerror     at runCallback (timers.js:781:20)
npm ERR! typeerror     at tryOnImmediate (timers.js:743:5)
npm ERR! typeerror     at processImmediate [as _immediateCallback] (timers.js:714:5)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <https://github.com/npm/npm/issues>

**Comment by kenany** [comment]
@dinanrm Could you provide more information about this issue? Node version, `npm` version, steps to reproduce? Thanks!

**Comment by AmbyrShae** [comment]
@KenanY I'm getting the same error.
Node version: v8.4.0 
Npm version: 5.3.0
Steps to reproduce: I simply ran npm install in a directory that requires `node_modules`

**Comment by dinanrm** [comment]
The issue has been resolved, thanks :)

**Comment by AmbyrShae** [comment]
@dinanrm @KenanY It is not resolved on my end. How did you resolve it?

**Comment by matheusanmo** [comment]
I'm running into the exact same issue. Running the exact same versions of node + npm @AmbyrShae is using. I'm also running into [this issue](https://github.com/npm/npm/issues/18258). Are you having the same problem @AmbyrShae? Maybe they are related.

**Comment by dinanrm** [comment]
@AmbyrShae I don't know why, but the cause of my problem is so many files are missing in my Node Modules folder.
Fortunately, I have an older backup of Node Modules, so I replace it.. And the problem solved :)

**Comment by AmbyrShae** [comment]
@matheusanmo I am not seeing the other issue you linked, only the one stated on this page. @dinanrm Unfortunately I don't have a node_modules directory and when I try to run npm install, I hit this error so I can't get the node_modules directory.

**Comment by AmbyrShae** [comment]
@matheusanmo @KenanY I passed in an object instead of a string and now this is the error I'm getting:

npm ERR! code EINVALIDTYPE
npm ERR! typeerror Error: Argument #1: Expected string but got object
npm ERR! typeerror     at inflatableChild (/usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:69:3)
npm ERR! typeerror     at BB.each (/usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:51:12)
npm ERR! typeerror     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm ERR! typeerror     at Object.gotValue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:155:18)
npm ERR! typeerror     at Object.gotAccum (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/reduce.js:144:25)
npm ERR! typeerror     at Object.tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm ERR! typeerror     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm ERR! typeerror     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
npm ERR! typeerror     at Promise._settlePromiseCtx (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:606:10)
npm ERR! typeerror     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
npm ERR! typeerror     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
npm ERR! typeerror     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
npm ERR! typeerror     at runCallback (timers.js:781:20)
npm ERR! typeerror     at tryOnImmediate (timers.js:743:5)
npm ERR! typeerror     at processImmediate [as _immediateCallback] (timers.js:714:5)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <https://github.com/npm/npm/issues>

So either way, it's unhappy.

**Comment by AmbyrShae** [comment]
@matheusanmo @KenanY @dinanrm I was able to resolve my issue by downloading node from it's site. Then rebuild node-sass. When I tried uninstalling and reinstalling with homebrew, it didn't work. But downloading the package from the site did.

**Comment by dinanrm** [comment]
@AmbyrShae. Of course you also have node_module directory :)

So your problem is solved?

**Comment by AmbyrShae** [comment]
@dinanrm For me yes.

**Comment by dinanrm** [comment]
@AmbyrShae Ok :)

**Comment by ubskogentix** [comment]
Remove 'package-lock.json' and run "npm install", this should solve your problem.

**Comment by tnoelcke** [comment]
I'm also getting this problem when trying to use npm link

**Comment by tnoelcke** [comment]
npm v 6.1.0
node v 9.4.0
