### ISSUE TITLE
NPM 5.x unable to install a local tarball while offline

### ISSUE THREAD

**Issue by JamieMason** [npm/npm#18339]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [x] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### How can the CLI team reproduce the problem?

1) Create a new project

```
mkdir tmp
cd tmp
npm init -y
```

2) Bundle and install an npm dependency

```
wget https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.11.tgz -P ./node_shrinkwrap
npm install --save ./node_shrinkwrap/graceful-fs-4.1.11.tgz
```

3) Shrinkwrap it

```
npm shrinkwrap
```

`npm-shrinkwrap.json` will look like this

```json
{
  "name": "tmp",
  "version": "0.0.0",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "graceful-fs": {
      "version": "file:node_shrinkwrap/graceful-fs-4.1.11.tgz",
      "integrity": "sha1-Dovf5NHduIVNZOBOp8AOKgJuVlg="
    }
  }
}
```

`package.json` will look something like this

```json
{
  "name": "tmp",
  "version": "0.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "dependencies": {
    "graceful-fs": "file:node_shrinkwrap/graceful-fs-4.1.11.tgz"
  }
}
```

5) Change `package.json` back to how it typically appears

```json
{
  "name": "tmp",
  "version": "0.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "dependencies": {
    "graceful-fs": "4.1.11"
  }
}
```

6) Reset your project

```
rm -rf node_modules
```

7) Disconnect from the internet

8) Re-install (NPM cache still contains this dependency)

```
npm install
```

##### Actual Behaviour

Installs correctly, but `npm-shrinkwrap.json` changes to this

```
{
  "name": "tmp",
  "version": "0.0.0",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "graceful-fs": {
      "version": "4.1.11",
      "resolved": "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.11.tgz",
      "integrity": "sha1-Dovf5NHduIVNZOBOp8AOKgJuVlg="
    }
  }
}
```

##### Expected behaviour

Installs correctly, but `npm-shrinkwrap.json` to remain as I left it

```json
{
  "name": "tmp",
  "version": "0.0.0",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "graceful-fs": {
      "version": "file:node_shrinkwrap/graceful-fs-4.1.11.tgz",
      "integrity": "sha1-Dovf5NHduIVNZOBOp8AOKgJuVlg="
    }
  }
}
```

##### Additional info

If you clear NPM's internal cache and try to install this project from the offline tarball, an error is thrown.

### supporting information:

 - `npm -v` prints: 5.3.0
 - `node -v` prints: v6.10.
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

#### What's the feature?

Installing npm projects from a shrinkwrap while offline

#### What problem is the feature intended to solve?

More info detailed at [JamieMason/shrinkpack](https://github.com/JamieMason/shrinkpack) and issue https://github.com/JamieMason/shrinkpack/issues/83

#### Is the absence of this feature blocking you or your team? If so, how?

AFAICT NPM v5 support for https://github.com/JamieMason/shrinkpack is not possible while this issue stands.

#### Is this a feature you're prepared to implement, with support from the npm CLI team?

Yes

**Comment by iarna** [comment]
Wooow, huh, that is super weird!

**Comment by pietermees** [comment]
Hi @iarna, given that this is a blocker for us to move to npm5 I just wanted to check in if there was any progress on this issue? Thanks!

**Comment by iarna** [comment]
@pietermees When https://github.com/npm/npm/pull/18726 lands, this should be fixed.

**Comment by iarna** [comment]
#18726 did indeed land (and was released in 5.6.0) so I'm gonna close this. If you still have issues, please ping me. (Ideally, out of band from here—while I do get github pings, they're higher latency for me.)

**Comment by JamieMason** [comment]
If my interpretation of what package.json and npm-shrinkwrap.json should contain is correct, I think this issue is still in need of a fix @iarna.

I have put together this script to help reproduce and run it this morning against npm 5.6.0.

```shell
#!/usr/bin/env bash

rm -rf ./can-npm5-install-offline
mkdir ./can-npm5-install-offline
cd ./can-npm5-install-offline
npm init -y
wget -P ./node_shrinkwrap https://registry.npmjs.org/whatwg-fetch/-/whatwg-fetch-2.0.3.tgz >/dev/null 2>&1
npm install --save ./node_shrinkwrap/whatwg-fetch-2.0.3.tgz
npm shrinkwrap
rm -rf ./node_modules
npm cache clear --force

read -r -p "Disconnect from the internet, then hit enter to continue" response

npm install

echo ''
echo 'That should have worked, but notice that package.json is like this:'
echo ''
echo '    "whatwg-fetch": "file:node_shrinkwrap/whatwg-fetch-2.0.3.tgz"'
echo ''
echo "This isn't how most developers use package.json, so change it to:"
echo ''
echo '    "whatwg-fetch": "2.0.3"'
echo ''
echo 'and change the entry in npm-shrinkwrap.json to:'
echo ''
echo '    "whatwg-fetch": {'
echo '      "version": "2.0.3",'
echo '      "resolved": "file:node_shrinkwrap/whatwg-fetch-2.0.3.tgz",'
echo '      "integrity": "sha512-SA2KdOXATOroD3EBUYvcdugsusXS5YiQFqwskSbsp5b1gK8HpNi/YP0jcy/BDpdllp305HMnrsVf9K7Be9GiEQ=="'
echo '    }'
echo ''

read -r -p "When you've done that, stay disconnected from the internet and hit enter to continue" response

rm -rf ./node_modules
npm cache clear --force
npm install

echo ''
echo 'At time of writing (latest npm in 5.6.0) that should have failed due to'
echo 'npm trying to hit the network to visit the registry.'
echo ''
```

**Comment by iarna** [comment]
Ok, so npm is pulling registry metadata for registry sources with a resolved pointing at a tarball. 

Conceptually this makes some sense—the canonical package data for registry sources is the registry, not some tarball.

What's confusing is why it thinks it needs anything. the package-lock tells us what its dependencies are. And we read the package.json off disk to get scripts to run. Hmmm…

**Comment by iarna** [comment]
Ok, so we call `pacote.extract` with _just_ the spec. The resolved is ignored for that purpose, which makes me wonder what purpose it serves at all… mmm…

**Comment by iarna** [comment]
Ahh, ok, so it looks like resolved from the lock isn't getting added in such a way that `extract` is aware… 
```
  const args = [
    pkg.package._resolved
    ? npa.resolve(pkg.package.name, pkg.package._resolved)
    : pkg.package._requested,
    extractTo,
    opts
  ]
```

**Comment by iarna** [comment]
ah, ok, so when inflating the shrinkwrap we were explicitly throwing away any `resolved` field that didn't point at the current registry.

this was done to support scenarios where a lock file was created on the real registry but folks wanted to install from a proxy, or vice-versa.

an exception to this can easily be made for file deps.

**Comment by erickj** [comment]
@iarna thanks for the investigation. But I see the issue was marked closed before the last comment re: what can be done. Is this fix planned?
