### ISSUE TITLE
Unsupported version of node

### ISSUE THREAD

**Issue by ilog2000** [npm/npm#19019]
#### I'm opening this issue because:

  - [x] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?
"npm install" gives an error after installing node.js v9.0.0

npm WARN npm npm does not support Node.js v9.0.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8.
npm WARN npm You can find the latest version at https://nodejs.org/
C:\Program Files\nodejs\node.exe: src\node_zlib.cc:430: Assertion `args.Length() == 7 && "init(windowBits, level, memLevel, strategy, writeResult, writeCallback," " dictionary)"' failed.

#### How can the CLI team reproduce the problem?
Install node.js v9.0.0, open any project, type:
npm install

### supporting information:

 - `npm -v` prints: 5.5.1
 - `node -v` prints: v9.0.0
 - `npm config get registry` prints: npm WARN npm npm does not support Node.js v9.0.0
 - Windows, OS X/macOS, or Linux?: Windows 10

**Comment by amritk** [comment]
Here's the issue from the node repo 
https://github.com/nodejs/node/issues/16649

**Comment by addaleax** [comment]
For now, you should be able to work around this 
- by using `npmc` rather than `npm`, i.e. `npx npmc install` instead of `npm install`; or
- by using the version of `npm` that is bundled with Node 9 **edit**: see https://github.com/npm/npm/issues/19019#issuecomment-341978497 for how to do that; or
- by downgrading to `npm@5.3.x`: `[sudo] npm install -g npm@5.3.x`

The “real” fix would be waiting for the next `npm` release.

**Comment by ilovezfs** [comment]
Is there an ETA until the next npm release? In Homebrew we're planning to withhold node 9 indefinitely until npm has a compatible release.

**Comment by jaromanda** [comment]
"_by using the version of npm that is bundled with Node 9_" - that's not a viable fix in Windows 10 x64, `npm` fails "out of the box"

**Comment by lll000111** [comment]
https://stackoverflow.com/questions/47044126/npm-does-not-support-node-js-v9-0-0

> `npm uninstall -g npm`

Indeed worked for me (Win10 x64)

**Comment by jaromanda** [comment]
of course, disregard my stupidness - comments removed

**Comment by ilog2000** [comment]
Thank you for work around. I simply use yarn as for now, it shows a warning but works. I am just not sure if it is possible to upgrade npm with it after new version is out.

**Comment by LayZeeDK** [comment]
Uninstalling previous version of Node as well as deleting `%AppData%\npm` and `%AppData%\npm-cache` and then installing Node 9.0.0 worked for me. However, I had to install my globally installed packages again.

**Comment by ilog2000** [comment]
Thank you, uninstall Node v9.0.0, delete npm & npm-cache, then re-install Node v9.0.0 works for me as well.

**Comment by hatzipanis** [comment]
This is failing when building on Heroku but I'm not sure if this is the correct issue. Any ideas here?

**Comment by iwadam** [comment]
@hatzipanis Try this solution: https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
Basically you have to specify node version in your package.json file like this:
```
"engines": {
   "node": "8.x"
 }
```

**Comment by MuhammadHasham23** [comment]
I've just upgraded to Node v9 and ran into the same issue.Following the advice to uninstall a global instance of npm has resolved the issue for me, using:

`npm uninstall -g npm`

This caused my system to fall back on the version of npm installed by node 9.0.0, thereby resolving the warning.

**Comment by cybernetics** [comment]
@LayZeeDK I just deleted %AppData%\npm and %AppData%\npm-cache and then I reran node-v9.1.0-x64.msi setup without uninstalling existing node first. It prompted me to repair the existing setup and I went ahead with. after that I was able to run npm command.

> npm -v
5.5.1

it saved me from the hassle of uninstalling & installation of global packages again.

**Comment by jameswomack** [comment]
Looks like it has to do with npm/lib/utils/unsupported.js
```js
var supportedNode = [
  {ver: '4', min: '4.7.0'},
  {ver: '6', min: '6.0.0'},
  {ver: '7', min: '7.0.0'},
  {ver: '8', min: '8.0.0'}
]
```

**Comment by ghost** [comment]
Also had the same issue

**Comment by Yonezpt** [comment]
Followed @MohammadHasham steps in https://github.com/npm/npm/issues/19019#issuecomment-341978497 and the issue went away in node 9.1.0 update

**Comment by duggum** [comment]
@jameswomack said:

> Looks like it has to do with npm/lib/utils/unsupported.js

That's it for sure. It looks like the Node.js folks may have just updated the unsupported file on their own.
```javascript
//  This is from Node 9.1.0's npm/lib/utils/unsupported.js
var supportedNode = [
  {ver: '4', min: '4.7.0'},
  {ver: '6', min: '6.0.0'},
  {ver: '7', min: '7.0.0'},
  {ver: '8', min: '8.0.0'},
  {ver: '9', min: '9.0.0'}
]
```
The question is, what's the reason the npm folks haven't made such a simple change? Are they still testing compatibility before updating? If that's the case, then why would the node folks just make a potentially risky change before compatibility testing is finished?

**Comment by kenany** [comment]
Since it hasn't been linked here yet, https://github.com/npm/npm/pull/18964 is the PR which adds v9 to that `supportedNode` array 👍

**Comment by mutantkeyboard** [comment]
@MohammadHasham that did the trick for me too.

**Comment by djnaumov** [comment]
I think that I have the same issue with node 9.2.0

npm WARN npm npm does not support Node.js v9.2.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8.
npm WARN npm You can find the latest version at https://nodejs.org/
WARNING: You are likely using a version of node-tar or npm that is incompatible with this version of Node.js.atus
Please use either the version of npm that is bundled with Node.js, or a version of npm (> 5.5.1 or < 5.4.0) or node-tar (> 4.0.1) that is compatible with Node.js 9 and above.
C:\Program Files\nodejs\node.exe: src\node_zlib.cc:437: Assertion `args.Length() == 7 && "init(windowBits, level, memLevel, strategy, writeResult, writeCallback," " dictionary)"' failed.

**Comment by bonesoul** [comment]
Yep same with 9.2.0

**Comment by rjdesignz** [comment]
I am having similar issues as well. Not able to run npm after upgrading to Node 9.2.0
Even uninstall of npm isn't working. It gives me error as follows:

> rj$ npm uninstall -g npm
npm WARN npm npm does not support Node.js v9.2.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8.
npm WARN npm You can find the latest version at https://nodejs.org/
up to date in 0.057s

**Comment by kenany** [comment]
Patch has landed: https://github.com/npm/npm/commit/6caf2309613d14ce77923ad3d1275cb89c6cf223.

**Comment by ilovezfs** [comment]
There's no 5.5.2 release so that requires a very loose definition of landed.

**Comment by bonesoul** [comment]
@KenanY this patch doesn't seem to resolve the zlib issue

``C:\Program Files\nodejs\node.exe: src\node_zlib.cc:430: Assertion `args.Length() == 7 && "init(windowBits, level, memLevel, strategy, writeResult, writeCallback," " dictionary)"' failed.``

so not really useful

**Comment by kenany** [comment]
@ilovezfs Sorry, I'm used to using "landed" as a synonym for "merged" 😆 

@boneskull Right, I should've clarified that the patch removes the warning. I think the zlib issue might be fixed by the `pacote` update (which contains the `node-tar` update to Node 9)?

**Comment by ilovezfs** [comment]
@KenanY I know. I'm just being snarky because I _really_ want a node 9 compatible 5.5.2 release ASAP. Currently the Homebrew formula is stuck on node 8 because that doesn't exist yet.

**Comment by irejwanul** [comment]
npm uninstall npm -g
simply solved the issue and now npm version 5.5.1 and node v9.2.0 is working normal

**Comment by Frederick888** [comment]
`npm *uninstall* npm -g` to fix `npm`??? Join GitHub they said, it'll be fun they said.

(I did not really try it out, sorry if it does work but this appears to be a bit hilarious :laughing:)

**Comment by ilovezfs** [comment]
@Frederick888 node 9 is currently shipping a hacked version of npm because the standard upstream npm 5.5.1 doesn't work with node 9 yet. So uninstalling the broken standard version unhides the hacked, functional version.

**Comment by Frederick888** [comment]
@ilovezfs Well, running Arch Linux and installed `npm` manually instead of using the [repo](https://www.archlinux.org/packages/community/any/npm/) one. Just executed the command and `npm` was simply gone. `curl -L https://www.npmjs.com/install.sh | sh` got `npm` back for me but the issue still persists.

Hmm... I mean... hmm...

**Comment by ilovezfs** [comment]
@Frederick888 right. The hacked version would have to be included with Arch's node distribution. You can use npmc instead.

**Comment by bonesoul** [comment]
Why we don't see a fixed npm shipped already?

**Comment by kleinfreund** [comment]
Maybe it’s better to lock this and refer to https://github.com/npm/npm/issues/19019#issuecomment-341978497 in the meantime.

**Comment by bonesoul** [comment]
That's not a solution for people using NVM and so.

**Comment by rob** [comment]
Very weird there's not a fix released for this yet. Running OS X and nvm here with the same issue.

**Comment by Frederick888** [comment]
The ecosystem of package management in Node.js is so concise and robust that things like `npm install` installs hundreds of packages never happen. Hence the Node.js team believes we could just manually handle the dependencies without a package manager.

**Comment by aeroxy** [comment]
@duggum adding 9.0.0 to unsupported.js doesn't solve the issue. It just suppresses the WARN info. When running npm the runtime still emits error:

```
../src/node_zlib.cc:437:static void node::{anonymous}::ZCtx::Init(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args.Length() == 7 && "init(windowBits, level, memLevel, strategy, writeResult, writeCallback," " dictionary)"' failed.
 1: node::Abort() [npm]
 2: node::Assert(char const* const (*) [4]) [npm]
 3: 0x1255aff [npm]
 4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [npm]
 5: 0xb77f9c [npm]
 6: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [npm]
 7: 0x2cc17e1042fd
Aborted (core dumped)
```

**Comment by aeroxy** [comment]
@MohammadHasham @kleinfreund while using NVM, doing a `npm uninstall -g npm` will result at removing npm entirely, thus rendering the entire program useless. **Caution**.

**Comment by targos** [comment]
It's weird that you have this issue with nvm. I installed node 9.2.0 with `nvm install 9` and it works out of the box.

**Comment by aeroxy** [comment]
@targos clearly a lot of people have issue with NVM, a quick Google search can prove just that. When did you do the `nvm install 9` and what is your OS/version?

**Comment by ilovezfs** [comment]
@targos it's not weird at all. You're using the hacked version of npm from node. Not the stock npm that people are complaining about.

**Comment by targos** [comment]
@aeroxy A few days ago, on Linux (Fedora 26).
@ilovezfs That's the point. It works because nvm extracts the version of npm bundled in node, I think.

**Comment by ilovezfs** [comment]
@targos the hacked npm is only a fraction of the npm in use in the wild. These problems are going to persist until npm itself rolls a new release.

**Comment by targos** [comment]
Of course. I totally agree that npm should do a new release ASAP. But while we wait, it's good to understand why the alternatives don't work for everyone.

**Comment by eorroe** [comment]
@Frederick888 believe it or not @irejwanul solution actually worked!! `npm uninstall npm -g` it didn't even uninstall npm, but when I used it again no errors

Thanks @irejwanul

**Comment by aeroxy** [comment]
@eorroe again, while using NVM, doing a `npm uninstall -g npm` will result at removing npm entirely, thus rendering the entire program useless. **Caution!**

**Comment by thornjad** [comment]
@aeroxy on the contrary, I'm using nvm and `npm uninstall -g npm` fixed it for me too

**Comment by hg8** [comment]
Not sure why but `npm uninstall -g npm` was not enough for me. I also had to reinstall the `npm` package on my system (Arch Linux) to completley fix the issue.

    pacman -S npm

**Comment by eorroe** [comment]
@aeroxy you're probably right, I don't have nvm installed so no idea. But `npm uninstall -g npm` without nvm worked for me

**Comment by robcresswell** [comment]
Could we please get a new tag with node 9 support? Just landing a patch isn't enough. This is holding up homebrew, which is a sizeable install base for node + npm. Thanks!

**Comment by dnalborczyk** [comment]
wow, node v9.0 has been released almost a month ago. the ignorance of the npm folks speaks volumes, _specially_ after putting a lot of afford into catching up with _yarn_ and trying to regain user trust.

@ilovezfs is it possible to point the brew script to the node modified package?

**Comment by ilovezfs** [comment]
@dnalborczyk many workarounds are possible, but as you can see from this issue itself, they lead to chaos.

**Comment by robcresswell** [comment]
@dnalborczyk No need to insult them. Keep it civil and just ask for a tag.

**Comment by dnalborczyk** [comment]
@robcresswell you're joking, right?

**Comment by ilovezfs** [comment]
@dnalborczyk you should read, or re-read, the [Code of Conduct](https://www.npmjs.com/policies/conduct)

**Comment by dnalborczyk** [comment]
I don't really see how the above is an insult, just my personal opinion on that matter.

Not a single word or statement from npm regarding this issue, and I can give you guys plenty of references and cc's where people have _asked_ for almost a month now.

npm is backed by npm, Inc. - and I'm more referring to the corporate entity, than the open source project.

Unfortunately npm is pretty much baked into node, and users are not given a choice of alternatives, and so here we are ...

**Comment by robcresswell** [comment]
@dnalborczyk I'm not joking. I also don't think saying "it's my opinion" is a valid way of defending an insult. The team (who are humans, not corporate robots) are clearly overburdened (1000+ issues) so I'd assume there is more to the story than them just being "ignorant". Just request prioritisation politely and apply a workaround in the meantime. It's a little inconvenient, but that's life, especially when you're dealing with software that costs you no money or time.

**Comment by robertmain** [comment]
:+1: +1  on this issue

**Comment by zkat** [comment]
I spoke to @MylesBorins about this, but I'm literally cooking up the next release of npm _right now_. It'll go into `next` once that's done, and y'all _should_ wait a week to merge it into node, because we want to make sure there's no surprises, since it does involve some nontrivial refactorings and a couple new features. It should be ready for Node to consume by next Thursday (7 Dec).

**Comment by MylesBorins** [comment]
Thanks for the update and hard work @zkat!

**Comment by zkat** [comment]
https://twitter.com/maybekatz/status/935357840872554496 And it's out.

Please go ahead and try it out. We'll be watching for early warnings on breakage for the next week to make sure everything looks ok. Thanks y'all for your patience. It's been a hell of a couple of months for the team :s

**Comment by ilovezfs** [comment]
Thanks @zkat! You're awesome :)

**Comment by magiksd** [comment]
Hello, I'm stuck with npm 5.5.1 on Node.js 9.2.0, I can't update npm with "npm i -g npm" or "npm i -g npm@next", I'm getting this error :

```
$ npm i -g npm@next
npm WARN npm npm does not support Node.js v9.2.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8.
npm WARN npm You can find the latest version at https://nodejs.org/
WARNING: You are likely using a version of node-tar or npm that is incompatible with this version of Node.js.
Please use either the version of npm that is bundled with Node.js, or a version of npm (> 5.5.1 or < 5.4.0) or node-tar (> 4.0.1) that is compatible with Node.js 9 and above.
/usr/bin/node[23747]: ../src/node_zlib.cc:437:static void node::{anonymous}::ZCtx::Init(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args.Length() == 7 && "init(windowBits, level, memLevel, strategy, writeResult, writeCallback," " dictionary)"' failed.
 1: node::Abort() [npm]
 2: node::Assert(char const* const (*) [4]) [npm]
 3: 0x1255aff [npm]
 4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [npm]
 5: 0xb77f9c [npm]
 6: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [npm]
 7: 0x2d3e12842fd
Aborted
```

**Comment by magiksd** [comment]
Found a "solution" :
```
npm remove -g npm
apt-get install --reinstall nodejs
npm i -g npm@next
```

**Comment by ilovezfs** [comment]
`brew install --devel node` will now give you node 9.2.0 + npm 5.6.0

**Comment by Evanto** [comment]
I've started having this `npm does not support Node.js v9.2.0` issue along with:
```
eva@eva-CR70-2M-CX70-2OC-CX70-2OD:~/Develop/Netlify/pizza4$ ws --spa index.htmlServing at http://eva-CR70-2M-CX70-2OC-CX70-2OD:8050, http://127.0.0.1:8050, http://192.168.0.103:8050
12:09:20: Middleware error
Error: ENOENT: no such file or directory, stat '/home/eva/Develop/Netlify/pizza4/src/index.html'
```
Are they related? My project worked fine previously, so I'm guessing ENOENT err is not about code, is it some conflict in software or a result of incompatible node/npm versions?
Also I have `npm update check failed`.

I tried I think every solution offered in this thread, but can't get rid of `ENOENT` and  `npm update check failed`. 
Ubuntu 16.04.3 LTS
Nodejs v9.2.0
npm 5.6.0

**Comment by mutantkeyboard** [comment]
@Evanto try doing `npm install --no-optional`, and see what it returns.

**Comment by Evanto** [comment]
@mutantkeyboard 

```
eva@eva-CR70-2M-CX70-2OC-CX70-2OD:~/Develop/Netlify/pizza4$ sudo npm install --no-optional

npm WARN logo.pizza@2.0.0 No repository field.
npm WARN logo.pizza@2.0.0 No license field.
npm WARN The package gulp-jshint is included as both a dev and production dependency.
npm WARN The package gulp-uglify is included as both a dev and production dependency.
npm WARN The package jshint is included as both a dev and production dependency.

up to date in 1.122s
```

**Comment by cloakedninjas** [comment]
Downloaded the 9.2.0 package from the NodeJS homepage and have ended up here... So looks like this is still an issue?

**Comment by robcresswell** [comment]
@cloakedninjas Could you give some more information or open a new issue? Just commenting "me too" on a closed bug is not terribly helpful :)

**Comment by cloakedninjas** [comment]
Unfortunately I didn't keep my shell output, but after some digging around node-gyp, it looks like my specific issue was related to deps of deps. Specifically webpack and fsevents, bumping to latest webpack release allowed me to install without issue.

**Comment by thornjad** [comment]
Node 9.2.1 + npm 5.6.0 using nvm seems to be all back to normal!

**Comment by zkat** [comment]
`npm@5.6.0` became `latest` yesterday. I'm locking this now.
