### ISSUE TITLE
Error with .\node_modules\ionic-angular\package.json file: FILE_NOT_FOUND

### ISSUE THREAD

**Issue by hamendrasingh200** [npm/npm#19499]
#### I'm opening this issue because:
i have recover node modules of my ionic 3 project by this command  'npm i @ionic/app-scripts' .and now  I got one error when I run 'ionic Cordova build android --prod' 
   
    Error: ENOENT: no such file or directory, open 'F:\Ionic-Test_project\pulakiosk_node_modules\pulakiosk\node_modules\@angular\core\package.json'
    at Error (native)
[ERROR] Error with .\node_modules\ionic-angular\package.json file: FILE_NOT_FOUND

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

### supporting information:

 - `npm -v` prints:
 - `node -v` prints:
 - `npm config get registry` prints:
 - Windows, OS X/macOS, or Linux?:
 - Network issues:
   - Geographic location where npm was run:
   - [ ] I use a proxy to connect to the npm registry.
   - [ ] I use a proxy to connect to the web.
   - [ ] I use a proxy when downloading Git repos.
   - [ ] I access the npm registry via a VPN
   - [ ] I don't use a proxy, but have limited or unreliable internet access.
 - Container:
   - [ ] I develop using Vagrant on Windows.
   - [ ] I develop using Vagrant on OS X or Linux.
   - [ ] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS (Triton, Heroku).

**Comment by dhruv4** [comment]
I'm having this issue too. And, when I try to run `ionic serve`, I get a laundry list of errors along the lines of `Cannot find name 'Observable'` and `Cannot find name 'NgControl'` in `ionic-angular`.

**Comment by mumairofficial** [comment]
I found this issue while generating the project with Ionic CLI by the way after updating it to latest one `npm i -g ionic@latest` error went away.

In your case try to install ionic-angular by `npm install --save ionic-angular` possibly would help

**Comment by faisal3389** [comment]
@hamendrasingh200 any update on this, were you able to solve this issue?

**Comment by mumairofficial** [comment]
@faisal3389 Upgrade to latest Ionic CLI this problem is actually resolved.

**Comment by mumairofficial** [comment]
@faisal3389 This problem is actually resolved... If you are facing this problem with **Ionic CLI** then upgrade it to latest one.
`npm i -g ionic@latest`

**Comment by faisal3389** [comment]
yes, that is resolved with 
```
npm i -g ionic@latest
```
thanks @mumairofficial

**Comment by peterson-umoke** [comment]
i have updated my ionic to the latest and it still the same thing.... what is the quick fix just in case?

**Comment by larsonapplicationsdev** [comment]
I'm having the same issue as @peterson-umoke

**Comment by ferd-i** [comment]
same here

**Comment by jocelino** [comment]
same here too
