### ISSUE TITLE
Valid package version cannot be installed

### ISSUE THREAD

**Issue by jamesplease** [npm/npm#19534]
### This issue has been resolved. [See this comment if you're still having problems.](https://github.com/npm/npm/issues/19534#issuecomment-356178939).

---

### Official status on this issue can be seen here:

https://status.npmjs.org/incidents/41zfb8qpvrdj

-----

#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [x] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

A dependency on `require-from-string@^1.1.0` causes npm to error:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for require-from-string@^1.1.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'require-from-string-test'
npm ERR! notarget
```

However, `npm info require-from-string` lists 1.1.0 as a valid version:

```js
{ name: 'require-from-string',
  time:
   { modified: '2018-01-06T18:57:39.402Z',
     created: '2015-07-18T15:08:53.362Z',
     '1.0.0': '2015-07-18T15:08:53.362Z',
     '1.0.1': '2015-11-03T08:09:49.990Z',
     '1.0.2': '2015-11-06T19:08:43.545Z',
     '1.1.0': '2015-11-07T11:43:15.008Z',
     '1.2.0': '2016-05-03T07:32:12.394Z',
     '1.2.1': '2016-10-01T19:32:05.278Z',
     '2.0.0': '2017-09-16T07:04:34.217Z',
     '2.0.1': '2017-09-17T06:52:37.555Z',
     '2.0.2': '2018-01-06T18:57:39.402Z' }
}
```

#### How can the CLI team reproduce the problem?

Create a new project. Try to run `npm i require-from-string@^1.0.0`

~~**This appears to be caused by publishing new versions in 2018**. Versions from before 2018 are inaccessible once a new version is published in 2018.~~

Nevermind. This appears to just be floatdrop's packages have disappeared.

### supporting information:

 - `npm -v` prints: 5.6.0
 - `node -v` prints: v8.9.1
 - `npm config get registry` prints: https://registry.npmjs.org/
 - Windows, OS X/macOS, or Linux?: macOS

**Comment by karllhughes** [comment]
Also seeing this for `timed-out` and `duplexer3`.

I think something is happening to npmjs.com right now.

**Comment by robbiethegeek** [comment]
Yup running a NodeSchool event at the moment and people who didn't have javascripting or learnyounode installed can't move forward

**Comment by jamesplease** [comment]
One trend I'm seeing is that it may have to do with packages that have releases from _before_ 2018 as well as releases _after_ 2018. Releasing a new version in 2018 may be breaking pre-2018 releases.

**Comment by JAertgeerts** [comment]
https://github.com/npm/registry/issues/255

**Comment by louisiscoding** [comment]
Okay ! Glad i'm not the only one having this issue.
Tried to install gatsby-cli.
I've had problem with `duplexer3` and now `timed-out`

**Comment by mdw233** [comment]
It seems like the author of all these packages - __floatdrop__ - deleted his/her account.

**Comment by Windrushfarer** [comment]
floatdrop's github account exists and he has twitter too, maybe somebody will tweet about this errors

**Comment by fernandes** [comment]
@mdw233 at least can be accessed https://www.npmjs.com/~floatdrop //cc @floatdrop

**Comment by ashleygwilliams** [comment]
this is an ongoing incident. the team is working on it. sorry to all https://status.npmjs.org/incidents/41zfb8qpvrdj

**Comment by fernandes** [comment]
thank you for clarifying @ashleygwilliams

**Comment by yianni-ververis** [comment]
yarn gives you the option of choosing 
Please choose a version of "require-from-string" from this list: 2.0.2

you need to update your package

**Comment by Vitorspk** [comment]
Thank you for explam @ashleygwilliams 

Follow my error, i try to npm install a vuejs project.

npm ERR! code ETARGET
npm ERR! notarget No matching version found for require-from-string@^1.1.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'cosmiconfig'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:

**Comment by Vitorspk** [comment]
Good new Poeple,

Most of the deleted packages have been restored and installation of those packages should succeed. Nine packages are still in the process of restoration.

**Comment by w3kp** [comment]
@yianni-ververis Skeptical on installing that version. Might be a package takeover or not? not sure tho.

**Comment by bbottema** [comment]
require-from-string@^1.1.0 still missing, breaking my builds

**Comment by siggirh** [comment]
It seems like require-from-string original maintainer deleted his stuff?

**Comment by patrickoliveras** [comment]
Get in here https://github.com/npm/registry/issues/255 
There is where all the fun is at.

**Comment by Mauriciom77** [comment]
someone knows when will be normal to use NPM INSTALL? 

I'm with this problema too.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: pinkie-promise@^2.0.0 (node_modules\read-pkg-up\node_modules\find-up\node_modules\pinkie-promise):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: No valid versions available for pinkie-promise

npm ERR! code ETARGET
npm ERR! notarget No matching version found for require-from-string@^1.1.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'cosmiconfig'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mau77\AppData\Roaming\npm-cache\_logs\2018-01-06T20_24_55_375Z-debug.log

**Comment by jamesplease** [comment]
See status updates here @mauriciom77 : https://status.npmjs.org

**Comment by bbottema** [comment]
> **patrickoliveras** commented **5 minutes** ago
> Get in here [npm/registry#255](https://github.com/npm/registry/issues/255)
>There is where all the fun is at.
--

Hmm, #17379 is also about losing (https+github) packages on subsequent installs. NPM is having a good day!

**Comment by Amine-H** [comment]
require-from-string is breaking my build

```
Couldn't find any versions for "require-from-string" that matches "^1.1.0"
? Please choose a version of "require-from-string" from this list: (Use arrow keys)
error Received malformed response from registry for "pinkie-promise". The registry may be down.

```

**Comment by shivali04** [comment]
having the same error. Can anyboy help.? I tried installing require-from-string as a diffrent dependency but still getting same error

D:\>npm install -g @angular/cli
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: pinkie-promise@^2.0.0 (node_modules\@angular\cli\node_modules\read-pkg-up\node_modules\find-up\node_modules\pinkie-promise):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: No valid versions available for pinkie-promise
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: pinkie-promise@^2.0.0 (node_modules\@angular\cli\node_modules\load-json-file\node_modules\pinkie-promise):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: No valid versions available for pinkie-promise

npm ERR! code ETARGET
npm ERR! notarget No matching version found for require-from-string@^1.1.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'cosmiconfig'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Shivali\AppData\Roaming\npm-cache\_logs\2018-01-06T20_37_46_265Z-debug.log

**Comment by jamesplease** [comment]
@shivali04 , npm is working on fixing the problem. Once they've fixed it, your install will work again. It may take some time for it to be fixed, though. I linked to the npm status page above. Once it's fixed, the status page will be updated.

**Comment by Mauriciom77** [comment]
I tryed here and is back... :)

**Comment by bbottema** [comment]
require-from-string still unavailable for me in NL

**Comment by softcoder** [comment]
Basically everyone using angular-cli is broken till the string dep comes back: No matching version found for require-from-string@^1.1.0

**Comment by matthiaw** [comment]
Yep, "npm install" and "create-react-app" are not working in 2018. Still looking for a solution and found this posts. Glad you are working on it. I use Ubuntu 17.10 and atom-editor. Console shows with "create-react-app"
```
warning ../package.json: No license field
info No lockfile found.
[1/4] Resolving packages...
Couldn't find any versions for "require-from-string" that matches "^1.1.0"
? Please choose a version of "require-from-string" from this list: (Use arrow keys)
❯ 2.0.2
```
and crashes with
```
error Received malformed response from registry for "pinkie-promise". The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Aborting installation.
  yarnpkg add --exact react react-dom react-scripts --cwd /home/matthias/workspace/test has failed.
Deleting generated file... package.json
```
because i use yarn.

**Comment by LukePeters** [comment]
Same issue for me when trying to npm install some Vue.js stuff.

> No matching version found for require-from-string@^1.1.0

**Comment by wlnaim** [comment]
Cannot install ionic with **sudo npm install ionic cordova -g**
the error is:

npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for pinkie-promise

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/macbook1/.npm/_logs/2018-01-06T20_57_38_170Z-debug.log

**Comment by HackAfro** [comment]
Same error here in an express app. This is breaking my deployment builds. Hope this is resolved soon

**Comment by kelvinwatson** [comment]
trying to install web3 and getting `No valid versions available for pinkie-promise`

**Comment by jsperezg** [comment]
Same issue here. pinkie-promise seems that has dissapeared.

**Comment by ljharb** [comment]
again, see https://status.npmjs.org/incidents/41zfb8qpvrdj

**Comment by mehranabi** [comment]
Hello, I have similar issue:

```
C:\Users\Mehran\Desktop>create-react-app my-app

Creating a new React app in C:\Users\Mehran\Desktop\my-app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts...

yarn add v1.3.2
info No lockfile found.
[1/4] Resolving packages...
Couldn't find any versions for "require-from-string" that matches "^1.1.0"
? Please choose a version of "require-from-string" from this list: 2.0.2
error Received malformed response from registry for "pinkie-promise". The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Aborting installation.
  yarnpkg add --exact react react-dom react-scripts --cwd C:\Users\Mehran\Desktop\my-app has failed.

Deleting generated file... package.json
Deleting my-app / from C:\Users\Mehran\Desktop
Done.
```

I create a React app with `create-react-app` command some hours ago but now, it's not working!

**Comment by softcoder** [comment]
Ok lets make this the last post in this thread the status page as previously mentioned is here, no need to waste more disk space:

again, see https://status.npmjs.org/incidents/41zfb8qpvrdj

**Comment by danielfnz** [comment]
It's explained!

**Comment by sfate** [comment]
Resolved ❤️
https://github.com/npm/registry/issues/255#issuecomment-355780293

**Comment by jmeas** [comment]
This issue is not completely resolved. As the comment explains, several packages are still being restored, so builds may still fail.

**Comment by jamesplease** [comment]
Closing as resolved. Thanks npm team! :v:

**Comment by aManso** [comment]
It seems to be solved for me :-)

**Comment by danielfnz** [comment]
Thank  for solving it!

**Comment by remram44** [comment]
Once again the ability to delete packages from NPM is causing issue. Why is this option offered to users at all? Why not a "yank" feature that hides it but doesn't break people's builds, like crates.io?

Surely not breaking people's builds is still a goal of NPM Inc?
 
Having the NPM team manually go in and restore deleted packages cannot be the normal way of operating this registry...

**Comment by jamesplease** [comment]
> Once again the ability to delete packages from NPM is causing issue. Why is this option offered to users at all?

It is not. See the [unpublish docs](https://docs.npmjs.com/cli/unpublish) for restrictions around unpublishing.

**Comment by remram44** [comment]
> Even if a package version is unpublished, that specific name and version combination can never be reused

> With the default registry (registry.npmjs.org), unpublish is only allowed with versions published in the last 24 hours

That does seem sensible yeah. Hurray!

I take it there is also no way to remove a package completely from the website, or that the same restrictions apply?

**Comment by jamesplease** [comment]
That is correct afaik

**Comment by amakm** [comment]
Is this issue resolved for all? I'm getting the same error now.
But there is no active incident in [https://status.npmjs.org/](url)
Am I missing something here? Can someone advice?

`npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: require-from-string@1.1.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 2.0.2`

**Comment by yianni-ververis** [comment]
Mine is fine with node 9.3.0

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jamesplease** [comment]
> Is this issue resolved for all? I'm getting the same error now.
> But there is no active incident in https://status.npmjs.org/
> Am I missing something here? Can someone advice?
> 
> `npm ERR! node v7.3.0
> npm ERR! npm v3.10.10
> npm ERR! code ETARGET
> 
> npm ERR! notarget No compatible version found: require-from-string@1.1.0
> npm ERR! notarget Valid install targets:
> npm ERR! notarget 2.0.2`

Paste the output from `npm get registry`?

**Comment by hzhisc** [comment]
Same issue is still 100% reproducible for me in a local project created with https://github.com/facebookincubator/create-react-app. 

Steps to reproduce: 
1. delete node_modules folder and package-lock.json; 
2. run 'npm install'

As here the issue is marked as "resolved" on the npm incident status page https://status.npmjs.org/incidents/41zfb8qpvrdj, is there any one who faced the same on create-react-app but had it fixed?

**Comment by sfate** [comment]
@hzhisc @amakm 
Seems like cached registry, can you please clean the cache `npm cache clean --force` and then try again?

**Comment by hzhisc** [comment]
@sfate thank you for checking, I just tried cleaning npm cache and then rerun npm install, but no luck.

**Comment by jamesplease** [comment]
@hzhisc what registry are you using? Paste the output from `npm get registry`?

**Comment by hzhisc** [comment]
Thank you for the hint @jmeas , I was using a private registry which caused this issue. After switching to combination of official public registry and scoped private registry, I am now able to make it working.

**Comment by jamesplease** [comment]
# Future visitors: read this

### Are you still having this problem?

Type `npm get registry`. What do you see? If it's not `https://registry.npmjs.org/`, then you are using a private registry. Chances are your registry is still broken, and you need to manually fix it.

To verify, you can use the public registry to see if you still run into the same issue.

### I am on the public registry

This is likely a different issue that you are running into, because **the problem that this issue was created for has been resolved**. I encourage you to open a new GitHub issue.
