### ISSUE TITLE
npx bundled with npm always showing error on Windows 10

### ISSUE THREAD

**Issue by TotallyInformation** [npm/npm#20580]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [x] npm is producing incorrect or undesirable behavior.
  - [ ] Other (_see below for feature requests_):

#### What's going wrong?

Running npx on Windows 10 always produces the following error/warning:

```
λ  npx --version
npx: installed 1 in 3.33s
Path must be a string. Received undefined
9.7.1
``` 

#### How can the CLI team reproduce the problem?

Issue _any_ npx command.

### supporting information:

 - `npm -v` prints: **5.6.0**
 - `node -v` prints:  **v8.11.1**
 - `npm config get registry` prints: **https://registry.npmjs.org/**
 - Windows, OS X/macOS, or Linux?: **Windows 10 1709**

This is a straight install of the latest Node.JS v8.

Note that my user folder name does **not** contain a space.

**Comment by saschanaz** [comment]
See also https://github.com/npm/npm/issues/20580

**Comment by saschanaz** [comment]
See also https://github.com/zkat/npx/issues/144

**Comment by FranklinYu** [comment]
Note that this is fixed in latest NPM. Not just Windows 10, all versions of Windows have this issue.

**Comment by saschanaz** [comment]
>Note that this is fixed in latest NPM.

6.1.0 is the latest, right? I'm still seeing this issue on that version.

**Comment by FranklinYu** [comment]
@saschanaz 

```text
PS > C:\Users\franklinyu\AppData\Roaming\npm\npx.cmd -v
6.0.1
```

No issue for 6.0.1. Note that full path is required.

**Comment by saschanaz** [comment]
>Note that full path is required.

Yes, and that's the problem. Node does not use the latest npx by default.

**Comment by saschanaz** [comment]
Also see zkat/npx#193 and https://github.com/nodejs/node/issues/21001#issuecomment-392694032.

**Comment by saschanaz** [comment]
I found that Node.js 10.4.0 fixed this issue, although now `npx --version` incorrectly shows npm version instead of npx one.
