### ISSUE TITLE
Can't install NPM packages(Cloudflare)

### ISSUE THREAD

**Issue by thibaultmeyer** [npm/npm#20802]
#### I'm opening this issue because:

  - [ ] npm is crashing.
  - [ ] npm is producing an incorrect install.
  - [ ] npm is doing something I don't understand.
  - [ ] npm is producing incorrect or undesirable behavior.
  - [x] Other (_see below for feature requests_):

#### What's going wrong?
Can't install NPM packages cause Cloudflare bullshit. Continuous integrations for all our projects are now broken.

```
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! Linux 4.14.11-coreos
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "--loglevel=error" "--progress=false" "install" "chakram" "mocha" "expect"
npm ERR! node v6.14.2
npm ERR! npm  v3.10.10
npm ERR! Unexpected token < in JSON at position 0
npm ERR! <!DOCTYPE html>
npm ERR! <!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
npm ERR! <!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
npm ERR! <!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
npm ERR! <!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
npm ERR! <head>
npm ERR! <title>Access denied | packages.npmjs.org used Cloudflare to restrict access</title>
npm ERR! <meta charset="UTF-8" />
npm ERR! <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
npm ERR! <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
npm ERR! <meta name="robots" content="noindex, nofollow" />
npm ERR! <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
npm ERR! <link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />
npm ERR! <!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/css" media="screen,projection" /><![endif]-->
npm ERR! <style type="text/css">body{margin:0;padding:0}</style>
npm ERR! 
npm ERR! 
npm ERR! <!--[if gte IE 10]><!--><script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script><!--<![endif]-->
npm ERR! <!--[if gte IE 10]><!--><script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script><!--<![endif]-->
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! </head>
npm ERR! <body>
npm ERR!   <div id="cf-wrapper">
npm ERR!     <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
npm ERR!     <div id="cf-error-details" class="cf-error-details-wrapper">
npm ERR!       <div class="cf-wrapper cf-header cf-error-overview">
npm ERR!         <h1>
npm ERR!           <span class="cf-error-type" data-translate="error">Error</span>
npm ERR!           <span class="cf-error-code">1015</span>
npm ERR!           <small class="heading-ray-id">Ray ID: 4228fbe947e59f4e &bull; 2018-05-29 12:32:29 UTC</small>
npm ERR!         </h1>
npm ERR!         <h2 class="cf-subheadline">You are being rate limited</h2>
npm ERR!       </div><!-- /.header -->
npm ERR! 
npm ERR!       <section></section><!-- spacer -->
npm ERR! 
npm ERR!       <div class="cf-section cf-wrapper">
npm ERR!         <div class="cf-columns two">
npm ERR!           <div class="cf-column">
npm ERR!             <h2 data-translate="what_happened">What happened?</h2>
npm ERR!             <p>The owner of this website (packages.npmjs.org) has banned you temporarily from accessing this website.</p>
npm ERR!           </div>
npm ERR! 
npm ERR!           
npm ERR!         </div>
npm ERR!       </div><!-- /.section -->
npm ERR! 
npm ERR!       <div class="cf-error-footer cf-wrapper">
npm ERR!   <p>
npm ERR!     <span class="cf-footer-item">Cloudflare Ray ID: <strong>4228fbe947e59f4e</strong></span>
npm ERR!     <span class="cf-footer-separator">&bull;</span>
npm ERR!     <span class="cf-footer-item"><span>Your IP</span>: 34.236.25.177</span>
npm ERR!     <span class="cf-footer-separator">&bull;</span>
npm ERR!     <span class="cf-footer-item"><span>Performance &amp; security by</span> <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>
npm ERR!     
npm ERR!   </p>
npm ERR! </div><!-- /.error-footer -->
npm ERR! 
npm ERR! 
npm ERR!     </div><!-- /#cf-error-details -->
npm ERR!   </div><!-- /#cf-wrapper -->
npm ERR! 
npm ERR!   <script type="text/javascript">
npm ERR!   window._cf_translation = {};
npm ERR!   
npm ERR!   
npm ERR! </script>
npm ERR! 
npm ERR! </body>
npm ERR! </html>
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /opt/atlassian/pipelines/agent/build/npm-debug.log
```

**Comment by varunmehra03** [comment]
Looks like related to https://github.com/npm/npm/issues/20798

**Comment by jasonsemko** [comment]
Same thing on AWS code build for me

**Comment by bosbaber** [comment]
Same thing from bitbucket pipelines. Please help.

**Comment by matt-filion** [comment]
Pipelines again here.

**Comment by ravialgo** [comment]
Same issue facing from bitbucket pipelines. any solution?

**Comment by tomLadder** [comment]
having the same issue from bitbucket pipelines...

**Comment by ubaidazad** [comment]
same issue with bitbucket pipelines 

bitbucket has mentioned that they are using shared service and a set of IP addresses, may be that is the problem.

https://confluence.atlassian.com/bitbucket/what-are-the-bitbucket-cloud-ip-addresses-i-should-use-to-configure-my-corporate-firewall-343343385.html
_You can use these IP ranges to whitelist requests made from your build environments. Note that Bitbucket Pipelines is a shared service and the IP addresses below are used for builds configured by all of our customers_

**Comment by SamanthaAdrichem** [comment]
Same here from bitbucket pipelines!

**Comment by boodera** [comment]
Same issue with bitbucket pipelines

**Comment by stm-dschulz** [comment]
Same issue with bitbucket pipelines

**Comment by stm-dschulz** [comment]
Can someone from NPM jump in here? This is really a serious issue for us as this breaks all the CI based on bitbucket pipelines. I also file a bitbucket support case and got the answer that NPM has to raise there limits for bitbucket pipelines requests.

thx
daniel

**Comment by si-harps** [comment]
Another Bitbucket Pipelines fail, please assist

**Comment by Sushil231088** [comment]
We are facing the same issue.

**Comment by stm-dschulz** [comment]
#20816

**Comment by FarooqAR** [comment]
Same problem while installing firebase-tools on bitbucket pipelines

**Comment by SANTOSHKVNSP** [comment]
Same issue with bitbucket pipelines

**Comment by ubaidazad** [comment]
https://github.com/npm/registry/issues/334#issuecomment-393121957

https://status.bitbucket.org/?_ga=2.20995326.497816218.1527647425-770271235.1522817183

**Comment by marciomsm** [comment]
Issue solved to bitbucket...
https://status.bitbucket.org/

**Comment by thibaultmeyer** [comment]
Still broken (bitbucket pipelines) !

Seriously, why Cloudflare? this is the worst decision ever made by npm owners. Of course you can use it as netscaler, but disable stupid IP based """"protection""""

**Comment by boodera** [comment]
The issue has been resolved. Pipelines are working fine, as for now!

**Comment by thibaultmeyer** [comment]
Still not working... The error page has disapear, but now, installing a simple package take infinite time (waited 90 minutes and nothing happen)... This is not acceptable, especially when we pay the continuous integration to the consummated time or we have to publish quick fix on production...

**Comment by zkat** [comment]
This is a registry issue, and was marked as resolved by bitbucket: https://bitbucket.org/site/master/issues/16373/bitbucket-pipelines-banned-from.

Please post over there if you're still seeing this, since it involves bitbucket getting in touch with our registry folks, and it's not a CLI issue.
