### ISSUE TITLE
npm runs postinstall script before dependencies are loaded

### ISSUE THREAD

**Issue by fresheneesz** [npm/npm#4134]
I gave some information in here: https://github.com/isaacs/npm/issues/4096 but basically, I'm getting majorly bizarre issues when installing `build-modules`. It looks to me like the postinstall script of one of its dependencies is being run too early. If that's true, its a huge problem.

**Comment by smikes** [comment]
Is this still a problem for you?

Some of the raciness of `npm install` may have been mitigated by solving race conditions around caching, and installation; coupled with the `inflight` module which allows callbacks to be added to in-process installations, this seems to have been improved.

Unfortunately I cannot build `deadunit@2.0.7` because it throws errors that appear to be unrelated to this problem:
```
 
> proto@1.0.8 postinstall /Users/smikes/src/github/baz/node_modules/deadunit/node_modules/proto
> node build.js

building and minifying...
done
/
> stackinfo@1.0.0 postinstall /Users/smikes/src/github/baz/node_modules/deadunit/node_modules/deadunit-core/node_modules/stackinfo
> node build.js

building and minifying...
Error: bundle() no longer accepts option arguments.
Move all option arguments to the browserify() constructor.
```

`deadunit@latest` is 5.1.7, which installs with no apparent problems.

If you still believe this bug is present in `npm`, please let us know.  Probably the upcoming `multi-stage-install` milestone will include a fix for it -- that is the eventual completion of the "lot of work" referred to above.

/cc @iarna as possibly multi-stage-install related

**Comment by fresheneesz** [comment]
I've worked around this issue by not ever using postinstall in my packages anymore. So I have had no opportunity to run across this bug anytime recently.

**Comment by ralphtheninja** [comment]
@fresheneesz You don't need to commit generated files. This is why you should use `prepublish` hook instead as @domenic said. You just do the same thing in your `prepublish` script as you would in `postinstall`. The only difference is that you are running the code before publishing it, as opposed to the user running it after the module as been installed.

**Comment by fresheneesz** [comment]
@ralphtheninja How could I build generated files if I can't be sure the dependencies of those generated files are loaded when i try to generate them?

**Comment by lennym** [comment]
@smikes I've been able to replicate this bug in certain environments with npm running assorted versions (latest confirmed is 2.7.6) by adding https://github.com/lennym/test-project-2 as a dependency.

I understand "don't use postinstall, use prepublish" as a solution, but it's not a particularly viable solution if you don't actually publish modules to npm. We have a number of modules which we install from git repos, which I would like to be able to compile certain assets postinstall so I don't have to check compiled code into source control. Is there a similar solution for this instance?

**Comment by fresheneesz** [comment]
@lennym If you're not publishing what you're building, you could build a script that you run in place of npm install, which calls npm install as a child process and then runs whatever stuff you wanted to do in postinstall.

**Comment by joshuajabbour** [comment]
I agree with @lennym, the "don't use postinstall, use prepublish" is not a solution. They are plenty of use-cases where a package might not be published (private packages, in-development packages).

Maybe if the lifecycle was altered to run `prepublish` on the user system if the module wasn't installed from the npm registry? I dunno, but this is annoying, and crops up constantly for me.

**Comment by amb26** [comment]
@domenic re "we are trying to kill postinstall" - why would you do this if npm has so enthusiastically recommended it? http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging

**Comment by ehsalazar** [comment]
This has been addressed in `npm@3`. Postinstall scripts are now guaranteed to run after postinstall (and previous stages) have run for all of its dependencies. (Except, obviously, in the case of cycles.) If you run into issues after [updating](https://github.com/npm/npm/wiki/Troubleshooting#try-the-latest-stable-version-of-npm), please let is know.

**Comment by maxrimue** [comment]
@ehsalazar Hello, I think this problem is still occurring to me. I have a repo with a `postinstall` script that gets executed when I run `npm i -g` in the repo's folder, but fails, telling me the dependency used by the script (properly declared in `package.json`) is unavailable. Note that if I install the dependencies locally in the folder and then run the `postinstall` script manually, it works. Here's the output when trying to install the repo on my Windows 10 machine (this also occurred on the latest Linux Mint, both using the latest npm and Node.js):

```shell
C:\Users\Max\Documents\GitHub\packe>npm i -g
C:\Users\Max\AppData\Roaming\npm\packe -> C:\Users\Max\AppData\Roaming\npm\node_modules\packe\lib\run.js

> packe@1.0.0 postinstall C:\Users\Max\AppData\Roaming\npm\node_modules\packe
> node lib/build.js force

module.js:329
    throw err;
    ^

Error: Cannot find module 'electron-packager'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (C:\Users\Max\AppData\Roaming\npm\node_modules\packe\lib\build.js:1:16)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function.Module.runMain (module.js:431:10)
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! packe@1.0.0 postinstall: `node lib/build.js force`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the packe@1.0.0 postinstall script 'node lib/build.js force'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the packe package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/build.js force
npm ERR! You can get their info via:
npm ERR!     npm owner ls packe
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Max\Documents\GitHub\packe\npm-debug.log

C:\Users\Max\Documents\GitHub\packe>
```

You can try to reproduce this by cloning my repository [packe](https://github.com/maxrimue/packe) and running `npm i -g` in the clone's folder. Thanks.
