### ISSUE TITLE
Install fails to unpack tarball

### ISSUE THREAD

**Issue by wheresrhys** [npm/npm#5273]
The situation is I'm using npm to install a branch of a repo. The repo is on stash, which uses crazy long urls for its branch/tag/ref tarballs, so I don't think the `git+http` protocol will work and I'm forced to use a tarball url. When manually retrieved this tarball has the expected content. Installing using `npm install responsive-ft-grunt={the url}` in the cli doesn't work either

[files & debug info](https://gist.github.com/wheresrhys/35b6a66b29c00faa0a77)

**Comment by smikes** [comment]
Thanks for the bug report, @daxogg.  Have you tried to reproduce this with `npm@2.2.0` (currently the "latest" version).

I am getting a `403` when I try to download the tar link you provide above - could you please make sure that the permissions are set so I can download it?

Thanks!

**Comment by daxxog** [comment]
I deleted the download link as this problem should be fixed with the latest version.

See PR #6874

**Comment by smikes** [comment]
Ah, okay, I remember the pull request coming through now that you mention it.  OK, then I will ask @wheresrhys and @gpempro -

Is this still a problem for you when you update to the latest version of `npm`, `2.2.0`?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by wheresrhys** [comment]
I'm on npm 2.x (not sure of exact version as not on my work machine right now) and it was still happening very recently. Can you reproduce if you use a proxy to install a github tarball via a different url?

**Comment by smikes** [comment]
This fix landed in 2.1.13, December 16th 2014, so quite recently.

When I test with `npm@2.3.0`, using a tar file, I do not see the error anymore.

**Comment by othiym23** [comment]
Closing as resolved.

**Comment by jcollum** [comment]
I'm seeing this exact same behavior in 2.7.4 

```
$ ll /var/folders/8f/_69wtqh94zd0g2h4jrh_vd991s8s7l/T/npm-22273-1d807825/unpack-08d5ed23bd94/
total 168
-rw-r--r--  1 collumj  DS\Domain Users    83K Jul 29 14:46 index.js

$ npm --version
2.7.4
```

83K, one file. 

Vote to re-open.

**Comment by jcollum** [comment]
I'll put in a new issue and reference this one.
