### ISSUE TITLE
npm link doesn't play nice with peer dependencies

### ISSUE THREAD

**Issue by aldendaniels** [npm/npm#5875]
It's a simple use case:
 1. Break out shared helpers in a multi-project codebase
 2. Include helpers using `npm link`
 3. Helpers use [Peer Dependencies](http://blog.nodejs.org/2013/02/07/peer-dependencies/) (in my case because some helpers are also required via browserify, where it's important not to duplicate dependencies)

The gotcha is that when a library is included using `npm link`, npm doesn't appear to treat the linked directory as a child of the parent project, so peer dependencies aren't resolved.

@jaredhanson created [this small library](https://github.com/jaredhanson/node-parent-require) to work around precisely this issue.

Unless I'm missing something, npm's behavior in this scenario is non-ideal. Linked dependencies should be treated as if they are children (e.g. in the `node_modules` directory) of the project that includes them.

Thoughts?

**Comment by seeden** [comment]
+1 Any update?

**Comment by yoavniran** [comment]
ran into this issue now with a helper im writing (used with npm link) not working because it cant require the dependency from the parent. 
Would love to get an update on whether this will be fixed anytime soon.

**Comment by ssbb** [comment]
+1 any update?

**Comment by Dakuan** [comment]
+1

**Comment by francoislaberge** [comment]
+1

**Comment by mciparelli** [comment]
+1. This would be nice to have!

**Comment by henrikhaugboelle** [comment]
+1

**Comment by barneycarroll** [comment]
> Browserify correctly handles linked modules, so I only need this hack for node

@aldendaniels I haven't found that to be the case at all. Hours of head-scratching have finally led me to understand that my browser is loading 2 instances of framework X, whose singular runtime is essential for my application to work with the plugin I'm attempting to debug. Any magic at all involved in your Browserify solution?

**Comment by doctariouz** [comment]
+1

**Comment by aldendaniels** [comment]
@barneycarroll - sorry for the delayed reply. No, no magic that I remember. I'm now using NPM private modules instead of the structure described in this issue, so this is no longer affecting me.

The issue that I encountered when I opened this was independent from the module duplication problem (which gets better in NPMv3, BTW). The issue was that NPM would climb the directory from a linked module when resolving peerDependencies instead looking up via the symlink.

I don't know whether or not this behavior still exists today.

**Comment by francoislaberge** [comment]
Yeah, hopefully this becomes less of an issue as it becomes easier to dedupe a module in v3:
http://www.infoq.com/news/2015/06/npm

**Comment by donabrams** [comment]
Oi, the normal workaround doesn't work with use of `require('babel-core/register')` Why does `npm link $LIB` install peer dependencies instead of walking the tree? If it's too late to change can we at least add a flag `--no-peer` to npm link?

**Comment by donabrams** [comment]
Actually this is fixed in npm3, no need to worry.

**Comment by vjpr** [comment]
I'm having this problem too. It seems a simple fix would be to walk up the dir structure from the symlink.

E.g.
```
cd ~/dev/foo
npm link ~/dev/bar
ls -al ~/dev/foo/node_modules
bar -> ~/dev/bar
```

If we look at `require.cache['~/dev/bar'].paths` it would be:

```
['~/dev/bar/node_modules', '~/dev/node_modules', '~/node_modules', '/Users/node_modules', '/node_modules']
```

Alternatively, you could create a directory such as `~/dev/foo/local_modules/bar`, and `npm link ./local_modules/bar`, which would cause `~/dev/foo/node_modules` to be one of the stops in the require search path walk.

The downside is you cannot share this library with multiple projects easily - you would have to run `npm link` each time, and `npm link` is designed to be shared globally.

**Comment by louy** [comment]
I had the same issue while working with a framework that used React. I ended up with two versions of react which gave me very weird errors.

I worked around this issue by adding a file within that framework called `react.js` which is basically the following:

    module.exports = require('react');

and in my application, I required that file instead of the original `react`.

Of course, this is an inconvenient workaround; there was a bug that I wanted to fix and I only had this option.

**Comment by iarna** [comment]
So the work around for this in npm@2 would be to directly depend on the various peerDependencies. In npm@3, peerDependencies never trigger installs, so what was a work around in npm@2 is now mandatory behavior for npm@3.

As I don't believe this issue makes sense any more in the context of npm@3, I'm going to close it, but if you feel otherwise or have some other related problem, please don't hesitate to open a new issue.

**Comment by VanCoding** [comment]
Hi guys, Im on npm 3.3.3 and node 4.1.1 and still have problems with this!

I'm working on 2 packages simultaneously: "app" and "plugin". "app" depends on "plugin" and "express" and "plugin" peer depends on "express".

Since it's impossible to place "plugin" into the node_modules directory of "app", I've done `npm link` in "plugin" and then `npm link plugin` in "app".

Now when I try to start, "plugin" cannot find "express", even if it is correctly located in the node_modules directory of "app". Interestingly, when I console.log(__dirname) in "plugin"'s index.js, then it returns it's realy path rather than its virtual path.


So if I have the following folder structure:
```
/path/to/modules/
    app
        index.js
        node_modules
            express
                ...
            plugin -> app
    plugin
        index.js
```
Then it outputs 
`/path/to/modules/plugin` rather than `/path/to/modules/app/node_modules/plugin` which I think is the reason why it cannot find express.

What am I doing wrong here?

**Comment by th0r** [comment]
@VanCoding You aren't doing anything wrong.

`npm link` just creates symlink in your `/<your_projects_root>/app/node_modules` directory, and when you call `require('react')` from your plugin's source code node searches for it in the following folders: `/<your_projects_root>/plugin/node_modules` => `/<your_projects_root>/node_modules` => `/node_modules` and it never searches in `/<your_projects_root>/app/node_modules` directory.

As the workaround you can temporary change `plugin` entry in your app's `package.json` file to `"plugin": "file:../plugin"` and call `npm i plugin`, but in this case you'll have to call it every time you change the plugin's code so it's no very convenient.

@iarna I think it's still an issue with `npm link` and `peerDependencies` and is should be reopened.

**Comment by educastellano** [comment]
I'm having the same problem as @th0r and @VanCoding is seeing. Any ideas for workarounds other than the file: thing?

**Comment by th0r** [comment]
@educastellano I think we should open another issue.

**Comment by tomwidmer** [comment]
I have another workaround. You need to set the node path to include app/node_modules. E.g. I have this in my app/package.json scripts, to run my browserify build:

    "build:js:debug": "NODE_PATH=./node_modules browserify -d src/app.js > build/staging/app.js"

(N.B. there is an issue with using watchify with this approach, which I'm looking into)

**Comment by yordis** [comment]
:+1:

**Comment by cztomsik** [comment]
You can use `require.main.require('peerPkgName')`
http://stackoverflow.com/a/25800501/569051

**Comment by moodysalem** [comment]
Just ran into this..

It kindof forces you to develop your modules independently. Which is probably the right way but also really time consuming.

**Comment by raine** [comment]
Great workaround, @tomwidmer.

I have this problem with [hubot](http://hubot.github.com) when using `npm link` with an adapter you're developing. The adapter module does not have `hubot` as a dependency of its own but still expects `require('hubot')` to work and load it from the parent. If you try to install `hubot` as its own dependency under `./node_modules/hubot-gitter2/node_modules/hubot`, "module not found" error will go away, but weird things happen and things don't work as expected.

**Comment by dalanmiller** [comment]
Still having this issue on `npm` `3.6.0`. This process should be a lot easier.

**Comment by artisologic** [comment]
Hi,

I'm still having the same issue as @VanCoding as well.
Pretty much same situation with `react`.

I have a main package that depends directly on `react` and `other-package`.
Then `other-package` has a peer dependency of `react`.

Did `npm link` and I also get `Cannot resolve module 'react'`

I don't think this issue has been resolved, is there a new one opened for this?

**Comment by VanCoding** [comment]
@artisologic The real problem we're having here is this: https://github.com/nodejs/node/issues/3402

`npm link` is completely useless until node.js changes the behavior of `require`. I'm still stuck to npm2 because of this.

**Comment by dlongley** [comment]
If you're using node 6.x, symlinks are now preserved (not deep-resolved with realpath), so npm link may now play a little more nicely with peer dependencies.

**Comment by kobalicek** [comment]
I'm on node 6.2 and it's still broken - I cannot develop packages that have peer dependencies

**Comment by dlongley** [comment]
@kobalicek -- That's because they just rolled back the change on node 6.2. It's currently hidden behind a flag `--preserve-symlinks` (see: #6537) until the behavior can be integrated back in without causing a problem for a few other use cases. Using that flag, you should be able to develop peer dependencies.

**Comment by kobalicek** [comment]
Is there anywhere an explanation why it doesn't work and what's the technical reason behind it (also node bug would help)? Because I think this is a valid use case that should _just_ work without any flag.

Suppose I have two packages `a` and `b`, where `b` requires `a` and I have a directory structure like this:

```
main_package
  node_modules
    a -> symlink
    b -> symlink
```

Then `b` fails to require `a` if `b` is a symlink, but it works if `b` is a directory. This means that node doesn't walk the file-system back from `b` to the `main_package`, so where it walks?

**Comment by dlongley** [comment]
@kobalicek,

Yes, I meant to link to this issue: https://github.com/nodejs/node/pull/6537

The original issue is here: https://github.com/nodejs/node/issues/3402

And the original fix is here: https://github.com/nodejs/node/pull/5950

**Comment by bholloway** [comment]
When npm@3 was released I read somewhere that `peerDepdendencies` are deprecated and should no longer be used.

Which seems to be confirmed by [this comment](https://github.com/npm/npm/issues/5875#issuecomment-140881106).

As I understand it, you should convert `peerDependencies` to `dependencies`.

* npm@3 installs maximally flat. Both your package and the containing project specify the dependency. But it will only be installed in the containing project.

* When you `npm link` your package it is equivalent to running `npm install` in the linked directory. It does not see the containing project and cannot leverage the existing dependency installation there. The dependency is installed in both the containing project and the linked directory.

Isn't this the desired behaviour?

Personally I am confused because I see lots of **react** code that is still using `peerDependencies` and people with projects broken by `npm link`.

That said, I still experience problems with libraries that use Singleton `Symbol` constants:

*Consider a library that stores a value using a `Symbol` key. Data is stored in a linked project and accessed in the containing project. However, these both have different installations of the package and so different instances of the `Symbol`.*

Maybe this issue is solved?

**Comment by barneycarroll** [comment]
>  I read somewhere that `peerDepdendencies` are deprecated and should no longer be used.
> 
> Which seems to be confirmed by [this comment](https://github.com/npm/npm/issues/5875#issuecomment-140881106).

It's not deprecated: the implementation has changed. [It's explained in the package.json docs](https://docs.npmjs.com/files/package.json#peerdependencies): `peerDependencies` will never be installed automatically as a result of installing a dependency that specifies a peer dependency you don't have. Instead you will get a warning about the need for that dependency.

So if you have dependent package A#1, and install dependent package B#1 which specifies A#1 as a peer dependency, you're fine. If you didn't have A#1, the install procedure will ask you to resolve this yourself.

This puts the onus on the author to use their own judgment on a case by case basis, because there is no procedural correct solution for eg you are dependent on package A#1 and install a package B#2 that has a peer dependency on A#2.

**Comment by bholloway** [comment]
@barneycarroll you explain the problem well.

I guess I am arguing that the author of B#1 should change A#1 from `peerDependencies` to `dependencies`. Since npm@3 de-duplication gives the desired outcome.

The exceptions is if the A#1 you already have is semver incompatible, in which case you will get a silent duplication. Which may be a deal-breaker.

The other issue is that some people may still be using npm@<3.

**Comment by abelnation** [comment]
> When you npm link your package it is equivalent to running npm install in the linked directory. It does not see the containing project and cannot leverage the existing dependency installation there.  The dependency is installed in both the containing project and the linked directory.

@bholloway have you figured out a way to address the other issue you mentioned in your above comment?  Would `npm dedupe` be enough to remove the duplicated deps from the linked sub-package?

**Comment by bholloway** [comment]
@abelnation I have not tried it. If it does de-duplicate modules as you hope then it will break your code unless you can use [the `--preserve-symlinks` flag](https://github.com/npm/npm/issues/5875#issuecomment-220888292).

**Comment by dcaillibaud** [comment]
More than two years later the pb is still here. I don't want to duplicate eslint, babel and their plugins and preset in every project (more than 300k files each time, I run out free inodes !), so I link them, but with eslint it doesn't work, I still have `Cannot find module 'eslint-config-standard'`

Changing shebang in /usr/lib/node_modules/eslint/bin/eslint.js from `#!/usr/bin/env node` to `#!/usr/bin/nodejs --preserve-symlinks` doesn't solve the pb (npm 3.10.9 and node 6.9.1), so the only workaround I found is making hard links on eslint package (others eslint-* can play whith npm link), it preserve a little space but not inodes :-/ (hopefully it isn't the bigger package)

**Comment by cztomsik** [comment]
@dcaillibaud `require.main.require('pkg')` does not work for you?

**Comment by dcaillibaud** [comment]
@cztomsik I don't understand, I don't want to modify the eslint module to use it if it's linked, same for babel, webpack & co. You suggest to make wy own eslint wrapper, and use it for linting ?

**Comment by kevzettler** [comment]
You can npm link the peer dependencies back to your host projects dependencies

http://stackoverflow.com/a/38818358/93212

**Comment by nelsonomuto** [comment]
can't you install the peer dependency as a dev dependency?
