### ISSUE TITLE
Error: Cannot find module 'readable-stream' [Recreate]

### ISSUE THREAD

**Issue by robertmain** [npm/npm#6366]
The previous issue was locked and closed despite remaining unresolved.

@othiym23 was keen to point out that I should re-install npm (I actually re-installed node, and by implication npm).

After attempting to run `npm install` on my project gives me [this](https://gist.github.com/robertmain/f10c33721688ed3c8b96)

Running that a second time produces [this](https://gist.github.com/robertmain/0c77bda1414852d430a9). Manually `npm install`ing lodash(it should be installed as a normal dependency as it's listed in package.json, but nevermind...) finally produces [this](https://gist.github.com/robertmain/af43923e4a6c341ece17) (`Error: Cannot find module 'readable-stream/transform'` for those who can't/don't want to open the link)

**Comment by smikes** [comment]
Is this still a problem for you?

We are trying to clean up older npm issues, so if we don't hear back from you within a week, we will close this issue. (Don't worry -- you can always come back again and open a new issue!)

Thanks!

**Comment by robertmain** [comment]
No, this is now fixed. `npm cache-clean` seemed to fix things for me

**Comment by ActionCommunity** [comment]
No its not fixed, now I got it too. 

C:\Users\mbaarz>npm
module.js:341
    throw err;
    ^

Error: Cannot find module 'readable-stream'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\mbaarz\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog\node_modules\are-we-there-yet\index.js:2:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

C:\Users\mbaarz>npm cache clean
module.js:341
    throw err;
    ^

Error: Cannot find module 'readable-stream'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\mbaarz\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog\node_modules\are-we-there-yet\index.js:2:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

C:\Users\mbaarz>npm cache clear
module.js:341
    throw err;
    ^

```
Error: Cannot find module 'readable-stream'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\mbaarz\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog\node_modules\are-we-there-yet\index.js:2:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

C:\Users\mbaarz>npm
module.js:341
    throw err;
    ^

Error: Cannot find module 'readable-stream'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\mbaarz\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog\node_modules\are-we-there-yet\index.js:2:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

**Comment by deepakvasa** [comment]
same here

**Comment by cabeggar** [comment]
@deepakvasa Very helpful advice! I've also met with this problem and solve it by remove node_modules and reinstall npm

**Comment by ca0v** [comment]
How do you re-install npm when npm isn't working?

**Comment by LeoCecilia** [comment]
@cabeggar how to remove node_modules

**Comment by robertmain** [comment]
....delete the folder.

**Comment by blenderdeluxe** [comment]
On windows for me this work deleting 

C:\Users\YOURUSER\AppData\Roaming\npm
C:\Users\YOURUSER\AppData\Roaming\npm-cache

:D
