### ISSUE TITLE
/tmp files not cleaned up for shrinkwrapped packages

### ISSUE THREAD

**Issue by ianbamforth** [npm/npm#6855]
It appears that `npm install` cleans out /tmp only if the package you're installing is not shrinkwrapped.

To test, I created a very basic package (with a single dependency), publish it as 'unwrapped', then wrap (using `npm shrinkwrap`) and rename as wrapped, and publish again.  `npm install unwrapped` results in a clean /tmp folder. `npm install wrapped` results in a npm-<rand> folder being left in /tmp.

Either the code is wrong (i.e. the /tmp/npm-<rand> folder should be deleted) or the documentation needs updating to reflect the behaviour, preferably with an explanation as I can't think why they'd be treated differently!

**Comment by avdd** [comment]
Just a thought: it's fair enough to defer to the user/OS regarding cleaning up tempfiles, but it would be polite to put them in a subdirectory (e.g. /tmp/npm-$USER) so they don't pollute the shared space.

**Comment by ianbamforth** [comment]
avdd - not sure I agree, neither Windows nor Ubuntu will clean these up for you automatically, and in a successful install the tempfiles have no meaning / utility.  It's basically littering!

**Comment by peterjmit** [comment]
To add a data point, we turned on `shrinkwrap.json` and within a couple of days our builds started failing. After some investigation we found __>15g__ of files from npm in our `/tmp` directory, and then we found this issue. 

I am not sure I agree with the labelling of this issue as a `feature-request` - on a reasonable sized app it takes 2/3 days for this to cause a failure, and there is no documentation for `shrinkwrap` or `install` that provides a warning or suggested resolution for this failure. As such I had no reasonable chance of avoiding this failure and nor will users in the future.

**Comment by andiby** [comment]
Yes feature-request is wrong.
Either it is a bug that the Temp files are not deleted upon successful exit or the wrong documentation is a bug:
"Temp files are given a unique folder under this root for each run of the program, and are deleted upon successful exit." (npm-folders.md)
Already mentioned in #6853

**Comment by othiym23** [comment]
This isn't specific to `npm shrinkwrap` -- npm does a lot of stuff in `$TMPDIR`, and very frequently doesn't clean up after itself. I'm not sure that documentation has *ever* been correct, but if it ever was, it hasn't been for a long time now. In general, Unixy tools don't clean up after their own usage of `/tmp`, but most tools don't use tmp as much as npm does. A workaround is to look at using `tmpwatch` or a similar tool that will automatically clean up `/tmp`. Either way, this is more a feature-request than a bug, and a patch that adds automatic cleanup would be welcome.

**Comment by andiby** [comment]
I don't find a lot of stuff. There are only three places in where npm.tmp is used:
- lib/cache/add-remote-tarball.js addRemoteTarball() with url as folder
- lib/cache/add-local-tarball.js addTmpTarball() for unpack-*
- lib/cache/add-remote-git.js cache() for git-cache-*

**Comment by othiym23** [comment]
The thing is, we don't want to remove stuff right when we're done with it, because that will slow down the installation process significantly (and that may not sound like a major consideration when you're talking about a package manager, but npm's performance does matter, especially when doing large installs in build and CI environments). The way to handle this is probably to enqueue all of the things to be removed at process exit and then do it all at once. npm already [does something similar](https://github.com/npm/npm/issues/6533) for installation rollbacks when npm runs into install problems, but this would be simpler, because it's just a set of calls to `rimraf` rather than an unbuild step.

Like I said, I don't have time to get to this immediately, but it doesn't seem like a particularly hard problem to solve, and there _is_ a workaround in the meantime.

**Comment by andiby** [comment]
Just an easy and fast way would be to remove the npm.tmp directory on exit if the exitCode is 0:
```javascript
function rmdirSync(dir) {
	var list = fs.readdirSync(dir);
	for (var i = 0, l = list.length; i < l; i++) {
		var fileName = list[i];
		if (fileName == "." || fileName == "..")
			continue
		var filePath = path.join(dir, fileName);
		if (fs.statSync(filePath).isDirectory())
			rmdirSync(filePath);
		else
			fs.unlinkSync(filePath);
	}
	fs.rmdirSync(dir);
};
process.on("exit", function (code) {
  if (!code && tmpFolder)
	rmdirSync(npm.tmp);
});
```
Put it directly in lib/npm.js after the ```Object.defineProperty(npm, "tmp",...})``` and it's fine.

**Comment by smikes** [comment]
@andiby That will cause `npm` to block at exit until all the temp directories are cleaned up.  Something more like:

```
process.on("exit", function (code) {
  if (!code && tmpFolder) {
      require('child_process').spawn(path.resolve(__dirname, "node_modules", ".bin", "rimraf"),
                                     [tmpFolder],
                                     { cwd: npm.config.get("tmp"),
                                       detached: true,
                                       stdio: "ignore" })
  }
})
```

**Comment by ianbamforth** [comment]
I’d say that blocking at exit until clean-up is complete could be considered desirable.  Clean-up should be considered part of the process, and as such any failure to clean up should result in non-zero exit code, therefore you have to wait for clean-up.

**Comment by othiym23** [comment]
Depending on the complexity of the install, this could have a major impact on npm's perceived importance, which as a command-line tool, is basically the same as its actual performance. I agree that @smikes's approach is less robust than waiting for deletion to complete and notifying on errors, but it returns users to the prompt and lets them move on to their next tasks faster.

**Comment by othiym23** [comment]
@ianbamforth, after reviewing @smike's candidate PR, #7324, I think I've come around to agreeing with you. If something goes wrong during cleanup, there's no clean way of communicating to users that they might have an issue that needs reviewing unless it's reported right then and there.

But I also think that for systems where administrators have control over temporary directory cleanup, if npm is going to clean up after its own temporary directories, it should be configurable. Something like `remove-tmpdir` could be set to true by default, so CI processes could run `npm install --no-remove-tmpdir` if the ops team knows that `tmpwatch` is on the case. Otherwise, npm would make a single call to `rimraf` on exit. But be aware that this would have a significant impact on build speed in precisely those cases where it's most important – removing a bunch of git repos and the other detritus from a big, complicated build could take up to a minute on shared hardware like an EC2 instance using EBS.

I think this is worth adding as described above, and have labeled it as such. The trick is that it may be a while before @iarna or I have time to get to this, so if somebody else wants to give it a shot, they would have my gratitude and assistance.

As more general context, @isaacs and I discussed this issue, and we're in agreement that npm has not really changed how much it relies on the temporary directory, it's just that builds have gotten a great deal more complicated over time, and it's now starting to add up.

**Comment by smikes** [comment]
Bringing this note back over here, so it doesn't get lost in the dead pull-request:

> an async rimraf of a /tmp git repo could be fired off as soon as we know we don't need it anymore, i.e., as soon as the git-clone-to-cache completes.

**Comment by nemisj** [comment]
We put an oneliner in the postinstall scripts which will cleanup the folder.

```javascript
{
    "scripts": {
        "postinstall": "ppid=$(ps -p ${1:-$$} -o ppid=;); if [ -z ${npm_config_tmp} ]; then npm_config_tmp=/tmp; fi; rm -rf \"${npm_config_tmp}\"/npm-${ppid}* "
    }
}
```

https://gist.github.com/nemisj/e27c942439863dfb4375#file-package-json

**Comment by kleini** [comment]
We need to have that immediately fixed because that problem kills our build infrastructure. /tmp directories on build machines grow about 6G per day.

**Comment by nemisj** [comment]
@kleini: https://gist.github.com/nemisj/11f6d01ef9638af283d3 though it works only on *nix machines

**Comment by kleini** [comment]
@nemisj This would require to modify every project using npm. That is not feasible about 50 projects each having 5 or more branches.

**Comment by nemisj** [comment]
@kleini, that explains

**Comment by ianbamforth** [comment]
@kleini presumably you're ok using a cronjob to clean up your /tmp folder though?  I'm using:

    #!/bin/bash

    # Removes any folder starting with npm- in the /tmp folder.
    sudo find /tmp/ -name 'npm-*' -type d -mmin +10 -exec rm -rf {} +

which removes anything older than 10 minutes that starts with `npm-`, adjust as required.

**Comment by binarykitchen** [comment]
Killed our test infrastructure too so yes, would be good to get this fixed.

**Comment by othiym23** [comment]
This is at the very least improved in [`npm@3`](https://github.com/npm/npm/releases/tag/v3.0.0) (look in the TINY JEWELS section down near the end), so give that a shot and let us know if the beta is working more like how you'd expect.

**Comment by smoya** [comment]
Im using the `3.0.1` but still i have residual npm dirs in /tmp

**Comment by othiym23** [comment]
This has been moved to the [npm roadmap](https://github.com/npm/npm/wiki/Roadmap), which we're using instead of the confusing `next-*` labels now.

**Comment by madarche** [comment]
@othiym23 FYI it's not to be found on the npm roadmap, or am I missing something?

Cheers

**Comment by madarche** [comment]
@ianbamforth I've modified your command line with the  `-maxdepth 1` option so that `npm-*'` directories are only search at the root of `/tmp` otherwise `npm-*'` directories are searched in places like `/tmp/whatever-restricted-dir-not-owned-by-the-user-issuing-the-find-command` :

find /tmp -maxdepth 1 -name 'npm-*' -type d -mmin +10 -exec rm -rf {} +

**Comment by ianbamforth** [comment]
@madarche good call, thanks

**Comment by twexler** [comment]
This actually seems to be a huge deal for me in my CI environment. Is there any timeline for fixing this?

**Comment by MarkRose** [comment]
This is also affecting us, killing our CI environment.

**Comment by am-jo-zt** [comment]
We're facing the same issue here. This is very inconvenient.

**Comment by ianbamforth** [comment]
@MarkRose @twexler @am-jo-zt - have you tried using a cronjob to tidy up after npm?  See my comment above (May 21) or my stackoverflow page on the same problem: http://stackoverflow.com/questions/27226558/npm-install-doesnt-delete-tmp-on-successful-exit-when-installing-packages-that/27310115#27310115

**Comment by ianbamforth** [comment]
@othiym23 - I also can't see that on the roadmap, has this fallen through the cracks somewhere?

**Comment by gdbtek** [comment]
+1

**Comment by am-jo-zt** [comment]
@ianbamforth Yes, we already are using your workaround (thanks, btw) that's why it's "just" inconvenient.

+1 for this to be implemented / fixed

**Comment by rifelpet** [comment]
@othiym23 and @ianbamforth: It looks like its in the [Big Bugs](https://github.com/npm/npm/wiki/Roadmap-area-of-focus%3A-big-bugs) item of the [Maintenance, internals, and technical debt](https://github.com/npm/npm/wiki/Roadmap#4-maintenance-internals-and-technical-debt) area of focus.

I'm also +1 on this

**Comment by mtisi** [comment]
+1

**Comment by abourdon** [comment]
+1

**Comment by geertweening** [comment]
+1

**Comment by gonzochic** [comment]
+1 from my side too :)

**Comment by magec** [comment]
Same here, having crons for deleting the stuff a program incorrectly leave behind does not seem to be a good solution. :+1:

**Comment by dasrecht** [comment]
:+1: we're also having issues with the /tmp/ directories being filled up.

**Comment by razvanphp** [comment]
Really unexpected, +1 please!

**Comment by geertweening** [comment]
Had to implement the work around with cron jobs, please get this fixed. +1

**Comment by STRML** [comment]
This is killing instances left and right (running out of inodes), sorry to put another :+1: in the pile but we really need this.

**Comment by twexler** [comment]
Seriously, this is getting out of hand. I run a large CI cluster, and many of them have 100GB+ of npm tempfiles. Can someone *please* look at this?

**Comment by othiym23** [comment]
The CLI team isn't going to have time to get to this ourselves anytime soon. I strongly recommend that ops people running build / CI servers running Unixy systems set up [`tmpwatch`](http://linux.die.net/man/8/tmpwatch) to clean out leftover npm files as a workaround. For Windows, look into something like [`forfiles`](http://rootmypc.net/blog/?p=17). Also, be aware that npm respects `TMPDIR`, so it could be as simple as pointing that at an ephemeral volume that gets recreated on a periodic basis.

**Comment by twexler** [comment]
I'm gonna come out and say it. That answer is pretty unacceptable. Tempfiles are supposed to be *temporary*, so this is a pretty severe bug in shrinkwrap. I'm engaging some of our node developers on this but I'd like to see more traction from npm core contributors. Very disappointed in the node community at this point.

**Comment by othiym23** [comment]
@twexler The list of the CLI team's outstanding tasks is very long, the team is relatively small, and we're currently heads down on paying off some of npm's accumulated technical debt by improving our test suite, so I'm only being transparent here. Tools like `tmpwatch` and `forfiles` exist because npm is far from being alone in not cleaning up after itself in `TMPDIR`, and while it's a distraction having to configure (and potentially install) another tool, it will address your problem.

For context, we've looked at changing how npm cleans up after itself, and there are complications that aren't immediately apparent. Because of the number of files and directories created by unpacking packages can be quite large, removing those trees on many (if not most) filesystems can be quite time-consuming, which makes npm significantly slower to return control to the command prompt. There are many concerns about npm's performance already, so any change here needs to take that into account. We've looked at spawning an independent process to remove files after installs successfully complete, but there are open questions around how to do that safely, especially on Windows. The team would be delighted were someone to send us a patch that handled these complications (@smikes made some efforts in this direction towards the end of last year), and I think the reason that hasn't happened so far is that it's complicated.

**Comment by STRML** [comment]
@othiym23 On shrinkwrapped installs this is a must for OS reliability - I've taken to clearing /tmp on a cron job but I'm sure this is biting thousands of production apps.

NPM v3 was all about doing the right thing, despite performance costs, no? If so then this fix belongs there. But if the cost is too much to bear, how do you feel about a CLI flag? 

As OSS is all about contribution - I'm sure many of us would be happy to contribute a patch if someone from the core team could point us in the right direction.

**Comment by lxe** [comment]
Just like with `npm_config_cache` directly, for CI builds, it's a good practice to keep `npm install`s as isolated as possible. I recommend just doing something like this:

```bash
# set cache and tmp to build-local directories
export npm_config_cache=./npm_cache 
export npm_config_tmp=./npm_tmp

npm install

# ...

# cleanup
rm -rf $npm_config_tmp
rm -rf $npm_config_cache #optional
```

Not only this helps with cleanup and management of tmp files, this isolates the cache directory, making multiple builds running on one box isolated from each other. So if any build decides to `npm cache clean` or to do some wacky stuff, other builds won't fail.

**Comment by othiym23** [comment]
> NPM v3 was all about doing the right thing, despite performance costs, no? If so then this fix belongs there.

As far as I know, this _is_ fixed in `npm@3`. I just ran several installs of large packages including Hapi and Ionic. The Hapi install left behind nothing in `TMPDIR`, and the only reason that Ionic left behind anything (which was an empty directory tree in this case) is because it depends on `npm@2.1.3`, and Ionic also transitively depends on `ionic-cordova-lib@5.1.10`, which in turn depends on `npm@^2`. `npm@3` does all of its temporary building and rolling back in `node_modules/.staging`, and when it scans for shrinkwrap metadata, it's streaming files into memory directly from the cached tarballs in `$HOME/.npm`.

In general, `npm@3` uses `TMPDIR` only while cloning hosted git dependencies, unpacking bundled dependencies to scan them for metadata, and downloading package tarballs (before moving them into the cache). In all of those cases, `npm@3` has a cleanup operation that removes the unpacked package or cloned repo after it's done with it. Sometimes this leaves behind a directory tree, but it's uncommon for that tree to containing anything other than the directories themselves.

**Comment by TheSavior** [comment]
@othiym23 I'm fine with the answer to this being that it is solved in `npm@3`.

The work arounds are listed and numerous for people on `npm@2`

**Comment by Yvem** [comment]
@TheSavior I respectfully disagree. In my company, we use node v4 LTS (which uses npm 2) and, of course, shrinkwrap. Right now, we failed at deploying, for our integration server is, once again, full. Because of npm-* left in /tmp. I'm writing a cleanup cron script right now, but it's definitely a serious bug.

**Comment by claycephas** [comment]
Those looking for a workaround on WIndows (using PowerShell):

    Get-ChildItem "$env:LOCALAPPDATA\Temp\" -Filter npm* | `
    Foreach-Object{

        if ($_.LastWriteTime -lt (Get-Date).AddDays(-1)) {
            Write-Host "Deleting $_..."
            Remove-Item -Recurse -Force $_.FullName
        }
    }

This will delete folders/files beginning with `npm` if they're older than 1 day.

**Comment by ankurp** [comment]
@othiym23 Its not entirely fixed in npm3. It only outputs git cache file in npm tmp folder but does not clean it after npm process ends.

**Comment by ankurp** [comment]
@othiym23  Try installing with a npm-shrinkwrap file containing following node_module `pm2@0.14.7`

**Comment by paglias** [comment]
This bug is biting us with `npm@3`: using shrinkwrap we're unable to deploy to our EC2 instances (`c4.2xlarge`) while without it deploys are fine.

**Comment by othiym23** [comment]
After looking at the code, the CLI team believes the only remaining place where `npm@>=3` leaves behind files in `$TMPDIR` is when cloning hosted Git repositories. The simplest way to fix this would be to fire off a `rimraf(tmpdir, function () { log.debug('updateSubmodules', 'removed', tmpdir) })` (or maybe something slightly less take-no-prisoners) inside the call to `addLocal()` within `updateSubmodules` in `lib/cache/add-remote-git.js`. (This is written specifically to avoid blocking the completion of installs on the rimraf's completion while still ensuring that the files will get removed before the process exits, which is both a little gross but also takes advantage of concurrency in a not-too-invasive way.)

If somebody wants to send us a patch to that effect, we'd be happy to merge it in. Given the other tasks on the team's to-do list, though, we're unlikely to have time to deal with this in the near- to medium-term. (Also, `npm@2` is entering maintenance mode, and will not be patched to include this functionality – investigate one of the many OS-level packages for cleaning up temporary directories if you're restricted to using `npm@2`.)

Because the CLI team isn't going to have time to do this themselves, I'm going to close this feature request. Because we'd be happy to merge a patch to npm's master branch cleaning up Git clones, I'm marking it `patch-welcome`. Thanks to all for their time, patience, and discussion.

**Comment by TheSavior** [comment]
@othiym23 If you meant to tag this with `patch-welcome`, you may have unintentionally tagged this with `platform-integration`

**Comment by othiym23** [comment]
It already had `patch-welcome`, and given that there are concerns tied to the operating system and distro, it's very much a platform integration problem.

**Comment by idautocfator** [comment]
Having high hopes for Yarn: https://code.facebook.com/posts/1840075619545360

**Comment by twexler** [comment]
+1 Yarn looks cool. Maybe will have a better set of collaborators who care about running large scale systems.

**Comment by jarig** [comment]
Started killing our infra as well, had to workaround with forceful cleanups...

**Comment by dinomite** [comment]
For anyone whose Jenkins runs on Ubuntu  or Debian and it hangs on boot, this is likely why.  I have two headless Jenkins instances that rebooted because of power outage and both hung on startup at the line `A start job is running for Create Volatile Files and Directories`, which is a task that is unfortunately not time limited.  The fix is to [boot directly into bash and clear `/tmp`](http://deshack.net/debian-hangs-during-boot/).

The response from NPM maintainers is pretty sad.  Playing off this bug as a feature request and saying, "we're too busy, look at our to do list!" is cowardly avoidance of accepting a mistake.  Worse, claiming that it would slow things down too much—why don't you use my database that stores everything in `/dev/null`, it's super fast!

**Comment by twifty** [comment]
Supposedly fixed in npm@3, yet running npm@4.6.1 and my \tmp folder is still full of npm's leftovers.

**Comment by mcstover** [comment]
Still an issue in NPM5 as well when installing using shrinkwrap.

**Comment by diggabyte** [comment]
I've confirmed that when using git hosted dependencies in a package.json, the git repo files do NOT get removed (using npm@3.10.10) after package installation.

This contradicts the explanation given here:
https://github.com/npm/npm/issues/6855#issuecomment-163047091

There is a workaround if you are the owner of the git hosted package (i.e. your own package or a fork or whatever) that is causing the /tmp files to be left behind, you can add a postinstall script to clean up after itself:
https://gist.github.com/nemisj/11f6d01ef9638af283d3

**Comment by icybin** [comment]
this is disk killer feature in our company. I'm not sure if the installation process and/or the shrinkwrap tool is creating them. "(

**Comment by diggabyte** [comment]
I made a small package that deletes all the `/tmp/npm-*` directories as postinstall step. If you're desperate, you can add this package as a dependency.
https://www.npmjs.com/package/npm-tmp-cleanup

**Comment by nemisj** [comment]
@diggabyte it's not nice to steal gists from other people - https://gist.github.com/nemisj/11f6d01ef9638af283d3 :) at least, maybe change content a bit. BTW, there is already a package, which works also in windows - https://www.npmjs.com/package/clean-npm-tmp

**Comment by diggabyte** [comment]
@nemisj thanks, hadn't seen that package yet. I'll edit previous post to point to your gist as well

**Comment by nemisj** [comment]
@diggabyte , sure, no problem :))
