### ISSUE TITLE
npm version Throwing Up An Error

### ISSUE THREAD

**Issue by realph** [npm/npm#7128]
When I run `npm version` it's throwing up some errors. Here's the entire npm-debug.log file:

    0 info it worked if it ends with ok
    1 verbose cli [ 'node', '/usr/local/bin/npm', 'version' ]
    2 info using npm@2.1.17
    3 info using node@v0.10.35
    4 verbose node symlink /usr/local/bin/node
    5 verbose config Skipping project config: /Users/realph/.npmrc. (matches userconfig)
    6 error version Bad package.json data undefined
    7 verbose type unexpected_token
    8 verbose stack SyntaxError: Unexpected token u
    8 verbose stack     at Object.parse (native)
    8 verbose stack     at /usr/local/lib/node_modules/npm/lib/version.js:36:19
    8 verbose stack     at evalmachine.<anonymous>:208:20
    8 verbose stack     at OpenReq.Req.done (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:141:5)
    8 verbose stack     at OpenReq.done (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:61:22)
    8 verbose stack     at Object.oncomplete (evalmachine.<anonymous>:108:15)
    9 verbose cwd /Users/realph
    10 error Darwin 14.0.0
    11 error argv "node" "/usr/local/bin/npm" "version"
    12 error node v0.10.35
    13 error npm  v2.1.17
    14 error Unexpected token u
    15 error If you need help, you may report this error at:
    15 error     <http://github.com/npm/npm/issues>
    16 verbose exit [ 1, true ]

Not sure if it's got anything to do with changing my shell to zsh.

Any help is appreciated. Thanks in advance!

**Update**

I'm using zsh and I installed npm and node via `brew install node`, and I get an error when returning either `node version`:

    module.js:340
        throw err;
              ^
    Error: Cannot find module '/Users/realph/version'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)
        at Function.Module.runMain (module.js:497:10)
        at startup (node.j

Or `npm version`:

    npm ERR! version Bad package.json data undefined
    npm ERR! Darwin 14.0.0
    npm ERR! argv "node" "/usr/local/bin/npm" "version"
    npm ERR! node v0.10.35
    npm ERR! npm  v2.1.18

    npm ERR! Unexpected token u
    npm ERR!
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <http://github.com/npm/npm/issues>

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/realph/Desktop/npm-debug.log

**Comment by linclark** [comment]
I'm getting the same issue using bash and npm@2.1.18

**Comment by linclark** [comment]
That's odd... I linked it to my local directory to try to debug this, but that resolved the problem and now I can't reproduce it, even when I go back to using 2.1.18 in my global directory.

Could you try updating with ```npm install -g npm@latest``` (using sudo if you need to) and then running the version command again?

**Comment by realph** [comment]
@linclark When I run that command I get this returned to me:

    /Users/realph/.node/bin/npm -> /Users/realph/.node/lib/node_modules/npm/bin/npm-cli.js
    npm@2.1.18 /Users/realph/.node/lib/node_modules/npm

Then when I run `npm version` I get the same error (below):

    npm ERR! version Bad package.json data undefined
    npm ERR! Darwin 14.0.0
    npm ERR! argv "node" "/usr/local/bin/npm" "version"
    npm ERR! node v0.10.35
    npm ERR! npm  v2.1.17

    npm ERR! Unexpected token u
    npm ERR!
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <http://github.com/npm/npm/issues>

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/realph/npm-debug.log

**Comment by linclark** [comment]
I have one console where I can reproduce this issue again. I'll run it by the CLI team when they get in.

**Comment by realph** [comment]
Thanks so much, @linclark!

**Comment by smikes** [comment]
I think I saw a related issue - something about `npm version` in 2.1.18 failing if there was no `package.json` ; and I think it was fixed in `2.2.0`.  I'll see if I can find the live issue.

**Comment by linclark** [comment]
@smikes Good call, it looks like it is #7056.

@realph you can update to npm@2.2.0 using ```npm install -g npm@next```.

**Comment by smikes** [comment]
Thank you, I got lost in the issue tracker. ;-)

**Comment by realph** [comment]
@smikes @linclark This is what I get when I run `sudo npm install -g npm@next`: 

    Users/realph/.node/bin/npm -> /Users/realph/.node/lib/node_modules/npm/bin/npm-cli.js
    npm ERR! Darwin 14.0.0
    npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "npm@next"
    npm ERR! node v0.10.35
    npm ERR! npm  v2.1.17
    npm ERR! path ../../../lib/node_modules/npm/man/man3/npm-restart.3
    npm ERR! code ENOENT
    npm ERR! errno 34

    npm ERR! enoent ENOENT, symlink '../../../lib/node_modules/npm/man/man3/npm-restart.3'
    npm ERR! enoent This is most likely not a problem with npm itself
    npm ERR! enoent and is related to npm not being able to find a file.
    npm ERR! enoent

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/realph/npm-debug.log

**Comment by realph** [comment]
@linclark @smikes  If it's of any note, I've installed npm through `brew install node`. I'm on a brand new machine, so very weird that I've run into this issue. Never experienced anything like it before.

**Comment by smikes** [comment]
Hm... well, you probably don't need `sudo` since you've got `node` installed under your home directory.  But I have no idea why the install is failing.  Can you try the curl-based installer, `curl -L https://www.npmjs.org/install.sh | sh` as described here: <https://github.com/npm/npm/wiki/Troubleshooting#if-your-npm-is-broken>

**Comment by smikes** [comment]
I know that the people responsible for the `brew` recipes for `node` and `npm` have recently updated them, but I'm surprised that `npm install -g npm` would ever fail with that particular error.  That almost looks like a corrupt `pack` file or a broken download or something.  Maybe try `npm cache clean` ?

**Comment by realph** [comment]
@smikes Unfortunatlyt, `npm cache clean` doesn't seem to resolve the issue. Is it worth pointing out that `npm -v` returns the version (2.1.18), but `npm version` keeps throwing back that same `npm ERR! version Bad package.json data undefined` error?

**Comment by smikes** [comment]
I have no more suggestions, sorry. I think the west coast people will be up soon though.

**Comment by realph** [comment]
No worries @smikes! Hopefully someone will see it and be able to assist.

**Comment by realph** [comment]
@smikes This [solution](https://gist.github.com/DanHerbert/9520689#solution) has partially helped me get gulp installed through npm, and up and running.

However, `npm version` still returns those errors. Hmm...

**Comment by othiym23** [comment]
This [is fixed](https://github.com/npm/npm/releases) in `npm@next` / `npm@2.2.0`, so `npm -g install npm@next` if you want `npm version` to work correctly again.

**Comment by realph** [comment]
@othiym23 Still getting the same error after running that command. Are there any steps I need to take beforehand? Uninstalling brew, etc.?

**Comment by othiym23** [comment]
What does `npm -v` return?

**Comment by realph** [comment]
@othiym23 That returns 2.2.0.

**Comment by othiym23** [comment]
@realph It looks like your npm install has gotten messed up. Start over by completely uninstalling and reinstalling Node / npm, and then reinstalling it and then updating npm to `npm@next`? (Sorry!)
