### ISSUE TITLE
Error installing bower on Windows server 2012 (CB() never called)

### ISSUE THREAD

**Issue by Thomaspunt** [npm/npm#7177]
Hi,

I came across some errors after trying to install bower with NPM (2.2.0) on Windows server 2012. Git and Node are installed, also because of the company firewall I've configured git to use https:// instead of git:// as described here: http://jgoodall.me/posts/2013/05/29/git-use-https/

So this is what happens after typing npm install bower -g: 

![error2](https://cloud.githubusercontent.com/assets/2996457/5819498/a4670cfc-a0be-11e4-96d0-c9abe3d23e55.PNG)

I've also tried to remove user after reading this thread: https://github.com/npm/npm/issues/7133
Please advise, thank you! 

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'bower',
1 verbose cli   '-g' ]
2 info using npm@2.2.0
3 info using node@v0.10.35
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 silly cache add args [ 'bower', null ]
6 verbose cache add spec bower
7 silly cache add parsed spec { raw: 'bower',
7 silly cache add   scope: null,
7 silly cache add   name: 'bower',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed bower@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'bower', range: '*', hasData: false }
12 silly mapToRegistry name bower
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/bower
16 verbose addNameRange registry:https://registry.npmjs.org/bower not in flight; fetching
17 verbose request uri https://registry.npmjs.org/bower
18 verbose request no auth needed
19 info attempt registry request try #1 at 14:54:28
20 verbose request id 7103ea323827e24d
21 http request GET https://registry.npmjs.org/bower
22 http 200 https://registry.npmjs.org/bower
23 silly get cb [ 200,
23 silly get   { date: 'Tue, 20 Jan 2015 13:54:29 GMT',
23 silly get     server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
23 silly get     etag: '"BM4XOUYLXN0EGW9Q6SWUA1ZLW"',
23 silly get     'content-type': 'application/json',
23 silly get     'cache-control': 'max-age=60',
23 silly get     'content-length': '106041',
23 silly get     'accept-ranges': 'bytes',
23 silly get     via: '1.1 varnish',
23 silly get     age: '0',
23 silly get     'x-served-by': 'cache-ams4148-AMS',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1421762068.964560,VS0,VE385',
23 silly get     vary: 'Accept',
23 silly get     'keep-alive': 'timeout=10, max=50',
23 silly get     connection: 'Keep-Alive' } ]
24 verbose getCacheStat cache creation not in flight; initializing
25 verbose stack TypeError: uid must be an unsigned int
25 verbose stack     at Object.fs.chown (fs.js:865:11)
25 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\chownr\chownr.js:12:43
25 verbose stack     at Object.oncomplete (fs.js:108:15)
26 verbose cwd C:\Program Files\nodejs
27 error Windows_NT 6.2.9200
28 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "bower" "-g"
29 error node v0.10.35
30 error npm  v2.2.0
31 error uid must be an unsigned int
32 error If you need help, you may report this error at:
32 error     <http://github.com/npm/npm/issues>
33 verbose exit [ 1, true ]
```

**Comment by KenanY** [comment]
@Thomaspunt I think this was fixed in [`npm@2.3.0`](https://github.com/npm/npm/releases/tag/v2.3.0). A bad change was made as to how `npm` interacted with the cache that was causing a lot of people to have issues when they cached something new. Can you see if updating helps?:

``` bash
$ npm install -g npm@2.3.0
```

**Comment by Thomaspunt** [comment]
Updating to 2.3.0 gives the uid must be an unsigned int error as well. 

![error3](https://cloud.githubusercontent.com/assets/2996457/5832858/c0cfc7c0-a14b-11e4-8145-f83030323526.PNG)

**Comment by Thomaspunt** [comment]
The following error remains: 

'npm ERR! cb() never called!'

npm cache clean doesn't fix it, tried 3 times. Any suggestions? :)

**Comment by KenanY** [comment]
I believe `cb() never called!` always implies the presence of a bug. Is there a `npm-debug.log` created when this happens (I don't think it is for this kind of error but I might as well ask).

If not, maybe adding the `-d` flag to your install command (to increase log verbosity) will shed some context on the error.

**Comment by Thomaspunt** [comment]
`npm http 200 https://registry.npmjs.org/shell-quote
npm http 200 https://registry.npmjs.org/stringify-object
npm http 200 https://registry.npmjs.org/tar-fs
npm http 200 https://registry.npmjs.org/tmp
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/bower-endpoint-parser/-/bower-endp
oint-parser-0.2.2.tgz
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/bower-json/-/bower-json-0.4.0.tgz
npm http 200 https://registry.npmjs.org/update-notifier
npm http 200 https://registry.npmjs.org/which
npm http fetch 200 https://registry.npmjs.org/archy/-/archy-0.0.2.tgz
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/bower-config/-/bower-config-0.5.2.
tgz
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/bower-logger/-/bower-logger-0.2.2.
tgz
npm http fetch 200 https://registry.npmjs.org/abbrev/-/abbrev-1.0.5.tgz
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/chalk/-/chalk-0.5.0.tgz
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/chmodr/-/chmodr-0.1.0.tgz
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/decompress-zip/-/decompress-zip-0.
0.8.tgz
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/bower-registry-client/-/bower-regi
stry-client-0.2.2.tgz
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/cardinal/-/cardinal-0.4.0.tgz
npm info retry will retry, error on last attempt: Error: write ECONNRESET
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/fstream/-/fstream-1.0.3.tgz
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/fstream-ignore/-/fstream-ignore-1.
0.2.tgz
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/inquirer/-/inquirer-0.7.1.tgz
npm info retry will retry, error on last attempt: Error: write ECONNRESET
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/insight/-/insight-0.4.3.tgz
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/graceful-fs/-/graceful-fs-3.0.5.tg
z
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/handlebars/-/handlebars-2.0.0.tgz
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/glob/-/glob-4.0.6.tgz
npm info retry will retry, error on last attempt: Error: write ECONNRESET
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/is-root/-/is-root-1.0.0.tgz
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.0.tgz
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/junk/-/junk-1.0.0.tgz
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/lockfile/-/lockfile-1.0.0.tgz
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/lru-cache/-/lru-cache-2.5.0.tgz
npm info retry will retry, error on last attempt: Error: write ECONNRESET
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/p-throttler/-/p-throttler-0.1.0.tg
z
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/mout/-/mout-0.9.1.tgz
npm info retry will retry, error on last attempt: Error: write ECONNRESET
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/nopt/-/nopt-3.0.1.tgz
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/opn/-/opn-1.0.1.tgz
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/promptly/-/promptly-0.2.0.tgz
npm info retry will retry, error on last attempt: Error: write ECONNRESET
npm http 200 https://registry.npmjs.org/osenv
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/request-progress/-/request-progres
s-0.3.0.tgz
npm info retry will retry, error on last attempt: Error: write ECONNRESET
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/retry/-/retry-0.6.0.tgz
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/q/-/q-1.0.1.tgz
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/request/-/request-2.42.0.tgz
npm info retry will retry, error on last attempt: Error: write ECONNRESET
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/semver/-/semver-2.3.2.tgz
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/rimraf/-/rimraf-2.2.8.tgz
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/tar-fs/-/tar-fs-0.5.2.tgz
npm info retry will retry, error on last attempt: Error: write ECONNRESET
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/tmp/-/tmp-0.0.23.tgz
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/shell-quote/-/shell-quote-1.4.2.tg
z
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/stringify-object/-/stringify-objec
t-1.0.0.tgz
npm info retry will retry, error on last attempt: Error: write ECONNRESET
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/update-notifier/-/update-notifier-
0.2.0.tgz
npm info retry will retry, error on last attempt: Error: write ECONNRESET
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/which/-/which-1.0.8.tgz
npm info retry fetch attempt 1 at 13:24:58
npm info attempt registry request try #1 at 13:24:58
npm http fetch GET https://registry.npmjs.org/osenv/-/osenv-0.1.0.tgz
npm info retry will retry, error on last attempt: Error: read ECONNRESET
npm info retry will retry, error on last attempt: Error: read ECONNRESET
npm info retry will retry, error on last attempt: Error: read ECONNRESET
npm info retry will retry, error on last attempt: Error: read ECONNRESET
npm info retry will retry, error on last attempt: Error: read ECONNRESET
npm info retry will retry, error on last attempt: Error: read ECONNRESET
npm info retry will retry, error on last attempt: Error: read ECONNRESET
npm info retry will retry, error on last attempt: Error: read ECONNRESET
npm info retry will retry, error on last attempt: Error: read ECONNRESET
npm info retry will retry, error on last attempt: Error: read ECONNRESET
npm http fetch 200 https://registry.npmjs.org/lru-cache/-/lru-cache-2.5.0.tgz
npm http fetch 200 https://registry.npmjs.org/lockfile/-/lockfile-1.0.0.tgz
npm http fetch 200 https://registry.npmjs.org/p-throttler/-/p-throttler-0.1.0.tg
z
npm info retry will retry, error on last attempt: Error: read ECONNRESET
npm http fetch 200 https://registry.npmjs.org/request-progress/-/request-progres
s-0.3.0.tgz
npm http fetch 200 https://registry.npmjs.org/retry/-/retry-0.6.0.tgz
npm info retry will retry, error on last attempt: Error: read ECONNRESET
npm http fetch 200 https://registry.npmjs.org/q/-/q-1.0.1.tgz
npm http fetch 200 https://registry.npmjs.org/semver/-/semver-2.3.2.tgz
npm http fetch 200 https://registry.npmjs.org/rimraf/-/rimraf-2.2.8.tgz
npm info retry will retry, error on last attempt: Error: read ECONNRESET
npm info retry will retry, error on last attempt: Error: read ECONNRESET
npm http fetch 200 https://registry.npmjs.org/tmp/-/tmp-0.0.23.tgz
npm http fetch 200 https://registry.npmjs.org/shell-quote/-/shell-quote-1.4.2.tg
z
npm http fetch 200 https://registry.npmjs.org/update-notifier/-/update-notifier-
0.2.0.tgz
npm http fetch 200 https://registry.npmjs.org/osenv/-/osenv-0.1.0.tgz
npm info retry will retry, error on last attempt: Error: read ECONNRESET
npm info retry will retry, error on last attempt: Error: read ECONNRESET
npm info attempt registry request try #2 at 13:25:08
npm http fetch GET https://registry.npmjs.org/bower-endpoint-parser/-/bower-endp
oint-parser-0.2.2.tgz
npm info attempt registry request try #2 at 13:25:08
npm http fetch GET https://registry.npmjs.org/bower-json/-/bower-json-0.4.0.tgz
npm info retry will retry, error on last attempt: Error: read ECONNRESET
npm info retry will retry, error on last attempt: Error: read ECONNRESET
npm info attempt registry request try #2 at 13:25:08
npm http fetch GET https://registry.npmjs.org/bower-config/-/bower-config-0.5.2.
tgz
npm info retry will retry, error on last attempt: Error: read ECONNRESET
npm info attempt registry request try #2 at 13:25:08
npm http fetch GET https://registry.npmjs.org/bower-logger/-/bower-logger-0.2.2.
tgz
npm info attempt registry request try #2 at 13:25:08
npm http fetch GET https://registry.npmjs.org/chalk/-/chalk-0.5.0.tgz
npm info attempt registry request try #2 at 13:25:08
npm http fetch GET https://registry.npmjs.org/chmodr/-/chmodr-0.1.0.tgz
npm info attempt registry request try #2 at 13:25:08
npm http fetch GET https://registry.npmjs.org/decompress-zip/-/decompress-zip-0.
0.8.tgz
npm http fetch 200 https://registry.npmjs.org/chalk/-/chalk-0.5.0.tgz
npm http fetch 200 https://registry.npmjs.org/bower-logger/-/bower-logger-0.2.2.
tgz
npm info attempt registry request try #2 at 13:25:08
npm http fetch GET https://registry.npmjs.org/bower-registry-client/-/bower-regi
stry-client-0.2.2.tgz
npm info attempt registry request try #2 at 13:25:08
npm http fetch GET https://registry.npmjs.org/cardinal/-/cardinal-0.4.0.tgz
npm info attempt registry request try #2 at 13:25:08
npm http fetch GET https://registry.npmjs.org/fstream/-/fstream-1.0.3.tgz
npm info attempt registry request try #2 at 13:25:08
npm http fetch GET https://registry.npmjs.org/fstream-ignore/-/fstream-ignore-1.
0.2.tgz
npm http fetch 200 https://registry.npmjs.org/chmodr/-/chmodr-0.1.0.tgz
npm http fetch 200 https://registry.npmjs.org/decompress-zip/-/decompress-zip-0.
0.8.tgz
npm info attempt registry request try #2 at 13:25:08
npm http fetch GET https://registry.npmjs.org/inquirer/-/inquirer-0.7.1.tgz
npm info attempt registry request try #2 at 13:25:08
npm http fetch GET https://registry.npmjs.org/insight/-/insight-0.4.3.tgz
npm info attempt registry request try #2 at 13:25:08
npm http fetch GET https://registry.npmjs.org/graceful-fs/-/graceful-fs-3.0.5.tg
z
npm info attempt registry request try #2 at 13:25:08
npm http fetch GET https://registry.npmjs.org/handlebars/-/handlebars-2.0.0.tgz
npm info attempt registry request try #2 at 13:25:08
npm http fetch GET https://registry.npmjs.org/glob/-/glob-4.0.6.tgz
npm info attempt registry request try #2 at 13:25:08
npm http fetch GET https://registry.npmjs.org/is-root/-/is-root-1.0.0.tgz
npm info attempt registry request try #2 at 13:25:08
npm http fetch GET https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.0.tgz
npm info attempt registry request try #2 at 13:25:08
npm http fetch GET https://registry.npmjs.org/junk/-/junk-1.0.0.tgz
npm info attempt registry request try #2 at 13:25:08
npm http fetch GET https://registry.npmjs.org/mout/-/mout-0.9.1.tgz
npm info attempt registry request try #2 at 13:25:08
npm http fetch GET https://registry.npmjs.org/nopt/-/nopt-3.0.1.tgz
npm info attempt registry request try #2 at 13:25:08
npm http fetch GET https://registry.npmjs.org/opn/-/opn-1.0.1.tgz
npm info attempt registry request try #2 at 13:25:08
npm http fetch GET https://registry.npmjs.org/promptly/-/promptly-0.2.0.tgz
npm info attempt registry request try #2 at 13:25:08
npm http fetch GET https://registry.npmjs.org/request/-/request-2.42.0.tgz
npm info attempt registry request try #2 at 13:25:08
npm http fetch GET https://registry.npmjs.org/tar-fs/-/tar-fs-0.5.2.tgz
npm info attempt registry request try #2 at 13:25:08
npm http fetch GET https://registry.npmjs.org/stringify-object/-/stringify-objec
t-1.0.0.tgz
npm info attempt registry request try #2 at 13:25:08
npm http fetch GET https://registry.npmjs.org/which/-/which-1.0.8.tgz
npm http fetch 200 https://registry.npmjs.org/fstream-ignore/-/fstream-ignore-1.
0.2.tgz
npm http fetch 200 https://registry.npmjs.org/bower-registry-client/-/bower-regi
stry-client-0.2.2.tgz
npm http fetch 200 https://registry.npmjs.org/cardinal/-/cardinal-0.4.0.tgz
npm http fetch 200 https://registry.npmjs.org/fstream/-/fstream-1.0.3.tgz
npm info retry will retry, error on last attempt: Error: read ECONNRESET
npm info retry will retry, error on last attempt: Error: read ECONNRESET
npm http fetch 200 https://registry.npmjs.org/graceful-fs/-/graceful-fs-3.0.5.tg
z
npm http fetch 200 https://registry.npmjs.org/is-root/-/is-root-1.0.0.tgz
npm http fetch 200 https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.0.tgz
npm http fetch 200 https://registry.npmjs.org/junk/-/junk-1.0.0.tgz
npm info retry will retry, error on last attempt: Error: read ECONNRESET
npm info retry will retry, error on last attempt: Error: read ECONNRESET
npm http fetch 200 https://registry.npmjs.org/mout/-/mout-0.9.1.tgz
npm http fetch 200 https://registry.npmjs.org/nopt/-/nopt-3.0.1.tgz
npm http fetch 200 https://registry.npmjs.org/opn/-/opn-1.0.1.tgz
npm http fetch 200 https://registry.npmjs.org/tar-fs/-/tar-fs-0.5.2.tgz
npm http fetch 200 https://registry.npmjs.org/stringify-object/-/stringify-objec
t-1.0.0.tgz
npm info retry will retry, error on last attempt: Error: read ECONNRESET
npm http fetch 200 https://registry.npmjs.org/which/-/which-1.0.8.tgz
npm http fetch 200 https://registry.npmjs.org/request/-/request-2.42.0.tgz
npm info attempt registry request try #3 at 13:26:08
npm http fetch GET https://registry.npmjs.org/bower-endpoint-parser/-/bower-endp
oint-parser-0.2.2.tgz
npm info attempt registry request try #3 at 13:26:08
npm http fetch GET https://registry.npmjs.org/bower-json/-/bower-json-0.4.0.tgz
npm info attempt registry request try #3 at 13:26:08
npm http fetch GET https://registry.npmjs.org/bower-config/-/bower-config-0.5.2.
tgz
npm info attempt registry request try #3 at 13:26:08
npm http fetch GET https://registry.npmjs.org/inquirer/-/inquirer-0.7.1.tgz
npm info attempt registry request try #3 at 13:26:08
npm http fetch GET https://registry.npmjs.org/insight/-/insight-0.4.3.tgz
npm info attempt registry request try #3 at 13:26:08
npm http fetch GET https://registry.npmjs.org/handlebars/-/handlebars-2.0.0.tgz
npm info attempt registry request try #3 at 13:26:08
npm http fetch GET https://registry.npmjs.org/glob/-/glob-4.0.6.tgz
npm info attempt registry request try #3 at 13:26:08
npm http fetch GET https://registry.npmjs.org/promptly/-/promptly-0.2.0.tgz
npm http fetch 200 https://registry.npmjs.org/glob/-/glob-4.0.6.tgz
npm http fetch 200 https://registry.npmjs.org/handlebars/-/handlebars-2.0.0.tgz
npm ERR! cb() never called!`

**Comment by smikes** [comment]
Could you please upload your npm-debug.log as a  gist <http://gist.github.com>? If possible, run npm with at least one `-d` flag to increase the logging level.

I see a lot of `ECONNRESET` errors in the log you posted -- is it possible that you are running into some sort of rate limiting or bandwidth limiting applied by your company's proxy?

**Comment by Thomaspunt** [comment]
https://gist.github.com/Thomaspunt/856f9755d301b4dce940

And there is no npm-debug.log created. This is the output from `npm install -g bower -ddd`. 

Not too sure about rate or bandwidth limiting, but there were no error flags raised according by network admins when using npm.

**Comment by smikes** [comment]
Nothing about that output log jumps out at me; I did notice that the ECONNRESET messages are absent, so it looks like the cache is working fine..

Looks like this may be yet another hard-to-diagnose race condition.  I will ask Forrest to weigh in, since he has been running on Windows in recently (though I don't know if he uses Windows Server 2012, which may be part of the issue...) /cc @othiym23

**Comment by Thomaspunt** [comment]
That's what we concluded, so we're downgrading at the moment to win server 2008 rc2. I'll let you know how that goes with npm.

**Comment by Thomaspunt** [comment]
Downgrading to win server 2008 rc2 resolved the problem. :)

**Comment by othiym23** [comment]
Closing as resolved.
