### ISSUE TITLE
strict-ssl doesn't work correctly in npm 2.3.0

### ISSUE THREAD

**Issue by LoneBoco** [npm/npm#7237]
I am behind a corporate firewall that intercepts SSL traffic and signs it with its own CA certificate.  This causes problems with applications that use their own certificate store as my company's certificates aren't trusted.

I was able to resolve this issue with older npm releases by adding **strict-ssl = false** into my **%USERPROFILE%\\.npmrc** file.  It would ignore the self-signed certificate and be happy.

The latest version of Atom (0.176.0) is packaged with npm 2.3.0 and I am once again getting SELF_SIGNED_CERT_IN_CHAIN errors.  By using the previous version of Atom (0.175.0) with an older npm (2.1.18), I am able to install packages without issues.

Here is a debug log of what happened:
```
0 info it worked if it ends with ok
1 verbose cli [ 'node',
1 verbose cli   'C:\\Users\\JOHN8160\\AppData\\Local\\atom\\app-0.176.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'package.tgz',
1 verbose cli   '--strict-ssl',
1 verbose cli   'false' ]
2 info using npm@2.3.0
3 info using node@v0.10.35
4 silly cache add args [ 'package.tgz', null ]
5 verbose cache add spec package.tgz
6 silly cache add parsed spec { raw: 'package.tgz',
6 silly cache add   scope: null,
6 silly cache add   name: null,
6 silly cache add   rawSpec: 'package.tgz',
6 silly cache add   spec: 'C:\\Users\\JOHN8160\\AppData\\Local\\atom\\app-0.176.0\\resources\\app\\apm\\bin\\package.tgz',
6 silly cache add   type: 'local' }
7 silly addLocalTarball shasum (computed) 3e20299c8ed1ab57323377416a5d02d2ff9cccfb
8 verbose addTmpTarball C:\Users\JOHN8160\AppData\Local\atom\app-0.176.0\resources\app\apm\bin\package.tgz not in flight; adding
9 verbose addTmpTarball validating metadata from C:\Users\JOHN8160\AppData\Local\atom\app-0.176.0\resources\app\apm\bin\package.tgz
10 verbose tar unpack C:\Users\JOHN8160\AppData\Local\atom\app-0.176.0\resources\app\apm\bin\package.tgz
11 verbose tar unpacking to C:\Users\JOHN8160\AppData\Local\Temp\npm-5000-3c29fb77\unpack-271b6e3e53ec
12 verbose gentlyRm vacuuming C:\Users\JOHN8160\AppData\Local\Temp\npm-5000-3c29fb77\unpack-271b6e3e53ec
13 silly gunzTarPerm modes [ '777', '666' ]
14 silly gunzTarPerm extractEntry
15 silly gunzTarPerm modified mode [ '', 509, 511 ]
16 silly gunzTarPerm extractEntry .gitignore
17 silly gunzTarPerm modified mode [ '.gitignore', 436, 438 ]
18 silly gunzTarPerm extractEntry .pairs
19 silly gunzTarPerm modified mode [ '.pairs', 436, 438 ]
20 silly gunzTarPerm extractEntry .travis.yml
21 silly gunzTarPerm modified mode [ '.travis.yml', 436, 438 ]
22 silly gunzTarPerm extractEntry CONTRIBUTING.md
23 silly gunzTarPerm modified mode [ 'CONTRIBUTING.md', 436, 438 ]
24 silly gunzTarPerm extractEntry LICENSE.md
25 silly gunzTarPerm modified mode [ 'LICENSE.md', 436, 438 ]
26 silly gunzTarPerm extractEntry README.md
27 silly gunzTarPerm modified mode [ 'README.md', 436, 438 ]
28 silly gunzTarPerm extractEntry keymaps/
29 silly gunzTarPerm modified mode [ 'keymaps/', 509, 511 ]
30 silly gunzTarPerm extractEntry keymaps/autocomplete-plus.cson
31 silly gunzTarPerm modified mode [ 'keymaps/autocomplete-plus.cson', 436, 438 ]
32 silly gunzTarPerm extractEntry lib/
33 silly gunzTarPerm modified mode [ 'lib/', 509, 511 ]
34 silly gunzTarPerm extractEntry lib/autocomplete-manager.coffee
35 silly gunzTarPerm modified mode [ 'lib/autocomplete-manager.coffee', 436, 438 ]
36 silly gunzTarPerm extractEntry lib/fuzzy-provider.coffee
37 silly gunzTarPerm modified mode [ 'lib/fuzzy-provider.coffee', 436, 438 ]
38 silly gunzTarPerm extractEntry lib/main.coffee
39 silly gunzTarPerm modified mode [ 'lib/main.coffee', 436, 438 ]
40 silly gunzTarPerm extractEntry lib/provider-manager.coffee
41 silly gunzTarPerm modified mode [ 'lib/provider-manager.coffee', 436, 438 ]
42 silly gunzTarPerm extractEntry lib/provider.coffee
43 silly gunzTarPerm modified mode [ 'lib/provider.coffee', 436, 438 ]
44 silly gunzTarPerm extractEntry lib/suggestion-list-element.coffee
45 silly gunzTarPerm modified mode [ 'lib/suggestion-list-element.coffee', 436, 438 ]
46 silly gunzTarPerm extractEntry lib/suggestion-list.coffee
47 silly gunzTarPerm modified mode [ 'lib/suggestion-list.coffee', 436, 438 ]
48 silly gunzTarPerm extractEntry lib/suggestion.coffee
49 silly gunzTarPerm modified mode [ 'lib/suggestion.coffee', 436, 438 ]
50 silly gunzTarPerm extractEntry package.json
51 silly gunzTarPerm modified mode [ 'package.json', 436, 438 ]
52 silly gunzTarPerm extractEntry spec/
53 silly gunzTarPerm modified mode [ 'spec/', 509, 511 ]
54 silly gunzTarPerm extractEntry spec/autocomplete-blacklist-spec.coffee
55 silly gunzTarPerm modified mode [ 'spec/autocomplete-blacklist-spec.coffee', 436, 438 ]
56 silly gunzTarPerm extractEntry spec/autocomplete-manager-async-spec.coffee
57 silly gunzTarPerm modified mode [ 'spec/autocomplete-manager-async-spec.coffee', 436, 438 ]
58 silly gunzTarPerm extractEntry spec/autocomplete-manager-integration-spec.coffee
59 silly gunzTarPerm modified mode [ 'spec/autocomplete-manager-integration-spec.coffee', 436, 438 ]
60 silly gunzTarPerm extractEntry spec/autocomplete-manager-undo-spec.coffee
61 silly gunzTarPerm modified mode [ 'spec/autocomplete-manager-undo-spec.coffee', 436, 438 ]
62 silly gunzTarPerm extractEntry spec/fixtures/
63 silly gunzTarPerm modified mode [ 'spec/fixtures/', 509, 511 ]
64 silly gunzTarPerm extractEntry spec/fixtures/blacklisted.md
65 silly gunzTarPerm modified mode [ 'spec/fixtures/blacklisted.md', 436, 438 ]
66 silly gunzTarPerm extractEntry spec/fixtures/css.css
67 silly gunzTarPerm modified mode [ 'spec/fixtures/css.css', 436, 438 ]
68 silly gunzTarPerm extractEntry spec/fixtures/issues/
69 silly gunzTarPerm modified mode [ 'spec/fixtures/issues/', 509, 511 ]
70 silly gunzTarPerm extractEntry spec/fixtures/issues/11.js
71 silly gunzTarPerm modified mode [ 'spec/fixtures/issues/11.js', 436, 438 ]
72 silly gunzTarPerm extractEntry spec/fixtures/issues/15.js
73 silly gunzTarPerm modified mode [ 'spec/fixtures/issues/15.js', 436, 438 ]
74 silly gunzTarPerm extractEntry spec/fixtures/issues/23-25.js
75 silly gunzTarPerm modified mode [ 'spec/fixtures/issues/23-25.js', 436, 438 ]
76 silly gunzTarPerm extractEntry spec/fixtures/issues/50.js
77 silly gunzTarPerm modified mode [ 'spec/fixtures/issues/50.js', 436, 438 ]
78 silly gunzTarPerm extractEntry spec/fixtures/issues/57.js
79 silly gunzTarPerm modified mode [ 'spec/fixtures/issues/57.js', 436, 438 ]
80 silly gunzTarPerm extractEntry spec/fixtures/issues/64.css
81 silly gunzTarPerm modified mode [ 'spec/fixtures/issues/64.css', 436, 438 ]
82 silly gunzTarPerm extractEntry spec/fixtures/sample.js
83 silly gunzTarPerm modified mode [ 'spec/fixtures/sample.js', 436, 438 ]
84 silly gunzTarPerm extractEntry spec/fixtures/sample.txt
85 silly gunzTarPerm modified mode [ 'spec/fixtures/sample.txt', 436, 438 ]
86 silly gunzTarPerm extractEntry spec/fixtures/samplelong.js
87 silly gunzTarPerm modified mode [ 'spec/fixtures/samplelong.js', 436, 438 ]
88 silly gunzTarPerm extractEntry spec/fuzzy-provider-spec.coffee
89 silly gunzTarPerm modified mode [ 'spec/fuzzy-provider-spec.coffee', 436, 438 ]
90 silly gunzTarPerm extractEntry spec/html-label-spec.coffee
91 silly gunzTarPerm modified mode [ 'spec/html-label-spec.coffee', 436, 438 ]
92 silly gunzTarPerm extractEntry spec/issues/
93 silly gunzTarPerm modified mode [ 'spec/issues/', 509, 511 ]
94 silly gunzTarPerm extractEntry spec/issues/11-spec.coffee
95 silly gunzTarPerm modified mode [ 'spec/issues/11-spec.coffee', 436, 438 ]
96 silly gunzTarPerm extractEntry spec/issues/15-spec.coffee
97 silly gunzTarPerm modified mode [ 'spec/issues/15-spec.coffee', 436, 438 ]
98 silly gunzTarPerm extractEntry spec/issues/23-25-spec.coffee
99 silly gunzTarPerm modified mode [ 'spec/issues/23-25-spec.coffee', 436, 438 ]
100 silly gunzTarPerm extractEntry spec/issues/50-spec.coffee
101 silly gunzTarPerm modified mode [ 'spec/issues/50-spec.coffee', 436, 438 ]
102 silly gunzTarPerm extractEntry spec/issues/52-spec.coffee
103 silly gunzTarPerm modified mode [ 'spec/issues/52-spec.coffee', 436, 438 ]
104 silly gunzTarPerm extractEntry spec/issues/56-spec.coffee
105 silly gunzTarPerm modified mode [ 'spec/issues/56-spec.coffee', 436, 438 ]
106 silly gunzTarPerm extractEntry spec/issues/57-spec.coffee
107 silly gunzTarPerm modified mode [ 'spec/issues/57-spec.coffee', 436, 438 ]
108 silly gunzTarPerm extractEntry spec/issues/63-spec.coffee
109 silly gunzTarPerm modified mode [ 'spec/issues/63-spec.coffee', 436, 438 ]
110 silly gunzTarPerm extractEntry spec/issues/64-spec.coffee
111 silly gunzTarPerm modified mode [ 'spec/issues/64-spec.coffee', 436, 438 ]
112 silly gunzTarPerm extractEntry spec/issues/65-spec.coffee
113 silly gunzTarPerm modified mode [ 'spec/issues/65-spec.coffee', 436, 438 ]
114 silly gunzTarPerm extractEntry spec/issues/67-spec.coffee
115 silly gunzTarPerm modified mode [ 'spec/issues/67-spec.coffee', 436, 438 ]
116 silly gunzTarPerm extractEntry spec/language-css-spec.coffee
117 silly gunzTarPerm modified mode [ 'spec/language-css-spec.coffee', 436, 438 ]
118 silly gunzTarPerm extractEntry spec/lib/
119 silly gunzTarPerm modified mode [ 'spec/lib/', 509, 511 ]
120 silly gunzTarPerm extractEntry spec/lib/test-provider.coffee
121 silly gunzTarPerm modified mode [ 'spec/lib/test-provider.coffee', 436, 438 ]
122 silly gunzTarPerm extractEntry spec/main-spec.coffee
123 silly gunzTarPerm modified mode [ 'spec/main-spec.coffee', 436, 438 ]
124 silly gunzTarPerm extractEntry spec/provider-api-spec.coffee
125 silly gunzTarPerm modified mode [ 'spec/provider-api-spec.coffee', 436, 438 ]
126 silly gunzTarPerm extractEntry spec/provider-manager-spec.coffee
127 silly gunzTarPerm modified mode [ 'spec/provider-manager-spec.coffee', 436, 438 ]
128 silly gunzTarPerm extractEntry spec/spec-helper.coffee
129 silly gunzTarPerm modified mode [ 'spec/spec-helper.coffee', 436, 438 ]
130 silly gunzTarPerm extractEntry styles/
131 silly gunzTarPerm modified mode [ 'styles/', 509, 511 ]
132 silly gunzTarPerm extractEntry styles/autocomplete.less
133 silly gunzTarPerm modified mode [ 'styles/autocomplete.less', 436, 438 ]
134 silly cache afterAdd autocomplete-plus@2.0.1
135 verbose afterAdd C:\Users\JOHN8160\AppData\Roaming\npm-cache\autocomplete-plus\2.0.1\package\package.json not in flight; writing
136 verbose afterAdd C:\Users\JOHN8160\AppData\Roaming\npm-cache\autocomplete-plus\2.0.1\package\package.json written
137 silly install resolved [ { name: 'autocomplete-plus',
137 silly install resolved     version: '2.0.1',
137 silly install resolved     main: './lib/main',
137 silly install resolved     description: 'Display possible completions in the editor while typing',
137 silly install resolved     repository:
137 silly install resolved      { type: 'git',
137 silly install resolved        url: 'https://github.com/atom-community/autocomplete-plus' },
137 silly install resolved     engines: { atom: '*' },
137 silly install resolved     dependencies:
137 silly install resolved      { async: '>=0.9.0',
137 silly install resolved        'event-kit': '>=0.8.1',
137 silly install resolved        fuzzaldrin: '>=1.0.0',
137 silly install resolved        grim: '>=0.12.0',
137 silly install resolved        minimatch: '>=0.2.14',
137 silly install resolved        'node-uuid': '>=1.4.1',
137 silly install resolved        'scoped-property-store': '>=0.16.2',
137 silly install resolved        temp: '>=0.7.0',
137 silly install resolved        theorist: '>=1.0.2',
137 silly install resolved        'underscore-plus': '>=1.0.0' },
137 silly install resolved     readme: '# autocomplete+ package [![Build Status](https://travis-ci.org/atom-community/autocomplete-plus.svg?branch=master)](https://travis-ci.org/atom-community/autocomplete-plus) [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/atom-community/autocomplete-plus)\n\n\n[View the changelog](https://github.com/atom-community/autocomplete-plus/releases)\n\nView and insert possible completions in the editor while typing\n\n![Autocomplete+](http://s14.directupload.net/images/140304/y7r7g5df.gif)\n\n**Note:** In the example above, `Show Suggestions On Keystroke` is enabled.\n\n![The Show Suggestions On Keystroke Setting](https://cloud.githubusercontent.com/assets/744740/5886909/a7071c2a-a372-11e4-9894-f12db4e8a1ae.png)\n\n## Installation\n\n* APM: `apm install autocomplete-plus`\n* Preferences: Open Atom and go to `Preferences > Packages`, search for `autocomplete-plus`, and install it\n\n## Providers\n\n`autocomplete+` has a powerful autocomplete provider API, allowing provider authors to add language-specific behavior to this package.\n\nYou should *definitely* install additional providers (the default provider bundled with this package is somewhat crude): https://github.com/atom-community/autocomplete-plus/wiki/Autocomplete-Providers\n\n## Usage\n\nJust type some stuff, and autocomplete+ will automatically show you some suggestions.\nPress `UP` and `DOWN` to select another suggestion, press `TAB` to confirm your selection. You can change the default keymap in `Preferences`:\n\n* Keymap For Confirming A Suggestion\n* Keymap For Navigating The Suggestion List\n\nAdditionally, the keymap can be customized in your keymap.cson:\n\n```coffeescript\n\'atom-text-editor:not(mini) .autocomplete-plus.autocomplete-suggestion-list\':\n  \'tab\': \'unset!\'\n  \'enter\': \'autocomplete-plus:confirm\'\n  \'up\': \'unset!\'\n  \'down\': \'unset!\'\n  \'ctrl-p\': \'autocomplete-plus:select-previous\'\n  \'ctrl-n\': \'autocomplete-plus:select-next\'\n```\n\n## Features\n\n* Shows suggestions while typing\n* Includes a default provider (`FuzzyProvider`):\n  * Wordlist generation happens when you open a file, while editing the file, and on save\n  * Suggestions are calculated using `fuzzaldrin`\n* Exposes a provider API which can be used to extend the functionality of the package and provide targeted / contextually correct suggestions\n* Disable autocomplete for file(s) via blacklisting\n* Disable autocomplete for editor scope(s) via blacklisting\n\n## Provider API\n\nGreat autocomplete depends on having great autocomplete providers. If there is not already a great provider for the language / grammar that you are working in, please consider creating a provider.\n\n[Read the `Provider API` documentation](https://github.com/atom-community/autocomplete-plus/wiki/Provider-API) to learn how to create a new autocomplete provider.\n',
137 silly install resolved     readmeFilename: 'README.md',
137 silly install resolved     bugs: { url: 'https://github.com/atom-community/autocomplete-plus/issues' },
137 silly install resolved     homepage: 'https://github.com/atom-community/autocomplete-plus',
137 silly install resolved     _id: 'autocomplete-plus@2.0.1',
137 silly install resolved     _shasum: '3e20299c8ed1ab57323377416a5d02d2ff9cccfb',
137 silly install resolved     _resolved: 'file:bin\\package.tgz',
137 silly install resolved     _from: 'bin\\package.tgz' } ]
138 info install autocomplete-plus@2.0.1 into C:\Users\JOHN8160\AppData\Local\atom\app-0.176.0\resources\app\apm
139 info installOne autocomplete-plus@2.0.1
140 verbose installOne of autocomplete-plus to C:\Users\JOHN8160\AppData\Local\atom\app-0.176.0\resources\app\apm not in flight; installing
141 verbose lock using C:\Users\JOHN8160\AppData\Roaming\npm-cache\_locks\autocomplete-plus-8a78fd2ef2006116.lock for C:\Users\JOHN8160\AppData\Local\atom\app-0.176.0\resources\app\apm\node_modules\autocomplete-plus
142 silly install write writing autocomplete-plus 2.0.1 to C:\Users\JOHN8160\AppData\Local\atom\app-0.176.0\resources\app\apm\node_modules\autocomplete-plus
143 silly cache addNamed cb autocomplete-plus@2.0.1
144 verbose unbuild node_modules\autocomplete-plus
145 verbose gentlyRm vacuuming C:\Users\JOHN8160\AppData\Local\atom\app-0.176.0\resources\app\apm\node_modules\autocomplete-plus
146 verbose tar unpack C:\Users\JOHN8160\AppData\Roaming\npm-cache\autocomplete-plus\2.0.1\package.tgz
147 verbose tar unpacking to C:\Users\JOHN8160\AppData\Local\atom\app-0.176.0\resources\app\apm\node_modules\autocomplete-plus
148 verbose gentlyRm vacuuming C:\Users\JOHN8160\AppData\Local\atom\app-0.176.0\resources\app\apm\node_modules\autocomplete-plus
149 silly gunzTarPerm modes [ '777', '666' ]
150 silly gunzTarPerm extractEntry
151 silly gunzTarPerm modified mode [ '', 509, 511 ]
152 silly gunzTarPerm extractEntry .gitignore
153 silly gunzTarPerm modified mode [ '.gitignore', 436, 438 ]
154 silly gunzTarPerm extractEntry .pairs
155 silly gunzTarPerm modified mode [ '.pairs', 436, 438 ]
156 silly gunzTarPerm extractEntry .travis.yml
157 silly gunzTarPerm modified mode [ '.travis.yml', 436, 438 ]
158 silly gunzTarPerm extractEntry CONTRIBUTING.md
159 silly gunzTarPerm modified mode [ 'CONTRIBUTING.md', 436, 438 ]
160 silly gunzTarPerm extractEntry LICENSE.md
161 silly gunzTarPerm modified mode [ 'LICENSE.md', 436, 438 ]
162 silly gunzTarPerm extractEntry README.md
163 silly gunzTarPerm modified mode [ 'README.md', 436, 438 ]
164 silly gunzTarPerm extractEntry keymaps/
165 silly gunzTarPerm modified mode [ 'keymaps/', 509, 511 ]
166 silly gunzTarPerm extractEntry keymaps/autocomplete-plus.cson
167 silly gunzTarPerm modified mode [ 'keymaps/autocomplete-plus.cson', 436, 438 ]
168 silly gunzTarPerm extractEntry lib/
169 silly gunzTarPerm modified mode [ 'lib/', 509, 511 ]
170 silly gunzTarPerm extractEntry lib/autocomplete-manager.coffee
171 silly gunzTarPerm modified mode [ 'lib/autocomplete-manager.coffee', 436, 438 ]
172 silly gunzTarPerm extractEntry lib/fuzzy-provider.coffee
173 silly gunzTarPerm modified mode [ 'lib/fuzzy-provider.coffee', 436, 438 ]
174 silly gunzTarPerm extractEntry lib/main.coffee
175 silly gunzTarPerm modified mode [ 'lib/main.coffee', 436, 438 ]
176 silly gunzTarPerm extractEntry lib/provider-manager.coffee
177 silly gunzTarPerm modified mode [ 'lib/provider-manager.coffee', 436, 438 ]
178 silly gunzTarPerm extractEntry lib/provider.coffee
179 silly gunzTarPerm modified mode [ 'lib/provider.coffee', 436, 438 ]
180 silly gunzTarPerm extractEntry lib/suggestion-list-element.coffee
181 silly gunzTarPerm modified mode [ 'lib/suggestion-list-element.coffee', 436, 438 ]
182 silly gunzTarPerm extractEntry lib/suggestion-list.coffee
183 silly gunzTarPerm modified mode [ 'lib/suggestion-list.coffee', 436, 438 ]
184 silly gunzTarPerm extractEntry lib/suggestion.coffee
185 silly gunzTarPerm modified mode [ 'lib/suggestion.coffee', 436, 438 ]
186 silly gunzTarPerm extractEntry package.json
187 silly gunzTarPerm modified mode [ 'package.json', 436, 438 ]
188 silly gunzTarPerm extractEntry spec/
189 silly gunzTarPerm modified mode [ 'spec/', 509, 511 ]
190 silly gunzTarPerm extractEntry spec/autocomplete-blacklist-spec.coffee
191 silly gunzTarPerm modified mode [ 'spec/autocomplete-blacklist-spec.coffee', 436, 438 ]
192 silly gunzTarPerm extractEntry spec/autocomplete-manager-async-spec.coffee
193 silly gunzTarPerm modified mode [ 'spec/autocomplete-manager-async-spec.coffee', 436, 438 ]
194 silly gunzTarPerm extractEntry spec/autocomplete-manager-integration-spec.coffee
195 silly gunzTarPerm modified mode [ 'spec/autocomplete-manager-integration-spec.coffee', 436, 438 ]
196 silly gunzTarPerm extractEntry spec/autocomplete-manager-undo-spec.coffee
197 silly gunzTarPerm modified mode [ 'spec/autocomplete-manager-undo-spec.coffee', 436, 438 ]
198 silly gunzTarPerm extractEntry spec/fixtures/
199 silly gunzTarPerm modified mode [ 'spec/fixtures/', 509, 511 ]
200 silly gunzTarPerm extractEntry spec/fixtures/blacklisted.md
201 silly gunzTarPerm modified mode [ 'spec/fixtures/blacklisted.md', 436, 438 ]
202 silly gunzTarPerm extractEntry spec/fixtures/css.css
203 silly gunzTarPerm modified mode [ 'spec/fixtures/css.css', 436, 438 ]
204 silly gunzTarPerm extractEntry spec/fixtures/issues/
205 silly gunzTarPerm modified mode [ 'spec/fixtures/issues/', 509, 511 ]
206 silly gunzTarPerm extractEntry spec/fixtures/issues/11.js
207 silly gunzTarPerm modified mode [ 'spec/fixtures/issues/11.js', 436, 438 ]
208 silly gunzTarPerm extractEntry spec/fixtures/issues/15.js
209 silly gunzTarPerm modified mode [ 'spec/fixtures/issues/15.js', 436, 438 ]
210 silly gunzTarPerm extractEntry spec/fixtures/issues/23-25.js
211 silly gunzTarPerm modified mode [ 'spec/fixtures/issues/23-25.js', 436, 438 ]
212 silly gunzTarPerm extractEntry spec/fixtures/issues/50.js
213 silly gunzTarPerm modified mode [ 'spec/fixtures/issues/50.js', 436, 438 ]
214 silly gunzTarPerm extractEntry spec/fixtures/issues/57.js
215 silly gunzTarPerm modified mode [ 'spec/fixtures/issues/57.js', 436, 438 ]
216 silly gunzTarPerm extractEntry spec/fixtures/issues/64.css
217 silly gunzTarPerm modified mode [ 'spec/fixtures/issues/64.css', 436, 438 ]
218 silly gunzTarPerm extractEntry spec/fixtures/sample.js
219 silly gunzTarPerm modified mode [ 'spec/fixtures/sample.js', 436, 438 ]
220 silly gunzTarPerm extractEntry spec/fixtures/sample.txt
221 silly gunzTarPerm modified mode [ 'spec/fixtures/sample.txt', 436, 438 ]
222 silly gunzTarPerm extractEntry spec/fixtures/samplelong.js
223 silly gunzTarPerm modified mode [ 'spec/fixtures/samplelong.js', 436, 438 ]
224 silly gunzTarPerm extractEntry spec/fuzzy-provider-spec.coffee
225 silly gunzTarPerm modified mode [ 'spec/fuzzy-provider-spec.coffee', 436, 438 ]
226 silly gunzTarPerm extractEntry spec/html-label-spec.coffee
227 silly gunzTarPerm modified mode [ 'spec/html-label-spec.coffee', 436, 438 ]
228 silly gunzTarPerm extractEntry spec/issues/
229 silly gunzTarPerm modified mode [ 'spec/issues/', 509, 511 ]
230 silly gunzTarPerm extractEntry spec/issues/11-spec.coffee
231 silly gunzTarPerm modified mode [ 'spec/issues/11-spec.coffee', 436, 438 ]
232 silly gunzTarPerm extractEntry spec/issues/15-spec.coffee
233 silly gunzTarPerm modified mode [ 'spec/issues/15-spec.coffee', 436, 438 ]
234 silly gunzTarPerm extractEntry spec/issues/23-25-spec.coffee
235 silly gunzTarPerm modified mode [ 'spec/issues/23-25-spec.coffee', 436, 438 ]
236 silly gunzTarPerm extractEntry spec/issues/50-spec.coffee
237 silly gunzTarPerm modified mode [ 'spec/issues/50-spec.coffee', 436, 438 ]
238 silly gunzTarPerm extractEntry spec/issues/52-spec.coffee
239 silly gunzTarPerm modified mode [ 'spec/issues/52-spec.coffee', 436, 438 ]
240 silly gunzTarPerm extractEntry spec/issues/56-spec.coffee
241 silly gunzTarPerm modified mode [ 'spec/issues/56-spec.coffee', 436, 438 ]
242 silly gunzTarPerm extractEntry spec/issues/57-spec.coffee
243 silly gunzTarPerm modified mode [ 'spec/issues/57-spec.coffee', 436, 438 ]
244 silly gunzTarPerm extractEntry spec/issues/63-spec.coffee
245 silly gunzTarPerm modified mode [ 'spec/issues/63-spec.coffee', 436, 438 ]
246 silly gunzTarPerm extractEntry spec/issues/64-spec.coffee
247 silly gunzTarPerm modified mode [ 'spec/issues/64-spec.coffee', 436, 438 ]
248 silly gunzTarPerm extractEntry spec/issues/65-spec.coffee
249 silly gunzTarPerm modified mode [ 'spec/issues/65-spec.coffee', 436, 438 ]
250 silly gunzTarPerm extractEntry spec/issues/67-spec.coffee
251 silly gunzTarPerm modified mode [ 'spec/issues/67-spec.coffee', 436, 438 ]
252 silly gunzTarPerm extractEntry spec/language-css-spec.coffee
253 silly gunzTarPerm modified mode [ 'spec/language-css-spec.coffee', 436, 438 ]
254 silly gunzTarPerm extractEntry spec/lib/
255 silly gunzTarPerm modified mode [ 'spec/lib/', 509, 511 ]
256 silly gunzTarPerm extractEntry spec/lib/test-provider.coffee
257 silly gunzTarPerm modified mode [ 'spec/lib/test-provider.coffee', 436, 438 ]
258 silly gunzTarPerm extractEntry spec/main-spec.coffee
259 silly gunzTarPerm modified mode [ 'spec/main-spec.coffee', 436, 438 ]
260 silly gunzTarPerm extractEntry spec/provider-api-spec.coffee
261 silly gunzTarPerm modified mode [ 'spec/provider-api-spec.coffee', 436, 438 ]
262 silly gunzTarPerm extractEntry spec/provider-manager-spec.coffee
263 silly gunzTarPerm modified mode [ 'spec/provider-manager-spec.coffee', 436, 438 ]
264 silly gunzTarPerm extractEntry spec/spec-helper.coffee
265 silly gunzTarPerm modified mode [ 'spec/spec-helper.coffee', 436, 438 ]
266 silly gunzTarPerm extractEntry styles/
267 silly gunzTarPerm modified mode [ 'styles/', 509, 511 ]
268 silly gunzTarPerm extractEntry styles/autocomplete.less
269 silly gunzTarPerm modified mode [ 'styles/autocomplete.less', 436, 438 ]
270 info preinstall autocomplete-plus@2.0.1
271 silly prepareForInstallMany adding async@>=0.9.0 from autocomplete-plus dependencies
272 silly prepareForInstallMany adding event-kit@>=0.8.1 from autocomplete-plus dependencies
273 silly prepareForInstallMany adding fuzzaldrin@>=1.0.0 from autocomplete-plus dependencies
274 silly prepareForInstallMany adding grim@>=0.12.0 from autocomplete-plus dependencies
275 silly prepareForInstallMany adding minimatch@>=0.2.14 from autocomplete-plus dependencies
276 silly prepareForInstallMany adding node-uuid@>=1.4.1 from autocomplete-plus dependencies
277 silly prepareForInstallMany adding scoped-property-store@>=0.16.2 from autocomplete-plus dependencies
278 silly prepareForInstallMany adding theorist@>=1.0.2 from autocomplete-plus dependencies
279 silly cache add args [ 'async@>=0.9.0', null ]
280 verbose cache add spec async@>=0.9.0
281 silly cache add args [ 'event-kit@>=0.8.1', null ]
282 verbose cache add spec event-kit@>=0.8.1
283 silly cache add parsed spec { raw: 'async@>=0.9.0',
283 silly cache add   scope: null,
283 silly cache add   name: 'async',
283 silly cache add   rawSpec: '>=0.9.0',
283 silly cache add   spec: '>=0.9.0',
283 silly cache add   type: 'range' }
284 verbose addNamed async@>=0.9.0
285 silly addNamed semver.valid null
286 silly addNamed semver.validRange >=0.9.0
287 silly addNameRange { name: 'async', range: '>=0.9.0', hasData: false }
288 silly mapToRegistry name async
289 silly mapToRegistry using default registry
290 silly mapToRegistry registry https://registry.npmjs.org/
291 silly mapToRegistry uri https://registry.npmjs.org/async
292 verbose addNameRange registry:https://registry.npmjs.org/async not in flight; fetching
293 silly cache add parsed spec { raw: 'event-kit@>=0.8.1',
293 silly cache add   scope: null,
293 silly cache add   name: 'event-kit',
293 silly cache add   rawSpec: '>=0.8.1',
293 silly cache add   spec: '>=0.8.1',
293 silly cache add   type: 'range' }
294 verbose addNamed event-kit@>=0.8.1
295 silly addNamed semver.valid null
296 silly addNamed semver.validRange >=0.8.1
297 silly addNameRange { name: 'event-kit', range: '>=0.8.1', hasData: false }
298 silly mapToRegistry name event-kit
299 silly mapToRegistry using default registry
300 silly mapToRegistry registry https://registry.npmjs.org/
301 silly mapToRegistry uri https://registry.npmjs.org/event-kit
302 verbose addNameRange registry:https://registry.npmjs.org/event-kit not in flight; fetching
303 silly cache add args [ 'fuzzaldrin@>=1.0.0', null ]
304 verbose cache add spec fuzzaldrin@>=1.0.0
305 silly cache add parsed spec { raw: 'fuzzaldrin@>=1.0.0',
305 silly cache add   scope: null,
305 silly cache add   name: 'fuzzaldrin',
305 silly cache add   rawSpec: '>=1.0.0',
305 silly cache add   spec: '>=1.0.0',
305 silly cache add   type: 'range' }
306 verbose addNamed fuzzaldrin@>=1.0.0
307 silly addNamed semver.valid null
308 silly addNamed semver.validRange >=1.0.0
309 silly addNameRange { name: 'fuzzaldrin', range: '>=1.0.0', hasData: false }
310 silly mapToRegistry name fuzzaldrin
311 silly mapToRegistry using default registry
312 silly mapToRegistry registry https://registry.npmjs.org/
313 silly mapToRegistry uri https://registry.npmjs.org/fuzzaldrin
314 verbose addNameRange registry:https://registry.npmjs.org/fuzzaldrin not in flight; fetching
315 silly cache add args [ 'grim@>=0.12.0', null ]
316 verbose cache add spec grim@>=0.12.0
317 silly cache add parsed spec { raw: 'grim@>=0.12.0',
317 silly cache add   scope: null,
317 silly cache add   name: 'grim',
317 silly cache add   rawSpec: '>=0.12.0',
317 silly cache add   spec: '>=0.12.0',
317 silly cache add   type: 'range' }
318 verbose addNamed grim@>=0.12.0
319 silly addNamed semver.valid null
320 silly addNamed semver.validRange >=0.12.0
321 silly addNameRange { name: 'grim', range: '>=0.12.0', hasData: false }
322 silly mapToRegistry name grim
323 silly mapToRegistry using default registry
324 silly mapToRegistry registry https://registry.npmjs.org/
325 silly mapToRegistry uri https://registry.npmjs.org/grim
326 verbose addNameRange registry:https://registry.npmjs.org/grim not in flight; fetching
327 silly cache add args [ 'minimatch@>=0.2.14', null ]
328 verbose cache add spec minimatch@>=0.2.14
329 silly cache add parsed spec { raw: 'minimatch@>=0.2.14',
329 silly cache add   scope: null,
329 silly cache add   name: 'minimatch',
329 silly cache add   rawSpec: '>=0.2.14',
329 silly cache add   spec: '>=0.2.14',
329 silly cache add   type: 'range' }
330 verbose addNamed minimatch@>=0.2.14
331 silly addNamed semver.valid null
332 silly addNamed semver.validRange >=0.2.14
333 silly addNameRange { name: 'minimatch', range: '>=0.2.14', hasData: false }
334 silly mapToRegistry name minimatch
335 silly mapToRegistry using default registry
336 silly mapToRegistry registry https://registry.npmjs.org/
337 silly mapToRegistry uri https://registry.npmjs.org/minimatch
338 verbose addNameRange registry:https://registry.npmjs.org/minimatch not in flight; fetching
339 silly cache add args [ 'node-uuid@>=1.4.1', null ]
340 verbose cache add spec node-uuid@>=1.4.1
341 silly cache add parsed spec { raw: 'node-uuid@>=1.4.1',
341 silly cache add   scope: null,
341 silly cache add   name: 'node-uuid',
341 silly cache add   rawSpec: '>=1.4.1',
341 silly cache add   spec: '>=1.4.1',
341 silly cache add   type: 'range' }
342 verbose addNamed node-uuid@>=1.4.1
343 silly addNamed semver.valid null
344 silly addNamed semver.validRange >=1.4.1
345 silly addNameRange { name: 'node-uuid', range: '>=1.4.1', hasData: false }
346 silly mapToRegistry name node-uuid
347 silly mapToRegistry using default registry
348 silly mapToRegistry registry https://registry.npmjs.org/
349 silly mapToRegistry uri https://registry.npmjs.org/node-uuid
350 verbose addNameRange registry:https://registry.npmjs.org/node-uuid not in flight; fetching
351 silly cache add args [ 'scoped-property-store@>=0.16.2', null ]
352 verbose cache add spec scoped-property-store@>=0.16.2
353 silly cache add parsed spec { raw: 'scoped-property-store@>=0.16.2',
353 silly cache add   scope: null,
353 silly cache add   name: 'scoped-property-store',
353 silly cache add   rawSpec: '>=0.16.2',
353 silly cache add   spec: '>=0.16.2',
353 silly cache add   type: 'range' }
354 verbose addNamed scoped-property-store@>=0.16.2
355 silly addNamed semver.valid null
356 silly addNamed semver.validRange >=0.16.2
357 silly addNameRange { name: 'scoped-property-store',
357 silly addNameRange   range: '>=0.16.2',
357 silly addNameRange   hasData: false }
358 silly mapToRegistry name scoped-property-store
359 silly mapToRegistry using default registry
360 silly mapToRegistry registry https://registry.npmjs.org/
361 silly mapToRegistry uri https://registry.npmjs.org/scoped-property-store
362 verbose addNameRange registry:https://registry.npmjs.org/scoped-property-store not in flight; fetching
363 silly cache add args [ 'theorist@>=1.0.2', null ]
364 verbose cache add spec theorist@>=1.0.2
365 silly cache add parsed spec { raw: 'theorist@>=1.0.2',
365 silly cache add   scope: null,
365 silly cache add   name: 'theorist',
365 silly cache add   rawSpec: '>=1.0.2',
365 silly cache add   spec: '>=1.0.2',
365 silly cache add   type: 'range' }
366 verbose addNamed theorist@>=1.0.2
367 silly addNamed semver.valid null
368 silly addNamed semver.validRange >=1.0.2
369 silly addNameRange { name: 'theorist', range: '>=1.0.2', hasData: false }
370 silly mapToRegistry name theorist
371 silly mapToRegistry using default registry
372 silly mapToRegistry registry https://registry.npmjs.org/
373 silly mapToRegistry uri https://registry.npmjs.org/theorist
374 verbose addNameRange registry:https://registry.npmjs.org/theorist not in flight; fetching
375 verbose request uri https://registry.npmjs.org/async
376 verbose request no auth needed
377 info attempt registry request try #1 at 11:06:54
378 verbose request id e9644c544990afc8
379 http request GET https://registry.npmjs.org/async
380 verbose request uri https://registry.npmjs.org/event-kit
381 verbose request no auth needed
382 info attempt registry request try #1 at 11:06:54
383 http request GET https://registry.npmjs.org/event-kit
384 verbose request uri https://registry.npmjs.org/fuzzaldrin
385 verbose request no auth needed
386 info attempt registry request try #1 at 11:06:54
387 http request GET https://registry.npmjs.org/fuzzaldrin
388 verbose request uri https://registry.npmjs.org/grim
389 verbose request no auth needed
390 info attempt registry request try #1 at 11:06:54
391 http request GET https://registry.npmjs.org/grim
392 verbose request uri https://registry.npmjs.org/minimatch
393 verbose request no auth needed
394 info attempt registry request try #1 at 11:06:54
395 http request GET https://registry.npmjs.org/minimatch
396 verbose request uri https://registry.npmjs.org/node-uuid
397 verbose request no auth needed
398 info attempt registry request try #1 at 11:06:54
399 http request GET https://registry.npmjs.org/node-uuid
400 verbose request uri https://registry.npmjs.org/scoped-property-store
401 verbose request no auth needed
402 info attempt registry request try #1 at 11:06:54
403 http request GET https://registry.npmjs.org/scoped-property-store
404 verbose request uri https://registry.npmjs.org/theorist
405 verbose request no auth needed
406 info attempt registry request try #1 at 11:06:54
407 http request GET https://registry.npmjs.org/theorist
408 info retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
409 info retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
410 info retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
411 info retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
412 info retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
413 info retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
414 info retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
415 info retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
416 info attempt registry request try #2 at 11:07:05
417 http request GET https://registry.npmjs.org/async
418 info attempt registry request try #2 at 11:07:05
419 http request GET https://registry.npmjs.org/fuzzaldrin
420 info attempt registry request try #2 at 11:07:05
421 http request GET https://registry.npmjs.org/grim
422 info attempt registry request try #2 at 11:07:05
423 http request GET https://registry.npmjs.org/minimatch
424 info attempt registry request try #2 at 11:07:05
425 http request GET https://registry.npmjs.org/event-kit
426 info attempt registry request try #2 at 11:07:05
427 http request GET https://registry.npmjs.org/node-uuid
428 info attempt registry request try #2 at 11:07:05
429 http request GET https://registry.npmjs.org/scoped-property-store
430 info retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
431 info retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
432 info retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
433 info attempt registry request try #2 at 11:07:06
434 http request GET https://registry.npmjs.org/theorist
435 info retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
436 info retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
437 info retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
438 info retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
439 info retry will retry, error on last attempt: Error: SELF_SIGNED_CERT_IN_CHAIN
440 info attempt registry request try #3 at 11:08:06
441 http request GET https://registry.npmjs.org/async
442 info attempt registry request try #3 at 11:08:06
443 http request GET https://registry.npmjs.org/grim
444 info attempt registry request try #3 at 11:08:06
445 http request GET https://registry.npmjs.org/fuzzaldrin
446 info attempt registry request try #3 at 11:08:06
447 http request GET https://registry.npmjs.org/minimatch
448 info attempt registry request try #3 at 11:08:06
449 http request GET https://registry.npmjs.org/event-kit
450 info attempt registry request try #3 at 11:08:06
451 http request GET https://registry.npmjs.org/node-uuid
452 info attempt registry request try #3 at 11:08:06
453 http request GET https://registry.npmjs.org/scoped-property-store
454 info attempt registry request try #3 at 11:08:07
455 http request GET https://registry.npmjs.org/theorist
456 verbose about to build C:\Users\JOHN8160\AppData\Local\atom\app-0.176.0\resources\app\apm\node_modules\autocomplete-plus
457 verbose unlock done using C:\Users\JOHN8160\AppData\Roaming\npm-cache\_locks\autocomplete-plus-8a78fd2ef2006116.lock for C:\Users\JOHN8160\AppData\Local\atom\app-0.176.0\resources\app\apm\node_modules\autocomplete-plus
458 verbose stack Error: SELF_SIGNED_CERT_IN_CHAIN
458 verbose stack     at SecurePair.<anonymous> (tls.js:1381:32)
458 verbose stack     at SecurePair.emit (events.js:92:17)
458 verbose stack     at SecurePair.maybeInitFinished (tls.js:980:10)
458 verbose stack     at CleartextStream.read [as _read] (tls.js:472:13)
458 verbose stack     at CleartextStream.Readable.read (_stream_readable.js:341:10)
458 verbose stack     at EncryptedStream.write [as _write] (tls.js:369:25)
458 verbose stack     at doWrite (_stream_writable.js:226:10)
458 verbose stack     at writeOrBuffer (_stream_writable.js:216:5)
458 verbose stack     at EncryptedStream.Writable.write (_stream_writable.js:183:11)
458 verbose stack     at write (_stream_readable.js:602:24)
458 verbose stack     at flow (_stream_readable.js:611:7)
458 verbose stack     at Socket.pipeOnReadable (_stream_readable.js:643:5)
459 verbose cwd C:\Users\JOHN8160\AppData\Local\atom\app-0.176.0\resources\app\apm\bin
460 error Windows_NT 6.1.7601
461 error argv "node" "C:\\Users\\JOHN8160\\AppData\\Local\\atom\\app-0.176.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "install" "package.tgz" "--strict-ssl" "false"
462 error node v0.10.35
463 error npm  v2.3.0
464 error SELF_SIGNED_CERT_IN_CHAIN
465 error If you need help, you may report this error at:
465 error     <http://github.com/npm/npm/issues>
466 verbose exit [ 1, true ]
467 verbose unbuild node_modules\autocomplete-plus
468 info preuninstall autocomplete-plus@2.0.1
469 info uninstall autocomplete-plus@2.0.1
470 verbose unbuild rmStuff autocomplete-plus@2.0.1 from C:\Users\JOHN8160\AppData\Local\atom\app-0.176.0\resources\app\apm\node_modules
471 info postuninstall autocomplete-plus@2.0.1
472 verbose gentlyRm vacuuming C:\Users\JOHN8160\AppData\Local\atom\app-0.176.0\resources\app\apm\node_modules\autocomplete-plus
473 silly gentlyRm purging C:\Users\JOHN8160\AppData\Local\atom\app-0.176.0\resources\app\apm\node_modules\autocomplete-plus
474 silly gentlyRm quitting because other entries in C:\Users\JOHN8160\AppData\Local\atom\app-0.176.0\resources\app\apm\node_modules
```

**Comment by othiym23** [comment]
This is a regression introduced by npm/npm-registry-client@4701a29bcda41bc14aa91f361dd0d576e24677d7, which was landed to address some problems with Keep-Alive in Node 0.11.x / io.js 1.0.x. I'm working on putting together a fix now. Thanks for the log!

**Comment by ajamal00** [comment]
I am getting similer issues. I have proxy settings running fine. Trying to install cordova. using npm 2.3.0. npm install -g cordova worked ONLY when i set strict ssl to false... cordova platform add android present the following results:

with strict ssl false

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
        <title>Certificate Verification Error</title>
        <link rel="stylesheet" href="https://registry.npmjs.org/%24%24%24%26%3f%26%3f%24%24%24?cmd=get_file&arg=block_style.css&sid=52986A32DACD1C9A713430547C06474A41B9777C" type="text/css">
    </head>
    <body>

        <div id="pagecontainer">
            <img class="icon" src="https://registry.npmjs.org/%24%24%24%26%3f%26%3f%24%24%24?cmd=get_file&arg=images/block.png&sid=C59E432BFFD37DB49027D9C40A441F5F195775B9"> 
            <h1>A certificate verification error occured</h1>

            <div class="row">
                <p class="label">Overview:</p>
                <p class="item">The access to the URL registry.npmjs.org is restricted because the validation of the certificate failed</p>
            </div>
            <div class="row">
                <p class="label">Details:</p>
                <p class="item"><b><i>VERIFY DENY: depth=0</i></b>, CommonName "a.sni.fastly.net" does not match URL "registry.npmjs.org"</p>
            </div>

            <div id="options">
                <p class="label">Options:</p>
                <form name="ask" method="get" action="https://registry.npmjs.org/%24%24%24%26%3f%26%3f%24%24%24">
                    <INPUT type=hidden value="ask_add" name=cmd>
                    <INPUT type=hidden value="registry.npmjs.org_02b2d53d_0464F9423464BAFF7D746CEA6BD134AB" name=arg>
                    
                    <INPUT type=hidden value="D8C1488B04CE0E7536F4634CF0BCAD62DB1F3732" name=sid>
                    <INPUT type=hidden value="https://registry.npmjs.org/cordova-android" name=url>
                    <input type="submit" class="button" name="Override" value="   Visit Site anyway   "       >
                </form><p class="item">Pressing the button allows you to visit the website although the certificate is not valid.</p>
                <form action=""><input type="button" class="button" onclick="history.back();" value="   Go Back   "></form><p class="item">Pressing the button allows you to go to the previous page.</p
                >
                <p class="last-item">To find out more about the reason for the block message, please contact your administrator and refer to ID 0.</p>
            </div>

            <div><img class="logo" title="Websense" src="https://registry.npmjs.org/%24%24%24%26%3f%26%3f%24%24%24?cmd=get_file&arg=images/wslogo_block_page.png&sid=A300DD9CDDB6F1341908FFBE59352535ABD4D27
                      1" alt="Websense Logo">
                <div style="clear: both; overflow: hidden; height:1px;"></div>
            </div>
        </div>

    </body>
</html>

With strict ssl true

Unable to fetch platform android: Error: SELF_SIGNED_CERT_IN_CHAIN

**Comment by othiym23** [comment]
This is fixed by npm/npm-registry-client@169ae3082a69e97d0b36ea7f0686f06c7fdd9343 / f9313a066c9889a0ee898d8a35676e40b8101e7f, which is included in `npm@2.5.0`, which is currently `npm@next`. `npm -g install npm@next` will install it, if you want to confirm the fix / get a working, new version of npm.

Sorry about this! The change that broke it was needed for Node 0.11 / io.js 1.0.x compatibility, and we don't have adequate test coverage around all of the SSL and proxy use cases, mostly because they're really hard to write in a portable way.

**Comment by ajamal00** [comment]
Hi, sorry but upgrade to npm 2.5.0 does not solve the issue for me.. Still the same errors (tried with strict-ssl set to true and false both).

registry is set to http://regisrty.npm.org/
config ca=""

please help...
