### ISSUE TITLE
scoped package install doesn't add bin to PATH.

### ISSUE THREAD

**Issue by samkelleher** [npm/npm#8640]
Using new NPM private packages, with a scope package. However, when installing, the projects bin is no longer added to path. For example, if I have a package called 'hello', logged in to npm I run `npm install hello -g`.

This works, with the tool available in the PATH, I can run 'hello'.

```
{
 name: 'hello',
 bin: { 'hello':'hello.js' }
}
```

This does not work, once the scope has been added, 'hello' returns no command found, when it should have been created in `/usr/local/bin/hello`.

```
{
 name: '@private/hello',
 bin: { 'hello':'hello.js' }
}
```

Error is:

-bash: /usr/local/bin/hello: No such file or directory
Does the bin path need to change? Running `npm link` manually from the source folder works fine. 

```
/usr/local/bin/hello -> /usr/local/lib/node_modules/@private/hello/hello.js
/usr/local/lib/node_modules/@private/hello -> /Path/To/HomeDirectory/SourceFolder.git
```

**Comment by davidmarkclements** [comment]
Is it installed to `/usr/local/bin/@private/hello` ? 

I'm seeing a similar PATH issue for reference local dep executables.

For instance the following would fail when running `npm test` (providing mocha isn't installed globally)

```js
{
  "name": "unimportant",
  "dependencies": {
    "@forker/mocha": "^2.0.0"
  },
  "scripts": {
     test: "mocha"
   }
}
```

Instead you have to do

```
{
  "name": "unimportant",
  "dependencies": {
    "@forker/mocha": "^2.0.0"
  },
  "scripts": {
     test: "./node_modules/.bin/@forker/mocha"
   }
}
``

**Comment by toddself** [comment]
I'd love to add a warning at least to a user who has installed a scoped module explaining that they have to alter their path to make the "bin" part accessible without the full path.

What branch or tag should I start on for this? Is this an acceptable solution?

I would prefer nothing automatically alter my path (especially since that would mean altering my login scripts for my shell or whatever windows needs to do for this) but giving a message saying "you'll need to make sure that /usr/local/bin/@private is in your path" would be aces.

**Comment by iarna** [comment]
@toddself We actually don't want scoped bins installing in a path in `/usr/local/bin`– That anything shows up in `@private` is a bug.

That said, I can't reproduce this with `npm@2` or `npm@3`. I _can_ reproduce this with `npm@1.4.28`, but that's because it doesn't support scoped modules at all.

**Comment by toddself** [comment]
```
13:51:57 ~/src
↳ npm i -g @scriptollc/dump-folder
[lots of install messages]
/opt/iojs-v2.0.2-darwin-x64/bin/@scriptollc/dump-folder -> /opt/iojs-v2.0.2-darwin-x64/lib/node_modules/@scriptollc/dump-folder/cli.js
@scriptollc/dump-folder@1.1.1 /opt/iojs-v2.0.2-darwin-x64/lib/node_modules/@scriptollc/dump-folder
├── xtend@4.0.0
├── async@1.4.2
├── minimist@1.1.3
├── lodash.find@3.2.1 (lodash._basefindindex@3.6.0, lodash._basefind@3.0.0, lodash._baseeach@3.0.4, lodash.isarray@3.0.4, lodash.keys@3.1.2, lodash._basecallback@3.3.1)
└── request@2.60.0 (aws-sign2@0.5.0, forever-agent@0.6.1, caseless@0.11.0, stringstream@0.0.4, oauth-sign@0.8.0, tunnel-agent@0.4.1, form-data@1.0.0-rc3, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, node-uuid@1.4.3, qs@4.0.0, tough-cookie@2.0.0, http-signature@0.11.0, combined-stream@1.0.5, mime-types@2.1.4, hawk@3.1.0, bl@1.0.0, har-validator@1.8.0)
13:52:13 ~/src
↳ npm version
{ npm: '2.13.4',
  ares: '1.10.1-DEV',
  http_parser: '2.5.0',
  modules: '44',
  node: '2.0.2',
  openssl: '1.0.2a',
  uv: '1.5.0',
  v8: '4.2.77.20',
  zlib: '1.2.8' }
```

**Comment by iarna** [comment]
Huh, that's really interesting...

```
21:08 rebecca@Caldina:~/code/emojitime$ [master] npm -v
2.13.3
21:08 rebecca@Caldina:~/code/emojitime$ [master] npm install -g @iarna/emojitime
/Users/rebecca/.nvm/versions/io.js/v3.0.0/bin/emojitime -> /Users/rebecca/.nvm/versions/io.js/v3.0.0/lib/node_modules/@iarna/emojitime/cli.js
21:08 rebecca@Caldina:~/code/emojitime$ [master] npm install -g @iarna/emojitime
/Users/rebecca/.nvm/versions/io.js/v2.4.0/bin/emojitime -> /Users/rebecca/.nvm/versions/io.js/v2.4.0/lib/node_modules/@iarna/emojitime/cli.js
/Users/rebecca/.nvm/versions/io.js/v2.4.0/lib
└── @iarna/emojitime@1.0.1
```

**Comment by toddself** [comment]
Your package.json contains:

```json
"bin": {
"emojitime": "cli.js"
},
```
Ours is:

```json
"bin": "cli.js",
```

When I change your package to be the same as ours I get:
```
14:33:23 ~/src/.../@iarna/emojitime:master
↳ vi package.json
14:33:32 ~/src/.../@iarna/emojitime:master
↳ npm i -g
/opt/iojs-v2.0.2-darwin-x64/bin/@iarna/emojitime -> /opt/iojs-v2.0.2-darwin-x64/lib/node_modules/@iarna/emojitime/cli.js
cat pack@iarna/emojitime@1.0.1 /opt/iojs-v2.0.2-darwin-x64/lib/node_modules/@iarna/emojitime
14:33:39 ~/src/.../@iarna/emojitime:master
↳ cat package.json
{
  "name": "@iarna/emojitime",
  "version": "1.0.1",
  "description": "A command line toollet to print the time as an emoji",
  "main": "index.js",
  "bin": "cli.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": {
    "name": "Rebecca Turner",
    "email": "me@re-becca.org"
  },
  "license": "ISC",
  "gitHead": "189bf77c020c38a48f7fbd1d21cf53aed0584630",
  "_id": "@iarna/emojitime@1.0.1",
  "_shasum": "5d4111ecc95dd44b6adf6ebcb204131cab239f48",
  "_from": "@iarna/emojitime@*",
  "_npmVersion": "2.13.3",
  "_nodeVersion": "3.0.0",
  "_npmUser": {
    "name": "iarna",
    "email": "me@re-becca.org"
  },
  "dist": {
    "shasum": "5d4111ecc95dd44b6adf6ebcb204131cab239f48",
    "tarball": "http://registry.npmjs.org/@iarna/emojitime/-/emojitime-1.0.1.tgz"
  },
  "maintainers": [
    {
      "name": "iarna",
      "email": "me@re-becca.org"
    }
  ],
  "directories": {},
  "_resolved": "https://registry.npmjs.org/@iarna/emojitime/-/emojitime-1.0.1.tgz"
}
```

So this appears to be a bug when specifying the `bin` using a string rather than an object!

**Comment by toddself** [comment]
So I guess this leads to what is the appropriate behavior?

It would be AWESOME if you kept symlinking -- I've explained to my team that they need to add `/usr/local/bin/@scriptollc` to their path when they want to use one of the tools I've written.

If no symlinking were to happen they'd have to manually add the symlink as well as add to their path (which is a bit more complicated since the symlink would have to be added per installed tool).

**Comment by davidmarkclements** [comment]
In terms of locally installed modules, it would be great if npm run-script added all first level sub folders in node_modules/.bin to the run-script environments path (as it currently does with node_modules/.bin) 

I realise that multiple executables with same name could then exist in the path but conflicts would be resolved as per the normal left to right algorithm that applies to PATH - I would say put the scoped bins before the general bins (if  I accidentally install two modules and one of them is scoped, I'm probably expecting the private behaviour - or if I'm not I would realise I was using a custom bin because of the deviation whereas the other way I may just think my custom bin isn't working)

**Comment by toddself** [comment]
Are there any ideas on resolution for this?

It's a tough support scenario to have to determine a) which type of `bin` statement was made in the package.json and then b) figure out where the file pointed to by the `bin` statement lives in that users particular node installation.

**Comment by zkat** [comment]
Hey! So -- this is most likely an issue in `normalize-package-json` or `read-package-json`. You can start by taking a look at how those are used and see if you can track down what's triggering this from there. We'd be more than happy to review/accept a PR for this! We do have other (pretty high) priority items atm, too, so while this would be a fairly high-priority ticket, we would still not really be able to get to it for a while (on the order of at least a couple to a few weeks, is my totally-non-binding guesstimate).

**Comment by toddself** [comment]
My confusion stems from (and lack of PR so far) stems from this:

[@iarna says:](https://github.com/npm/npm/issues/8640#issuecomment-131235858)
>@toddself We actually don't want scoped bins installing in a path in /usr/local/bin– That > /usr/local/bin/@private exists or anything is installed in it is a bug.

My idea for resolving this is to make symlinks work for `bin` keys in the package.json regardless of whether or not the package is scoped.  If you're looking for a different resolution for this issue, I will likely just write a new package that will run during the `postinstall` lifecycle that will properly symlink scoped packages into the user's path.

**Comment by othiym23** [comment]
@toddself Sorry for not getting on this sooner, but if I'm understanding you correctly, then you're saying you'll have something that will link the bin name of the non-scope part of the name to the appropriate script, which is exactly what we want. At some point we'll have to come up with a strategy for dealing with name conflicts, but making it so that binaries work out of the box in all cases come first. Or did I misunderstand you?

**Comment by toddself** [comment]
@othiym23 yes!  that was my solution to resolving the bug -- just making it work as it seems it would be expected regardless of scoping.

i'll get to a patch hopefully today.

Thanks!

**Comment by iarna** [comment]
This should be fixed w/ 3.4.0 and 31c0080!

**Comment by subshad** [comment]
@iarna, @othiym23 Can I confirm the expected behaviour with regard to this issue? I believe I am still seeing the error.

Expected behaviour:

On installing a package @foo/bar with a bin: cli.js, we expect to see a file ./node_modules/.bin/bar -> ./node_modules/@foo/bar/cli.js ?

Current behaviour in 3.4.0 -> 3.5.x-latest:

On installing a package @foo/bar with a bin: cli.js, we currently see a file ./node_modules/.bin/@foo/bar -> ./node_modules/@foo/bar/cli.js

This means that a script in package.json cannot access bar without providing the entire path to the binary, and a package installed globally cannot be run without the path to the binary.

**Comment by subshad** [comment]
Also, I've tested the "@foo/bar" string against the regex in the PR in https://github.com/npm/normalize-package-data/pull/69 and that seems to return `match[1] === bar` so I'm not sure what could be causing this.

**Comment by subshad** [comment]
Apologies. It seems a malformed path in the bin K/V pair was causing the problem. When the bin K/V pair was `"bin": "cli"` it would scope the binary and symlink to node_modules/.bin/@foo/bar, but when it is `"bin": "./cli"` it correctly symlinks to node_modules/.bin/bar .

**Comment by s-a** [comment]
could this impact non scoped packeages too? I am experiacing same behaivor at https://github.com/s-a/terminal-center/blob/master/package.json and ```npm install -g``` node v4

**Comment by s-a** [comment]
Just tried from npm without success.

```
)npm install -g terminal-center
C:\Users\sahlf\AppData\Roaming\npm\ctrl -> C:\Users\sahlf\AppData\Roaming\npm\node_modules\terminal-center\cli.js
C:\Users\sahlf\AppData\Roaming\npm\central -> C:\Users\sahlf\AppData\Roaming\npm\node_modules\terminal-center\cli.js
terminal-center@0.0.5 C:\Users\sahlf\AppData\Roaming\npm\node_modules\terminal-center
├── open@0.0.5
├── shelljs@0.6.0
├── commander@2.9.0 (graceful-readlink@1.0.1)
└── inquirer@0.12.0 (ansi-escapes@1.3.0, strip-ansi@3.0.1, ansi-regex@2.0.0, figures@1.4.0, rx-lite@3.1.2, through@2.3.8, cli-width@2.1.0, run-async@0.1.0, cli-cursor@1.0.2, readline2@1.0.1, string-width@1.0.1, chalk@1.1.1, lodash@4.6.1)

C:\Users\sahlf>
)ctrl
Das System kann den angegebenen Pfad nicht finden.
```

Any ideas whats going wrong on my system?
