### ISSUE TITLE
multi-stage: npm marks third party dependency as extraneous and then fails on npm ls

### ISSUE THREAD

**Issue by mantoni** [npm/npm#8660]
Reproduce:

```
$ git clone https://github.com/mantoni/hub.js.git
$ npm i
```

Has this in the install tree listing:

```
...
├── nan@1.8.4  extraneous
...
```

I don't even know where `nan` is coming from.

When I then go `npm ls` it fails with error code 1 and the message:

```
npm ERR! extraneous: nan@1.8.4 /home/u25749/projects/hub.js/node_modules/nan
```

@iarna While you're at it :dancer: :smile:

**Comment by iarna** [comment]
hah, ok, I know already what's going on. `nan` is a subdep of `fsevents`– the rollback isn't... rolling back enough.

**Comment by lukeapage** [comment]
+1 got caught out by this, its not obvious after doing `npm install` that you need `npm prune` before you are allowed `npm shrinkwrap` - it would be handy if shrinkwrap suggested you checkout the prune command, though I guess that will not be needed in the future.

**Comment by iarna** [comment]
Pushing this out till next week, as this was too big to fit in a 2 day week.

**Comment by iarna** [comment]
Fixed in v3.1.1

**Comment by mantoni** [comment]
Unfortunately, I can't confirm this to be fixed. I can still reproduce as before, but now it's moaning about `os-shim@0.1.2` being extraneous.
