### ISSUE TITLE
npm@3 missing are-we-there-yet module (Windows 7, Node 0.10.26)

### ISSUE THREAD

**Issue by mattdsteele** [npm/npm#8759]
I'm running:

* Windows 7 (64-bit)
* Node.js 0.10.26
* npm 1.4.3
* A self-hosted NPM registry (not sure if that makes a difference)

And attempting to install and use npm@3. My process for install:

```
> npm install -g npm@3
npm http GET http://hostedrepo.com/content/groups/npm-all/npm
npm http 200 http://hostedrepo.com/content/groups/npm-all/npm
npm http GET http://hostedrepo.com/content/groups/npm-all/npm/-/npm-3.0.0.tgz
npm http 200 http://hostedrepo.com/content/groups/npm-all/npm/-/npm-3.0.0.tgz
C:\Users\matt\AppData\Roaming\npm\npm -> C:\Users\matt\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
npm@3.0.0 C:\Users\matt\AppData\Roaming\npm\node_modules\npm
```

All attempts to use `npm@3` fail with this error:

```
> c:\Users\matt\AppData\Roaming\npm\npm -v

module.js:340
    throw err;
          ^
Error: Cannot find module 'are-we-there-yet'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (c:\Users\matt\AppData\Roaming\npm\node_modules\npm\node_modules\npmlog\log.js:2:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

I don't see the `are-we-there-yet` module anywhere on the filesystem under `node_modules/npm`. A gist including the full `tree` is available here: https://gist.github.com/mattdsteele/f0ee0a10c73624e903a2

**Comment by iarna** [comment]
Your steps work fine for me w/ node v0.10.38 and npm v1.4.28

**Comment by iarna** [comment]
1.4.3 is really old... I wonder if updating to a more recent 1.4.x release first might not help. On the other hand, I don't honestly know how that would result in some tarballs not being extracted. =/

**Comment by iarna** [comment]
Can you put your copy of `http://hostedrepo.com/content/groups/npm-all/npm/-/npm-3.0.0.tgz` somewhere I can examine it? I'd like to see if the tarball in your private repo is actually the same as the one in our public repo

**Comment by mattdsteele** [comment]
Will do.

As info I just tried updating to 1.4.28, and then used that to install npm@3, but got the same "cannot find module" error once I tried using npm@3.

**Comment by mattdsteele** [comment]
Tarball is available here: http://msteele-random-files.s3-website-us-west-2.amazonaws.com/npm-3.0.0.tgz

**Comment by simonbuchan** [comment]
FWIW, I saw the same problem, with a similar (maybe not same) old npm for the original install that downloaded it (due to default node install resulting in C:\Program Files\nodejs being in front of %APPDATA%\npm in PATH - user PATH is *appended* to system PATH).
I grabbed the node_modules out of the github zip to fix.
Looks like whatever tarball is being pulled is one built from a partially deduped install.

**Comment by iarna** [comment]
The tarball definitely has the module:
```
-rw-r--r--  0 501    20       1919 Jun 25 21:02 package/node_modules/are-we-there-yet/package.json
-rw-r--r--  0 501    20         20 Jun 25 21:02 package/node_modules/are-we-there-yet/.npmignore
-rw-r--r--  0 501    20       6035 Jun 25 21:02 package/node_modules/are-we-there-yet/README.md
-rw-r--r--  0 501    20       3588 Jun 25 21:02 package/node_modules/are-we-there-yet/index.js
-rw-r--r--  0 501    20       1660 Jun 25 21:02 package/node_modules/are-we-there-yet/test/tracker.js
-rw-r--r--  0 501    20       3292 Jun 25 21:02 package/node_modules/are-we-there-yet/test/trackergroup.js
-rw-r--r--  0 501    20       1826 Jun 25 21:02 package/node_modules/are-we-there-yet/test/trackerstream.js
```

Hmm, ok, new theory:

1. Do `1.x` npms repack any tarball they download?
2. If so, then that would explain modules (like `are-we-there-yet`) that are only implicitly bundled being purged.

For the time being you can almost certainly work around this w/

1. npm install -g npm@latest
2. npm install -g npm@3

As npm@2 can definitely upgrade to npm@3.

**Comment by iarna** [comment]
Ooor, you can give this a try, made a friend-of-npm at Microsoft: https://www.npmjs.com/package/npm-windows-upgrade

**Comment by mattdsteele** [comment]
@iarna npm-windows-upgrade looks awesome, but alas I don't have admin rights on this machine :( Hooray for corporate lockdown.

Going to npm@latest, then npm@3 worked for me.

**Comment by willbuck** [comment]
I'm having this exact same problem on a

- MacBook Pro (OSX 10.10.3)
- Node v0.12.6 (installed via nvm to my user home)
- NPM 2.12.1 (came with the above node version)

Steps I followed were basically the same as @mattdsteele, only I can't use npm anymore at all, I'm going to need to blow away my node install and re-install it in order to have a functioning npm to work with again.

My output looks very much the same to Matt's as well

```
{Mon 6 22:09:56} ~ ➭ npm install -g npm@3.1.0
/Users/willbuck/.nvm/v0.12.6/bin/npm -> /Users/willbuck/.nvm/v0.12.6/lib/node_modules/npm/bin/npm-cli.js
npm@3.1.0 /Users/willbuck/.nvm/v0.12.6/lib/node_modules/npm
```

Any other info I can provide I am happy to do, thanks very much!

**Comment by iarna** [comment]
@willbuck On npm@2? Well, that's unexpected. Can you include the exact output when you go to run npm?

Also, can you put the output of `ls -lR /Users/willbuck/.nvm/v0.12.6/lib/node_modules/npm` in a gist?

**Comment by iarna** [comment]
Oh @willbuck, are you using a self hosted registry as well?

**Comment by willbuck** [comment]
@iarna I am not, at least not to my knowledge (perhaps I am by virtue of sourcing node from nvm?)

Here's the exact output of running `npm`

```
{Mon 6 22:37:33} ~ ➭ npm
module.js:338
    throw err;
          ^
Error: Cannot find module 'are-we-there-yet'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/willbuck/.nvm/v0.12.6/lib/node_modules/npm/node_modules/npmlog/log.js:2:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

I will get the ls output in a gist shortly and edit this comment

**Comment by iarna** [comment]
@willbuck Nah, if you didn't explicitly set one up, then you won't have one. (I use nvm too ¯\_(ツ)_/¯)

**Comment by iarna** [comment]
I _am_ suspicious about one thing... `2.12.1` is currently `npm@next` and is not in any release of node. node `0.12.6` comes with `2.11.2`.

**Comment by iarna** [comment]
Trying to reproduce this...
```
🕦  rebecca@Caldina:~/code/npm$ [master] nvm use v0.12.6
Now using node v0.12.6
🕦  rebecca@Caldina:~/code/npm$ [master] npm -v
2.11.2
🕦  rebecca@Caldina:~/code/npm$ [master] npm install -g npm@3.1.0
/Users/rebecca/.nvm/versions/node/v0.12.6/bin/npm -> /Users/rebecca/.nvm/versions/node/v0.12.6/lib/node_modules/npm/bin/npm-cli.js
npm@3.1.0 /Users/rebecca/.nvm/versions/node/v0.12.6/lib/node_modules/npm
🕦  rebecca@Caldina:~/code/npm$ [master] npm -v
3.1.0
```


```
🕛  rebecca@Caldina:~/code/npm$ [master] nvm uninstall v0.12.6
Uninstalled node v0.12.6
🕛  rebecca@Caldina:~/code/npm$ [master] nvm install v0.12.6
######################################################################## 100.0%
Now using node v0.12.6
🕛  rebecca@Caldina:~/code/npm$ [master] npm -v
2.11.2
🕛  rebecca@Caldina:~/code/npm$ [master] npm install -g npm@latest
/Users/rebecca/.nvm/versions/node/v0.12.6/bin/npm -> /Users/rebecca/.nvm/versions/node/v0.12.6/lib/node_modules/npm/bin/npm-cli.js
npm@2.12.1 /Users/rebecca/.nvm/versions/node/v0.12.6/lib/node_modules/npm
🕛  rebecca@Caldina:~/code/npm$ [master] npm -v
2.12.1
🕛  rebecca@Caldina:~/code/npm$ [master] npm install -g npm@3.1.0
/Users/rebecca/.nvm/versions/node/v0.12.6/bin/npm -> /Users/rebecca/.nvm/versions/node/v0.12.6/lib/node_modules/npm/bin/npm-cli.js
npm@3.1.0 /Users/rebecca/.nvm/versions/node/v0.12.6/lib/node_modules/npm
🕛  rebecca@Caldina:~/code/npm$ [master] npm -v
3.1.0
```

**Comment by willbuck** [comment]
@iarna that's an interesting fact I did not know... I did install npm @ latest before doing npm install @3. 

However, I re-ran things and I have just confirmed that these steps will reproduce the error for me

```
nvm install 0.12 
node -v # 0.12.6
npm -v # 2.11.2, like you say
npm install -g npm@3 # looks like success
npm -v # OMG WHERE IS YOUR ARE WE THERE YET YOU MONSTER
```

You read my mind lol

**Comment by willbuck** [comment]
What other details might I be able to provide to diagnose the issue further? Clearly something must be wrong somewhat uniquely with my machine, as it looks to work for you very nicely. I have a borked install of node in my /usr/local/lib folder, but I don't think that should affect things here right? I mean that's why I started using nvm in the first place

**Comment by iarna** [comment]
This is _definitely_ an issue with installing if you're starting from npm@1.x. Why this seems to be an issue only for you on npm@2 I don't know. I may split this off into two separate tickets actually…

**Comment by iarna** [comment]
@willbuck: Well... the /usr/local copy _shouldn't_ effect things but I am curious what version that is..

**Comment by willbuck** [comment]
@iarna totally fine with splitting the issues as they seem somewhat unrelated. I believe it was 0.10.26? I brew uninstalled it after I started seeing these issues. Any tips on cleaning out usr/local of node related things? I believe I still have a good number of node modules globally installed in there as well, some stuff like gulp I still use regularly :/

Just on a side note, I hope I'm being helpful; I don't mean to complain as I am really pleased to hear about the dependency flattening changes going on in 3.x and really appreciate all the hard work going into the npm ecosystem!

**Comment by iarna** [comment]
Hmm, 0.10.26 could have left residue around, although it's not obvious how, since `npm -v` is reporting the correct version. Still, that's something else I can try.

You absolutely are being helpful! Being able to quickly bounce diagnostics off you is super useful.  I may have a few more for you in the next few days

**Comment by simonbuchan** [comment]
For me, later installs with npm 2 were probably using npm-cache:

```
$ tar --list --file /c/Users/sbuchan/AppData/Roaming/npm-cache/npm/3.0.0/package.tgz  | grep are-we-there-yet
$ ls /c/Users/sbuchan/AppData/Roaming/npm-cache/npm/3.0.0/package/node-modes/are-*
$ 
```

Reinstalling:

```
$ /c/Program\ Files/nodejs/npm cache clean npm
$ /c/Program\ Files/nodejs/npm -g rm npm
$ /c/Program\ Files/nodejs/npm -g i npm
C:\Users\sbuchan\AppData\Roaming\npm\npm -> C:\Users\sbuchan\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
npm@2.12.1 C:\Users\sbuchan\AppData\Roaming\npm\node_modules\npm
$ npm -v
2.12.1
```

Annoyingly, `npm -g i npm@3` doesn't work at this point, but that looks like a separate issue, as `npm -g i npm` fails too. I'll open a separate issue for that.

```
$ /c/Program\ Files/nodejs/npm -g i npm@3
C:\Users\sbuchan\AppData\Roaming\npm\npm -> C:\Users\sbuchan\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
npm@3.1.0 C:\Users\sbuchan\AppData\Roaming\npm\node_modules\npm
$ npm -v
3.1.0
```

At this point, I suspect a bad CDN regional upload or something? Might be a systemic problem, but I'd wait for it to come up again.

**Comment by simonbuchan** [comment]
Looks like my bug is #7562

**Comment by iarna** [comment]
@simonbuchan  We verify shasums of the tarball, so a bad CDN entry would result in a complete install failure.

Hey, do you still have that tarball that didn't have `are-we-there-yet` hanging about? I would LOVE to get a copy! It would be super helpful. (It looks like the answer is "no" but I figure it can't hurt to ask. 😁)

**Comment by simonbuchan** [comment]
@iarna Of course I realized you would probably want that ~ 2 seconds after npm cache clean :'(. But yeah, when I was checking it out, it *looked* pretty much the same as the unpacked `package/` and `$APPDATA/npm/node_modules/npm`, in particular they all had sane looking structure, and the missing packages in `node_modules` - so I have to expect the checksum was of a badly built package file?

**Comment by nhducit** [comment]
I have same issue on Ubuntu 14.04 and node 0.10.25.

This issue occur when I try to update npm v3 through npm v2 by command:

```js
npm install -g npm
```

**Comment by robbietapping** [comment]
Im also having the same issue when trying to install on 
Ubuntu 14.04 and node 0.12.7

<pre><code>Error: Cannot find module 'are-we-there-yet'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npmlog/log.js:2:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)</code></pre>

**Comment by robschuh** [comment]
Try it http://stackoverflow.com/questions/31025048/npm-doesnt-work-get-always-this-error-error-cannot-find-module-are-we-ther

**Comment by MauJFernandezUVR** [comment]
@robschuh Thanks, that solution worked.

Weird bug, I just updated npm and it broke everything, I couldn't even execute ```npm```.

**Comment by nhducit** [comment]
I resolved this issue on my computer running ubuntu 64bit by remove and install node and npm.

# Using Ubuntu
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs

# Using Debian, as root
curl -sL https://deb.nodesource.com/setup_4.x | bash -
apt-get install -y nodejs


https://github.com/nodesource/distributions

**Comment by Burbaka** [comment]
Was able to resolve this issue with http://stackoverflow.com/a/32981881

**Comment by othiym23** [comment]
This is also addressed by `npm@3.3.9`, which has been repackaged using an older version of npm that doesn't handle `bundledDependencies` in a way that confuses old versions of npm. Landed as 25a234b4595ee3f1a2c09e2a39e3c238aa642557. Closing this as resolved. Thanks for your patience, everybody!

**Comment by ApfelUser** [comment]
Hm. I have the same issue. But on Travis CI, and as you don't have access to the shell I can't use the fixes described above. `npm@3.3.9` doesn't fix it either. Related PR: https://github.com/donpark/hbs/pull/112

**Comment by ApfelUser** [comment]
@othiym23 Any updates?

**Comment by othiym23** [comment]
@ApfelUser Do you have an `npm install -g npm` in `before_install` stanza in your project's `.travis.yml`? `npm@3.3.9`, which is now `npm@latest`, has been repackaged in such a way that pretty much any version of npm should be able to upgrade directly to it without getting confused by how the dependencies are bundled.

**Comment by ApfelUser** [comment]
@othiym23 Yeah. We (Not actually my project, I just created a PR upgrading npm) do have a `npm install -g npm` in our `travis.yml`. The failing part is where we require `npm@3.3.9´ over the `package.json`. This error also actually just happens on **node 0.8**, as you can see in the [Travis CI](https://travis-ci.org/donpark/hbs/builds/86799976) build.

**Comment by lenovouser** [comment]
Any updates?

**Comment by ninovsnino** [comment]
I have the same issue with @mattdsteele in my Window machine although the difference is it complain about missing other module.
Cause of this issue is in Windows 7+ it has c:/users/<username>/AppData/Roaming/ npm and npm-cache, and npm installer still pointing to this directory.
The easiest way to get rid of it is to 1. uninstall npm, 2. delete npm and npm-cache folder in your /AppData/Roaming, and finally 3. install npm back again.
