### ISSUE TITLE
npm search hangs when not given search

### ISSUE THREAD

**Issue by KylePalko** [npm/npm#9251]
npm search hangs if you don't give it a term to search for. I'm sure it's working as intended and hanging because it's trying to pull every package, but this can be confusing to some people.

**Comment by sinkingshriek** [comment]
I think this has been addressed in npm@3+ already with the progress bar.

**Comment by KylePalko** [comment]
That's great. Thanks. I would still think we would just want to disable the ability to search for all packages, but this is better than nothing I guess.

**Comment by marcbachmann** [comment]
> I think this has been addressed in npm@3+ already with the progress bar.

Nope, there's no progress bar at the search command. And it still hangs if you don't pass a search term in npm v3.

**Comment by othiym23** [comment]
Closing as a duplicate of #6016, but also see #11984, which addresses this specific situation by disallowing search with no parameters (in times of yore, this would return every package known to npm, which isn't useful with a registry containing 250,000 packages). Thanks for your time and patience!
