### ISSUE TITLE
node_modules/history included in npm pack'd tarball

### ISSUE THREAD

**Issue by lukekarrys** [npm/npm#9642]
When running `npm pack` in a directory that contains `node_modules/history/`, the resulting tarball contains `node_modules/history/` when I think it should be ignored. I'm using a `.gitignore` to try and ignore `node_modules`. Other directories within `node_modules/` are ignored, expect for `history`.

I created [a gist](https://gist.github.com/lukekarrys/7ba04eb61a8d88f933fc) with the steps I used to reproduce, which I also pasted below.

A quick glance at the code makes it seem like the possible culprit could be [this regex](https://github.com/npm/npm/blob/v2.14.4/node_modules/fstream-npm/fstream-npm.js#L102) from `fstream-npm` (which is also in the [`v3.3.3` release](https://github.com/npm/npm/blob/v3.3.3/lib/utils/tar.js#L72)).

**Steps to repro**
- `git clone git@gist.github.com:7ba04eb61a8d88f933fc.git`
- `cd 7ba04eb61a8d88f933fc`
- `npm install`
- `npm pack`
- `tar xzf history-huh-1.0.0.tgz`
- `tree -L 2 package`

**Output**
```sh
> tree -L 2 package
package
├── README.md
├── node_modules
│   └── history
└── package.json
```

**Expected**
```sh
> tree -L 2 package
package
├── README.md
└── package.json
```

**Comment by othiym23** [comment]
Your diagnosis of what's going on looks absolutely correct. The fix would be to modify `fstream-npm` to verify that the entry is a file as well as being named something like "history" or "changelog", and off the top of my head, I don't know how tough that would to be. From the outside, this looks pretty innocuous, along the lines of an involuntary `bundledDependency`. How is this affecting you, @lukekarrys? (We'd be happy to review and land patches that fix this, but otherwise it might be a while until we have the cycles to get to this, unless it's causing users serious problems.)

**Comment by lukekarrys** [comment]
@othiym23 No serious problems. I noticed it and was mostly curious why it was happening, as it just seemed odd.

It affected me when `node_modules/history` it ended up in the tarball of [`redux-react-router`](https://github.com/rackt/redux-react-router/issues/54) where it's listed as `devDependency` but no a `dependency`. I usually run `npm ls` as a `npm run validate` step on projects to make sure everything is good with my deps, but in this case it errors since `redux-react-router/node_modules/history` is extraneous.

I'm happy to submit a PR for this. One question, should the fix go in `fstream-npm` or `util/lib/tar.js` or both?

**Comment by othiym23** [comment]
I can totally see how that would be confusing. A way to work around this for `redux-react-router` would be to add a `postversion` script that runs `npm prune --prod`, which will strip out `devDependencies` as long as you publish right after versioning. (Using `prepublish` here is tricky because that will uninstall `devDependencies` right after installling them.)

> should the fix go in `fstream-npm` or `util/lib/tar.js` or both?

It should go in `fstream-npm`, which will fix it in `util/lib/tar.js` when we pull down the updated dependency.

**Comment by lukekarrys** [comment]
:+1:  I'll work on a PR with a fix+test to `fstream-npm`.

And just because I'm still slightly confused and want to be sure, it looks to me like `lib/utils/tar.js` is different in `v3` and `applyIgnores()` is being overridden with [some of the same logic](https://github.com/npm/npm/blob/v3.3.3/lib/utils/tar.js#L72) before being passed of to `fstream-npm`. Wouldn't the fix need to be applied there as well?

**Comment by othiym23** [comment]
I'm pretty sure that code is redundant at this point (it might predate the existence of `fstream-npm`, in fact). If you wanted to do us a solid and put together a separate PR that strips that out and incorporates the new `fstream-npm` (and maybe adds a test to make sure everything works correctly), one of us will work with you to make sure all the Ts are dotted and Is are crossed. Thanks, Luke!

**Comment by lukekarrys** [comment]
A duplicate issue has been opened at https://github.com/npm/npm/issues/9894, so I thought I'd update this and say I haven't been able to find a fix for this in the small amount of time I tried.

If anyone else wants to attempt a fix I think @othiym23's advice above as for how to go about it still holds.

**Comment by taion** [comment]
Sure. PR submitted with the fix.

Contra https://github.com/npm/npm/issues/9642#issuecomment-141254777, this is actively causing issues when packaging React Router, and also causes issues with people using `npm shrinkwrap`. See https://github.com/rackt/react-router/issues/2195 and https://github.com/react-bootstrap/react-bootstrap/issues/1395 respectively.

**Comment by taion** [comment]
@othiym23 Any chance to look at the PR?

**Comment by lukekarrys** [comment]
I'm still seeing this behavior when testing with my gist above and `npm@3.4.1`. I understand that the bug will still be present in packages until they publish a new version with the latest `npm`, but my test was using `npm pack` which still isn't exluding `node_modules/history/` from the tarball.

**Comment by lukekarrys** [comment]
It looks like the culprit is similar logic in [`lib/utils/tar.js`](https://github.com/npm/npm/blob/65a64c9277184b1a0665d78fce0a9b00f930d9bc/lib/utils/tar.js#L75).

I'll create a PR for this in `npm`.

**Comment by taion** [comment]
It's fixed with npm2, BTW. (sorry)

**Comment by bvaughn** [comment]
Looks like this issue is back. (At least I'm seeing node_modules/history included with my dist using Npm 3.3.12)

**Comment by taion** [comment]
The fix landed in 3.8.7, BTW. I think your version is just too old.

**Comment by bvaughn** [comment]
Oh. Thanks! I could have sworn I saw elsewhere a comment that said it was fixed in 2.2... Sorry! 😁
