### ISSUE TITLE
fetching .tgz package fails while package is correctly listed on npm

### ISSUE THREAD

**Issue by KurtPattyn** [npm/npm#9796]
When issuing `npm install konsol` the following error is logged:

```
npm ERR! fetch failed https://registry.npmjs.org/konsol/-/konsol-0.1.3.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/konsol/-/konsol-0.1.3.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/konsol/-/konsol-0.1.3.tgz
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4

npm ERR! fetch failed with status code 404

```

The `konsol` module exists on npm, and issuing `npm info konsol` returns the correct information.  
But retrieving the .tgz file results in an error.

**Comment by KurtPattyn** [comment]
Solved by pushing a new version. But the version 0.1.3 and 0.1.2 still give errors.

**Comment by busches** [comment]
@othiym23 this issue is still happening today, is this a registry issue or a one off issue that has since been fixed?
